table BudgetVersion
	lineageTag: 48bc2535-b80c-4c21-b9aa-62be3a59603d

	measure SlctdBudVersion = SELECTEDVALUE(BudgetVersion[BudgetActualisation],"BUD")
		lineageTag: 14063b09-b635-4d46-a84a-4f49dc25eb48

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BudgetVersion
		dataType: string
		lineageTag: 5b6d24e5-07ab-4bc3-9bc4-bbaf4a82ef82
		summarizeBy: none
		sourceColumn: BudgetVersion

		annotation SummarizationSetBy = Automatic

	column BudgetActualisation
		dataType: double
		formatString: 0
		lineageTag: 3f5830eb-3842-41f4-97f6-f06008839265
		summarizeBy: sum
		sourceColumn: BudgetActualisation

		annotation SummarizationSetBy = Automatic

	partition BudgetVersion = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wcgp1UdJRMjIwMjM0V4qNBQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [BudgetVersion = _t, BudgetActualisation = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"BudgetVersion", type text}, {"BudgetActualisation", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

