table factSRIVDispatchChannelForecast
	lineageTag: 0061df29-25b5-42be-824d-f0ef03654d86

	/// This measure is the sum of column 'factSRIVDispatchChannelForecast'[sriv]
	measure sum_sriv_factSRIVDispatchChannelForecast = SUM ( 'factSRIVDispatchChannelForecast'[sriv] )
		formatString: #,##0,,.0;(#,##0,,.0)
		lineageTag: 36a14656-a4df-482b-a2ca-578279d03b14

	column fiscalWeek
		dataType: int64
		formatString: 0
		lineageTag: 8d24c9b5-be8e-4355-a6b9-baf6b912736b
		summarizeBy: none
		sourceColumn: fiscalWeek

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: 28853b2b-1f10-44aa-8a09-58533891016d
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column product
		dataType: string
		lineageTag: d5e41ffe-7078-40c1-a20b-ea2175cc3adc
		summarizeBy: none
		sourceColumn: product

		annotation SummarizationSetBy = Automatic

	column siteID
		dataType: int64
		formatString: 0
		lineageTag: 259bec1e-f03d-44f7-bcea-b05dba986519
		summarizeBy: none
		sourceColumn: siteID

		annotation SummarizationSetBy = Automatic

	column fp_rp_ind
		dataType: string
		lineageTag: 13f1422e-2577-446a-8c09-4dc37f743146
		summarizeBy: none
		sourceColumn: fp_rp_ind

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: a5c3a84b-3811-475c-ab41-36e45ea09a9b
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column sriv
		dataType: double
		isHidden
		lineageTag: ff92121b-71f6-4378-8b24-ed9323de4749
		summarizeBy: sum
		sourceColumn: sriv

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition factSRIVDispatchChannelForecast-753c5f3d-af44-4a0b-b27a-9e54e7c0f9a3 = m
		mode: import
		queryGroup: 'Dispatch fact tables'
		source =
				let
				    Source = factSRIVDispatchForecastActualisation,
				    appendCompositeOnlineFC = Table.Combine({Source, SRIVcompositeOnlineForecastDispatchActualised}),
				    #"Pivoted Column" = Table.Pivot(appendCompositeOnlineFC, List.Distinct(appendCompositeOnlineFC[channel]), "channel", "sriv", List.Sum),
				    FillNulls = Table.ReplaceValue(#"Pivoted Column",null,0,Replacer.ReplaceValue,{"01", "05", "03"}),
				    RenameTempRetail = Table.RenameColumns(FillNulls,{{"01", "01 - temp"}}),
				    RetailMinusOnline = Table.AddColumn(RenameTempRetail, "01", each [#"01 - temp"] - [03]),
				    MakeDecimal = Table.TransformColumnTypes(RetailMinusOnline,{{"01", type number}}),
				    RemoveTempRetail = Table.RemoveColumns(MakeDecimal,{"01 - temp"}),
				    UnpivotChannel = Table.UnpivotOtherColumns(RemoveTempRetail, {"fiscalWeek", "plan", "product", "siteID", "fp_rp_ind"}, "channel", "sriv"),
				    #"Grouped Rows" = Table.Group(UnpivotChannel, {"fiscalWeek", "plan", "product", "siteID", "fp_rp_ind", "channel"}, {{"sriv", each List.Sum([sriv]), type number}})
				in
				    #"Grouped Rows"

	annotation PBI_ResultType = Table

