table factDeriskBudget
	lineageTag: d23891cc-121f-418a-a725-b50991c441db

	measure sum_GSM_derisk_BUD = SUM(factDeriskBudget[GSM])
		lineageTag: 079f090f-1a40-4b96-b901-723ae55efdc2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure sum_SREV_derisk_BUD = SUM ( 'factDeriskBudget'[SREV] )
		lineageTag: eca05bf4-f908-44f3-83f9-f0dfbeac31d9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure sum_SRIV_derisk_BUD = SUM ( 'factDeriskBudget'[SRIV] )
		lineageTag: db53d046-b3df-4ae8-9c87-4b176537020c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_type
		dataType: string
		lineageTag: b9dccbc1-fab0-45e9-b12e-41b9b1b078a4
		summarizeBy: none
		sourceColumn: sales_type

		annotation SummarizationSetBy = Automatic

	column fiscalWeek
		dataType: int64
		formatString: 0
		lineageTag: de7cffde-da95-4ad5-8377-d0a7db88ae06
		summarizeBy: none
		sourceColumn: fiscalWeek

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: d0775a90-6855-4d3f-a285-58186da54e25
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column GSM
		dataType: double
		lineageTag: 8529b66f-ee78-4d59-9209-577a1d911b1b
		summarizeBy: sum
		sourceColumn: GSM

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SREV
		dataType: double
		isHidden
		lineageTag: 5e7938e4-d086-4a33-b37b-49174f5b99d7
		summarizeBy: sum
		sourceColumn: SREV

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SRIV
		dataType: double
		isHidden
		lineageTag: cde31cb8-1bfb-4689-a2a6-b9b838be17ce
		summarizeBy: sum
		sourceColumn: SRIV

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dept
		dataType: string
		lineageTag: af4dcc0e-c743-4313-abeb-690927833152
		summarizeBy: none
		sourceColumn: dept

		annotation SummarizationSetBy = Automatic

	column siteID
		dataType: int64
		formatString: 0
		lineageTag: cbce8595-6bf6-4b56-9b24-7ef1afd5f1a7
		summarizeBy: none
		sourceColumn: siteID

		annotation SummarizationSetBy = Automatic

	partition factDeriskBudget = m
		mode: import
		queryGroup: 'Other fact tables'
		source =
				let
				    Source = PowerBI.Dataflows(null),
				    #"1e21bb0e-7319-4d52-a1b9-84f8819e9fa0" = Source{[workspaceId="1e21bb0e-7319-4d52-a1b9-84f8819e9fa0"]}[Data],
				    #"bf447173-6542-484b-a2ea-78c25d75e485" = #"1e21bb0e-7319-4d52-a1b9-84f8819e9fa0"{[dataflowId="bf447173-6542-484b-a2ea-78c25d75e485"]}[Data],
				    #"Derisk Forecast" = #"bf447173-6542-484b-a2ea-78c25d75e485"{[entity="Derisk Budget"]}[Data]
				in
				    #"Derisk Forecast"

	annotation PBI_ResultType = Table

