table factTradingCommentary
	lineageTag: 25a6ddfe-bf6b-4207-a069-4e2cb4437bce

	measure SelectedCommentary = SELECTEDVALUE(factTradingCommentary[Commentary])
		lineageTag: 82af5454-c20f-4a42-89fb-b69addde760d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure tiTradingCommentary = [tiWeekNo] & " - Clothing & Home Trading Commentary"
		lineageTag: 07d5430c-1767-44d3-88be-a41e70b11d93

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CommentaryWeekNo
		dataType: int64
		formatString: 0
		lineageTag: 1d09f132-573e-4748-af93-71081b426a06
		summarizeBy: none
		sourceColumn: CommentaryWeekNo

		annotation SummarizationSetBy = User

	column CommentaryType
		dataType: string
		lineageTag: 00b4cde5-94b8-4bcd-99da-39486d758e7e
		summarizeBy: none
		sourceColumn: CommentaryType
		sortByColumn: CommentaryRank

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Commentary
		dataType: string
		lineageTag: c6a451b3-a86f-4714-b500-e95f0f7c413e
		summarizeBy: none
		sourceColumn: Commentary

		annotation SummarizationSetBy = Automatic

	column CommentaryWeeksToShow =
			if(factTradingCommentary[CommentaryWeekNo]=[LatestSalesFiscalWeek],"This Week",
			if(factTradingCommentary[CommentaryWeekNo]=[LatestSalesFiscalWeek]+1,"Next Week",
			if(factTradingCommentary[CommentaryWeekNo]=[LatestSalesFiscalWeek]+2,"Week " & factTradingCommentary[CommentaryWeekNo] - 202400,
			if(factTradingCommentary[CommentaryWeekNo]=[LatestSalesFiscalWeek]+3,"Week " & factTradingCommentary[CommentaryWeekNo] - 202400,"Other (Week " & factTradingCommentary[CommentaryWeekNo] - 202400 & ")"))))
		lineageTag: 79075318-1f65-4ada-ba16-6a76dc941e3b
		summarizeBy: none
		sortByColumn: CommentaryWeeksRank

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column CommentaryRank
		dataType: int64
		formatString: 0
		lineageTag: 4769cd70-8f71-48af-85af-94a96e99fe2d
		summarizeBy: sum
		sourceColumn: CommentaryRank

		annotation SummarizationSetBy = Automatic

	column CommentaryWeeksRank =
			if(factTradingCommentary[CommentaryWeekNo]=[LatestSalesFiscalWeek],1,
			if(factTradingCommentary[CommentaryWeekNo]=[LatestSalesFiscalWeek]+1,2,
			if(factTradingCommentary[CommentaryWeekNo]=[LatestSalesFiscalWeek]+2,3,
			if(factTradingCommentary[CommentaryWeekNo]=[LatestSalesFiscalWeek]+3,4,factTradingCommentary[CommentaryWeekNo] - 202400+60))))
		formatString: 0
		lineageTag: 85b7429e-86c0-4218-ba72-31172385c958
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition factTradingCommentary-feb0d1b0-cc1e-4ce2-9ad0-98f48209dab5 = m
		mode: import
		queryGroup: 'Other fact tables'
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"1e21bb0e-7319-4d52-a1b9-84f8819e9fa0" = Workspaces{[workspaceId="1e21bb0e-7319-4d52-a1b9-84f8819e9fa0"]}[Data],
				    #"b736db3b-f191-4520-a8a3-8936b071a054" = #"1e21bb0e-7319-4d52-a1b9-84f8819e9fa0"{[dataflowId="b736db3b-f191-4520-a8a3-8936b071a054"]}[Data],
				    #"Trading Commentary_" = #"b736db3b-f191-4520-a8a3-8936b071a054"{[entity="Trading Commentary",version=""]}[Data]
				in
				    #"Trading Commentary_"

	annotation PBI_ResultType = Table

