table MarginBridgeVariable
	lineageTag: 27ba757b-db4b-4aec-b2b2-25e42214041a

	/// This measure is the SELECTEDVALUE of column 'BridgeMetricVariable'[Variable]
	measure slctd_Variable = SELECTEDVALUE ( 'MarginBridgeVariable'[Variable] )
		lineageTag: d2f330df-390f-4edf-ac03-61da4b5a7334

	column Variable
		dataType: string
		lineageTag: e0dbdee6-0efb-4031-acd5-ce1db7fc66c2
		summarizeBy: none
		sourceColumn: Variable
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 1f27b7da-001f-4afc-b471-83b0cc4acf02
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition MarginBridgeVariable-a1b4f293-cbe8-47d3-af11-0b80d7a8bb5c = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCsvPUYrViVZyC4gpNTAwMgtQ8M2sAIs4efqC6QD/YDDtku8MpsMcQ5RiYwE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Variable = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Variable", type text}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type", "Index", 1, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_ResultType = Table

