table ReturnsBridge
	lineageTag: 0a2e3c77-ed49-4c46-a331-d3310b4c68a2

	column Item
		dataType: string
		lineageTag: 6b8e01aa-4fd6-4134-9cb6-f2827191b5af
		summarizeBy: none
		sourceColumn: Item
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 3282b864-bf4b-4f1a-ac10-f0ae7bfd3375
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition ReturnsBridge-0cf1802b-1c2c-4846-a3e4-6669b24d5e71 = m
		mode: import
		queryGroup: 'Dimension tables'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8olUitWJVnIqSsxLKQYznTMS8/JScxR8MyvA/ICi/JTS5BI4PyixJBXM8C/JSC0Cs0KAhsQCAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Item = _t]),
				    #"Added Index" = Table.AddIndexColumn(Source, "Index", 1, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_ResultType = Table

