DEFINE
	VAR __DS0FilterTable = 
		FILTER(
			KEEPFILTERS(VALUES('IntakeMeasureSelection'[IntakeMeasureSelection])),
			AND(
				NOT('IntakeMeasureSelection'[IntakeMeasureSelection] IN {"FP&P Intake Vol"}),
				'IntakeMeasureSelection'[IntakeMeasureSelection] IN {"FP&P Sales",
					"FP&P Intake"}
			)
		)

	VAR __DS0FilterTable2 = 
		TREATAS({"QTD",
			"QTG"}, 'Time Period'[Time Period])

	VAR __DS0FilterTable3 = 
		TREATAS({"Order"}, 'SalesRecognitionType'[SalesRecognitionType])

	VAR __DS0FilterTable4 = 
		TREATAS({"LY"}, 'ComparatorMaster'[Comparator])

	VAR __DS0FilterTable5 = 
		TREATAS({4}, 'RollingWeeks'[WeeksRolling])

	VAR __DS0FilterTable6 = 
		TREATAS({"UK"}, 'Company Code'[Country])

	VAR __DS0FilterTable7 = 
		FILTER(
			KEEPFILTERS(VALUES('Stores'[worldwideHierName])),
			NOT('Stores'[worldwideHierName] IN {"International Website"})
		)

	VAR __DS0FilterTable8 = 
		TREATAS({"M&S C&H"}, 'Stores'[M&S/Other])

	VAR __DS0FilterTable9 = 
		FILTER(
			KEEPFILTERS(VALUES('Calendar'[Week])),
			NOT('Calendar'[Week] IN {BLANK()})
		)

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			'IntakeMeasureSelection'[IntakeMeasureSelection],
			'IntakeMeasureSelection'[Index],
			'Time Period'[Time Period],
			'Time Period'[Order],
			__DS0FilterTable,
			__DS0FilterTable2,
			__DS0FilterTable3,
			__DS0FilterTable4,
			__DS0FilterTable5,
			__DS0FilterTable6,
			__DS0FilterTable7,
			__DS0FilterTable8,
			__DS0FilterTable9,
			"Intake_ACT", 'IntakeMeasureSelection'[Intake_ACT],
			"v_Intake_ACT_FormatString", IGNORE('IntakeMeasureSelection'[_Intake_ACT FormatString]),
			"Intake_Var", 'IntakeMeasureSelection'[Intake_Var],
			"v_Intake_Var_FormatString", IGNORE('IntakeMeasureSelection'[_Intake_Var FormatString]),
			"Intake_Var__", 'IntakeMeasureSelection'[Intake_Var %],
			"v_Intake_Var___FormatString", IGNORE('IntakeMeasureSelection'[_Intake_Var % FormatString])
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(
			101,
			SUMMARIZE(
				__DS0Core,
				'IntakeMeasureSelection'[IntakeMeasureSelection],
				'IntakeMeasureSelection'[Index]
			),
			'IntakeMeasureSelection'[Index],
			1,
			'IntakeMeasureSelection'[IntakeMeasureSelection],
			1
		)

	VAR __DS0SecondaryBase = 
		SUMMARIZE(__DS0Core, 'Time Period'[Time Period], 'Time Period'[Order])

	VAR __DS0Secondary = 
		TOPN(102, __DS0SecondaryBase, 'Time Period'[Order], 1, 'Time Period'[Time Period], 1)

	VAR __DS0BodyLimited = 
		NATURALLEFTOUTERJOIN(
			__DS0PrimaryWindowed,
			SUBSTITUTEWITHINDEX(
				__DS0Core,
				"ColumnIndex",
				__DS0Secondary,
				'Time Period'[Order],
				ASC,
				'Time Period'[Time Period],
				ASC
			)
		)

EVALUATE
	__DS0Secondary

ORDER BY
	'Time Period'[Order], 'Time Period'[Time Period]

EVALUATE
	__DS0BodyLimited

ORDER BY
	'IntakeMeasureSelection'[Index],
	'IntakeMeasureSelection'[IntakeMeasureSelection],
	[ColumnIndex]