table 1_Measures
	lineageTag: d97aaabe-4111-4467-96bb-44dee1403021

	/// This measure is the sum of column 'factSalesOrders'[sriv]
	measure 'SRIV Orders' = SUM ( 'factSalesOrders'[sriv] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\Actual
		lineageTag: 99a0976b-2954-4a7f-87c3-d564ec619907

	measure 'SRIV Orders LY' =
			CALCULATE (
			    [SRIV Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\LY
		lineageTag: 995ed551-5b19-4f65-9e26-2d0ca7f994f4

	measure 'SRIV Orders LY-1' =
			CALCULATE (
			    [SRIV Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of SRIV Orders LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\LY-1
		lineageTag: c36d04a8-00c1-487a-a4eb-bfff292476e5

	measure 'SRIV Orders LW' =
			CALCULATE (
			    [SRIV Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\LW
		lineageTag: 1ff10f1f-dbab-4ae6-9829-30dd9e170592

	/// This measure is the sum of column 'factSalesOrders'[gsm]
	measure 'GSM Orders' = SUM ( 'factSalesOrders'[gsm] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\GSM\Actual
		lineageTag: ef8b4df1-a042-4673-8278-5d648290bf9f

	measure 'GSM Orders LY' =
			CALCULATE (
			    [GSM Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\GSM\LY
		lineageTag: 5c7599d5-6fbb-4b81-8c26-9b14a309410d

	measure 'GSM Orders LY-1' =
			CALCULATE (
			    [GSM Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of GSM Orders LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\GSM\LY-1
		lineageTag: d4ed61bd-6d3e-4c1f-b53a-5917dcc72b34

	measure 'GSM Orders LW' =
			CALCULATE (
			    [GSM Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\GSM\LW
		lineageTag: 8ddab1ac-6464-4fdc-8c9e-56dc6bd86042

	/// This measure is column [GSM Orders] as a % of SREV
	measure 'GSM % SREV Orders' =
			VAR metric = [GSM Orders]
			VAR sales = [SREV Orders]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\GSM\Actual
		lineageTag: c820b12f-c939-4897-8bab-cd2d3eac7279

	measure 'SRIV Orders vs LY' =
			VAR act = [SRIV Orders]
			VAR comp = [SRIV Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\LY
		lineageTag: 1f9208d2-82b4-4b2b-9f08-cb0cd48c3f0b

	measure 'SRIV Orders vs LY-1' =
			VAR act = [SRIV Orders]
			VAR comp = [SRIV Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of SRIV Orders vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\LY-1
		lineageTag: 9cccf8d2-ed8a-4f00-8b29-1ac6a904a1b3

	measure 'SRIV Orders vs LW' =
			VAR act = [SRIV Orders]
			VAR comp = [SRIV Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\LW
		lineageTag: 5fa23f8a-f7c4-4a1a-bb4c-1b553e021e49

	measure 'GSM Orders vs LW' =
			VAR act = [GSM Orders]
			VAR comp = [GSM Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\GSM\LW
		lineageTag: 6975a71f-ffc6-4ffa-8091-0dd363df0a6b

	measure 'GSM Orders vs LY' =
			VAR act = [GSM Orders]
			VAR comp = [GSM Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\GSM\LY
		lineageTag: 2eb6d2c9-cec2-455f-a29e-8757381ff9a3

	measure 'GSM Orders vs LY-1' =
			VAR act = [GSM Orders]
			VAR comp = [GSM Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of GSM Orders vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\GSM\LY-1
		lineageTag: 36ed1171-a733-455a-a423-f4928bb21332

	/// This measure is the sum of column 'factSalesOrders'[srev]
	measure 'SREV Orders' = SUM ( 'factSalesOrders'[srev] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SREV\Actual
		lineageTag: 4663a0ae-826b-4f02-8630-219d9fc1946b

	measure 'SREV Orders LY' =
			CALCULATE (
			    [SREV Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SREV\LY
		lineageTag: e5d5fbe8-3553-46f5-b9a3-2de767133617

	measure 'SREV Orders LY-1' =
			CALCULATE (
			    [SREV Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of SREV Orders LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SREV\LY-1
		lineageTag: ca5f3625-87ef-4fbb-81be-8e444e31494c

	measure 'SREV Orders LW' =
			CALCULATE (
			    [SREV Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SREV\LW
		lineageTag: 7d290224-fd1f-4786-8c35-b9aa8477e9cf

	/// This measure is column [GSM Orders LY] as a % of SREV
	measure 'GSM % SREV Orders LY' =
			VAR metric = [GSM Orders LY]
			VAR sales = [SREV Orders LY]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Orders\GSM\LY
		lineageTag: 8b075d46-7ec9-4ec3-9411-4fecc00e7ffb

	measure 'GSM % SREV Orders LY-1' =
			VAR metric = [GSM Orders LY-1]
			VAR sales = [SREV Orders LY-1]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		description: Two years ago equivalent of GSM % SREV Orders LY.
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Orders\GSM\LY-1
		lineageTag: 43eba079-0d6f-46c6-afbe-ac5b392a2ba9

	/// This measure is column [GSM Orders LW] as a % of SREV
	measure 'GSM % SREV Orders LW' =
			VAR metric = [GSM Orders LW]
			VAR sales = [SREV Orders LW]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\GSM\LW
		lineageTag: 2c403c4b-88bd-43d1-9d81-f509c98bc57b

	measure 'SREV Orders vs LY' =
			VAR act = [SREV Orders]
			VAR comp = [SREV Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SREV\LY
		lineageTag: ea86e07a-eb04-4841-8906-1ed3812092af

	measure 'SREV Orders vs LY-1' =
			VAR act = [SREV Orders]
			VAR comp = [SREV Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of SREV Orders vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SREV\LY-1
		lineageTag: 0ba3b781-dfbc-45e1-bc2e-366a1205169e

	measure 'SREV Orders vs LW' =
			VAR act = [SREV Orders]
			VAR comp = [SREV Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SREV\LW
		lineageTag: 50ecce0a-4634-467b-a216-a06309120f6f

	measure 'GSM % SREV Orders vs LY' =
			VAR act = [GSM % SREV Orders]
			VAR comp = [GSM % SREV Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\GSM\LY
		lineageTag: 10c77011-68c7-4576-bff7-a6ef81f0473f

	measure 'GSM % SREV Orders vs LY-1' =
			VAR act = [GSM % SREV Orders]
			VAR comp = [GSM % SREV Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of GSM % SREV Orders vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\GSM\LY-1
		lineageTag: 243798bb-a788-4a41-9bcf-d434d96552cf

	measure 'GSM % SREV Orders vs LW' =
			VAR act = [GSM % SREV Orders]
			VAR comp = [GSM % SREV Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\GSM\LW
		lineageTag: 63275eab-2ceb-45c1-a74b-d455e5b8632e

	/// This measure is the sum of column 'factSalesDispatch[Sales Revenue (Inc VAT)]'
	measure 'SRIV Dispatch' =
			VAR sale_type = [slctd_SalesTypeLevelAware]
			VAR result =
			    SWITCH (
			        sale_type,
			        "Total", [sum_Sales Revenue (Inc VAT)],
			        "FP&P", [FPP SRIV Dispatch],
			        "Full Price", [FP SRIV Dispatch],
			        "Promo", [P SRIV Dispatch],
			        "Reduced", [RP SRIV Dispatch],
			        [sum_Sales Revenue (Inc VAT)]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\Actual
		lineageTag: bc377f53-db0d-415a-8fc6-cf76e9a1b9cf

	measure 'SRIV Dispatch LY' =
			CALCULATE (
			    [SRIV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\LY
		lineageTag: 82425818-0c85-4502-b9dc-b46068c86bbd

	measure 'SRIV Dispatch LY-1' =
			CALCULATE (
			    [SRIV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of SRIV Dispatch LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\LY-1
		lineageTag: b8961573-f9e2-4d21-a809-986f33e4f6d6

	measure 'SRIV Dispatch LW' =
			CALCULATE (
			    [SRIV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\LW
		lineageTag: 85b57154-742b-4e35-8104-2faae6d04cf3

	measure 'SRIV Dispatch vs LY' =
			VAR act = [SRIV Dispatch]
			VAR comp = [SRIV Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\LY
		lineageTag: a7c50678-4308-4c55-b915-fa924bce8783

	measure 'SRIV Dispatch vs LY-1' =
			VAR act = [SRIV Dispatch]
			VAR comp = [SRIV Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of SRIV Dispatch vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\LY-1
		lineageTag: f844bde1-c9f4-4f23-8aa9-157fdba73489

	measure 'SRIV Dispatch vs LW' =
			VAR act = [SRIV Dispatch]
			VAR comp = [SRIV Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\LW
		lineageTag: 978fc70d-5c1d-41df-af89-e966aeca9c93

	/// This measure is the sum of column 'factSalesDispatch[Sales Revenue (Exc VAT)]'
	measure 'SREV Dispatch' = SUM ( factSalesDispatch[Sales Revenue (Exc VAT)] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SREV\Actual
		lineageTag: 71ade7c0-b1fc-4700-9a4f-8c66495fd721

	measure 'SREV Dispatch LY' =
			CALCULATE (
			    [SREV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SREV\LY
		lineageTag: 78db5f0e-2d95-42a7-87cf-2d417b66a0d0

	measure 'SREV Dispatch LY-1' =
			CALCULATE (
			    [SREV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of SREV Dispatch LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SREV\LY-1
		lineageTag: a1106935-1ae4-47ac-b7b6-349605dc8a94

	measure 'SREV Dispatch LW' =
			CALCULATE (
			    [SREV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SREV\LW
		lineageTag: 6e2d9820-618c-4124-a2c0-3a2ba98b3eab

	measure 'SREV Dispatch vs LY' =
			VAR act = [SREV Dispatch]
			VAR comp = [SREV Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SREV\LY
		lineageTag: 3e0cae06-1823-4859-999a-938afbfa7661

	measure 'SREV Dispatch vs LY-1' =
			VAR act = [SREV Dispatch]
			VAR comp = [SREV Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of SREV Dispatch vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SREV\LY-1
		lineageTag: 761e61b2-4817-441d-b783-f4a98f428d0f

	measure 'SREV Dispatch vs LW' =
			VAR act = [SREV Dispatch]
			VAR comp = [SREV Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SREV\LW
		lineageTag: 6cfdef9d-9cce-400e-9fb1-6551eabed7ce

	/// This measure is the sum of column 'factSalesDispatch[Gross Selling Margin]'
	measure 'GSM Dispatch' = SUM ( factSalesDispatch[Gross Selling Margin] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\GSM\Actual
		lineageTag: 5e13ad9b-ae9c-44d9-861c-63e88e62d263

	measure 'GSM Dispatch LY' =
			CALCULATE (
			    [GSM Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\GSM\LY
		lineageTag: 5dae07e0-db9c-4310-b545-e74d233f2b6c

	measure 'GSM Dispatch LY-1' =
			CALCULATE (
			    [GSM Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of GSM Dispatch LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\GSM\LY-1
		lineageTag: 583c179e-4e6f-4579-a880-eae4ad686335

	measure 'GSM Dispatch LW' =
			CALCULATE (
			    [GSM Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\GSM\LW
		lineageTag: 637fbc33-92c2-4b8e-9bd8-00858b7ef401

	measure 'GSM Dispatch vs LY' =
			VAR act = [GSM Dispatch]
			VAR comp = [GSM Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\GSM\LY
		lineageTag: 8dd96c57-306c-409d-bb1d-b8255ef2cc28

	measure 'GSM Dispatch vs LY-1' =
			VAR act = [GSM Dispatch]
			VAR comp = [GSM Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of GSM Dispatch vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\GSM\LY-1
		lineageTag: c43cb7bb-1458-4753-be1f-3aeae28b6524

	measure 'GSM Dispatch vs LW' =
			VAR act = [GSM Dispatch]
			VAR comp = [GSM Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\GSM\LW
		lineageTag: 912fa55c-0bcd-49eb-8a3d-72956debfe52

	/// This measure is column [GSM Dispatch] as a % of SREV
	measure 'GSM % SREV Dispatch' =
			VAR metric = [GSM Dispatch]
			VAR sales = [SREV Dispatch]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\GSM\Actual
		lineageTag: 6d2132b2-1428-4ff5-8043-f9a581166bd2

	/// This measure is column [GSM Dispatch LY] as a % of SREV
	measure 'GSM % SREV Dispatch LY' =
			VAR metric = [GSM Dispatch LY]
			VAR sales = [SREV Dispatch LY]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\GSM\LY
		lineageTag: 8e6417ba-5af6-41cf-b5fe-33a67f03fdf5

	measure 'GSM % SREV Dispatch LY-1' =
			VAR metric = [GSM Dispatch LY-1]
			VAR sales = [SREV Dispatch LY-1]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		description: Two years ago equivalent of GSM % SREV Dispatch LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\GSM\LY-1
		lineageTag: 149a7618-494e-4321-b163-fbe612f4a9ed

	/// This measure is column [GSM Dispatch LW] as a % of SREV
	measure 'GSM % SREV Dispatch LW' =
			VAR metric = [GSM Dispatch LW]
			VAR sales = [SREV Dispatch LW]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\GSM\LW
		lineageTag: 27c1d980-575f-4b1d-91c9-661fac8c4f9f

	measure 'GSM % SREV Dispatch vs LY' =
			VAR act = [GSM % SREV Dispatch]
			VAR comp = [GSM % SREV Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\GSM\LY
		lineageTag: 8a96ff6a-549d-4c5f-8927-a71609cb9d1d

	measure 'GSM % SREV Dispatch vs LY-1' =
			VAR act = [GSM % SREV Dispatch]
			VAR comp = [GSM % SREV Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of GSM % SREV Dispatch vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\GSM\LY-1
		lineageTag: ed0e95ae-89e1-427e-a20c-6a9dbcb58189

	measure 'GSM % SREV Dispatch vs LW' =
			VAR act = [GSM % SREV Dispatch]
			VAR comp = [GSM % SREV Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\GSM\LW
		lineageTag: e54ae4dc-f8a3-410d-8c01-4cdea885fed5

	/// This measure is the sum of column 'factSalesDispatch[Full Price Sales (Inc VAT)]'
	measure 'FPP SRIV Dispatch' = SUM ( factSalesDispatch[Full Price Sales Revenue (Inc VAT)] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP SRIV\Actual
		lineageTag: 006ebb42-dbc8-4131-b1e2-23765b652eef

	measure 'FPP SRIV Dispatch LY' =
			CALCULATE (
			    [FPP SRIV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP SRIV\LY
		lineageTag: 7ec41f69-9bdd-4104-a3f4-1f7d0d316be2

	measure 'FPP SRIV Dispatch LY-1' =
			CALCULATE (
			    [FPP SRIV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of FPP SRIV Dispatch LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP SRIV\LY-1
		lineageTag: 7adaedd1-c3b8-4f92-a4d5-7a89aed08b4b

	measure 'FPP SRIV Dispatch LW' =
			CALCULATE (
			    [FPP SRIV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP SRIV\LW
		lineageTag: be51b370-723a-4fda-be80-433ccf267e38

	measure 'FPP SRIV Dispatch vs LY' =
			VAR act = [FPP SRIV Dispatch]
			VAR comp = [FPP SRIV Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP SRIV\LY
		lineageTag: 1ddc0d22-d43b-4616-9104-05308159bc23

	measure 'FPP SRIV Dispatch vs LY-1' =
			VAR act = [FPP SRIV Dispatch]
			VAR comp = [FPP SRIV Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of FPP SRIV Dispatch vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP SRIV\LY-1
		lineageTag: eaa1b8d3-d8ba-4576-be2c-83c70407d46a

	measure 'FPP SRIV Dispatch vs LW' =
			VAR act = [FPP SRIV Dispatch]
			VAR comp = [FPP SRIV Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP SRIV\LW
		lineageTag: f372aa1f-f4cb-465b-9d31-f1db71f4288c

	/// This measure is the sum of column 'factSalesDispatch[Reduced Price Sales (Inc VAT)]'
	measure 'RP SRIV Dispatch' = SUM ( factSalesDispatch[Reduced Price Sales Revenue (Inc VAT)] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP SRIV\Actual
		lineageTag: 430da113-b009-4322-9781-ab484c569884

	measure 'RP SRIV Dispatch LY' =
			CALCULATE (
			    [RP SRIV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP SRIV\LY
		lineageTag: 97835f04-7eea-4891-a65c-58646ee150ba

	measure 'RP SRIV Dispatch LY-1' =
			CALCULATE (
			    [RP SRIV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of RP SRIV Dispatch LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP SRIV\LY-1
		lineageTag: 3e79d0b7-0d06-4fd8-be60-5ead397f8a77

	measure 'RP SRIV Dispatch LW' =
			CALCULATE (
			    [RP SRIV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP SRIV\LW
		lineageTag: 5a693209-7719-41df-aaab-feb1e414e41c

	measure 'RP SRIV Dispatch vs LY' =
			VAR act = [RP SRIV Dispatch]
			VAR comp = [RP SRIV Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP SRIV\LY
		lineageTag: a1d1ce2b-4ffb-4f8d-9d6f-041f97fd2d05

	measure 'RP SRIV Dispatch vs LY-1' =
			VAR act = [RP SRIV Dispatch]
			VAR comp = [RP SRIV Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of RP SRIV Dispatch vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP SRIV\LY-1
		lineageTag: 2be66493-499a-4dba-82b5-77cbc92be969

	measure 'RP SRIV Dispatch vs LW' =
			VAR act = [RP SRIV Dispatch]
			VAR comp = [RP SRIV Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP SRIV\LW
		lineageTag: 86c14738-5bdd-403a-bb2b-2b53552093be

	measure 'SRIV Orders vs LY %' =
			VAR act = [SRIV Orders]
			VAR comp = [SRIV Orders LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\SRIV\LY
		lineageTag: a7bc596d-8f7e-4d83-a798-d25a166267e8

	measure 'SRIV Orders vs LW %' =
			VAR act = [SRIV Orders]
			VAR comp = [SRIV Orders LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\SRIV\LW
		lineageTag: 6d81ef27-2e16-4f57-9653-53cb666ebd4d

	measure 'GSM Orders vs LY %' =
			VAR act = [GSM Orders]
			VAR comp = [GSM Orders LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\GSM\LY
		lineageTag: 95da5530-29e4-4ec5-bacf-941512d5d045

	measure 'GSM Orders vs LW %' =
			VAR act = [GSM Orders]
			VAR comp = [GSM Orders LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\GSM\LW
		lineageTag: 7f8ae598-56fd-46ea-9c94-6b550dab726c

	measure 'SREV Orders vs LY %' =
			VAR act = [SREV Orders]
			VAR comp = [SREV Orders LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\SREV\LY
		lineageTag: cea6e347-67da-4079-8b39-0f4a4bd18f7d

	measure 'SREV Orders vs LW %' =
			VAR act = [SREV Orders]
			VAR comp = [SREV Orders LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\SREV\LW
		lineageTag: b77abd54-0cfd-492e-828e-3ec200b9bbe2

	measure 'SRIV Channel Orders BUD' =
			VAR result = [SRIV Orders BUD]
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\BUD
		lineageTag: a5ad3382-6891-4e45-bafa-6fd0f4c2b750

	measure 'SRIV Channel Orders vs BUD' =
			VAR act = [SRIV Orders]
			VAR comp = [SRIV Channel Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\BUD
		lineageTag: 38bb6d27-7717-4d5a-921b-2fae07a4d92e

	measure 'SRIV Channel Orders vs BUD %' =
			VAR act = [SRIV Orders]
			VAR comp = [SRIV Channel Orders BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\SRIV\BUD
		lineageTag: e73885ab-15a5-4dae-b547-31abd757d423

	measure 'SRIV Channel Orders FC' =
			VAR result = [SRIV Orders FC]
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\FC
		lineageTag: 5d59c5dc-bea5-4c0b-b7f8-8a1be0398f20

	measure 'SRIV Channel Orders vs FC' =
			VAR act = [SRIV Orders]
			VAR comp = [SRIV Channel Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\FC
		lineageTag: 09fee25f-24a3-4b12-9658-fc5141893b99

	measure 'SRIV Channel Orders vs FC %' =
			VAR act = [SRIV Orders]
			VAR comp = [SRIV Channel Orders FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\SRIV\FC
		lineageTag: a31ca7eb-253b-4689-b3ac-abe8e172bb6a

	measure 'SRIV Dispatch vs LY %' =
			VAR act = [SRIV Dispatch]
			VAR comp = [SRIV Dispatch LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\SRIV\LY
		lineageTag: 449fcbd6-f607-437b-a864-3b3e44ec66b4

	measure 'SRIV Dispatch vs LW %' =
			VAR act = [SRIV Dispatch]
			VAR comp = [SRIV Dispatch LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\SRIV\LW
		lineageTag: 269a2c4f-4b16-42cb-8ccb-4d206c5bbf61

	measure 'SREV Dispatch vs LY %' =
			VAR act = [SREV Dispatch]
			VAR comp = [SREV Dispatch LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\SREV\LY
		lineageTag: 2b17593e-eee3-4710-bb98-6337c7176cab

	measure 'SREV Dispatch vs LW %' =
			VAR act = [SREV Dispatch]
			VAR comp = [SREV Dispatch LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\SREV\LW
		lineageTag: 3c0e7572-3437-4177-b271-374e3cf77060

	measure 'GSM Dispatch vs LY %' =
			VAR act = [GSM Dispatch]
			VAR comp = [GSM Dispatch LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\GSM\LY
		lineageTag: db0100a3-3fde-4f26-917e-c81375a8d4ba

	measure 'GSM Dispatch vs LW %' =
			VAR act = [GSM Dispatch]
			VAR comp = [GSM Dispatch LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\GSM\LW
		lineageTag: c11b8c6f-3c4c-45ff-a279-13c607b36b7e

	measure 'FPP SRIV Dispatch vs LY %' =
			VAR act = [FPP SRIV Dispatch]
			VAR comp = [FPP SRIV Dispatch LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\FPP SRIV\LY
		lineageTag: 2e0ca5be-4f51-4d70-bddf-aefda37d7652

	measure 'FPP SRIV Dispatch vs LW %' =
			VAR act = [FPP SRIV Dispatch]
			VAR comp = [FPP SRIV Dispatch LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\FPP SRIV\LW
		lineageTag: 586f75c7-05ae-4bfb-a68e-3d90f51059ad

	measure 'RP SRIV Dispatch vs LY %' =
			VAR act = [RP SRIV Dispatch]
			VAR comp = [RP SRIV Dispatch LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\RP SRIV\LY
		lineageTag: 2f64c4ad-d09d-4431-bef1-c3b8e9dea068

	measure 'RP SRIV Dispatch vs LW %' =
			VAR act = [RP SRIV Dispatch]
			VAR comp = [RP SRIV Dispatch LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\RP SRIV\LW
		lineageTag: 1859c3c2-960d-4dbc-b90e-8a6dab185d87

	measure SRIV =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [SRIV Orders],
			        "Dispatch", [SRIV Dispatch],
			        [SRIV Orders]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\Actual
		lineageTag: 335492c8-1fa2-4da6-8db1-6d8bbb9b6204

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'SRIV LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [SRIV Orders LY],
			        "Dispatch", [SRIV Dispatch LY],
			        [SRIV Orders LY]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\LY
		lineageTag: 751bdc45-1e0e-49c4-86c9-6cde5f5817ce

	measure 'SRIV LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [SRIV Orders LY-1],
			        "Dispatch", [SRIV Dispatch LY-1],
			        [SRIV Orders LY-1]
			    )
			RETURN
			    result
		description: Two years ago equivalent of SRIV LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\LY-1
		lineageTag: aec295a7-adaa-4031-bbee-6603263131f1

	measure 'SRIV vs LY' =
			VAR act = [SRIV]
			VAR comp = [SRIV LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\LY
		lineageTag: 3f25a36b-123c-4cf6-a342-d38d80a048d8

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'SRIV vs LY-1' =
			VAR act = [SRIV]
			VAR comp = [SRIV LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of SRIV vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\LY-1
		lineageTag: da855622-e857-4332-b179-63d39bc893a7

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'SRIV vs LY %' =
			VAR act = [SRIV]
			VAR comp = [SRIV LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV\LY
		lineageTag: 7f0c367f-bbca-40c9-b0e8-52df8d37382c

	measure 'SRIV LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [SRIV Orders LW],
			        "Dispatch", [SRIV Dispatch LW],
			        [SRIV Orders LW]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\LW
		lineageTag: 5423dab3-e01e-451b-ae3e-e92294f84105

	measure 'SRIV vs LW' =
			VAR act = [SRIV]
			VAR comp = [SRIV LW]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\LW
		lineageTag: 231da81f-bae5-46fa-a8b6-6a5d48f85269

	measure 'SRIV vs LW %' =
			VAR act = [SRIV]
			VAR comp = [SRIV LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV\LW
		lineageTag: 7103edf2-3a40-4fa1-a311-a6d7cae71c94

	measure 'SRIV Channel BUD' = ```
			
			VAR firstweek_yr = [SlctdBudVersion]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    [fiscalWeek] <  firstweek_yr,
			            [SRIV],
			            [SRIV Channel Orders BUD]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] ) 
			
			/*VAR result = [SRIV Channel Orders BUD]
			RETURN
			    result*/
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\BUD
		lineageTag: 76ad9bae-4f68-4c14-bf70-aa6f59433330

	measure 'SRIV Channel vs BUD' =
			VAR act = [SRIV]
			VAR comp = [SRIV Channel BUD]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\BUD
		lineageTag: 36bc6287-48bc-439c-9f7b-71b2d5909423

	measure 'SRIV Channel vs BUD %' =
			VAR act = [SRIV]
			VAR comp = [SRIV Channel BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV\BUD
		lineageTag: 8172f130-1219-450d-a1f8-4c37bd4b1c38

	measure 'SRIV Channel FC' =
			//SelectedWeeks
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR firstweek_qtr = [SlctdFirstWeekQtrFC]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [SRIV],
			            [SRIV Channel Orders FC]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\FC
		lineageTag: 649f0e75-82ef-4116-8607-69776ca444e2

	measure 'SRIV Channel vs FC' =
			VAR act = [SRIV]
			VAR comp = [SRIV Channel FC]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\FC
		lineageTag: f4622610-9ca5-49d2-9aec-22633e3ee4bb

	measure 'SRIV Channel vs FC %' =
			VAR act = [SRIV]
			VAR comp = [SRIV Channel FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV\FC
		lineageTag: 05a1e682-2e35-48b7-aa55-a94c0009ac88

	measure SREV =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [SREV Orders],
			        "Dispatch", [SREV Dispatch],
			        [SREV Orders]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV\Actual
		lineageTag: 7705c861-81b3-41e5-b87d-b5ebbe348e8f

	measure 'SREV LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [SREV Orders LW],
			        "Dispatch", [SREV Dispatch LW],
			        [SREV Orders LW]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV\LW
		lineageTag: ad0bc5fb-b7bd-4502-94b8-de6b2130c8f1

	measure 'SREV vs LW' =
			VAR act = [SREV]
			VAR comp = [SREV LW]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV\LW
		lineageTag: 8a9c005e-baec-4f0f-882a-24c7189f17a6

	measure 'SREV vs LW %' =
			VAR act = [SREV]
			VAR comp = [SREV LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SREV\LW
		lineageTag: 4487958e-cbb9-4541-ae23-11377a56d4a3

	measure 'SREV LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [SREV Orders LY],
			        "Dispatch", [SREV Dispatch LY],
			        [SREV Orders LY]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV\LY
		lineageTag: 1f2f51b6-32b0-48a2-a90d-ed2d80ba4c3d

	measure 'SREV LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [SREV Orders LY-1],
			        "Dispatch", [SREV Dispatch LY-1],
			        [SREV Orders LY-1]
			    )
			RETURN
			    result
		description: Two years ago equivalent of SREV LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV\LY-1
		lineageTag: 0c2821f3-05dc-4b01-b352-2ec0e319dad1

	measure 'SREV vs LY' =
			VAR act = [SREV]
			VAR comp = [SREV LY]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV\LY
		lineageTag: ec057013-75af-41ea-9cfc-e811b7d495af

	measure 'SREV vs LY-1' =
			VAR act = [SREV]
			VAR comp = [SREV LY-1]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		description: Two years ago equivalent of SREV vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV\LY-1
		lineageTag: 50f37c18-6fd2-48a5-889a-a4cdb55cf0a3

	measure 'SREV vs LY %' =
			VAR act = [SREV]
			VAR comp = [SREV LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SREV\LY
		lineageTag: bf601c35-b5de-4e12-9096-3fc97ee647e1

	measure GSM =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [GSM Orders],
			        "Dispatch", [GSM Dispatch],
			        [GSM Orders]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM\Actual
		lineageTag: b50303bf-5c97-4ae4-92e1-1b6711b7fc1c

	measure 'GSM % SREV' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [GSM % SREV Orders],
			        "Dispatch", [GSM % SREV Dispatch],
			        [GSM % SREV Orders]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\Actual
		lineageTag: 3e889df0-431d-4f22-ae81-ad38b40b73eb

	measure 'GSM LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [GSM Orders LY],
			        "Dispatch", [GSM Dispatch LY],
			        [GSM Orders LY]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM\LY
		lineageTag: 33516aa6-51c0-4fbc-bc1f-1f410dc33457

	measure 'GSM LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [GSM Orders LY-1],
			        "Dispatch", [GSM Dispatch LY-1],
			        [GSM Orders LY-1]
			    )
			RETURN
			    result
		description: Two years ago equivalent of GSM LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM\LY-1
		lineageTag: 77b0c2bf-ee60-402d-8136-8fe6b37a69b8

	measure 'GSM vs LY' =
			VAR act = [GSM]
			VAR comp = [GSM LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM\LY
		lineageTag: ccd53a09-11f1-4070-bd34-a26586d7310a

	measure 'GSM vs LY-1' =
			VAR act = [GSM]
			VAR comp = [GSM LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of GSM vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM\LY-1
		lineageTag: 9b196d25-993c-45b0-bf21-0b400510d238

	/// This measure is column [GSM Orders LY] as a % of SREV
	measure 'GSM % SREV LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [GSM % SREV Orders LY],
			        "Dispatch", [GSM % SREV Dispatch LY],
			        [GSM % SREV Orders LY]
			    )
			RETURN
			    result
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\GSM\LY
		lineageTag: f22cbc1b-6509-48b3-a4fd-6bf4ac0d196f

	measure 'GSM % SREV LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [GSM % SREV Orders LY-1],
			        "Dispatch", [GSM % SREV Dispatch LY-1],
			        [GSM % SREV Orders LY-1]
			    )
			RETURN
			    result
		description: Two years ago equivalent of GSM % SREV LY.
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\GSM\LY-1
		lineageTag: bfdf7a57-a8be-4ee2-ac7a-f6e857545a05

	measure 'GSM % SREV vs LY' =
			VAR act = [GSM % SREV]
			VAR comp = [GSM % SREV LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\LY
		lineageTag: bde92874-4b04-4fb1-ada3-2c3bebf2b130

	measure 'GSM % SREV vs LY-1' =
			VAR act = [GSM % SREV]
			VAR comp = [GSM % SREV LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of GSM % SREV vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\LY-1
		lineageTag: f102f2a6-f57f-4b89-8c91-cd857e594789

	measure 'GSM vs LY %' =
			VAR act = [GSM]
			VAR comp = [GSM LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\LY
		lineageTag: af40e4f3-1d93-4832-8715-02f611e84e9f

	measure 'GSM LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [GSM Orders LW],
			        "Dispatch", [GSM Dispatch LW],
			        [GSM Orders LW]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM\LW
		lineageTag: 145e789d-9f61-4d0f-8211-4ef757edb85e

	measure 'GSM vs LW' =
			VAR act = [GSM]
			VAR comp = [GSM LW]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM\LW
		lineageTag: 3fe88536-c76c-4282-8e69-130340fb47cf

	/// This measure is column [GSM Orders LW] as a % of SREV
	measure 'GSM % SREV LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [GSM % SREV Orders LW],
			        "Dispatch", [GSM % SREV Dispatch LW],
			        [GSM % SREV Orders LW]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\LW
		lineageTag: 558e3f4e-f3aa-4bae-9c73-cf2e4a15f85f

	measure 'GSM % SREV vs LW' =
			VAR act = [GSM % SREV]
			VAR comp = [GSM % SREV LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\LW
		lineageTag: 3042cb83-9fed-4882-9550-9cd19ef85a6c

	measure 'GSM vs LW %' =
			VAR act = [GSM]
			VAR comp = [GSM LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\LW
		lineageTag: 9940e5d8-8c7c-4e78-8c10-5cf994959fd8

	measure 'SRIV Channel Orders QRF' = [SRIV Orders QRF]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\QRF
		lineageTag: b87ecd35-3a73-48b6-801e-266f7382f499

	measure 'SRIV Channel Orders vs QRF' =
			VAR act = [SRIV Orders]
			VAR comp = [SRIV Channel Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\QRF
		lineageTag: 62f61ba0-6df5-4135-b652-f43d8536026b

	measure 'SRIV Channel Orders vs QRF %' =
			VAR act = [SRIV Orders]
			VAR comp = [SRIV Channel Orders QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\SRIV\QRF
		lineageTag: c5c92593-4d0a-46ea-8e25-0674277416bb

	measure 'SRIV Channel QRF' =
			//SelectedWeeks
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR firstweek_qtr = [SlctdFirstWeekQtrQRF]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [SRIV],
			            [SRIV Channel Orders QRF]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\QRF
		lineageTag: 9138a989-ecaa-4fd1-8dca-48252f2c4533

	measure 'SRIV Channel vs QRF' =
			VAR act = [SRIV]
			VAR comp = [SRIV Channel QRF]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\QRF
		lineageTag: b6410894-028c-480d-97bb-6afc01d7c989

	measure 'SRIV Channel vs QRF %' =
			VAR act = [SRIV]
			VAR comp = [SRIV Channel QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV\QRF
		lineageTag: 9f1ff2f4-fc14-4646-806b-d481468b648f

	/// This measure is the sum of column 'factSalesDispatch[Sales Revenue (Exc VAT)]'
	measure Returns = ```
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Orders Returns],
			        "Dispatch", [Dispatch Returns],
			        [Orders Returns]
			    )
			RETURN
			    result
			 
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\Actual
		lineageTag: 1a3274bc-dc26-4760-aac2-a3ad662d9282

	measure 'Returns LY' =
			
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Orders Returns LY],
			        "Dispatch", [Dispatch Returns LY],
			        [Orders Returns LY]
			    )
			RETURN
			    result
			
			--Previous Measure--
			/*VAR sale_type = [slctd_SalesType]
			VAR total_returns = [FP Returns LY] + [RP Returns LY]
			VAR result =
			    SWITCH (
			        sale_type,
			        "Total", total_returns,
			        "FP&P", [FP Returns LY],
			        "Reduced", [RP Returns LY],
			        total_returns
			    )
			RETURN
			    result*/
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\LY
		lineageTag: 7a1c874f-fb8f-4c40-bbe6-db326820fbed

	measure 'Returns LY-1' =
			
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Orders Returns LY-1],
			        "Dispatch", [Dispatch Returns LY-1],
			        [Orders Returns LY-1]
			    )
			RETURN
			    result
			
			--Previous Measure--
			/*VAR sale_type = [slctd_SalesType]
			VAR total_returns = [FP Returns LY-1] + [RP Returns LY-1]
			VAR result =
			    SWITCH (
			        sale_type,
			        "Total", total_returns,
			        "FP&P", [FP Returns LY-1],
			        "Reduced", [RP Returns LY-1],
			        total_returns
			    )
			RETURN
			    result*/
		description: Two years ago equivalent of Returns LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\LY-1
		lineageTag: 0e49f52d-e86c-4964-b5ef-9e4afbc206c8

	measure 'Returns vs LY' =
			VAR act = [Returns]
			VAR comp = [Returns LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\LY
		lineageTag: d3ebe8e7-b92c-4b00-a862-64fcc89a4ba0

	measure 'Returns vs LY-1' =
			VAR act = [Returns]
			VAR comp = [Returns LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Returns vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\LY-1
		lineageTag: 3d05c0e2-3bdc-4c9d-8b6d-70cc8c25e26a

	measure 'Returns vs LY %' =
			VAR act = [Returns]
			VAR comp = [Returns LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\LY
		lineageTag: 4c91e946-f6db-4929-8dfa-0164aa05c0c3

	measure 'Returns LW' =
			
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Orders Returns LW],
			        "Dispatch", [Dispatch Returns LW],
			        [Orders Returns LW]
			    )
			RETURN
			    result
			
			--Previous measure--
			
			/*VAR sale_type = [slctd_SalesType]
			VAR total_returns = [FP Returns LW] + [RP Returns LW]
			VAR result =
			    SWITCH (
			        sale_type,
			        "Total", total_returns,
			        "FP&P", [FP Returns LW],
			        "Reduced", [RP Returns LW],
			        total_returns
			    )
			RETURN
			    result*/
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\LW
		lineageTag: 34c58320-42ac-4daf-ba01-269800048f6c

	measure 'Returns vs LW' =
			VAR act = [Returns]
			VAR comp = [Returns LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\LW
		lineageTag: cd2e6417-f62c-435c-a2c2-ea76a08657f5

	measure 'Returns vs LW %' =
			VAR act = [Returns]
			VAR comp = [Returns LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\LW
		lineageTag: aa9d5e66-270c-4779-b058-ef4e0838627c

	/// This measure is the sum of column 'factSalesDispatch[Sales Revenue (Exc VAT)]'
	measure 'FP Returns' = SUM ( factSalesDispatch[Full Price Returns (Inc VAT)] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\FP Returns\Actual
		lineageTag: 50275192-9702-44b3-a911-6395f726c550

	measure 'FP Returns LY' =
			CALCULATE (
			    [FP Returns],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\FP Returns\LY
		lineageTag: 1047cb86-f703-48a4-849f-3a31e6e812d3

	measure 'FP Returns LY-1' =
			CALCULATE (
			    [FP Returns],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of FP Returns LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\FP Returns\LY-1
		lineageTag: 786b93dd-da32-45a5-b909-79e5d9f9d284

	measure 'FP Returns vs LY' =
			VAR act = [FP Returns]
			VAR comp = [FP Returns LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\FP Returns\LY
		lineageTag: e5486c5a-5fc8-4472-8b63-fe4957e88567

	measure 'FP Returns vs LY-1' =
			VAR act = [FP Returns]
			VAR comp = [FP Returns LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of FP Returns vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\FP Returns\LY-1
		lineageTag: cc1fe53b-2aed-4a84-a895-1215c225b3d4

	measure 'FP Returns vs LY %' =
			VAR act = [FP Returns]
			VAR comp = [FP Returns LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\FP Returns\LY
		lineageTag: 3ab79d0a-4442-4be6-b725-8b638aeca4e7

	measure 'FP Returns LW' =
			CALCULATE (
			    [FP Returns],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\FP Returns\LW
		lineageTag: 112cb915-f6e2-449d-8507-e33024546fc9

	measure 'FP Returns vs LW' =
			VAR act = [FP Returns]
			VAR comp = [FP Returns LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\FP Returns\LW
		lineageTag: 06b8f7f2-9d59-4320-a63a-a29a605842cc

	measure 'FP Returns vs LW %' =
			VAR act = [FP Returns]
			VAR comp = [FP Returns LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\FP Returns\LW
		lineageTag: 9f06c9e3-4806-4034-a393-e4fdd8492e1d

	/// This measure is the sum of column 'factSalesDispatch[Sales Revenue (Exc VAT)]'
	measure 'RP Returns' = SUM ( factSalesDispatch[Reduced Price Returns (Inc VAT)] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\RP Returns\Actual
		lineageTag: 009eed5b-99fe-4da4-8a9e-e8a21d3001c3

	measure 'RP Returns LY' =
			CALCULATE (
			    [RP Returns],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\RP Returns\LY
		lineageTag: 28502b0f-beb1-4489-a21f-8ae243d3c410

	measure 'RP Returns LY-1' =
			CALCULATE (
			    [RP Returns],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of RP Returns LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\RP Returns\LY-1
		lineageTag: f953e259-e826-4eb5-91c6-bfd29bdf73b2

	measure 'RP Returns vs LY' =
			VAR act = [RP Returns]
			VAR comp = [RP Returns LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\RP Returns\LY
		lineageTag: 5e2aea26-e150-434f-a00d-7a70307c2a4d

	measure 'RP Returns vs LY-1' =
			VAR act = [RP Returns]
			VAR comp = [RP Returns LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of RP Returns vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\RP Returns\LY-1
		lineageTag: 3c62818f-2961-4b26-95df-8e6c66db9897

	measure 'RP Returns vs LY %' =
			VAR act = [RP Returns]
			VAR comp = [RP Returns LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\RP Returns\LY
		lineageTag: ae8b0368-c18e-4864-ab36-79705b27fd1b

	measure 'RP Returns LW' =
			CALCULATE (
			    [RP Returns],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\RP Returns\LW
		lineageTag: c1fc3f46-c532-4183-a36e-585e07ca9db6

	measure 'RP Returns vs LW' =
			VAR act = [RP Returns]
			VAR comp = [RP Returns LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\RP Returns\LW
		lineageTag: b39c8598-6112-465d-9132-7ddde557b4d6

	measure 'RP Returns vs LW %' =
			VAR act = [RP Returns]
			VAR comp = [RP Returns LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\RP Returns\LW
		lineageTag: a1cbc61c-818f-469a-9562-bdaf094cabde

	measure 'Return rate %' =
			VAR metric = - [Returns]
			VAR sales = [Gross SRIV]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\Actual
		lineageTag: 1ba998ff-2862-4099-8d34-cc345916ee98

	measure 'FP Return rate %' =
			VAR metric = - [FP Returns]
			VAR sales =
			    CALCULATE ( [SRIV], SalesType[fp_rp_ind] = "F" ) - [FP Returns]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\FP Returns\Actual
		lineageTag: aa8b921d-1809-4657-845f-e35c2ef83071

	measure 'Return rate % LY' =
			
			VAR metric = - [Returns LY]
			VAR sales = [SRIV LY] - [Returns LY]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\LY
		lineageTag: 275ce84c-8a8e-4e10-91a0-13f0662d248b

	measure 'Return rate % LY-1' =
			
			VAR metric = - [Returns LY-1]
			VAR sales = [SRIV LY-1] - [Returns LY-1]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		description: Two years ago equivalent of Return rate % LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\LY-1
		lineageTag: 0e67bb5f-7de8-408c-9e16-744446dc4142

	measure 'Return rate % LW' =
			VAR metric = - [Returns LW]
			VAR sales = [SRIV LW] - [Returns LW]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\LW
		lineageTag: 33870b21-22f3-49a2-a699-e3803f6cb9c4

	measure 'FP Return rate % LY' =
			VAR metric = - [FP Returns LY]
			VAR sales =
			    CALCULATE ( [SRIV LY], SalesType[fp_rp_ind] = "F" ) - [FP Returns LY]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\FP Returns\LY
		lineageTag: 20fad25a-ce6f-4d35-899b-78e99c25a7e0

	measure 'FP Return rate % LY-1' =
			VAR metric = - [FP Returns LY-1]
			VAR sales =
			    CALCULATE ( [SRIV LY-1], SalesType[fp_rp_ind] = "F" ) - [FP Returns LY-1]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		description: Two years ago equivalent of FP Return rate % LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\FP Returns\LY-1
		lineageTag: a3e99c0f-53ae-4484-b021-ff0afe3e9559

	measure 'FP Return rate % LW' =
			VAR metric = - [FP Returns LW]
			VAR sales =
			    CALCULATE ( [SRIV LW], SalesType[fp_rp_ind] = "F" ) - [FP Returns LW]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\FP Returns\LW
		lineageTag: db05ac67-df49-4bcb-94d6-2a04358e9ff5

	measure 'RP Return rate %' =
			VAR metric = - [RP Returns]
			VAR sales =
			    CALCULATE ( [SRIV], SalesType[fp_rp_ind] = "R" ) - [RP Returns]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\RP Returns\Actual
		lineageTag: edeff18b-63f5-4660-a8ef-5b8e329697e0

	measure 'RP Return rate % LY' =
			VAR metric = - [RP Returns LY]
			VAR sales =
			    CALCULATE ( [SRIV LY], SalesType[fp_rp_ind] = "R" ) - [RP Returns LY]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\RP Returns\LY
		lineageTag: 2c6cb7f9-db32-4ac8-aa3d-530db71c6ca8

	measure 'RP Return rate % LY-1' =
			VAR metric = - [RP Returns LY-1]
			VAR sales =
			    CALCULATE ( [SRIV LY-1], SalesType[fp_rp_ind] = "R" ) - [RP Returns LY-1]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		description: Two years ago equivalent of RP Return rate % LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\RP Returns\LY-1
		lineageTag: 8df15f0b-19d7-43aa-a6a1-5bdd7c9c349c

	measure 'RP Return rate % LW' =
			VAR metric = - [RP Returns LW]
			VAR sales =
			    CALCULATE ( [SRIV LW], SalesType[fp_rp_ind] = "R" ) - [RP Returns LW]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\RP Returns\LW
		lineageTag: 3b15bc46-0434-47f9-ba63-588809830404

	measure LatestSalesOrders =
			CALCULATE (
			    MAX ( statsLatestData[latestFiscalWeekEndingDate] ),
			    statsLatestData[dataSource] = "Sales Orders"
			)
		displayFolder: Metadata\Latest Data
		lineageTag: 563f1e71-d5d8-4ce4-bc4d-ee4b9b82865e

	measure LatestSalesDispatch =
			CALCULATE (
			    MAX ( statsLatestData[latestFiscalWeekEndingDate] ),
			    statsLatestData[dataSource] = "Sales Dispatch"
			)
		displayFolder: Metadata\Latest Data
		lineageTag: b44e094b-fe8a-4ebf-8512-194e9e2d617f

	measure LatestSalesOrdersLabel =
			VAR latest_sales =
			    FORMAT ( [LatestSalesOrders], "dd/mm/yyyy" )
			RETURN
			    "Latest Orders Data: w/e " & latest_sales
		displayFolder: Metadata\Latest Data
		lineageTag: e08b7b9c-e29f-4489-b6a6-2cb3d6c03cbb

	measure LatestSalesDispatchLabel =
			VAR latest_sales =
			    FORMAT ( [LatestSalesDispatch], "dd/mm/yyyy" )
			RETURN
			    "Latest Dispatch Data: w/e " & latest_sales
		displayFolder: Metadata\Latest Data
		lineageTag: e1986494-aa4f-4259-a552-c2780848fa90

	measure LatestSales =
			SWITCH (
			    [slctd_SalesRecognitionType],
			    "Order", [LatestSalesOrders],
			    "Dispatch", [LatestSalesDispatch],
			    [LatestSalesOrders]
			)
		displayFolder: Metadata\Latest Data
		lineageTag: 7f0048e5-cdf5-48af-b81b-6be91cbe64db

	measure LatestSalesLabel =
			VAR latest_sales =
			    FORMAT ( [LatestSales], "dd/mm/yyyy" )
			RETURN
			    "Latest Sales Data: w/e " & latest_sales
		displayFolder: Metadata\Latest Data
		lineageTag: f7526de0-ebfd-4c97-bd98-db31099c2ff6

	measure tiProduct =
			VAR _ProductDisplay =
			    SWITCH (
			        TRUE (),
			        OR ( ISFILTERED ( Products[Dept] ), ISFILTERED ( Products[Dept Code] ) ), SELECTEDVALUE ( Products[Dept], "Multiple Depts" ),
			        OR ( ISFILTERED ( Products[BU] ), ISFILTERED ( Products[BU Code] ) ), SELECTEDVALUE ( Products[BU], "Multiple BUs" ),
			        "All FH&B"
			    )
			RETURN
			    IF ( ISBLANK ( _ProductDisplay ), "All FH&B", _ProductDisplay )
		displayFolder: Dynamic Labels
		lineageTag: bc2d7b85-a023-4ce4-8a09-d6276cc2e5c4

	measure tiWeekNo =
			VAR _CalWeekNo =
			    MAX ( 'Calendar'[fiscalWeek] )
			VAR _LatestActuals = [LatestSalesFiscalWeek]
			VAR _WeekNo =
			    MIN ( _CalWeekNo, _LatestActuals )
			RETURN
			    "Week " & RIGHT ( _WeekNo, 2 )
		displayFolder: Dynamic Labels
		lineageTag: 4cfd8db3-9558-45e6-b7ba-4d47d1d6c38e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure tiTimePeriod = SELECTEDVALUE ( 'Time Period'[Time Period], "YTD" )
		displayFolder: Dynamic Labels
		lineageTag: aeae9838-d2a7-4009-b52f-e350d46e2464

	measure tiTimeLabel =
			VAR _WeekNo = [tiWeekNo]
			VAR _TimePeriod = [tiTimePeriod]
			RETURN
			    _WeekNo & " | " & _TimePeriod
		displayFolder: Dynamic Labels
		lineageTag: c0756b30-5a5a-47ce-a1f3-60e1348dec5b

	measure tiSalesRecogType =
			SWITCH (
			    [slctd_SalesRecognitionType],
			    "Order", "Orders",
			    [slctd_SalesRecognitionType]
			)
		displayFolder: Dynamic Labels
		lineageTag: f0d1837f-84dc-4c63-9a85-61463e776129

	measure tiChannel =
			IF (
			IF (    SELECTEDVALUE ( OutletsControl[Ex Outlets/Outlets], "" ) = "M&S Ex Outlets", "M&S Ex Outlets", "Multi") = "M&S Ex Outlets",
			        IF (SELECTEDVALUE ( Channels[Channel], "" ) = "Stores", "Mainchain", SELECTEDVALUE ( Channels[Channel], "Mainchain & Online" )),
			        IF (
			                SELECTEDVALUE ( Channels[Channel], "All Channels" ) = "Stores",
			                SELECTEDVALUE ( Channels[Channel Detail], "Mainchain & Outlets" ),
			                SELECTEDVALUE ( Channels[Channel], "All Channels" )
			            )
			    )
		displayFolder: Dynamic Labels
		lineageTag: a3b2a904-8dab-45c2-ad4d-c72c10d3a49f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure tiSalesType = [slctd_SalesTypeLevelAware] & " Sales"
		displayFolder: Dynamic Labels
		lineageTag: ad7a8de8-9a8c-4e41-963c-bcae52662d47

	measure tiTimeLabelProductChannelSalesTypeSalesRecogType = [tiTimeLabel] & " | " & [tiProduct] & " | " & [tiChannel] & " | " & [tiSalesType] & " | " & [tiSalesRecogType]
		displayFolder: Dynamic Labels\Sales
		lineageTag: 4bdd108d-9791-4665-a0c9-b2e464c23b0d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure tiSalesMeasureSelection = [tiSalesType] & " " & [SMS_slctd_MeasureName]
		displayFolder: Dynamic Labels\SalesMeasureSelection
		lineageTag: 4bf8ae5e-fd77-4cb7-8edd-055f2cc65ca3

	measure tiSalesMeasureSelectionByChannel = [tiSalesType] & " " & [SMS_slctd_MeasureName] & " by Channel"
		displayFolder: Dynamic Labels\SalesMeasureSelection
		lineageTag: dff00b40-066e-4b85-8218-939aa634a34b

	measure tiSalesMeasureSelectionByBU = [tiSalesType] & " " & [SMS_slctd_MeasureName] & " by BU"
		displayFolder: Dynamic Labels\SalesMeasureSelection
		lineageTag: f893a8bd-0e43-432b-9790-eff5d6ab8214

	measure tiSalesMeasureSelectionByWeek = [tiSalesType] & " " & [SMS_slctd_MeasureName] & " by Week"
		displayFolder: Dynamic Labels\SalesMeasureSelection
		lineageTag: ab209c4f-a516-46fa-9d63-2c719401bae5

	measure 'SRIV Dispatch vs Orders' =
			VAR dispatch = [SRIV Dispatch]
			VAR orders = [SRIV Orders]
			VAR postings = [SRIV Postings Dispatch]
			VAR result = dispatch - postings - orders
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch vs Orders\SRIV\Actual
		lineageTag: 7e023432-27bd-43e4-8b8e-444025b439b6

	measure 'SRIV Dispatch vs Orders LY' =
			VAR dispatch = [SRIV Dispatch LY]
			VAR orders = [SRIV Orders LY]
			VAR postings = [SRIV Postings Dispatch LY]
			VAR result = dispatch - postings - orders
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch vs Orders\SRIV\LY
		lineageTag: 25476b79-12c5-4173-b7aa-8c3a56c89c5c

	measure 'SRIV Dispatch vs Orders LY-1' =
			VAR dispatch = [SRIV Dispatch LY-1]
			VAR orders = [SRIV Orders LY-1]
			VAR postings = [SRIV Postings Dispatch LY-1]
			VAR result = dispatch - postings - orders
			RETURN
			    result
		description: Two years ago equivalent of SRIV Dispatch vs Orders LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch vs Orders\SRIV\LY-1
		lineageTag: 644d995a-40bb-4aa4-9b92-65cfb8bb32a5

	measure 'SRIV Dispatch vs Orders vs LY' =
			VAR act = [SRIV Dispatch vs Orders]
			VAR comp = [SRIV Dispatch vs Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch vs Orders\SRIV\LY
		lineageTag: 407b7ff6-1d17-4838-a9d7-a7ee2a8f1614

	measure 'SRIV Dispatch vs Orders vs LY-1' =
			VAR act = [SRIV Dispatch vs Orders]
			VAR comp = [SRIV Dispatch vs Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of SRIV Dispatch vs Orders vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch vs Orders\SRIV\LY-1
		lineageTag: eb83a3b7-e727-4fe8-8dce-4cb06791528b

	measure 'SRIV Dispatch vs Orders vs LY %' =
			VAR act = [SRIV Dispatch vs Orders]
			VAR comp = [SRIV Dispatch vs Orders LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch vs Orders\SRIV\LY
		lineageTag: 8b6e04c5-18b9-4478-b931-68d3d8c83f10

	measure 'SRIV Dispatch vs Orders LW' =
			VAR dispatch = [SRIV Dispatch LW]
			VAR orders = [SRIV Orders LW]
			VAR postings = [SRIV Postings Dispatch LW]
			VAR result = dispatch - postings - orders
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch vs Orders\SRIV\LW
		lineageTag: 20ca95c7-1ea0-4fa8-809e-7e88b760096f

	measure 'SRIV Dispatch vs Orders vs LW' =
			VAR act = [SRIV Dispatch vs Orders]
			VAR comp = [SRIV Dispatch vs Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch vs Orders\SRIV\LW
		lineageTag: af2ce1d4-e4ac-43b6-a9c2-9d09121ea999

	measure 'SRIV Dispatch vs Orders vs LW %' =
			VAR act = [SRIV Dispatch vs Orders]
			VAR comp = [SRIV Dispatch vs Orders LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch vs Orders\SRIV\LW
		lineageTag: 43b095c9-43cf-42dc-afa6-f491cec392f4

	measure 'SRIV Dispatch vs Orders BUD' =
			VAR dispatch = [SRIV Dispatch BUD]
			VAR orders = [SRIV Orders BUD]
			VAR postings = 0
			VAR result = dispatch - postings - orders
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch vs Orders\SRIV\BUD
		lineageTag: 12dde6ab-2f80-407d-aa3a-1a5a98feae4c

	measure 'SRIV Dispatch vs Orders vs BUD' =
			VAR act = [SRIV Dispatch vs Orders]
			VAR comp = [SRIV Dispatch vs Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch vs Orders\SRIV\BUD
		lineageTag: 7d0bc74c-4546-471a-8ffe-e7a9f1ad689c

	measure 'SRIV Dispatch vs Orders vs BUD %' =
			VAR act = [SRIV Dispatch vs Orders]
			VAR comp = [SRIV Dispatch vs Orders BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch vs Orders\SRIV\BUD
		lineageTag: 4a289b57-a22f-40c6-8128-840fd950889d

	measure 'SRIV Dispatch vs Orders FC' =
			VAR dispatch = [SRIV Dispatch FC]
			VAR orders = [SRIV Orders FC]
			VAR postings = 0
			VAR result = dispatch - postings - orders
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch vs Orders\SRIV\FC
		lineageTag: ae6b91fe-e995-4c82-b199-97019230fe24

	measure 'SRIV Dispatch vs Orders vs FC' =
			VAR act = [SRIV Dispatch vs Orders]
			VAR comp = [SRIV Dispatch vs Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch vs Orders\SRIV\FC
		lineageTag: 209c9449-c339-41cd-a1dd-03286b124055

	measure 'SRIV Dispatch vs Orders vs FC %' =
			VAR act = [SRIV Dispatch vs Orders]
			VAR comp = [SRIV Dispatch vs Orders FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch vs Orders\SRIV\FC
		lineageTag: 2f7f9701-4072-4a3a-9604-fccc3bb95d59

	measure 'SRIV Dispatch vs Orders QRF' =
			VAR dispatch = [SRIV Dispatch QRF]
			VAR orders = [SRIV Orders QRF]
			VAR postings = 0
			VAR result = dispatch - postings - orders
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch vs Orders\SRIV\QRF
		lineageTag: 17e0e19d-4826-4468-a7c5-7fc78dacd45b

	measure 'SRIV Dispatch vs Orders vs QRF' =
			VAR act = [SRIV Dispatch vs Orders]
			VAR comp = [SRIV Dispatch vs Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch vs Orders\SRIV\QRF
		lineageTag: 992f83fa-e1c7-4f6f-9a00-53c1aa4cc25c

	measure 'SRIV Dispatch vs Orders vs QRF %' =
			VAR act = [SRIV Dispatch vs Orders]
			VAR comp = [SRIV Dispatch vs Orders QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch vs Orders\SRIV\QRF
		lineageTag: b39a6760-29b9-43fd-9c8f-fa0bd6b7f256

	/// This measure is the sum of column 'factSalesDispatch[Dept/Manual Postings]'
	measure 'SRIV Postings Dispatch' = SUM ( factSalesDispatch[Dept/Manual Postings] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\Postings\Actual
		lineageTag: 4d1cfe6a-c8f0-4d6d-b5d7-00ddd8136cbb

	measure 'SRIV Postings Dispatch LY' =
			CALCULATE (
			    [SRIV Postings Dispatch],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\Postings\LY
		lineageTag: 5e2bd8f2-c36f-4d48-83e7-05b6990d2a02

	measure 'SRIV Postings Dispatch LY-1' =
			CALCULATE (
			    [SRIV Postings Dispatch],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of SRIV Postings Dispatch LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\Postings\LY-1
		lineageTag: 3dc49cc2-2796-498a-ac33-3f8cd4282da9

	measure 'SRIV Postings Dispatch vs LY' =
			VAR act = [SRIV Postings Dispatch]
			VAR comp = [SRIV Postings Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\Postings\LY
		lineageTag: d05fe392-da4a-48dd-922e-e9b53aa7f8d0

	measure 'SRIV Postings Dispatch vs LY-1' =
			VAR act = [SRIV Postings Dispatch]
			VAR comp = [SRIV Postings Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of SRIV Postings Dispatch vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\Postings\LY-1
		lineageTag: c0c01a1f-81c7-4178-98cd-726f53cedc5e

	measure 'SRIV Postings Dispatch vs LY %' =
			VAR act = [SRIV Postings Dispatch]
			VAR comp = [SRIV Postings Dispatch LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Postings\LY
		lineageTag: 6877916e-b6a3-4c2f-925d-2e9cefc2cbe6

	measure 'SRIV Postings Dispatch LW' =
			CALCULATE (
			    [SRIV Postings Dispatch],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\Postings\LW
		lineageTag: 05d95660-b42d-477f-b50d-efc7687bb2b6

	measure 'SRIV Postings Dispatch vs LW' =
			VAR act = [SRIV Postings Dispatch]
			VAR comp = [SRIV Postings Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\Postings\LW
		lineageTag: 1facc9f3-8cfa-44e5-9f0c-94f4f35c1614

	measure 'SRIV Postings Dispatch vs LW %' =
			VAR act = [SRIV Postings Dispatch]
			VAR comp = [SRIV Postings Dispatch LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Postings\LW
		lineageTag: c77684bd-7d0b-4426-9d3b-96846bc61433

	measure 'P SRIV Dispatch' = [sum_Promotional Sales Revenue (Inc VAT)]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\P SRIV\Actual
		lineageTag: b6c3ec3b-d1c2-411c-b15b-ac1dfcf30656

	measure 'P SRIV Dispatch LY' =
			CALCULATE (
			    [P SRIV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\P SRIV\LY
		lineageTag: 1750bd16-fcb8-4b77-aa53-6db8be310930

	measure 'P SRIV Dispatch LY-1' =
			CALCULATE (
			    [P SRIV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of P SRIV Dispatch LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\P SRIV\LY-1
		lineageTag: 58037454-420e-48a5-a8c2-ae076fe5b9c8

	measure 'P SRIV Dispatch vs LY' =
			VAR act = [P SRIV Dispatch]
			VAR comp = [P SRIV Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\P SRIV\LY
		lineageTag: 600545d3-e228-4ea4-8e85-4012f950a968

	measure 'P SRIV Dispatch vs LY-1' =
			VAR act = [P SRIV Dispatch]
			VAR comp = [P SRIV Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of P SRIV Dispatch vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\P SRIV\LY-1
		lineageTag: efc47a52-cd3a-4ec5-b0b1-7492908a6dc8

	measure 'P SRIV Dispatch vs LY %' =
			VAR act = [P SRIV Dispatch]
			VAR comp = [P SRIV Dispatch LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\P SRIV\LY
		lineageTag: 0a9dc273-0c2b-4db5-8402-bc6d78f7e84e

	measure 'P SRIV Dispatch LW' =
			CALCULATE (
			    [P SRIV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\P SRIV\LW
		lineageTag: 739d68dc-2da8-4fcf-ba5a-45de896cf0a1

	measure 'P SRIV Dispatch vs LW' =
			VAR act = [P SRIV Dispatch]
			VAR comp = [P SRIV Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\P SRIV\LW
		lineageTag: 513364cf-47a0-48f2-86e6-b8043425af94

	measure 'P SRIV Dispatch vs LW %' =
			VAR act = [P SRIV Dispatch]
			VAR comp = [P SRIV Dispatch LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\P SRIV\LW
		lineageTag: 7010b02a-eb39-4197-96df-9e26d93e6b60

	measure 'Buying Margin Dispatch' =
			VAR cogs_inc_vat = - [sum_Cost Of Goods Sold (Inc VAT)]
			VAR bm_denom = [sum_Buying Margin Denominator]
			VAR result = bm_denom - cogs_inc_vat
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Buying Margin\Actual
		lineageTag: c4e25f9d-edfd-4e1c-bec5-5bea0066fd16

	measure 'Buying Margin % Dispatch' =
			VAR metric = [Buying Margin Dispatch]
			VAR sales = [sum_Buying Margin Denominator]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Buying Margin\Actual
		lineageTag: 7f953e9c-38b6-4821-a0f4-581ad4c298d4

	measure 'Buying Margin Dispatch LY' =
			CALCULATE (
			    [Buying Margin Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Buying Margin\LY
		lineageTag: 4644f528-1ea2-43fb-b759-720915a85e57

	measure 'Buying Margin Dispatch LY-1' =
			CALCULATE (
			    [Buying Margin Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Buying Margin Dispatch LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Buying Margin\LY-1
		lineageTag: a4dbe957-d674-445c-b7f7-bef2d00b36b8

	measure 'Buying Margin Dispatch vs LY' =
			VAR act = [Buying Margin Dispatch]
			VAR comp = [Buying Margin Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Buying Margin\LY
		lineageTag: a628dd76-2d94-420d-bdec-45c568614be7

	measure 'Buying Margin Dispatch vs LY-1' =
			VAR act = [Buying Margin Dispatch]
			VAR comp = [Buying Margin Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Buying Margin Dispatch vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Buying Margin\LY-1
		lineageTag: a2896520-391a-43fe-97e5-f01c9c70667d

	measure 'Buying Margin % Dispatch LY' =
			CALCULATE (
			    [Buying Margin % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Buying Margin\LY
		lineageTag: 507689c0-bd48-40fc-8ee5-b3a9dcc1acdc

	measure 'Buying Margin % Dispatch LY-1' =
			CALCULATE (
			    [Buying Margin % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Buying Margin % Dispatch LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Buying Margin\LY-1
		lineageTag: 6a740b2a-1c01-4cb6-af90-1859fdab3d85

	measure 'Buying Margin % Dispatch vs LY' =
			VAR act = [Buying Margin % Dispatch]
			VAR comp = [Buying Margin % Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Buying Margin\LY
		lineageTag: 0ee89350-6266-484a-8969-698a3cdb8bbe

	measure 'Buying Margin % Dispatch vs LY-1' =
			VAR act = [Buying Margin % Dispatch]
			VAR comp = [Buying Margin % Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Buying Margin % Dispatch vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Buying Margin\LY-1
		lineageTag: 17947e08-4644-4028-ac14-74c3ec30e6ad

	measure 'Buying Margin Dispatch vs LY %' =
			VAR act = [Buying Margin Dispatch]
			VAR comp = [Buying Margin Dispatch LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Buying Margin\LY
		lineageTag: 8cb07433-6a2f-42c9-9ce3-30be194d2088

	measure 'Buying Margin Dispatch LW' =
			CALCULATE (
			    [Buying Margin Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Buying Margin\LW
		lineageTag: 883b2903-dc60-440b-ad09-a8901601bceb

	measure 'Buying Margin Dispatch vs LW' =
			VAR act = [Buying Margin Dispatch]
			VAR comp = [Buying Margin Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Buying Margin\LW
		lineageTag: 304182c5-48d4-48a0-b057-4ffa0c408eb7

	measure 'Buying Margin % Dispatch LW' =
			CALCULATE (
			    [Buying Margin % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Buying Margin\LW
		lineageTag: 44d55406-21f3-4605-85b6-c018aaf8cfc3

	measure 'Buying Margin % Dispatch vs LW' =
			VAR act = [Buying Margin % Dispatch]
			VAR comp = [Buying Margin % Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Buying Margin\LW
		lineageTag: 4ac3840e-f214-4f52-9bd3-5d135e5726e5

	measure 'Buying Margin Dispatch vs LW %' =
			VAR act = [Buying Margin Dispatch]
			VAR comp = [Buying Margin Dispatch LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Buying Margin\LW
		lineageTag: ebf415f6-5dfe-48c1-85b2-9e1eb01982d3

	measure 'Markdown Dispatch' = SUM ( factSalesDispatch[Markdown @SV] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Markdown\Actual
		lineageTag: 5d288180-de69-48d0-b0a8-34a37083c328

	/// This measure is column [GSM Dispatch] as a % of SREV
	measure 'Markdown % SRIV Dispatch' =
			VAR metric = - [Markdown Dispatch]
			VAR sales = [SRIV Dispatch]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Markdown\Actual
		lineageTag: c017683b-9ee8-4a59-a84c-856f5d8374e4

	measure 'Markdown Dispatch LY' =
			CALCULATE (
			    [Markdown Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Markdown\LY
		lineageTag: c86cb33d-1773-46f7-9ac1-df0b1fc5c6cf

	measure 'Markdown Dispatch LY-1' =
			CALCULATE (
			    [Markdown Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Markdown Dispatch LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Markdown\LY-1
		lineageTag: d3ecf226-fe6c-45d6-9ae7-63b5b2b8ffdb

	measure 'Markdown Dispatch vs LY' =
			VAR act = [Markdown Dispatch]
			VAR comp = [Markdown Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Markdown\LY
		lineageTag: bc35b872-29f3-4f0f-aa48-943c47875da3

	measure 'Markdown Dispatch vs LY-1' =
			VAR act = [Markdown Dispatch]
			VAR comp = [Markdown Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Markdown Dispatch vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Markdown\LY-1
		lineageTag: 17f69b5b-8f24-4ec6-a7e8-3dc3fcb36c5f

	measure 'Markdown % SRIV Dispatch LY' =
			CALCULATE (
			    [Markdown % SRIV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Markdown\LY
		lineageTag: a9f4e877-0b00-47bc-89a8-f6ea3445492a

	measure 'Markdown % SRIV Dispatch LY-1' =
			CALCULATE (
			    [Markdown % SRIV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Markdown % SRIV Dispatch LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Markdown\LY-1
		lineageTag: 83ef1018-0333-4186-890a-93a3829147f0

	measure 'Markdown % SRIV Dispatch vs LY' =
			VAR act = [Markdown % SRIV Dispatch]
			VAR comp = [Markdown % SRIV Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Markdown\LY
		lineageTag: 12b56596-b000-4102-8235-e466925878b7

	measure 'Markdown % SRIV Dispatch vs LY-1' =
			VAR act = [Markdown % SRIV Dispatch]
			VAR comp = [Markdown % SRIV Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Markdown % SRIV Dispatch vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Markdown\LY-1
		lineageTag: 5f69d206-b863-4c4e-bbaf-196655e9f5a3

	measure 'Markdown Dispatch vs LY %' =
			VAR act = [Markdown Dispatch]
			VAR comp = [Markdown Dispatch LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Markdown\LY
		lineageTag: 03c87e82-f485-4824-92f5-c190222cecc5

	measure 'Markdown Dispatch LW' =
			CALCULATE (
			    [Markdown Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Markdown\LW
		lineageTag: ab017426-0e1f-4399-b61f-251f29ef7168

	measure 'Markdown Dispatch vs LW' =
			VAR act = [Markdown Dispatch]
			VAR comp = [Markdown Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Markdown\LW
		lineageTag: dd2fdd1d-8d82-4c41-a249-847002c701df

	measure 'Markdown % SRIV Dispatch LW' =
			CALCULATE (
			    [Markdown % SRIV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Markdown\LW
		lineageTag: 501e6993-7841-4881-bac4-6cbf98d08dfa

	measure 'Markdown % SRIV Dispatch vs LW' =
			VAR act = [Markdown % SRIV Dispatch]
			VAR comp = [Markdown % SRIV Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Markdown\LW
		lineageTag: dd41a9ba-57ac-43b8-84e3-41b9c8a33ea1

	measure 'Markdown Dispatch vs LW %' =
			VAR act = [Markdown Dispatch]
			VAR comp = [Markdown Dispatch LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Markdown\LW
		lineageTag: 9c965f34-47e6-4362-93af-682c5fe4ec98

	measure 'Promo Markdown Dispatch' = SUM ( factSalesDispatch[Promo Markdown @SV] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Promo Markdown\Actual
		lineageTag: 81be76a4-de26-458a-8623-4230110d1d7a

	measure 'Promo Markdown Dispatch LY' =
			CALCULATE (
			    [Promo Markdown Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Promo Markdown\LY
		lineageTag: 656acb37-1bf2-4de8-a16d-0ab65b661268

	measure 'Promo Markdown Dispatch LY-1' =
			CALCULATE (
			    [Promo Markdown Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Promo Markdown Dispatch LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Promo Markdown\LY-1
		lineageTag: 500a2b27-d8ee-4614-9862-6631a54b2338

	measure 'Promo Markdown Dispatch vs LY' =
			VAR act = [Promo Markdown Dispatch]
			VAR comp = [Promo Markdown Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Promo Markdown\LY
		lineageTag: 2607f1a5-6f5b-4a63-9dad-d8e33b9fff23

	measure 'Promo Markdown Dispatch vs LY-1' =
			VAR act = [Promo Markdown Dispatch]
			VAR comp = [Promo Markdown Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Promo Markdown Dispatch vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Promo Markdown\LY-1
		lineageTag: 25f6bbaf-1912-4442-8ab2-00c7388d78f3

	measure 'Promo Markdown Dispatch LW' =
			CALCULATE (
			    [Promo Markdown Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Promo Markdown\LW
		lineageTag: 7ebfc638-fbe9-49f6-b3a2-e31bc7ac32ed

	measure 'Promo Markdown Dispatch vs LW' =
			VAR act = [Promo Markdown Dispatch]
			VAR comp = [Promo Markdown Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Promo Markdown\LW
		lineageTag: 85dd3099-550a-4344-9a43-a11aa47cbedd

	measure 'Sale Markdown Dispatch' = SUM ( factSalesDispatch[Sale Markdown @SV] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\Actual
		lineageTag: 445a4cbd-6bf1-4ace-89c3-1ae08bd150ad

	measure 'Sale Markdown Dispatch LY' =
			CALCULATE (
			    [Sale Markdown Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\LY
		lineageTag: 932b2901-fb2d-4630-8205-fea5e77962a7

	measure 'Sale Markdown Dispatch LY-1' =
			CALCULATE (
			    [Sale Markdown Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Sale Markdown Dispatch LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\LY-1
		lineageTag: 138d4e2f-7e5d-461e-b803-83f400f0a761

	measure 'Sale Markdown Dispatch vs LY' =
			VAR act = [Sale Markdown Dispatch]
			VAR comp = [Sale Markdown Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\LY
		lineageTag: cc2b87b3-f9ad-4ad3-ab44-12f27832a40b

	measure 'Sale Markdown Dispatch vs LY-1' =
			VAR act = [Sale Markdown Dispatch]
			VAR comp = [Sale Markdown Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Sale Markdown Dispatch vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\LY-1
		lineageTag: 9bc8c868-bf0f-43cf-a589-b6bb70332a85

	measure 'Sale Markdown Dispatch LW' =
			CALCULATE (
			    [Sale Markdown Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\LW
		lineageTag: 4131f292-75b3-4308-a176-86466db89eaa

	measure 'Sale Markdown Dispatch vs LW' =
			VAR act = [Sale Markdown Dispatch]
			VAR comp = [Sale Markdown Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\LW
		lineageTag: 8b76729e-e4b0-47da-8f0e-ac07fc6532ae

	measure 'SIS Sold Through Dispatch' = SUM ( factSalesDispatch[SIS Sold Through (Inc VAT)] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\SIS Sold Through\Actual
		lineageTag: b73a1a3f-7bad-4fd5-b70b-e5fc83160fa0

	measure 'SIS Sold Through Dispatch LY' =
			CALCULATE (
			    [SIS Sold Through Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\SIS Sold Through\LY
		lineageTag: c1dc3652-91f4-4931-b52a-b318cb1b3ca7

	measure 'SIS Sold Through Dispatch LY-1' =
			CALCULATE (
			    [SIS Sold Through Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of SIS Sold Through Dispatch LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\SIS Sold Through\LY-1
		lineageTag: e6c92f70-c109-4105-90a5-a99626c62336

	measure 'SIS Sold Through Dispatch vs LY' =
			VAR act = [SIS Sold Through Dispatch]
			VAR comp = [SIS Sold Through Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\SIS Sold Through\LY
		lineageTag: 57c01db3-e74e-4ff9-9cef-5494270a9d77

	measure 'SIS Sold Through Dispatch vs LY-1' =
			VAR act = [SIS Sold Through Dispatch]
			VAR comp = [SIS Sold Through Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of SIS Sold Through Dispatch vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\SIS Sold Through\LY-1
		lineageTag: 8b9960a6-01ee-4a56-9a00-c454d2425d76

	measure 'SIS Sold Through Dispatch LW' =
			CALCULATE (
			    [SIS Sold Through Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\SIS Sold Through\LW
		lineageTag: dc5ec551-511c-4dd2-85e0-2503997d7ca3

	measure 'SIS Sold Through Dispatch vs LW' =
			VAR act = [SIS Sold Through Dispatch]
			VAR comp = [SIS Sold Through Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\SIS Sold Through\LW
		lineageTag: 951ac1bb-c5af-4e9e-808b-4b5451040775

	measure 'Buying Margin' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Buying Margin Orders],
			        "Dispatch", [Buying Margin Dispatch],
			        [Buying Margin Orders]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Buying Margin\Actual
		lineageTag: 84659d4b-665c-4c5e-bfc3-319069b5f12a

	measure 'Buying Margin %' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Buying Margin % Orders],
			        "Dispatch", [Buying Margin % Dispatch],
			        [Buying Margin % Orders]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Buying Margin\Actual
		lineageTag: 8ef0d33c-3393-4d7d-9909-09aa68328671

	measure 'Buying Margin Orders' = SUM ( 'factSalesOrders'[bimev_num] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Buying Margin\Actual
		lineageTag: c392fd20-3eec-4b57-8fff-5137bca49978

	measure 'Buying Margin % Orders' =
			VAR metric = [Buying Margin Orders]
			VAR sales = SUM ( 'factSalesOrders'[bimev_denom] )
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Buying Margin\Actual
		lineageTag: 1c81a1fc-906f-4f2b-b7ec-26732dbc0449

	measure 'Buying Margin Orders LY' =
			CALCULATE (
			    [Buying Margin Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Buying Margin\LY
		lineageTag: 720db11c-0aa8-485f-b897-f8d4a23938a3

	measure 'Buying Margin Orders LY-1' =
			CALCULATE (
			    [Buying Margin Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Buying Margin Orders LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Buying Margin\LY-1
		lineageTag: 2850d703-f97c-485d-8f72-d13230242064

	measure 'Buying Margin Orders vs LY' =
			VAR act = [Buying Margin Orders]
			VAR comp = [Buying Margin Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Buying Margin\LY
		lineageTag: 09579f53-e99d-4ce8-9fd3-03c5a586efc1

	measure 'Buying Margin Orders vs LY-1' =
			VAR act = [Buying Margin Orders]
			VAR comp = [Buying Margin Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Buying Margin Orders vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Buying Margin\LY-1
		lineageTag: afebb046-6fdd-4b7c-8136-15c25f820e3a

	measure 'Buying Margin % Orders LY' =
			CALCULATE (
			    [Buying Margin % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Buying Margin\LY
		lineageTag: 40f742c7-7037-4ccb-8f0e-148ffb0665d1

	measure 'Buying Margin % Orders LY-1' =
			CALCULATE (
			    [Buying Margin % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Buying Margin % Orders LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Buying Margin\LY-1
		lineageTag: 03221e86-ae22-4f78-823a-ecbc345cf871

	measure 'Buying Margin % Orders vs LY' =
			VAR act = [Buying Margin % Orders]
			VAR comp = [Buying Margin % Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Buying Margin\LY
		lineageTag: 69808ee0-f061-457c-b3b8-57c8313252a4

	measure 'Buying Margin % Orders vs LY-1' =
			VAR act = [Buying Margin % Orders]
			VAR comp = [Buying Margin % Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Buying Margin % Orders vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Buying Margin\LY-1
		lineageTag: 216b74d4-fc10-40a6-954a-f447072e0ae1

	measure 'Buying Margin Orders vs LY %' =
			VAR act = [Buying Margin Orders]
			VAR comp = [Buying Margin Orders LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Buying Margin\LY
		lineageTag: a20264b5-8bf7-43d4-a090-e79e998b4087

	measure 'Buying Margin Orders LW' =
			CALCULATE (
			    [Buying Margin Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Buying Margin\LW
		lineageTag: f5864202-a897-44bc-b17f-21b570aa6942

	measure 'Buying Margin Orders vs LW' =
			VAR act = [Buying Margin Dispatch]
			VAR comp = [Buying Margin Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Buying Margin\LW
		lineageTag: b3fdd9bc-740e-4137-b0bd-9130b70bd571

	measure 'Buying Margin % Orders LW' =
			CALCULATE (
			    [Buying Margin % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Buying Margin\LW
		lineageTag: a767a1f5-91a3-42e9-a613-08d86e958147

	measure 'Buying Margin % Orders vs LW' =
			VAR act = [Buying Margin % Orders]
			VAR comp = [Buying Margin % Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Buying Margin\LW
		lineageTag: 8c7db289-6bfa-4aa9-b7b3-0cb8556a6050

	measure 'Buying Margin Orders vs LW %' =
			VAR act = [Buying Margin Orders]
			VAR comp = [Buying Margin Orders LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Buying Margin\LW
		lineageTag: 0465365a-86fd-4765-bf22-a65cb6e728be

	measure 'Markdown Orders' = [Promo Markdown Orders] + [Sale Markdown Orders]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Markdown\Actual
		lineageTag: e7fafab1-6fb7-4ef2-a49a-ba04b945d808

	/// This measure is column [GSM Dispatch] as a % of SREV
	measure 'Markdown % SRIV Orders' =
			VAR metric = - [Markdown Orders]
			VAR sales = [SRIV Orders]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Markdown\Actual
		lineageTag: d7c41117-147a-4870-9749-454b68c8574a

	measure 'Markdown Orders LY' =
			CALCULATE (
			    [Markdown Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Markdown\LY
		lineageTag: 543bfcf9-fd99-438b-b884-f6aeb53ed8fa

	measure 'Markdown Orders LY-1' =
			CALCULATE (
			    [Markdown Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Markdown Orders LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Markdown\LY-1
		lineageTag: c3562100-120f-4eb7-ade3-0b67da73244a

	measure 'Markdown Orders vs LY' =
			VAR act = [Markdown Orders]
			VAR comp = [Markdown Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Markdown\LY
		lineageTag: 769ced0d-9f6c-4472-a24d-a442e14570ae

	measure 'Markdown Orders vs LY-1' =
			VAR act = [Markdown Orders]
			VAR comp = [Markdown Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Markdown Orders vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Markdown\LY-1
		lineageTag: ed5e9c11-d31d-499e-a32f-2e87fc939951

	measure 'Markdown % SRIV Orders LY' =
			CALCULATE (
			    [Markdown % SRIV Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Markdown\LY
		lineageTag: e479a3b1-85be-4f60-aa1c-453b40ecf577

	measure 'Markdown % SRIV Orders LY-1' =
			CALCULATE (
			    [Markdown % SRIV Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Markdown % SRIV Orders LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Markdown\LY-1
		lineageTag: 0886a307-4146-4a21-a834-b44adce8bc29

	measure 'Markdown % SRIV Orders vs LY' =
			VAR act = [Markdown % SRIV Orders]
			VAR comp = [Markdown % SRIV Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Markdown\LY
		lineageTag: e2f36eec-cb49-4c08-9384-cc7d9465b27b

	measure 'Markdown % SRIV Orders vs LY-1' =
			VAR act = [Markdown % SRIV Orders]
			VAR comp = [Markdown % SRIV Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Markdown % SRIV Orders vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Markdown\LY-1
		lineageTag: 6627e4f2-3cf4-4cd9-90d0-a81cbdc24d75

	measure 'Markdown Orders vs LY %' =
			VAR act = [Markdown Orders]
			VAR comp = [Markdown Orders LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Markdown\LY
		lineageTag: 97e81ccb-5f03-4ba0-a231-60c6c86f537a

	measure 'Markdown Orders LW' =
			CALCULATE (
			    [Markdown Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Markdown\LW
		lineageTag: d1d5a546-75b4-4d3f-aea4-8de56c7d15fc

	measure 'Markdown Orders vs LW' =
			VAR act = [Markdown Orders]
			VAR comp = [Markdown Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Markdown\LW
		lineageTag: 08802b3d-14db-4d53-8207-71cbcd6a17df

	measure 'Markdown % SRIV Orders LW' =
			CALCULATE (
			    [Markdown % SRIV Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Markdown\LW
		lineageTag: 7f472e7d-749c-4a78-841b-cfe75af03834

	measure 'Markdown % SRIV Orders vs LW' =
			VAR act = [Markdown % SRIV Orders]
			VAR comp = [Markdown % SRIV Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Markdown\LW
		lineageTag: 016ca35f-ae83-4aa6-bf10-155c98b613fb

	measure 'Markdown Orders vs LW %' =
			VAR act = [Markdown Orders]
			VAR comp = [Markdown Orders LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Markdown\LW
		lineageTag: 39c9ef4a-548b-4e77-911a-bec1a742fcb7

	measure 'Buying Margin LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Buying Margin Orders LY],
			        "Dispatch", [Buying Margin Dispatch LY],
			        [Buying Margin Orders LY]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Buying Margin\LY
		lineageTag: f8dacf5b-20c0-42fa-891c-b5fcb9e61081

	measure 'Buying Margin LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Buying Margin Orders LY-1],
			        "Dispatch", [Buying Margin Dispatch LY-1],
			        [Buying Margin Orders LY-1]
			    )
			RETURN
			    result
		description: Two years ago equivalent of Buying Margin LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Buying Margin\LY-1
		lineageTag: 1084de24-1caa-45f6-90ad-3e4cf73b9e40

	measure 'Buying Margin vs LY' =
			VAR act = [Buying Margin]
			VAR comp = [Buying Margin LY]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Buying Margin\LY
		lineageTag: bb71f5dd-2fa5-4a51-a6c4-319ddf2b2c42

	measure 'Buying Margin vs LY-1' =
			VAR act = [Buying Margin]
			VAR comp = [Buying Margin LY-1]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		description: Two years ago equivalent of Buying Margin vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Buying Margin\LY-1
		lineageTag: 09e1e720-4172-4f99-89f7-bf02a9c4d63c

	measure 'Buying Margin % LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Buying Margin % Orders LY],
			        "Dispatch", [Buying Margin % Dispatch LY],
			        [Buying Margin % Orders LY]
			    )
			RETURN
			    result
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Buying Margin\LY
		lineageTag: 1aa6b99d-7be9-45a2-8555-fbbab9efb026

	measure 'Buying Margin % LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Buying Margin % Orders LY-1],
			        "Dispatch", [Buying Margin % Dispatch LY-1],
			        [Buying Margin % Orders LY-1]
			    )
			RETURN
			    result
		description: Two years ago equivalent of Buying Margin % LY.
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Buying Margin\LY-1
		lineageTag: b981f889-fef3-4e38-b5a9-712a633efeb9

	measure 'Buying Margin % vs LY' =
			VAR act = [Buying Margin %]
			VAR comp = [Buying Margin % LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Buying Margin\LY
		lineageTag: 3e8908e5-8f56-4252-9848-3600e88f93c7

	measure 'Buying Margin % vs LY-1' =
			VAR act = [Buying Margin %]
			VAR comp = [Buying Margin % LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Buying Margin % vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Buying Margin\LY-1
		lineageTag: 4c795607-aae8-402b-81c9-09d3d7be8c53

	measure 'Buying Margin vs LY %' =
			VAR act = [Buying Margin]
			VAR comp = [Buying Margin LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Buying Margin\LY
		lineageTag: 36164f55-4495-4bd4-98ac-36e1524f10a5

	measure 'Buying Margin LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Buying Margin Orders LW],
			        "Dispatch", [Buying Margin Dispatch LW],
			        [Buying Margin Orders LW]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Buying Margin\LW
		lineageTag: 9ac045cb-9236-4694-a489-ed5e620fc3c3

	measure 'Buying Margin vs LW' =
			VAR act = [Buying Margin]
			VAR comp = [Buying Margin LW]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Buying Margin\LW
		lineageTag: 3a0e0e69-b9b9-4876-8fef-6b1ebd25ec48

	measure 'Buying Margin % LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Buying Margin % Orders LW],
			        "Dispatch", [Buying Margin % Dispatch LW],
			        [Buying Margin % Orders LW]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Buying Margin\LW
		lineageTag: 781703d8-8dea-43eb-99f8-e8e3544a79d3

	measure 'Buying Margin % vs LW' =
			VAR act = [Buying Margin %]
			VAR comp = [Buying Margin % LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Buying Margin\LW
		lineageTag: d46f09a9-a3ef-458c-8d54-12e2236a712b

	measure 'Buying Margin vs LW %' =
			VAR act = [Buying Margin]
			VAR comp = [Buying Margin LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Buying Margin\LW
		lineageTag: b692d344-c05f-4961-9d05-c4284fbf4287

	measure Markdown =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Markdown Orders],
			        "Dispatch", [Markdown Dispatch],
			        [Markdown Orders]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Markdown\Actual
		lineageTag: f378edb1-67c8-4939-ae43-99e02694d509

	measure 'Markdown % SRIV' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Markdown % SRIV Orders],
			        "Dispatch", [Markdown % SRIV Dispatch],
			        [Markdown % SRIV Orders]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Markdown\Actual
		lineageTag: 4f160a86-50a7-4f03-8363-2a97e6651ebd

	measure 'Markdown LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Markdown Orders LY],
			        "Dispatch", [Markdown Dispatch LY],
			        [Markdown Orders LY]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Markdown\LY
		lineageTag: 3e9efd68-484d-456c-9d8a-f3ba3c7d1ab6

	measure 'Markdown LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Markdown Orders LY-1],
			        "Dispatch", [Markdown Dispatch LY-1],
			        [Markdown Orders LY-1]
			    )
			RETURN
			    result
		description: Two years ago equivalent of Markdown LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Markdown\LY-1
		lineageTag: efa5aee2-5f13-490c-9ada-89557e3bb75e

	measure 'Markdown vs LY' =
			VAR act = [Markdown]
			VAR comp = [Markdown LY]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Markdown\LY
		lineageTag: f69cc750-c93d-4568-94af-5c55a7d95b50

	measure 'Markdown vs LY-1' =
			VAR act = [Markdown]
			VAR comp = [Markdown LY-1]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		description: Two years ago equivalent of Markdown vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Markdown\LY-1
		lineageTag: a331dea8-d402-4b81-bfb5-8b0d6c8111f5

	measure 'Markdown % SRIV LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Markdown % SRIV Orders LY],
			        "Dispatch", [Markdown % SRIV Dispatch LY],
			        [Markdown % SRIV Orders LY]
			    )
			RETURN
			    result
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Markdown\LY
		lineageTag: 9d41ba2f-d084-43aa-80c8-cbd22bfd04ce

	measure 'Markdown % SRIV LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Markdown % SRIV Orders LY-1],
			        "Dispatch", [Markdown % SRIV Dispatch LY-1],
			        [Markdown % SRIV Orders LY-1]
			    )
			RETURN
			    result
		description: Two years ago equivalent of Markdown % SRIV LY.
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Markdown\LY-1
		lineageTag: f836d059-b01b-4ec1-b88b-7e08d7987c76

	measure 'Markdown % SRIV vs LY' =
			VAR act = [Markdown % SRIV]
			VAR comp = [Markdown % SRIV LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Markdown\LY
		lineageTag: 1afd63ae-6e9d-4b6b-bdac-f65b2661cfdb

	measure 'Markdown % SRIV vs LY-1' =
			VAR act = [Markdown % SRIV]
			VAR comp = [Markdown % SRIV LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Markdown % SRIV vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Markdown\LY-1
		lineageTag: 307a34f3-2c42-4f7a-a639-7a40c679f672

	measure 'Markdown vs LY %' =
			VAR act = [Markdown]
			VAR comp = [Markdown LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Markdown\LY
		lineageTag: 2519fdf7-a068-4508-9170-ef8358f69b7d

	measure 'Markdown LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Markdown Orders LW],
			        "Dispatch", [Markdown Dispatch LW],
			        [Markdown Orders LW]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Markdown\LW
		lineageTag: 55535335-61b2-4082-b42a-5f971ac561f6

	measure 'Markdown vs LW' =
			VAR act = [Markdown]
			VAR comp = [Markdown LW]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Markdown\LW
		lineageTag: 9348dd1d-86e1-4bc7-9573-df5c19879c96

	measure 'Markdown % SRIV LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Markdown % SRIV Orders LW],
			        "Dispatch", [Markdown % SRIV Dispatch LW],
			        [Markdown % SRIV Orders LW]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Markdown\LW
		lineageTag: 34ca2169-c379-4438-916d-c0b5a97c5bca

	measure 'Markdown % SRIV vs LW' =
			VAR act = [Markdown % SRIV]
			VAR comp = [Markdown % SRIV LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Markdown\LW
		lineageTag: 22f59f2c-36fd-4848-90c4-8c1820122b2a

	measure 'Markdown vs LW %' =
			VAR act = [Markdown]
			VAR comp = [Markdown LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Markdown\LW
		lineageTag: b1ad3f51-9e17-4b24-8285-1cdab330b894

	measure 'FP SRIV Dispatch' = [FPP SRIV Dispatch] - [P SRIV Dispatch]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FP SRIV\Actual
		lineageTag: 11b4a2a1-4d4c-4610-9fcb-362adc63af82

	measure 'FP SRIV Dispatch LY' =
			CALCULATE (
			    [FP SRIV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FP SRIV\LY
		lineageTag: 46efb04e-e500-4b97-9f58-ecb6cd2e91ef

	measure 'FP SRIV Dispatch LY-1' =
			CALCULATE (
			    [FP SRIV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of FP SRIV Dispatch LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FP SRIV\LY-1
		lineageTag: 794b375d-af61-4b69-b4f9-6ea94e39b49e

	measure 'FP SRIV Dispatch vs LY' =
			VAR act = [FP SRIV Dispatch]
			VAR comp = [FP SRIV Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FP SRIV\LY
		lineageTag: 585b48a7-313a-44d9-896c-5f8af08550bc

	measure 'FP SRIV Dispatch vs LY-1' =
			VAR act = [FP SRIV Dispatch]
			VAR comp = [FP SRIV Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of FP SRIV Dispatch vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FP SRIV\LY-1
		lineageTag: 416b2ebe-c522-4a6c-85ce-761e7bf1ab5f

	measure 'FP SRIV Dispatch vs LY %' =
			VAR act = [FP SRIV Dispatch]
			VAR comp = [FP SRIV Dispatch LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\FP SRIV\LY
		lineageTag: 19989fda-ac19-4362-a078-e05cc2919b83

	measure 'FP SRIV Dispatch LW' =
			CALCULATE (
			    [FP SRIV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FP SRIV\LW
		lineageTag: 1a43e751-cac6-4785-95c5-a3333a291e1c

	measure 'FP SRIV Dispatch vs LW' =
			VAR act = [FP SRIV Dispatch]
			VAR comp = [FP SRIV Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FP SRIV\LW
		lineageTag: a3bc653e-030d-40f6-9a33-7cd3fc0f45ca

	measure 'FP SRIV Dispatch vs LW %' =
			VAR act = [FP SRIV Dispatch]
			VAR comp = [FP SRIV Dispatch LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\FP SRIV\LW
		lineageTag: 69940d7f-bc40-4df4-8aa4-cb9dbce90c41

	/// This measure is the sum of column 'factSalesDispatch'[Other Gross Selling Margin Adjustments]
	measure 'Other GSM Adj Dispatch' = SUM ( 'factSalesDispatch'[Other Gross Selling Margin Adjustments] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Other GSM Adj\Actual
		lineageTag: 561f1636-a089-4c11-8130-c9c729902ec1

	measure 'Other GSM Adj Dispatch LY' =
			CALCULATE (
			    [Other GSM Adj Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Other GSM Adj\LY
		lineageTag: b3700d4d-ee2d-4fa8-9858-30ade31934a7

	measure 'Other GSM Adj Dispatch LY-1' =
			CALCULATE (
			    [Other GSM Adj Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Other GSM Adj Dispatch LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Other GSM Adj\LY-1
		lineageTag: 50d302fb-85c3-4c94-ad86-e7c85458ce6b

	measure 'Other GSM Adj Dispatch vs LY' =
			VAR act = [Other GSM Adj Dispatch]
			VAR comp = [Other GSM Adj Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Other GSM Adj\LY
		lineageTag: 1e201b19-3cb6-4cbc-9af4-a9a30eea2dab

	measure 'Other GSM Adj Dispatch vs LY-1' =
			VAR act = [Other GSM Adj Dispatch]
			VAR comp = [Other GSM Adj Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Other GSM Adj Dispatch vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Other GSM Adj\LY-1
		lineageTag: bde55ddd-de11-45c7-9107-d523bdde5e12

	measure 'Other GSM Adj Dispatch LW' =
			CALCULATE (
			    [Other GSM Adj Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Other GSM Adj\LW
		lineageTag: 1cc9096d-ee6d-4db3-bd61-1c36b79c020d

	measure 'Other GSM Adj Dispatch vs LW' =
			VAR act = [Other GSM Adj Dispatch]
			VAR comp = [Other GSM Adj Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Other GSM Adj\LW
		lineageTag: 276dbeda-9b29-4565-bb8e-bc06b0d826c3

	/// This measure is the sum of column 'factSalesDispatch'[Staff Discount & Loyalty]
	measure 'Staff Discount & Loyalty Dispatch' = SUM ( 'factSalesDispatch'[Staff Discount & Loyalty] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Staff Discount & Loyalty\Actual
		lineageTag: 797cf0b5-200c-4174-a730-1c13d1707143

	/// This measure is the sum of column 'factSalesDispatch'[Depth Of Cut]
	measure 'Depth Of Cut Dispatch' = SUM ( 'factSalesDispatch'[Depth Of Cut] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Depth Of Cut\Actual
		lineageTag: 17ea3fb3-8398-4050-8153-f5bde18c6f4c

	measure 'Staff Discount & Loyalty Dispatch LY' =
			CALCULATE (
			    [Staff Discount & Loyalty Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Staff Discount & Loyalty\LY
		lineageTag: 52474ca4-76db-4d4d-ba91-9e639aa960c8

	measure 'Staff Discount & Loyalty Dispatch LY-1' =
			CALCULATE (
			    [Staff Discount & Loyalty Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Staff Discount & Loyalty Dispatch LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Staff Discount & Loyalty\LY-1
		lineageTag: e40f43e1-5180-40ff-a01a-cd9d956afbfe

	measure 'Staff Discount & Loyalty Dispatch vs LY' =
			VAR act = [Staff Discount & Loyalty Dispatch]
			VAR comp = [Staff Discount & Loyalty Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Staff Discount & Loyalty\LY
		lineageTag: 28a6d67b-2596-4cd9-a163-39f3dd9be7ce

	measure 'Staff Discount & Loyalty Dispatch vs LY-1' =
			VAR act = [Staff Discount & Loyalty Dispatch]
			VAR comp = [Staff Discount & Loyalty Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Staff Discount & Loyalty Dispatch vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Staff Discount & Loyalty\LY-1
		lineageTag: 742f6dda-228f-42ec-81d3-6316c41d42cd

	measure 'Staff Discount & Loyalty Dispatch LW' =
			CALCULATE (
			    [Staff Discount & Loyalty Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Staff Discount & Loyalty\LW
		lineageTag: e6b5d680-57f0-4f79-81c5-d74464ab03a0

	measure 'Staff Discount & Loyalty Dispatch vs LW' =
			VAR act = [Staff Discount & Loyalty Dispatch]
			VAR comp = [Staff Discount & Loyalty Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Staff Discount & Loyalty\LW
		lineageTag: d25b7cf5-220b-4856-80f6-7a3120f97949

	measure 'Depth Of Cut Dispatch LY' =
			CALCULATE (
			    [Depth Of Cut Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Depth Of Cut\LY
		lineageTag: ab04c740-2e32-42be-ad5a-882af248c817

	measure 'Depth Of Cut Dispatch LY-1' =
			CALCULATE (
			    [Depth Of Cut Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Depth Of Cut Dispatch LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Depth Of Cut\LY-1
		lineageTag: 9a0d2304-023b-4e65-853d-d0501f60c3a9

	measure 'Depth Of Cut Dispatch vs LY' =
			VAR act = [Depth Of Cut Dispatch]
			VAR comp = [Depth Of Cut Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Depth Of Cut\LY
		lineageTag: 0af48f75-f809-49c7-a9ab-aff0669bcf5a

	measure 'Depth Of Cut Dispatch vs LY-1' =
			VAR act = [Depth Of Cut Dispatch]
			VAR comp = [Depth Of Cut Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Depth Of Cut Dispatch vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Depth Of Cut\LY-1
		lineageTag: 0f2197f6-4b3a-4e15-8b76-c3b38a458274

	measure 'Depth Of Cut Dispatch LW' =
			CALCULATE (
			    [Depth Of Cut Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Depth Of Cut\LW
		lineageTag: e5194bd7-3da7-41f6-b101-74e1b701a53a

	measure 'Depth Of Cut Dispatch vs LW' =
			VAR act = [Depth Of Cut Dispatch]
			VAR comp = [Depth Of Cut Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Depth Of Cut\LW
		lineageTag: c35b454a-f8ed-4252-8f24-84b027ff8533

	measure 'Depth Of Cut % Dispatch' =
			VAR metric = [Depth Of Cut Dispatch]
			VAR sales = [SIS Sold Through Dispatch]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Depth Of Cut\Actual
		lineageTag: 68c8e627-9f05-41ac-92bf-a4fa8020b264

	measure 'Depth Of Cut % Dispatch LY' =
			CALCULATE (
			    [Depth Of Cut % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Depth Of Cut\LY
		lineageTag: 4b073dde-cbc9-47dc-877f-676807fae7b3

	measure 'Depth Of Cut % Dispatch LY-1' =
			CALCULATE (
			    [Depth Of Cut % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Depth Of Cut % Dispatch LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Depth Of Cut\LY-1
		lineageTag: 3da42448-9fc4-4a9e-8bcf-e429b98d8f16

	measure 'Depth Of Cut % Dispatch vs LY' =
			VAR act = [Depth Of Cut % Dispatch]
			VAR comp = [Depth Of Cut % Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Depth Of Cut\LY
		lineageTag: d4f49d3d-f703-4d50-80fc-7416f427ad68

	measure 'Depth Of Cut % Dispatch vs LY-1' =
			VAR act = [Depth Of Cut % Dispatch]
			VAR comp = [Depth Of Cut % Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Depth Of Cut % Dispatch vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Depth Of Cut\LY-1
		lineageTag: d7bc1bf7-b285-447f-b564-67fc1d39984f

	measure 'Depth Of Cut % Dispatch LW' =
			CALCULATE (
			    [Depth Of Cut % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Depth Of Cut\LW
		lineageTag: 143a35f6-d4d3-4c05-b1d1-3004257a129f

	measure 'Depth Of Cut % Dispatch vs LW' =
			VAR act = [Depth Of Cut % Dispatch]
			VAR comp = [Depth Of Cut % Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Depth Of Cut\LW
		lineageTag: 7771db00-3673-40e8-85ec-e995e96d7bcd

	measure 'Discount Participation % Orders' =
			VAR total =
			    CALCULATE ( [SRIV Orders], ALL ( SalesType ) )
			VAR promo =
			    CALCULATE ( [SRIV Orders], SalesType[fp_rp_ind] = "P" )
			VAR reduced =
			    CALCULATE ( [SRIV Orders], SalesType[fp_rp_ind] = "R" )
			VAR result = ( reduced + promo ) / total
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Discount Participation\Actual
		lineageTag: 56e9c71b-7f16-41b1-8a9b-f4a953f22a6c

	measure 'Discount Participation % Orders LY' =
			CALCULATE (
			    [Discount Participation % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Discount Participation\LY
		lineageTag: 315b6a0f-a3ef-4c63-8a69-6a9dcc6d0953

	measure 'Discount Participation % Orders LY-1' =
			CALCULATE (
			    [Discount Participation % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Discount Participation % Orders LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Discount Participation\LY-1
		lineageTag: f56c6c08-be65-4428-99a9-a7f99dd4b910

	measure 'Discount Participation % Orders LW' =
			CALCULATE (
			    [Discount Participation % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Discount Participation\LW
		lineageTag: 8eaa78ab-8a32-4390-87ba-c6de5063e279

	measure 'Discount Participation % Orders vs LY' =
			VAR act = [Discount Participation % Orders]
			VAR comp = [Discount Participation % Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Discount Participation\LY
		lineageTag: 67c59955-64cc-4420-939b-96a80fbb0180

	measure 'Discount Participation % Orders vs LY-1' =
			VAR act = [Discount Participation % Orders]
			VAR comp = [Discount Participation % Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Discount Participation % Orders vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Discount Participation\LY-1
		lineageTag: ab26cd5d-aaf6-43b0-9a07-3c4fc70fed36

	measure 'Discount Participation % Orders vs LW' =
			VAR act = [Discount Participation % Orders]
			VAR comp = [Discount Participation % Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Discount Participation\LW
		lineageTag: f1b1ba9e-2210-4804-a602-e5d74753b98c

	measure 'Discount Participation % Dispatch' =
			VAR total = [sum_Sales Revenue (Inc VAT)]
			VAR promo = [P SRIV Dispatch]
			VAR reduced = [RP SRIV Dispatch]
			VAR result = ( reduced + promo ) / total
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Discount Participation\Actual
		lineageTag: 77f66173-eb28-4f4a-b94d-a92a67f3007a

	measure 'Discount Participation % Dispatch LY' =
			CALCULATE (
			    [Discount Participation % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Discount Participation\LY
		lineageTag: 189e0777-54d2-4c55-8e80-0b29fb31c93a

	measure 'Discount Participation % Dispatch LY-1' =
			CALCULATE (
			    [Discount Participation % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Discount Participation % Dispatch LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Discount Participation\LY-1
		lineageTag: d3e06ffe-baca-46cf-8f3e-cc98afb4675b

	measure 'Discount Participation % Dispatch vs LY' =
			VAR act = [Discount Participation % Dispatch]
			VAR comp = [Discount Participation % Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Discount Participation\LY
		lineageTag: eaa67874-7c3e-4c21-8a6f-af0818e5b7cc

	measure 'Discount Participation % Dispatch vs LY-1' =
			VAR act = [Discount Participation % Dispatch]
			VAR comp = [Discount Participation % Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Discount Participation % Dispatch vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Discount Participation\LY-1
		lineageTag: 36913944-d866-4c66-9afa-c62bbb163688

	measure 'Discount Participation % Dispatch LW' =
			CALCULATE (
			    [Discount Participation % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Discount Participation\LW
		lineageTag: d3aeb070-2537-46eb-aced-135d4817272c

	measure 'Discount Participation % Dispatch vs LW' =
			VAR act = [Discount Participation % Dispatch]
			VAR comp = [Discount Participation % Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Discount Participation\LW
		lineageTag: c97c3160-ae79-4cc3-a98b-e29120ae1d2b

	measure 'Discount Participation %' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Discount Participation % Orders],
			        "Dispatch", [Discount Participation % Dispatch],
			        [Discount Participation % Orders]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Discount Participation\Actual
		lineageTag: e7e670ce-b1a3-4b75-b837-1fbc8cade480

	measure 'Discount Participation % LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Discount Participation % Orders LY],
			        "Dispatch", [Discount Participation % Dispatch LY],
			        [Discount Participation % Orders LY]
			    )
			RETURN
			    result
		formatString: 0.0%;(0.0)%
		displayFolder: Sales\Discount Participation\LY
		lineageTag: bd18885c-78c0-4936-9479-04e5ee8983dc

	measure 'Discount Participation % LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Discount Participation % Orders LY-1],
			        "Dispatch", [Discount Participation % Dispatch LY-1],
			        [Discount Participation % Orders LY-1]
			    )
			RETURN
			    result
		description: Two years ago equivalent of Discount Participation % LY.
		formatString: 0.0%;(0.0)%
		displayFolder: Sales\Discount Participation\LY-1
		lineageTag: 9ba9e0c7-db15-455e-a754-386bf1e78d59

	measure 'Discount Participation % vs LY' =
			VAR act = [Discount Participation %]
			VAR comp = [Discount Participation % LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Discount Participation\LY
		lineageTag: 255f1524-d016-47ed-b68e-534949990f77

	measure 'Discount Participation % vs LY-1' =
			VAR act = [Discount Participation %]
			VAR comp = [Discount Participation % LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Discount Participation % vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Discount Participation\LY-1
		lineageTag: f9172a2b-a32c-4461-ad74-52010a10e724

	measure 'Discount Participation % LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Discount Participation % Orders LW],
			        "Dispatch", [Discount Participation % Dispatch LW],
			        [Discount Participation % Orders LW]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Discount Participation\LW
		lineageTag: a1c14c3e-cccb-4052-acfd-881e8f715a3d

	measure 'Discount Participation % vs LW' =
			VAR act = [Discount Participation %]
			VAR comp = [Discount Participation % LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Discount Participation\LW
		lineageTag: 7bc5091a-a2f1-4bd0-b4bf-eeeb9af4cad3

	measure 'FPP SRIV Dispatch BUD' =
			VAR edw =
			    CALCULATE (
			        [sum_Full Price Sales Revenue (Inc VAT) DispFor],
			        ForecastScenarios[Forecast Scenario] = "BUD"
			    )
			VAR derisk =
			    CALCULATE ( [sum_SRIV_derisk_BUD], SalesType[fp_rp_ind] = "F" )
			VAR result = edw + derisk
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP SRIV\BUD
		lineageTag: e90b7f51-d217-456d-b831-80434763f2a8

	measure 'FPP SRIV Dispatch vs BUD' =
			VAR act = [FPP SRIV Dispatch]
			VAR comp = [FPP SRIV Dispatch BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP SRIV\BUD
		lineageTag: e79acb94-0174-45c8-a199-27c35ecb61e9

	measure 'FPP SRIV Dispatch vs BUD % ' =
			VAR act = [FPP SRIV Dispatch]
			VAR comp = [FPP SRIV Dispatch BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\FPP SRIV\BUD
		lineageTag: b183427d-f945-4dfc-ad08-145292166cf3

	measure 'FPP SRIV Dispatch FC' =
			VAR edw =
			    CALCULATE (
			        [sum_Full Price Sales Revenue (Inc VAT) DispFor],
			        ForecastScenarios[Forecast Scenario] = "FC"
			    )
			VAR derisk =
			    CALCULATE ( [sum_SRIV_derisk_FC], SalesType[fp_rp_ind] = "F" )
			VAR result = edw + derisk
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP SRIV\FC
		lineageTag: bedbf9f9-3f0c-42a2-8255-9c7be0bb852a

	measure 'FPP SRIV Dispatch vs FC' =
			VAR act = [FPP SRIV Dispatch]
			VAR comp = [FPP SRIV Dispatch FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP SRIV\FC
		lineageTag: cff6eaef-c9aa-47a3-bab0-a038ab55e0df

	measure 'FPP SRIV Dispatch vs FC %' =
			VAR act = [FPP SRIV Dispatch]
			VAR comp = [FPP SRIV Dispatch FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\FPP SRIV\FC
		lineageTag: fac10cb8-392e-4e76-bb3b-bb4cd6a2d3d7

	measure 'RP SRIV Dispatch BUD' =
			VAR edw =
			    CALCULATE (
			        [sum_Reduced Price Sales Revenue (Inc VAT) DispFor],
			        ForecastScenarios[Forecast Scenario] = "BUD"
			    )
			VAR derisk =
			    CALCULATE ( [sum_SRIV_derisk_BUD], SalesType[fp_rp_ind] = "R" )
			VAR result = edw + derisk
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP SRIV\BUD
		lineageTag: aa81f327-654c-417b-93d4-d20451203808

	measure 'RP SRIV Dispatch vs BUD' =
			VAR act = [RP SRIV Dispatch]
			VAR comp = [RP SRIV Dispatch BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP SRIV\BUD
		lineageTag: 11f3c441-cb3f-4975-8e8e-df2161666a92

	measure 'RP SRIV Dispatch vs BUD %' =
			VAR act = [RP SRIV Dispatch]
			VAR comp = [RP SRIV Dispatch BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\RP SRIV\BUD
		lineageTag: 6fa10e47-fb7e-4d39-b47a-71ca447232d8

	measure 'RP SRIV Dispatch FC' =
			VAR edw =
			    CALCULATE (
			        [sum_Reduced Price Sales Revenue (Inc VAT) DispFor],
			        ForecastScenarios[Forecast Scenario] = "FC"
			    )
			VAR derisk =
			    CALCULATE ( [sum_SRIV_derisk_FC], SalesType[fp_rp_ind] = "R" )
			VAR result = edw + derisk
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP SRIV\FC
		lineageTag: 2dce3560-3ee1-440b-8edd-47fb91b71aa2

	measure 'RP SRIV Dispatch vs FC' =
			VAR act = [RP SRIV Dispatch]
			VAR comp = [RP SRIV Dispatch FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP SRIV\FC
		lineageTag: d910c1fa-615b-49b7-9f64-f08c7b702870

	measure 'RP SRIV Dispatch vs FC %' =
			VAR act = [RP SRIV Dispatch]
			VAR comp = [RP SRIV Dispatch FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\RP SRIV\FC
		lineageTag: ef0a8633-3d41-410c-9d1f-f4661e13dda0

	measure 'SRIV Dispatch BUD' =
			VAR is_channel_unfiltered = [is_channel_unfiltered]
			VAR sale_type = [slctd_SalesTypeLevelAware]
			VAR total_sales =
			    CALCULATE (
			        [sum_Sales Revenue (Inc VAT) DispFor],
			        ForecastScenarios[Forecast Scenario] = "BUD"
			    )
			VAR result =
			    SWITCH (
			        sale_type,
			        "Total", total_sales,
			        "FP&P", [FPP SRIV Dispatch BUD],
			        "Full Price", BLANK (),
			        "Promo", BLANK (),
			        "Reduced", [RP SRIV Dispatch BUD],
			        total_sales
			    )
			RETURN
			    IF ( is_channel_unfiltered, result, BLANK () )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\BUD
		lineageTag: b54b1724-3530-4b9c-8fa2-f667a5efde7f

	measure 'SRIV Dispatch vs BUD' =
			VAR act = [SRIV Dispatch]
			VAR comp = [SRIV Dispatch BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\BUD
		lineageTag: 919c3890-5609-477e-82ac-eb87fc721062

	measure 'SRIV Dispatch vs BUD %' =
			VAR act = [SRIV Dispatch]
			VAR comp = [SRIV Dispatch BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\SRIV\BUD
		lineageTag: 7d62bcb3-ff7b-474c-a125-ecba08f30f5d

	measure 'SRIV Dispatch FC' =
			VAR is_channel_unfiltered = [is_channel_unfiltered]
			VAR sale_type = [slctd_SalesTypeLevelAware]
			VAR total_sales = [FPP SRIV Dispatch FC] + [RP SRIV Dispatch FC]
			VAR result =
			    SWITCH (
			        sale_type,
			        "Total", total_sales,
			        "FP&P", [FPP SRIV Dispatch FC],
			        "Full Price", BLANK (),
			        "Promo", BLANK (),
			        "Reduced", [RP SRIV Dispatch FC],
			        total_sales
			    )
			RETURN
			    IF ( is_channel_unfiltered, result, BLANK () )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\FC
		lineageTag: 8ad5f8fb-f616-4bb7-bd98-551515077ba0

	measure 'SRIV Dispatch vs FC' =
			VAR act = [SRIV Dispatch]
			VAR comp = [SRIV Dispatch FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\FC
		lineageTag: 43076afb-5613-44df-aad9-6c038c8033b0

	measure 'SRIV Dispatch vs FC %' =
			VAR act = [SRIV Dispatch]
			VAR comp = [SRIV Dispatch FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\SRIV\FC
		lineageTag: 26526a29-9d71-4e3c-83f6-b58e4be531ab

	measure is_channel_unfiltered =
			VAR is_channel_filtered =
			    IF (
			        ISFILTERED ( Channels[Channel] ),
			        IF (
			            AND (
			                CONTAINS ( Channels, Channels[Channel], "Stores" ),
			                CONTAINS ( Channels, Channels[Channel], "Online" )
			            ),
			            FALSE,
			            TRUE
			        )
			    )
			VAR is_channel_detail_filtered =
			    IF (
			        ISFILTERED ( Channels[Channel Detail] ),
			        IF (
			            AND (
			                CONTAINS ( Channels, Channels[Channel Detail], "Mainchain" ),
			                CONTAINS ( Channels, Channels[Channel Detail], "Online" )
			            ),
			            FALSE,
			            TRUE
			        )
			    )
			VAR is_channel_control_filtered =
			    IF (
			        ISFILTERED ( ChannelControl[Channel] ),
			        IF (
			            CONTAINS ( ChannelControl, ChannelControl[Channel], "Total" )
			                || CONTAINS ( ChannelControl, ChannelControl[Channel], "Total ex. Outlets" )
			                || CONTAINS ( ChannelControl, ChannelControl[Channel], "Stores" )
			                    && CONTAINS ( ChannelControl, ChannelControl[Channel], "Online" )
			                || CONTAINS ( ChannelControl, ChannelControl[Channel], "Mainchain" )
			                    && CONTAINS ( ChannelControl, ChannelControl[Channel], "Online" ),
			            FALSE,
			            TRUE
			        )
			    )
			VAR result =
			    IF (
			        is_channel_filtered || is_channel_detail_filtered
			            || is_channel_control_filtered,
			        FALSE,
			        TRUE
			    )
			RETURN
			    result
		lineageTag: 3154a56e-3798-4776-aaf2-957787a0d27f

	measure 'Buying Margin Orders BUD' = CALCULATE ( [sum_TotBIMAV], ForecastScenarios[Forecast Scenario] = "BUD" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Buying Margin\BUD
		lineageTag: c5837c7c-7fc6-4845-b740-0e42dc1cab25

	measure 'Buying Margin Orders vs BUD' =
			VAR act = [Buying Margin Orders]
			VAR comp = [Buying Margin Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Buying Margin\BUD
		lineageTag: 8f95b984-ec74-4433-a9fd-545f1b13f65c

	measure 'Buying Margin % Orders BUD' =
			VAR metric = [Buying Margin Orders BUD]
			VAR sales =
			    CALCULATE ( [sum_TotBIMBV], ForecastScenarios[Forecast Scenario] = "BUD" )
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Buying Margin\BUD
		lineageTag: 29d70bc3-1f91-4196-ab63-8cb91915d1de

	measure 'Buying Margin % Orders vs BUD' =
			VAR act = [Buying Margin % Orders]
			VAR comp = [Buying Margin % Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Buying Margin\BUD
		lineageTag: bbdac930-d48b-4737-87db-8f89247faad4

	measure 'Buying Margin Orders vs BUD %' =
			VAR act = [Buying Margin Orders]
			VAR comp = [Buying Margin Orders BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Buying Margin\BUD
		lineageTag: 05a44b4b-cbb8-49fb-bae4-d8e684b5e126

	measure 'Buying Margin Orders FC' =
			
			VAR PlanVersion = [SlctdForecastVersion]
			Return
			CALCULATE ( [sum_TotBIMAV], factForecast[plan] = PlanVersion )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Buying Margin\FC
		lineageTag: 33cb908b-3367-4e7f-b9b3-ccdb2e78ec1f

	measure 'Buying Margin Orders vs FC' =
			
			VAR act = [Buying Margin Orders]
			VAR comp = [Buying Margin Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Buying Margin\FC
		lineageTag: 21f78e2a-0530-463d-acb2-43b6fb50494c

	measure 'Buying Margin % Orders FC' =
			
			VAR PlanVersion = [SlctdForecastVersion]
			VAR metric = [Buying Margin Orders FC]
			VAR sales =
			    CALCULATE ( [sum_TotBIMBV], factForecast[plan] = PlanVersion )
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Buying Margin\FC
		lineageTag: 78bd914f-14db-4ffd-a940-4a2c146d2a97

	measure 'Buying Margin % Orders vs FC' =
			VAR act = [Buying Margin % Orders]
			VAR comp = [Buying Margin % Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Buying Margin\FC
		lineageTag: 5722ba72-05cb-41c3-b6fd-ae06adaba9f4

	measure 'Buying Margin Orders vs FC %' =
			VAR act = [Buying Margin Orders]
			VAR comp = [Buying Margin Orders FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Buying Margin\FC
		lineageTag: b450e535-c1c9-4ba7-a485-43b516881c47

	measure 'Markdown Orders BUD' = CALCULATE ( [sum_DiscMDV], ForecastScenarios[Forecast Scenario] = "BUD" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Markdown\BUD
		lineageTag: 2f85278b-a877-4989-84df-1ccedcfbf699

	measure 'Markdown Orders vs BUD' =
			VAR act = [Markdown Orders]
			VAR comp = [Markdown Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Markdown\BUD
		lineageTag: 5483ca3e-4b50-4a84-a0b9-10a08cf49c80

	measure 'Markdown % SRIV Orders BUD' =
			VAR metric = - [Markdown Orders BUD]
			VAR sales = [SRIV Orders BUD]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Markdown\BUD
		lineageTag: d9f9b042-b8fd-4dad-80d7-9a799ddaa62b

	measure 'Markdown % SRIV Orders vs BUD' =
			VAR act = [Markdown % SRIV Orders]
			VAR comp = [Markdown % SRIV Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Markdown\BUD
		lineageTag: 2e277004-c1e1-408c-aff5-14120a2ddfaf

	measure 'Markdown Orders vs BUD %' =
			VAR act = [Markdown Orders]
			VAR comp = [Markdown Orders BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Markdown\BUD
		lineageTag: c95ce2af-8f54-43b3-8b28-874772246c4c

	measure 'SRIV Orders BUD' = ```
			
			VAR TotPlan = CALCULATE ( [sum_TotSlsV], ForecastScenarios[Forecast Scenario] = "BUD" )
			VAR FPPPlan = CALCULATE ( [sum_FPPSlsV], ForecastScenarios[Forecast Scenario] = "BUD" )
			VAR RedPlan = CALCULATE ( [sum_RedSlsV], ForecastScenarios[Forecast Scenario] = "BUD" )
			VAR result = SWITCH([slctd_SalesType],
			    "FP&P", FPPPlan,
			    "Reduced", RedPlan,
			    TotPlan)
			RETURN
			    result
			
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\BUD
		lineageTag: 1752c4d8-fdb5-4f0c-ba6a-ceeba325bb36

	measure 'SRIV Orders vs BUD' =
			VAR act = [SRIV Orders]
			VAR comp = [SRIV Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\BUD
		lineageTag: 239b44db-5e57-4d75-85e7-7b607dfeecad

	measure 'SRIV Orders vs BUD %' =
			VAR act = [SRIV Orders]
			VAR comp = [SRIV Orders BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\SRIV\BUD
		lineageTag: b63b156c-4e5d-4395-8dde-8d2b93191297

	measure 'SRIV Orders vs FC' =
			VAR act = [SRIV Orders]
			VAR comp = [SRIV Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\FC
		lineageTag: f36e5a39-ec2d-4c5e-8bf1-c49ad52b16d1

	measure 'SRIV Orders vs FC %' =
			VAR act = [SRIV Orders]
			VAR comp = [SRIV Orders FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\SRIV\FC
		lineageTag: e3dca5d2-6aba-4e86-8e13-83505d0b6576

	measure 'SRIV Orders FC' = ```
			
			VAR PlanVersion = [SlctdForecastVersion]
			VAR TotPlan = CALCULATE ( [sum_TotSlsV], factForecast[plan] = PlanVersion )
			VAR FPPPlan = CALCULATE ( [sum_FPPSlsV], factForecast[plan] = PlanVersion )
			VAR RedPlan = CALCULATE ( [sum_RedSlsV], factForecast[plan] = PlanVersion )
			VAR result = SWITCH([slctd_SalesType],
			    "FP&P", FPPPlan,
			    "Reduced", RedPlan,
			    TotPlan)
			RETURN
			    result
			
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\FC
		lineageTag: 1dd10f8e-ebc0-4f8c-a49b-fbc1c1b10ad4

	measure 'SRIV Orders vs QRF' =
			VAR act = [SRIV Orders]
			VAR comp = [SRIV Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\QRF
		lineageTag: cfdee6af-39e6-4b9e-9136-85b8dc95242a

	measure 'SRIV Orders vs QRF %' =
			VAR act = [SRIV Orders]
			VAR comp = [SRIV Orders QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\SRIV\QRF
		lineageTag: 10bee698-7ce5-4675-b8d7-8673517b66ac

	measure 'SRIV Orders QRF' = ```
			
			VAR PlanVersion = [SlctdQRFVersion]
			VAR TotPlan = CALCULATE ( [sum_TotSlsV], factForecast[plan] = PlanVersion )
			VAR FPPPlan = CALCULATE ( [sum_FPPSlsV], factForecast[plan] = PlanVersion )
			VAR RedPlan = CALCULATE ( [sum_RedSlsV], factForecast[plan] = PlanVersion )
			VAR result = SWITCH([slctd_SalesType],
			    "FP&P", FPPPlan,
			    "Reduced", RedPlan,
			    TotPlan)
			RETURN
			    result
			
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\QRF
		lineageTag: 1b664349-f5ff-421e-8032-57d8fc8db015

	measure 'GSM Orders BUD' =
			
			VAR Tot_mp_plan =  CALCULATE ( [sum_TotGSMV], ForecastScenarios[Forecast Scenario] = "BUD" )
			VAR FPP_mp_plan =  CALCULATE ( [sum_FPPGSMV], ForecastScenarios[Forecast Scenario] = "BUD" )
			VAR RP_mp_plan =  CALCULATE ( [sum_RedGSMV], ForecastScenarios[Forecast Scenario] = "BUD" )
			VAR result =    SWITCH([slctd_SalesType],
			                "FP&P", FPP_mp_plan,
			                "Reduced", RP_mp_plan,
			                Tot_mp_plan)
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\GSM\BUD
		lineageTag: 22270719-56ec-4157-ab8a-31f7cd0744ba

	measure 'GSM Orders vs BUD' =
			VAR act = [GSM Orders]
			VAR comp = [GSM Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\GSM\BUD
		lineageTag: 538e225e-11df-4110-a3f5-17bd5ae19960

	measure 'GSM % SREV Orders BUD' =
			VAR metric = [GSM Orders BUD]
			VAR sales = [SREV Orders BUD]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\GSM\BUD
		lineageTag: c2890bd0-f358-471c-b777-cc0d381dd7b9

	measure 'GSM % SREV Orders vs BUD' =
			VAR act = [GSM % SREV Orders]
			VAR comp = [GSM % SREV Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\GSM\BUD
		lineageTag: 88bf7441-d94d-40e5-850a-86ce2c73d11e

	measure 'GSM Orders vs BUD %' =
			VAR act = [GSM Orders]
			VAR comp = [GSM Orders BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\GSM\BUD
		lineageTag: 5ef19b18-44ab-419d-b776-05ed4f44f608

	measure 'SREV Orders BUD' =
			
			VAR Tot_mp_plan =  CALCULATE ( [sum_TotSlsxV], ForecastScenarios[Forecast Scenario] = "BUD" )
			VAR FPP_mp_plan =  CALCULATE ( [sum_FPPSlsxV], ForecastScenarios[Forecast Scenario] = "BUD" )
			VAR RP_mp_plan =  CALCULATE ( [sum_TotSlsxV] - [sum_FPPSlsxV], ForecastScenarios[Forecast Scenario] = "BUD" )
			VAR result =    SWITCH([slctd_SalesType],
			                "FP&P", FPP_mp_plan,
			                "Reduced", RP_mp_plan,
			                Tot_mp_plan)
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SREV\BUD
		lineageTag: 4ca3be37-ba89-4e86-874a-07c5deac3d50

	measure 'SREV Orders vs BUD' =
			VAR act = [SREV Orders]
			VAR comp = [SREV Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SREV\BUD
		lineageTag: d47cfd0d-5e17-4e4a-b58b-4997393baf11

	measure 'SREV Orders vs BUD %' =
			VAR act = [SREV Orders]
			VAR comp = [SREV Orders BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\SREV\BUD
		lineageTag: be3f46a3-af7d-4afa-9b6e-ecc787c4dd33

	measure 'SREV Orders vs FC' =
			VAR act = [SREV Orders]
			VAR comp = [SREV Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SREV\FC
		lineageTag: 6ba23b4b-2273-46a8-871c-94a635c63050

	measure 'SREV Orders vs FC %' =
			VAR act = [SREV Orders]
			VAR comp = [SREV Orders FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\SREV\FC
		lineageTag: 63b0b50f-29ad-4d95-941b-c378764b90f4

	measure 'SREV Orders FC' = ```
			
			VAR PlanVersion = [SlctdForecastVersion] 
			VAR Tot_mp_plan =  CALCULATE ( [sum_TotSlsxV], factForecast[plan] = PlanVersion )
			VAR FPP_mp_plan =  CALCULATE ( [sum_FPPSlsxV], factForecast[plan] = PlanVersion )
			VAR RP_mp_plan =  CALCULATE ( [sum_TotSlsxV] - [sum_FPPSlsxV], factForecast[plan] = PlanVersion )
			VAR result =    SWITCH([slctd_SalesType],
			                "FP&P", FPP_mp_plan,
			                "Reduced", RP_mp_plan,
			                Tot_mp_plan)
			RETURN
			    result
			
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SREV\FC
		lineageTag: 42b9bdff-ff05-4c19-a72e-189ee63907ff

	measure 'SREV Orders vs QRF' =
			VAR act = [SREV Orders]
			VAR comp = [SREV Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SREV\QRF
		lineageTag: cf566b43-5e29-47a1-829d-c0d569dd5765

	measure 'SREV Orders vs QRF %' =
			VAR act = [SREV Orders]
			VAR comp = [SREV Orders QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\SREV\QRF
		lineageTag: 41e0995a-8844-4d76-adad-6892efba5d64

	measure 'SREV Orders QRF' = ```
			
			VAR PlanVersion = [SlctdQRFVersion] 
			VAR Tot_mp_plan =  CALCULATE ( [sum_TotSlsxV], factForecast[plan] = PlanVersion )
			VAR FPP_mp_plan =  CALCULATE ( [sum_FPPSlsxV], factForecast[plan] = PlanVersion )
			VAR RP_mp_plan =  CALCULATE ( [sum_TotSlsxV] - [sum_FPPSlsxV], factForecast[plan] = PlanVersion )
			VAR result =    SWITCH([slctd_SalesType],
			                "FP&P", FPP_mp_plan,
			                "Reduced", RP_mp_plan,
			                Tot_mp_plan)
			RETURN
			    result
			
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SREV\QRF
		lineageTag: 910d8263-009a-4399-a42c-72ac8d1fc755

	measure 'GSM Orders FC' =
			
			VAR PlanVersion = [SlctdForecastVersion]
			VAR Tot_mp_plan =  CALCULATE ( [sum_TotGSMV], factForecast[plan] = PlanVersion )
			VAR FPP_mp_plan =  CALCULATE ( [sum_FPPGSMV], factForecast[plan] = PlanVersion )
			VAR RP_mp_plan =  CALCULATE ( [sum_RedGSMV], factForecast[plan] = PlanVersion )
			VAR result =    SWITCH([slctd_SalesType],
			                "FP&P", FPP_mp_plan,
			                "Reduced", RP_mp_plan,
			                Tot_mp_plan)
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\GSM\FC
		lineageTag: 541b10dd-de05-41cb-8f76-1e5c1d19d1ab

	measure 'GSM Orders vs FC' =
			VAR act = [GSM Orders]
			VAR comp = [GSM Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\GSM\FC
		lineageTag: 123a317a-aed2-419c-abb3-148ed3aff371

	measure 'GSM % SREV Orders FC' =
			VAR metric = [GSM Orders FC]
			VAR sales = [SREV Orders FC]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\GSM\FC
		lineageTag: 571b41e1-28bd-43ef-a476-e0a0c3ce0c6b

	measure 'GSM % SREV Orders vs FC' =
			VAR act = [GSM % SREV Orders]
			VAR comp = [GSM % SREV Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\GSM\FC
		lineageTag: 4e199184-6f9b-43f8-9dcd-b88203b05d3c

	measure 'GSM Orders vs FC %' =
			VAR act = [GSM Orders]
			VAR comp = [GSM Orders FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\GSM\FC
		lineageTag: 8cbcc271-77ce-4227-93b9-f4fd3dcb400f

	measure 'Markdown Orders FC' =
			
			VAR PlanVersion = [SlctdForecastVersion]
			Return CALCULATE ( [sum_DiscMDV], factForecast[plan] = PlanVersion )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Markdown\FC
		lineageTag: 31bbe478-5811-47e1-a6fa-1d42e90af7b6

	measure 'Markdown Orders vs FC' =
			VAR act = [Markdown Orders]
			VAR comp = [Markdown Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Markdown\FC
		lineageTag: c414a38a-f961-492a-8c48-02d52d886a97

	measure 'Markdown % SRIV Orders FC' =
			VAR metric = - [Markdown Orders FC]
			VAR sales = [SRIV Orders FC]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Markdown\FC
		lineageTag: d7803263-6a13-46db-93e2-6a6e3c82177d

	measure 'Markdown % SRIV Orders vs FC' =
			VAR act = [Markdown % SRIV Orders]
			VAR comp = [Markdown % SRIV Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Markdown\FC
		lineageTag: 233bbafa-6cfb-4136-ac37-606bb13eb799

	measure 'Markdown Orders vs FC %' =
			VAR act = [Markdown Orders]
			VAR comp = [Markdown Orders FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Markdown\FC
		lineageTag: 90e1ba9d-41d1-47a6-bbb0-e2041872c88b

	measure 'SRIV BUD' = ```
			
			VAR firstweek_yr = [SlctdBudVersion]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    [fiscalWeek] <  firstweek_yr,
			            [SRIV],
			            [SRIV Orders BUD]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] ) 
			 
			/*VAR result = [SRIV Orders BUD]
			RETURN
			    result*/
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\BUD
		lineageTag: ff88d414-c5eb-4793-9a31-efb88b0bf180

	measure 'SRIV vs BUD' =
			VAR act = [SRIV]
			VAR comp = [SRIV BUD]
			VAR result = act - comp
			RETURN
			    if(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\BUD
		lineageTag: 878e78e7-7d1c-416b-a1f9-a559d274f60c

	measure 'SRIV vs BUD %' =
			VAR act = [SRIV]
			VAR comp = [SRIV BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV\BUD
		lineageTag: a1bf0c30-a58f-4d7b-be62-0d37eb0d1972

	measure 'SRIV FC' =
			//SelectedWeeks
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR firstweek_qtr = [SlctdFirstWeekQtrFC]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [SRIV],
			            [SRIV Orders FC]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\FC
		lineageTag: 94fb4be1-db4e-4864-b92b-bbed0dd298c6

	measure 'SRIV vs FC' =
			VAR act = [SRIV]
			VAR comp = [SRIV FC]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\FC
		lineageTag: aaf2f930-6f5f-4b7a-91c1-f16d66837468

	measure 'SRIV vs FC %' =
			VAR act = [SRIV]
			VAR comp = [SRIV FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV\FC
		lineageTag: faa52472-17af-4b9d-b0ac-620c546db54b

	measure 'SRIV QRF' =
			//SelectedWeeks
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR firstweek_qtr = [SlctdFirstWeekQtrQRF]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [SRIV],
			            [SRIV Orders QRF]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\QRF
		lineageTag: 0b547f07-aba6-410c-9510-75de83492dd2

	measure 'SRIV vs QRF' =
			VAR act = [SRIV]
			VAR comp = [SRIV QRF]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\QRF
		lineageTag: 2befa22c-4e4f-4f4e-9a3b-adc3a3acce4d

	measure 'SRIV vs QRF %' =
			VAR act = [SRIV]
			VAR comp = [SRIV QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV\QRF
		lineageTag: 2c4f3456-d0ab-434f-bbc6-2e4f5aadc2b3

	measure 'SREV BUD' = ```
			
			VAR firstweek_yr = [SlctdBudVersion]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    [fiscalWeek] <  firstweek_yr,
			            [SREV],
			            [SREV Orders BUD]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] ) 
			
			/*VAR result = [SREV Orders BUD]
			RETURN
			    result*/
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV\BUD
		lineageTag: 729fdf32-1717-4826-a5c6-f9f8c2597bf8

	measure 'SREV vs BUD' =
			VAR act = [SREV]
			VAR comp = [SREV BUD]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV\BUD
		lineageTag: 9d28fd2c-1cda-4565-bcfa-aa546075bb57

	measure 'SREV vs BUD %' =
			VAR act = [SREV]
			VAR comp = [SREV BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SREV\BUD
		lineageTag: 8f56ce87-e2c1-4e2d-874d-da5fc3e91726

	measure 'SREV Dispatch BUD' =
			VAR edw =
			    CALCULATE (
			        [sum_Sales Revenue (Exc VAT) DispFor],
			        ForecastScenarios[Forecast Scenario] = "BUD"
			    )
			VAR derisk = [sum_SREV_derisk_BUD]
			VAR result = edw + derisk
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SREV\BUD
		lineageTag: e93213cd-8144-4a68-bce5-bb2caaa23541

	measure 'SREV Dispatch vs BUD' =
			VAR act = [SREV Dispatch]
			VAR comp = [SREV Dispatch BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SREV\BUD
		lineageTag: a49845c1-a990-4b15-b63d-b31dd50b66ca

	measure 'SREV Dispatch vs BUD %' =
			VAR act = [SREV Dispatch]
			VAR comp = [SREV Dispatch BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\SREV\BUD
		lineageTag: d6a5b8f7-68e1-4b00-9384-233ec70da831

	measure 'SREV Dispatch FC' =
			VAR edw =
			    CALCULATE (
			        [sum_Sales Revenue (Exc VAT) DispFor],
			        ForecastScenarios[Forecast Scenario] = "FC"
			    )
			VAR derisk = [sum_SREV_derisk_FC]
			VAR result = edw + derisk
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SREV\FC
		lineageTag: 39d56f28-4b88-4f25-ba44-ba243a10eac8

	measure 'SREV Dispatch vs FC' =
			VAR act = [SREV Dispatch]
			VAR comp = [SREV Dispatch FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SREV\FC
		lineageTag: ac4a13bb-671a-4fa2-94d6-3a633285af4a

	measure 'SREV Dispatch vs FC %' =
			VAR act = [SREV Dispatch]
			VAR comp = [SREV Dispatch FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\SREV\FC
		lineageTag: 73ffa564-2a93-407f-b865-34cc3b1448fe

	measure 'SREV FC' =
			//SelectedWeeks
			VAR firstweek_qtr = [SlctdFirstWeekQtrFC]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [SREV],
			            [SREV Orders FC]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV\FC
		lineageTag: 06c6ea8c-f7e9-4907-b6c0-b5e829f52d6a

	measure 'SREV vs FC' =
			VAR act = [SREV]
			VAR comp = [SREV FC]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV\FC
		lineageTag: 9be53fca-d694-400b-a5de-1b06491ae5fd

	measure 'SREV vs FC %' =
			VAR act = [SREV]
			VAR comp = [SREV FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SREV\FC
		lineageTag: d4304396-8c07-446b-af50-4e1f6ac9c64a

	measure 'GSM Dispatch BUD' =
			VAR mp_plan =
			    CALCULATE (
			        [sum_Gross Selling Margin DispFor],
			        ForecastScenarios[Forecast Scenario] = "BUD"
			    )
			VAR derisk = [sum_GSM_derisk_BUD]
			VAR result = mp_plan + derisk
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\GSM\BUD
		lineageTag: f9666342-c2d5-4277-af42-a0855d4f7892

	measure 'GSM Dispatch vs BUD' =
			VAR act = [GSM Dispatch]
			VAR comp = [GSM Dispatch BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\GSM\BUD
		lineageTag: 86b25568-4351-4b71-8711-5de487268e1a

	measure 'GSM % SREV Dispatch BUD' =
			VAR metric = [GSM Dispatch BUD]
			VAR sales = [SREV Dispatch BUD]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\GSM\BUD
		lineageTag: bd4cfe70-7161-4a97-829e-e032598d8c00

	measure 'GSM % SREV Dispatch vs BUD' =
			VAR act = [GSM % SREV Dispatch]
			VAR comp = [GSM % SREV Dispatch BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\GSM\BUD
		lineageTag: df0c6830-867a-48e9-84ed-cf367fe1abca

	measure 'GSM Dispatch vs BUD %' =
			VAR act = [GSM Dispatch]
			VAR comp = [GSM Dispatch BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\GSM\BUD
		lineageTag: 71cda17d-ed03-413f-b756-72433642ddfa

	measure 'GSM Dispatch FC' =
			VAR mp_plan =
			    CALCULATE (
			        [sum_Gross Selling Margin DispFor],
			        ForecastScenarios[Forecast Scenario] = "FC"
			    )
			VAR derisk = [sum_GSM_derisk_FC]
			VAR result = mp_plan + derisk
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\GSM\FC
		lineageTag: 2a1d1d3d-1c7c-42ac-94cd-02a9d2c7fb43

	measure 'GSM Dispatch vs FC' =
			VAR act = [GSM Dispatch]
			VAR comp = [GSM Dispatch FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\GSM\FC
		lineageTag: 74e56cda-a3aa-4e99-a1ec-37393761037d

	measure 'GSM % SREV Dispatch FC' =
			VAR metric = [GSM Dispatch FC]
			VAR sales = [SREV Dispatch FC]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\GSM\FC
		lineageTag: 2af272ae-094b-4e41-b3bc-e4f4e0cb7d22

	measure 'GSM % SREV Dispatch vs FC' =
			VAR act = [GSM % SREV Dispatch]
			VAR comp = [GSM % SREV Dispatch FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\GSM\FC
		lineageTag: 7db20f48-64c6-4450-aeeb-608d214eba59

	measure 'GSM Dispatch vs FC %' =
			VAR act = [GSM Dispatch]
			VAR comp = [GSM Dispatch FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\GSM\FC
		lineageTag: eddfd6ce-2eb3-419a-8d48-0c7ab0494f22

	measure 'Buying Margin Dispatch BUD' =
			VAR cogs_inc_vat =
			    CALCULATE (
			        - [sum_Cost Of Goods Sold (Inc VAT) DispFor],
			        ForecastScenarios[Forecast Scenario] = "BUD"
			    )
			VAR bm_denom =
			    CALCULATE (
			        [sum_Buying Margin Denominator DispFor],
			        ForecastScenarios[Forecast Scenario] = "BUD"
			    )
			VAR result = bm_denom - cogs_inc_vat
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Buying Margin\BUD
		lineageTag: 4cf2c708-c1ff-4f3d-8fd7-68ea20d2d9a4

	measure 'Buying Margin Dispatch vs BUD' =
			VAR act = [Buying Margin Dispatch]
			VAR comp = [Buying Margin Dispatch BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Buying Margin\BUD
		lineageTag: ff93802d-23a9-41fc-b768-bdf92b06a7ff

	measure 'Buying Margin % Dispatch BUD' =
			VAR metric = [Buying Margin Dispatch BUD]
			VAR sales =
			    CALCULATE (
			        [sum_Buying Margin Denominator DispFor],
			        ForecastScenarios[Forecast Scenario] = "BUD"
			    )
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Buying Margin\BUD
		lineageTag: b094e57c-c016-424d-8bfc-0679ccf2d792

	measure 'Buying Margin % Dispatch vs BUD' =
			VAR act = [Buying Margin % Dispatch]
			VAR comp = [Buying Margin % Dispatch BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Buying Margin\BUD
		lineageTag: e7efee00-4c1b-4e58-bbb6-12c5fa5e9757

	measure 'Buying Margin Dispatch vs BUD %' =
			VAR act = [Buying Margin Dispatch]
			VAR comp = [Buying Margin Dispatch BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Buying Margin\BUD
		lineageTag: e1c3e157-2487-4e00-9ed8-67d58604a1e7

	measure 'Buying Margin Dispatch FC' =
			VAR cogs_inc_vat =
			    CALCULATE (
			        - [sum_Cost Of Goods Sold (Inc VAT) DispFor],
			        ForecastScenarios[Forecast Scenario] = "FC"
			    )
			VAR bm_denom =
			    CALCULATE (
			        [sum_Buying Margin Denominator DispFor],
			        ForecastScenarios[Forecast Scenario] = "FC"
			    )
			VAR result = bm_denom - cogs_inc_vat
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Buying Margin\FC
		lineageTag: 86011048-17ff-48e9-8c54-927271407efa

	measure 'Buying Margin Dispatch vs FC' =
			VAR act = [Buying Margin Dispatch]
			VAR comp = [Buying Margin Dispatch FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Buying Margin\FC
		lineageTag: 266345ce-8a9a-4ea8-96b8-415b0707ad27

	measure 'Buying Margin % Dispatch FC' =
			VAR metric = [Buying Margin Dispatch FC]
			VAR sales =
			    CALCULATE (
			        [sum_Buying Margin Denominator DispFor],
			        ForecastScenarios[Forecast Scenario] = "FC"
			    )
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Buying Margin\FC
		lineageTag: b50a6399-a15d-483a-bca7-755e10e75c49

	measure 'Buying Margin % Dispatch vs FC' =
			VAR act = [Buying Margin % Dispatch]
			VAR comp = [Buying Margin % Dispatch FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Buying Margin\FC
		lineageTag: 8af0131c-103b-4d58-93bc-fd68cdfb61d1

	measure 'Buying Margin Dispatch vs FC %' =
			VAR act = [Buying Margin Dispatch]
			VAR comp = [Buying Margin Dispatch FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Buying Margin\FC
		lineageTag: 1d52cb3d-6d68-4110-a126-7de41bfd16a7

	measure 'Markdown Dispatch BUD' =
			CALCULATE (
			    [sum_Markdown DispFor],
			    ForecastScenarios[Forecast Scenario] = "BUD"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Markdown\BUD
		lineageTag: 67cddce5-a962-4703-911e-0baa6f0df7f6

	measure 'Markdown Dispatch vs BUD' =
			VAR act = [Markdown Dispatch]
			VAR comp = [Markdown Dispatch BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Markdown\BUD
		lineageTag: c9965827-028d-4ff5-b5b1-89d2c9660872

	measure 'Markdown % SRIV Dispatch BUD' =
			VAR metric = - [Markdown Dispatch BUD]
			VAR sales = [SRIV Dispatch BUD]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Markdown\BUD
		lineageTag: 08609e26-58c5-410c-96a2-a581b665c107

	measure 'Markdown % SRIV Dispatch vs BUD' =
			VAR act = [Markdown % SRIV Dispatch]
			VAR comp = [Markdown % SRIV Dispatch BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Markdown\BUD
		lineageTag: 8a143974-71eb-4f26-88ec-9646026bebad

	measure 'Markdown Dispatch vs BUD %' =
			VAR act = [Markdown Dispatch]
			VAR comp = [Markdown Dispatch BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Markdown\BUD
		lineageTag: 2404de42-56f1-4d36-a382-47df19bff0de

	measure 'Markdown Dispatch FC' =
			CALCULATE (
			    [sum_Markdown DispFor],
			    ForecastScenarios[Forecast Scenario] = "FC"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Markdown\FC
		lineageTag: 9a7dcb7f-9f65-4f6b-9e60-bd62a1ecadb3

	measure 'Markdown Dispatch vs FC' =
			VAR act = [Markdown Dispatch]
			VAR comp = [Markdown Dispatch FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Markdown\FC
		lineageTag: 38ecd92a-f770-405e-bb50-d53627694374

	measure 'Markdown % SRIV Dispatch FC' =
			VAR metric = - [Markdown Dispatch FC]
			VAR sales = [SRIV Dispatch FC]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Markdown\FC
		lineageTag: 5c6fe4c0-623d-4649-b343-00188bc30e2e

	measure 'Markdown % SRIV Dispatch vs FC' =
			VAR act = [Markdown % SRIV Dispatch]
			VAR comp = [Markdown % SRIV Dispatch FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Markdown\FC
		lineageTag: 49559b13-0ef2-475a-90de-ec890adc54ab

	measure 'Markdown Dispatch vs FC %' =
			VAR act = [Markdown Dispatch]
			VAR comp = [Markdown Dispatch FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Markdown\FC
		lineageTag: 13865e21-eac5-4350-8e48-74eae926e109

	measure 'Promo Markdown Dispatch BUD' =
			CALCULATE (
			    [sum_Promo Markdown DispFor],
			    ForecastScenarios[Forecast Scenario] = "BUD"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Promo Markdown\BUD
		lineageTag: 864a03da-365b-4788-ab32-7e0e4190465a

	measure 'Promo Markdown Dispatch vs BUD' =
			VAR act = [Promo Markdown Dispatch]
			VAR comp = [Promo Markdown Dispatch BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Promo Markdown\BUD
		lineageTag: 439f6267-54dd-4d4b-80e9-9b35b29e36fb

	measure 'Promo Markdown Dispatch FC' =
			CALCULATE (
			    [sum_Promo Markdown DispFor],
			    ForecastScenarios[Forecast Scenario] = "FC"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Promo Markdown\FC
		lineageTag: bd772eef-faba-469e-a923-4b634eced4c5

	measure 'Promo Markdown Dispatch vs FC' =
			VAR act = [Promo Markdown Dispatch]
			VAR comp = [Promo Markdown Dispatch FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Promo Markdown\FC
		lineageTag: 3614e470-13f9-42b7-8867-396ee9130554

	measure 'Sale Markdown Dispatch BUD' =
			CALCULATE (
			    [sum_Sale Markdown DispFor],
			    ForecastScenarios[Forecast Scenario] = "BUD"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\BUD
		lineageTag: eba95258-2ed6-40b9-af80-00d1734fd651

	measure 'Sale Markdown Dispatch vs BUD' =
			VAR act = [Sale Markdown Dispatch]
			VAR comp = [Sale Markdown Dispatch BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\BUD
		lineageTag: 24127a23-7550-4ade-bb20-85af9706501c

	measure 'Sale Markdown Dispatch FC' =
			CALCULATE (
			    [sum_Sale Markdown DispFor],
			    ForecastScenarios[Forecast Scenario] = "FC"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\FC
		lineageTag: 02b1202f-3e2e-4a29-815c-dc6188ed92d3

	measure 'Sale Markdown Dispatch vs FC' =
			VAR act = [Sale Markdown Dispatch]
			VAR comp = [Sale Markdown Dispatch FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\FC
		lineageTag: 63e24899-aa1b-4276-a608-7f97e715521a

	measure 'SIS Sold Through Dispatch BUD' =
			CALCULATE (
			    [sum_SIS Sold Through (Inc VAT) DispFor],
			    ForecastScenarios[Forecast Scenario] = "BUD"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\SIS Sold Through\BUD
		lineageTag: 3d97d1cb-2cde-49bb-ba04-5f14981bc80d

	measure 'SIS Sold Through Dispatch vs BUD' =
			VAR act = [SIS Sold Through Dispatch]
			VAR comp = [SIS Sold Through Dispatch BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\SIS Sold Through\BUD
		lineageTag: 49a222d2-6229-4c00-b4e1-f954a610f2db

	measure 'SIS Sold Through Dispatch FC' =
			CALCULATE (
			    [sum_SIS Sold Through (Inc VAT) DispFor],
			    ForecastScenarios[Forecast Scenario] = "FC"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\SIS Sold Through\FC
		lineageTag: e87fc1d1-6659-40a1-9288-001b2d8dec94

	measure 'SIS Sold Through Dispatch vs FC' =
			VAR act = [SIS Sold Through Dispatch]
			VAR comp = [SIS Sold Through Dispatch FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\SIS Sold Through\FC
		lineageTag: a2c649e5-a97a-4f16-8e91-4f9a5afadc99

	measure 'Other GSM Adj Dispatch BUD' =
			CALCULATE (
			    [sum_Other Gross Selling Margin Adjustments DispFor],
			    ForecastScenarios[Forecast Scenario] = "BUD"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Other GSM Adj\BUD
		lineageTag: fb5b0e79-df77-4222-9a3d-e2da3dabebfd

	measure 'Other GSM Adj Dispatch vs BUD' =
			VAR act = [Other GSM Adj Dispatch]
			VAR comp = [Other GSM Adj Dispatch BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Other GSM Adj\BUD
		lineageTag: 628bcab9-e4c0-4722-97ea-bbcd1a67735e

	measure 'Other GSM Adj Dispatch FC' =
			CALCULATE (
			    [sum_Other Gross Selling Margin Adjustments DispFor],
			    ForecastScenarios[Forecast Scenario] = "FC"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Other GSM Adj\FC
		lineageTag: 599a6c49-4659-49c3-9dd1-6a43c5624d9d

	measure 'Other GSM Adj Dispatch vs FC' =
			VAR act = [Other GSM Adj Dispatch]
			VAR comp = [Other GSM Adj Dispatch FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Other GSM Adj\FC
		lineageTag: 3c1c8df1-869b-4889-829d-cb6e996dda78

	measure 'Depth Of Cut Dispatch BUD' =
			CALCULATE (
			    [sum_Depth Of Cut DispFor],
			    ForecastScenarios[Forecast Scenario] = "BUD"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Depth Of Cut\BUD
		lineageTag: 02bed88d-eec1-4d73-a163-df2dd379ebd7

	measure 'Depth Of Cut Dispatch vs BUD' =
			VAR act = [Depth Of Cut Dispatch]
			VAR comp = [Depth Of Cut Dispatch BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Depth Of Cut\BUD
		lineageTag: 06f460b9-4d66-4869-8f8e-c71993037be8

	measure 'Depth Of Cut Dispatch FC' =
			CALCULATE (
			    [sum_Depth Of Cut DispFor],
			    ForecastScenarios[Forecast Scenario] = "FC"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Depth Of Cut\FC
		lineageTag: 387ccd93-dde6-4b66-82cb-012d935f07fa

	measure 'Depth Of Cut Dispatch vs FC' =
			VAR act = [Depth Of Cut Dispatch]
			VAR comp = [Depth Of Cut Dispatch FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Depth Of Cut\FC
		lineageTag: 65924929-f3f2-4bc7-a1a8-5911f7a19b9c

	measure 'Depth Of Cut % Dispatch BUD' =
			VAR metric = [Depth Of Cut Dispatch BUD]
			VAR sales = [SIS Sold Through Dispatch BUD]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Depth Of Cut\BUD
		lineageTag: 4330bb34-fab4-4d34-90cf-879db2ebd293

	measure 'Depth Of Cut % Dispatch FC' =
			VAR metric = [Depth Of Cut Dispatch FC]
			VAR sales = [SIS Sold Through Dispatch FC]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Depth Of Cut\FC
		lineageTag: 04d29278-2152-48de-aa11-cb18aef63492

	measure 'Buying Margin BUD' = ```
			
			VAR firstweek_yr = [SlctdBudVersion]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    [fiscalWeek] <  firstweek_yr,
			            [Buying Margin],
			            [Buying Margin Orders BUD]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] ) 
			
			/*VAR result = [Buying Margin Orders BUD]
			RETURN
			    result*/
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Buying Margin\BUD
		lineageTag: fdd7b372-2433-42d9-8cdd-b36b9845f22d

	measure 'Buying Margin vs BUD' =
			VAR act = [Buying Margin]
			VAR comp = [Buying Margin BUD]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Buying Margin\BUD
		lineageTag: d3c493cb-29c0-49be-b7b8-c61697616724

	measure 'Buying Margin % BUD' = ```
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Buying Margin % Orders BUD],
			        "Dispatch", [Buying Margin % Dispatch BUD],
			        [Buying Margin % Orders BUD]
			    ) 
			RETURN
			    result
			```
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Buying Margin\BUD
		lineageTag: b869763e-4d93-447d-afeb-63747e66dd34

	measure 'Buying Margin % vs BUD' =
			VAR act = [Buying Margin %]
			VAR comp = [Buying Margin % BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Buying Margin\BUD
		lineageTag: 08278e2e-a153-426f-a8b1-eb9236e6d028

	measure 'Buying Margin vs BUD %' =
			VAR act = [Buying Margin]
			VAR comp = [Buying Margin BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Buying Margin\BUD
		lineageTag: 0099aae4-fe36-41e8-a973-e22aa11e1658

	measure 'Buying Margin FC' =
			//SelectedWeeks
			VAR firstweek_qtr = [SlctdFirstWeekQtrFC]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [Buying Margin],
			            [Buying Margin Orders FC]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Buying Margin\FC
		lineageTag: 8a28972e-03b1-4e6a-ada3-617240b3aa74

	measure 'Buying Margin vs FC' =
			VAR act = [Buying Margin]
			VAR comp = [Buying Margin FC]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Buying Margin\FC
		lineageTag: 5e2b05a8-140b-46e8-9a40-3e68a0d273b3

	measure 'Buying Margin % FC' = ```
			
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Buying Margin % Orders FC],
			        "Dispatch", [Buying Margin % Dispatch FC],
			        [Buying Margin % Orders FC]
			    ) 
			RETURN
			    result
			```
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Buying Margin\FC
		lineageTag: 25dcaeb8-5f6a-40ca-8b73-59906ecf8bf8

	measure 'Buying Margin % vs FC' =
			VAR act = [Buying Margin %]
			VAR comp = [Buying Margin % FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Buying Margin\FC
		lineageTag: 3b807b46-9654-4fb7-9e07-c61bc72b740e

	measure 'Buying Margin vs FC %' =
			VAR act = [Buying Margin]
			VAR comp = [Buying Margin FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Buying Margin\FC
		lineageTag: 652214fb-4904-4df0-b780-ddd4e0840c59

	measure 'Markdown BUD' = ```
			
			VAR firstweek_yr = [SlctdBudVersion]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    [fiscalWeek] <  firstweek_yr, 
			 
			            [Markdown],
			            [Markdown Orders BUD]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] ) 
			 
			/*VAR result =
			[Markdown Orders BUD]
			RETURN
			    result*/
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Markdown\BUD
		lineageTag: 537d4db8-e533-48b1-8f6f-5402fab35ece

	measure 'Markdown vs BUD' =
			VAR act = [Markdown]
			VAR comp = [Markdown BUD]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Markdown\BUD
		lineageTag: 50d933b8-5945-4c5e-a09a-3b74229e7cab

	measure 'Markdown % SRIV BUD' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Markdown % SRIV Orders BUD],
			        "Dispatch", [Markdown % SRIV Dispatch BUD],
			        [Markdown % SRIV Orders BUD]
			    )
			RETURN
			    result
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Markdown\BUD
		lineageTag: e48596a7-bd0e-4036-96ea-783448a0178c

	measure 'Markdown % SRIV vs BUD' =
			VAR act = [Markdown % SRIV]
			VAR comp = [Markdown % SRIV BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Markdown\BUD
		lineageTag: 7f9274f0-6c99-48cf-ac39-f7bb8a538469

	measure 'Markdown vs BUD %' =
			VAR act = [Markdown]
			VAR comp = [Markdown BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Markdown\BUD
		lineageTag: 3821b05c-7f55-4f42-abc1-7ab0308c736c

	measure 'Markdown FC' =
			//SelectedWeeks
			VAR firstweek_qtr = [SlctdFirstWeekQtrFC]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [Markdown],
			            [Markdown Orders FC]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Markdown\FC
		lineageTag: 5ccc7c55-a826-4d91-97f5-8106c59b1892

	measure 'Markdown vs FC' =
			VAR act = [Markdown]
			VAR comp = [Markdown FC]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Markdown\FC
		lineageTag: ecf1da85-ab5f-4402-9053-9b6fb4b6d354

	measure 'Markdown % SRIV FC' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Markdown % SRIV Orders FC],
			        "Dispatch", [Markdown % SRIV Dispatch FC],
			        [Markdown % SRIV Orders FC]
			    )
			RETURN
			    result
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Markdown\FC
		lineageTag: 48712088-b2b9-4aab-82ed-a9df0a6f7b0f

	measure 'Markdown % SRIV vs FC' =
			VAR act = [Markdown % SRIV]
			VAR comp = [Markdown % SRIV FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Markdown\FC
		lineageTag: 56e21485-c82e-484f-947b-bf37a909b6a8

	measure 'Markdown vs FC %' =
			VAR act = [Markdown]
			VAR comp = [Markdown FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Markdown\FC
		lineageTag: f1e308e7-312f-42a3-9159-aa38e41a3231

	/// This measure is the sum of column 'factSalesDispatch'[Dept/Manual Postings GSM]
	measure 'GSM Postings Dispatch' = SUM ( 'factSalesDispatch'[Dept/Manual Postings GSM] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Postings\Actual
		lineageTag: 121b3fa7-733c-4a6b-8dec-e2a1e6bd6526

	measure 'GSM Postings Dispatch LY' =
			CALCULATE (
			    [GSM Postings Dispatch],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Postings\LY
		lineageTag: 4aea5ced-b945-4730-8199-3677ca9884f7

	measure 'GSM Postings Dispatch LY-1' =
			CALCULATE (
			    [GSM Postings Dispatch],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of GSM Postings Dispatch LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Postings\LY-1
		lineageTag: 24f8ade3-82bb-4ced-a647-6516edd8a66f

	measure 'GSM Postings Dispatch vs LY' =
			VAR act = [GSM Postings Dispatch]
			VAR comp = [GSM Postings Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Postings\LY
		lineageTag: 9125bbab-1c7f-4d3a-8333-3d4364af18bb

	measure 'GSM Postings Dispatch vs LY-1' =
			VAR act = [GSM Postings Dispatch]
			VAR comp = [GSM Postings Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of GSM Postings Dispatch vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Postings\LY-1
		lineageTag: 6b0f7ea6-2615-4f4c-b17a-9d1b9112144a

	measure 'GSM Postings Dispatch vs LY %' =
			VAR act = [GSM Postings Dispatch]
			VAR comp = [GSM Postings Dispatch LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Postings\LY
		lineageTag: 0354e5a7-1ff2-4af4-9e49-9b06bd436c70

	measure 'GSM Postings Dispatch LW' =
			CALCULATE (
			    [GSM Postings Dispatch],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Postings\LW
		lineageTag: 608e930f-87d2-4a15-85dc-85cfed858d45

	measure 'GSM Postings Dispatch vs LW' =
			VAR act = [GSM Postings Dispatch]
			VAR comp = [GSM Postings Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Postings\LW
		lineageTag: d2d47667-8e5b-430a-aa09-41632c0f492d

	measure 'GSM Postings Dispatch vs LW %' =
			VAR act = [GSM Postings Dispatch]
			VAR comp = [GSM Postings Dispatch LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Postings\LW
		lineageTag: 6a2bcfef-4953-4663-9669-7184be4e7411

	measure 'GSM Dispatch vs Orders' =
			VAR dispatch = [GSM Dispatch]
			VAR orders = [GSM Orders]
			VAR postings = [GSM Postings Dispatch]
			VAR result = dispatch - postings - orders
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch vs Orders\GSM\Actual
		lineageTag: 6d516d42-c446-4d87-a26f-7db627f07a10

	measure 'GSM Dispatch vs Orders LY' =
			VAR dispatch = [GSM Dispatch LY]
			VAR orders = [GSM Orders LY]
			VAR postings = [GSM Postings Dispatch LY]
			VAR result = dispatch - postings - orders
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch vs Orders\GSM\LY
		lineageTag: 40e38174-742b-48ef-b79e-4492af4093c6

	measure 'GSM Dispatch vs Orders LY-1' =
			VAR dispatch = [GSM Dispatch LY-1]
			VAR orders = [GSM Orders LY-1]
			VAR postings = [GSM Postings Dispatch LY-1]
			VAR result = dispatch - postings - orders
			RETURN
			    result
		description: Two years ago equivalent of GSM Dispatch vs Orders LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch vs Orders\GSM\LY-1
		lineageTag: 5d58d737-b00b-41d1-9630-4984eb5323c3

	measure 'GSM Dispatch vs Orders vs LY' =
			VAR act = [GSM Dispatch vs Orders]
			VAR comp = [GSM Dispatch vs Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch vs Orders\GSM\LY
		lineageTag: 2cd5604c-02ad-4cd9-8244-e237729baae1

	measure 'GSM Dispatch vs Orders vs LY-1' =
			VAR act = [GSM Dispatch vs Orders]
			VAR comp = [GSM Dispatch vs Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of GSM Dispatch vs Orders vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch vs Orders\GSM\LY-1
		lineageTag: 18d78f4f-8b77-4387-a96a-ad8156691232

	measure 'GSM Dispatch vs Orders vs LY %' =
			VAR act = [GSM Dispatch vs Orders]
			VAR comp = [GSM Dispatch vs Orders LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch vs Orders\GSM\LY
		lineageTag: 5b0bcb3f-d7c6-40ae-b3c1-676365a895a6

	measure 'GSM Dispatch vs Orders LW' =
			VAR dispatch = [GSM Dispatch LW]
			VAR orders = [GSM Orders LW]
			VAR postings = [GSM Postings Dispatch LW]
			VAR result = dispatch - postings - orders
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch vs Orders\GSM\LW
		lineageTag: 7743793b-5b08-4bf3-8816-4fe1f39ba456

	measure 'GSM Dispatch vs Orders vs LW' =
			VAR act = [GSM Dispatch vs Orders]
			VAR comp = [GSM Dispatch vs Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch vs Orders\GSM\LW
		lineageTag: 6268441b-7fa3-40c0-a378-5201c81cba58

	measure 'GSM Dispatch vs Orders vs LW %' =
			VAR act = [GSM Dispatch vs Orders]
			VAR comp = [GSM Dispatch vs Orders LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch vs Orders\GSM\LW
		lineageTag: c4fc8a1a-e309-4e79-a29d-f9bd2afc271b

	measure 'GSM Dispatch vs Orders BUD' =
			VAR dispatch = [GSM Dispatch BUD]
			VAR orders = [GSM Orders BUD]
			VAR postings = 0
			VAR result = dispatch - postings - orders
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch vs Orders\GSM\BUD
		lineageTag: a365563b-3570-47e9-82a3-8c37499bcc6e

	measure 'GSM Dispatch vs Orders vs BUD' =
			VAR act = [GSM Dispatch vs Orders]
			VAR comp = [GSM Dispatch vs Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch vs Orders\GSM\BUD
		lineageTag: d7571181-b68f-4777-82ff-0c9b5ee8f656

	measure 'GSM Dispatch vs Orders vs BUD %' =
			VAR act = [GSM Dispatch vs Orders]
			VAR comp = [GSM Dispatch vs Orders BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch vs Orders\GSM\BUD
		lineageTag: fcb52bde-5aff-4738-b10b-db6b153caab7

	measure 'GSM Dispatch vs Orders FC' =
			VAR dispatch = [GSM Dispatch FC]
			VAR orders = [GSM Orders FC]
			VAR postings = 0
			VAR result = dispatch - postings - orders
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch vs Orders\GSM\FC
		lineageTag: 21f4e9ba-b1ed-4066-9b84-5de64eb9fae8

	measure 'GSM Dispatch vs Orders vs FC' =
			VAR act = [GSM Dispatch vs Orders]
			VAR comp = [GSM Dispatch vs Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch vs Orders\GSM\FC
		lineageTag: fd08e015-f1a4-4711-83d5-40bc03852d7b

	measure 'GSM Dispatch vs Orders vs FC %' =
			VAR act = [GSM Dispatch vs Orders]
			VAR comp = [GSM Dispatch vs Orders FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch vs Orders\GSM\FC
		lineageTag: f6b1eb66-d19e-4043-abf0-916efc835e1c

	measure 'GSM Dispatch vs Orders QRF' =
			VAR dispatch = [GSM Dispatch QRF]
			VAR orders = [GSM Orders QRF]
			VAR postings = 0
			VAR result = dispatch - postings - orders
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch vs Orders\GSM\QRF
		lineageTag: abec6d5e-c795-4289-9a57-397f36ccd325

	measure 'GSM Dispatch vs Orders vs QRF' =
			VAR act = [GSM Dispatch vs Orders]
			VAR comp = [GSM Dispatch vs Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch vs Orders\GSM\QRF
		lineageTag: eb233c10-acb9-4534-a55e-ab80e5973ccd

	measure 'GSM Dispatch vs Orders vs QRF %' =
			VAR act = [GSM Dispatch vs Orders]
			VAR comp = [GSM Dispatch vs Orders QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch vs Orders\GSM\QRF
		lineageTag: a5f9574f-a4ea-4a7a-989b-119029c7eceb

	measure 'SRIV Dispatch QRF' =
			VAR is_channel_unfiltered = [is_channel_unfiltered]
			VAR sale_type = [slctd_SalesTypeLevelAware]
			VAR total_sales = [FPP SRIV Dispatch QRF] + [RP SRIV Dispatch QRF]
			VAR result =
			    SWITCH (
			        sale_type,
			        "Total", total_sales,
			        "FP&P", [FPP SRIV Dispatch QRF],
			        "Full Price", BLANK (),
			        "Promo", BLANK (),
			        "Reduced", [RP SRIV Dispatch QRF],
			        total_sales
			    )
			RETURN
			    IF ( is_channel_unfiltered, result, BLANK () )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\QRF
		lineageTag: 16837602-4b62-43d7-9468-774c46ecd1e8

	measure 'SRIV Dispatch vs QRF' =
			VAR act = [SRIV Dispatch]
			VAR comp = [SRIV Dispatch QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\QRF
		lineageTag: 0bfaf849-1a06-4d18-97e2-4a97264c3dd0

	measure 'SRIV Dispatch vs QRF %' =
			VAR act = [SRIV Dispatch]
			VAR comp = [SRIV Dispatch QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\SRIV\QRF
		lineageTag: 34bd4e32-8671-4d75-8062-637cd784190a

	measure 'FPP SRIV Dispatch QRF' =
			CALCULATE (
			    [sum_Full Price Sales Revenue (Inc VAT) DispFor],
			    ForecastScenarios[Forecast Scenario] = "QRF"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP SRIV\QRF
		lineageTag: 82bfb934-4bac-4504-908d-f060cdb82448

	measure 'FPP SRIV Dispatch vs QRF' =
			VAR act = [FPP SRIV Dispatch]
			VAR comp = [FPP SRIV Dispatch QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP SRIV\QRF
		lineageTag: 4a67649c-23fc-4217-b81f-abc56b8de1d5

	measure 'FPP SRIV Dispatch vs QRF %' =
			VAR act = [FPP SRIV Dispatch]
			VAR comp = [FPP SRIV Dispatch QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\FPP SRIV\QRF
		lineageTag: fa7eaa85-f20f-46ea-b831-0552fae563fa

	measure 'RP SRIV Dispatch QRF' =
			CALCULATE (
			    [sum_Reduced Price Sales Revenue (Inc VAT) DispFor],
			    ForecastScenarios[Forecast Scenario] = "QRF"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP SRIV\QRF
		lineageTag: 6cc93d99-41ce-4f86-878b-0ec9c803c247

	measure 'RP SRIV Dispatch vs QRF' =
			VAR act = [RP SRIV Dispatch]
			VAR comp = [RP SRIV Dispatch QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP SRIV\QRF
		lineageTag: 66ee4f9e-a381-4fd4-9681-78d3cd797a3a

	measure 'RP SRIV Dispatch vs QRF %' =
			VAR act = [RP SRIV Dispatch]
			VAR comp = [RP SRIV Dispatch QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\RP SRIV\QRF
		lineageTag: c1b4390f-d90b-472d-9ecb-bd5ec5c37d26

	measure 'SRIV Dispatch vs Channel Orders BUD' =
			VAR dispatch = [SRIV Dispatch BUD]
			VAR orders = [SRIV Channel Orders BUD]
			VAR postings = 0
			VAR result = dispatch - postings - orders
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch vs Orders\SRIV\BUD
		lineageTag: 982d6265-8069-485d-867b-848230dabafa

	measure 'SRIV Dispatch vs Channel Orders vs BUD' =
			VAR act = [SRIV Dispatch vs Orders]
			VAR comp = [SRIV Dispatch vs Channel Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch vs Orders\SRIV\BUD
		lineageTag: d874a058-6af4-402a-8465-66b9a7ab5216

	measure 'SRIV Dispatch vs Channel Orders vs BUD %' =
			VAR act = [SRIV Dispatch vs Orders]
			VAR comp = [SRIV Dispatch vs Channel Orders BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch vs Orders\SRIV\BUD
		lineageTag: c213a29b-99dd-4ea6-a608-64ff7fa8286a

	measure 'SRIV Dispatch vs Channel Orders FC' =
			VAR dispatch = [SRIV Dispatch FC]
			VAR orders = [SRIV Channel Orders FC]
			VAR postings = 0
			VAR result = dispatch - postings - orders
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch vs Orders\SRIV\FC
		lineageTag: 3feddf49-6c80-4d27-90a7-c42416f0abfa

	measure 'SRIV Dispatch vs Channel Orders vs FC' =
			VAR act = [SRIV Dispatch vs Orders]
			VAR comp = [SRIV Dispatch vs Channel Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch vs Orders\SRIV\FC
		lineageTag: 48ad7024-7184-4333-9fdc-125cfeb0d2b5

	measure 'SRIV Dispatch vs Channel Orders vs FC %' =
			VAR act = [SRIV Dispatch vs Orders]
			VAR comp = [SRIV Dispatch vs Channel Orders FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch vs Orders\SRIV\FC
		lineageTag: b26506f0-afb7-4dc0-bc58-7cfbfdba2fb3

	measure 'SRIV Dispatch vs Channel Orders QRF' =
			VAR dispatch = [SRIV Dispatch QRF]
			VAR orders = [SRIV Channel Orders QRF]
			VAR postings = 0
			VAR result = dispatch - postings - orders
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch vs Orders\SRIV\QRF
		lineageTag: 2f01a570-261e-494c-9035-25d1776d370b

	measure 'SRIV Dispatch vs Channel Orders vs QRF' =
			VAR act = [SRIV Dispatch vs Orders]
			VAR comp = [SRIV Dispatch vs Channel Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch vs Orders\SRIV\QRF
		lineageTag: cc1b3eda-d383-40b1-b093-2286668258e2

	measure 'SRIV Dispatch vs Channel Orders vs QRF %' =
			VAR act = [SRIV Dispatch vs Orders]
			VAR comp = [SRIV Dispatch vs Channel Orders QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch vs Orders\SRIV\QRF
		lineageTag: ed85ef45-c5d9-4d10-bdc9-f50c3d53b1e2

	measure 'GSM BUD' =
			
			VAR firstweek_yr = [SlctdBudVersion]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    [fiscalWeek] <  firstweek_yr,
			            [GSM],
			            [GSM Orders BUD]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
			
			/*VAR result = [GSM Orders BUD]
			RETURN
			    result*/
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM\BUD
		lineageTag: 40561622-68ff-4530-9b89-4a480939b90a

	measure 'GSM vs BUD' =
			VAR act = [GSM]
			VAR comp = [GSM BUD]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM\BUD
		lineageTag: dcd98a9d-3fb2-4eec-b5dc-910a8a95e14c

	/// This measure is column [GSM Orders LW] as a % of SREV
	measure 'GSM % SREV BUD' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [GSM % SREV Orders BUD],
			        "Dispatch", [GSM % SREV Orders BUD],
			        [GSM % SREV Orders BUD]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\BUD
		lineageTag: 00a701f1-3bed-4461-ab3e-69c66e11fca5

	measure 'GSM % SREV vs BUD' =
			VAR act = [GSM % SREV]
			VAR comp = [GSM % SREV BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\BUD
		lineageTag: e1c7d804-64e5-4a9a-92c7-ba626ad5891a

	measure 'GSM vs BUD %' =
			VAR act = [GSM]
			VAR comp = [GSM BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\BUD
		lineageTag: 4795923e-f8cb-45d0-93e8-c8c4edb976a0

	measure 'GSM FC' =
			//SelectedWeeks
			VAR firstweek_qtr = [SlctdFirstWeekQtrFC]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [GSM],
			            [GSM Orders FC]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM\FC
		lineageTag: 1ce731b0-c4db-4191-9edf-3c6a3fd256d5

	measure 'GSM vs FC' =
			VAR act = [GSM]
			VAR comp = [GSM FC]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM\FC
		lineageTag: 34f2d339-56a5-40f2-8356-bb01b7e23873

	/// This measure is column [GSM Orders LW] as a % of SREV
	measure 'GSM % SREV FC' =
			
			VAR result =
			DIVIDE([GSM FC],[SREV FC],blank())
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\FC
		lineageTag: 052b8f7c-6e02-4b54-86ea-c2b896cc67ed

	measure 'GSM % SREV vs FC' =
			VAR act = [GSM % SREV]
			VAR comp = [GSM % SREV FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\FC
		lineageTag: d73a9f17-a73c-4fea-932d-456f1f7f8fbc

	measure 'GSM vs FC %' =
			VAR act = [GSM]
			VAR comp = [GSM FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\FC
		lineageTag: 96ed5620-e71f-4e1b-bff7-c4f7f393682c

	measure 'GSM QRF' =
			//SelectedWeeks
			VAR firstweek_qtr = [SlctdFirstWeekQtrQRF]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [GSM],
			            [GSM Orders QRF]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM\QRF
		lineageTag: 5cbf4ffc-6e35-4264-8d19-929aa1599aaf

	measure 'GSM vs QRF' =
			VAR act = [GSM]
			VAR comp = [GSM QRF]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM\QRF
		lineageTag: 015dcc20-62d7-4a2f-91a1-4991712c1be7

	/// This measure is column [GSM Orders LW] as a % of SREV
	measure 'GSM % SREV QRF' =
			
			VAR result =
			DIVIDE([GSM QRF],[SREV QRF],blank())
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\QRF
		lineageTag: e4d84e8c-b7b4-4940-a55e-86759afbfdd8

	measure 'GSM % SREV vs QRF' =
			VAR act = [GSM % SREV]
			VAR comp = [GSM % SREV QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\QRF
		lineageTag: 5178c185-9040-489f-8d51-3b3aaaa48827

	measure 'GSM vs QRF %' =
			VAR act = [GSM]
			VAR comp = [GSM QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\QRF
		lineageTag: 02c33a93-b999-4270-8111-7c32599651d2

	measure 'GSM Orders QRF' =
			
			VAR PlanVersion = [SlctdQRFVersion]
			VAR Tot_mp_plan =  CALCULATE ( [sum_TotGSMV], factForecast[plan] = PlanVersion )
			VAR FPP_mp_plan =  CALCULATE ( [sum_FPPGSMV], factForecast[plan] = PlanVersion )
			VAR RP_mp_plan =  CALCULATE ( [sum_RedGSMV], factForecast[plan] = PlanVersion )
			VAR result =    SWITCH([slctd_SalesType],
			                "FP&P", FPP_mp_plan,
			                "Reduced", RP_mp_plan,
			                Tot_mp_plan)
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\GSM\QRF
		lineageTag: f701514f-0f03-475a-8444-1c12ac0d3167

	measure 'GSM Orders vs QRF' =
			VAR act = [GSM Orders]
			VAR comp = [GSM Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\GSM\QRF
		lineageTag: df91ac3e-d692-4ca7-b8ab-f20f81d2b2bf

	measure 'GSM % SREV Orders QRF' =
			VAR metric = [GSM Orders QRF]
			VAR sales = [SREV Orders QRF]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\GSM\QRF
		lineageTag: a0b72e45-9114-4d5c-9358-c0496ed9919b

	measure 'GSM % SREV Orders vs QRF' =
			VAR act = [GSM % SREV Orders]
			VAR comp = [GSM % SREV Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\GSM\QRF
		lineageTag: c93bf810-387c-47a6-b693-0d29a0730dd3

	measure 'GSM Orders vs QRF %' =
			VAR act = [GSM Orders]
			VAR comp = [GSM Orders QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\GSM\QRF
		lineageTag: fc05f038-3b42-4ec7-b1af-a15bafddd2c2

	measure 'Buying Margin Orders QRF' =
			
			VAR PlanVersion = [SlctdQRFVersion]
			Return
			CALCULATE ( [sum_TotBIMAV], factForecast[plan] = PlanVersion )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Buying Margin\QRF
		lineageTag: c3d36e24-e450-4a96-a9b5-e9a65f1106db

	measure 'Buying Margin Orders vs QRF' =
			VAR act = [Buying Margin Orders]
			VAR comp = [Buying Margin Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Buying Margin\QRF
		lineageTag: 9c1c54b9-f127-41ce-8e49-14a918812230

	measure 'Buying Margin % Orders QRF' =
			
			VAR PlanVersion = [SlctdQRFVersion]
			VAR metric = [Buying Margin Orders FC]
			VAR sales =
			    CALCULATE ( [sum_TotBIMBV], factForecast[plan] = PlanVersion )
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Buying Margin\QRF
		lineageTag: 6ce9f0a0-2875-4345-9ec6-5b4423b437dc

	measure 'Buying Margin % Orders vs QRF' =
			VAR act = [Buying Margin % Orders]
			VAR comp = [Buying Margin % Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Buying Margin\QRF
		lineageTag: ed4e8c3f-9ac9-4616-a2b4-ecc48ece296f

	measure 'Buying Margin Orders vs QRF %' =
			VAR act = [Buying Margin Orders]
			VAR comp = [Buying Margin Orders QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Buying Margin\QRF
		lineageTag: 0f76ebde-62bc-4b2f-b5b7-7c148f69606f

	measure 'Markdown Orders QRF' =
			
			VAR PlanVersion = [SlctdQRFVersion]
			Return CALCULATE ( [sum_DiscMDV], factForecast[plan] = PlanVersion )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Markdown\QRF
		lineageTag: f945d559-5063-4995-8e29-5b5176db1a5c

	measure 'Markdown Orders vs QRF' =
			VAR act = [Markdown Orders]
			VAR comp = [Markdown Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Markdown\QRF
		lineageTag: 44039349-e57d-4b65-8190-7e4b2de2fe95

	measure 'Markdown % SRIV Orders QRF' =
			VAR metric = - [Markdown Orders QRF]
			VAR sales = [SRIV Orders QRF]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Markdown\QRF
		lineageTag: 2e4ca9ef-b01a-406d-b9f3-d51eac23b34a

	measure 'Markdown % SRIV Orders vs QRF' =
			VAR act = [Markdown % SRIV Orders]
			VAR comp = [Markdown % SRIV Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Markdown\QRF
		lineageTag: 4ac8e4f2-cda9-4a05-a9db-c7e16f9c088d

	measure 'Markdown Orders vs QRF %' =
			VAR act = [Markdown Orders]
			VAR comp = [Markdown Orders QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Markdown\QRF
		lineageTag: aa13070e-f458-4a4e-aad7-c53478ac9c2f

	measure 'GSM Dispatch QRF' =
			CALCULATE (
			    [sum_Gross Selling Margin DispFor],
			    ForecastScenarios[Forecast Scenario] = "QRF"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\GSM\QRF
		lineageTag: 3522adba-d1c4-4cf9-aebc-65aa32ad1376

	measure 'GSM Dispatch vs QRF' =
			VAR act = [GSM Dispatch]
			VAR comp = [GSM Dispatch QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\GSM\QRF
		lineageTag: 1733df16-b873-4442-9c47-7dbe01f7ce87

	measure 'GSM % SREV Dispatch QRF' =
			VAR metric = [GSM Dispatch QRF]
			VAR sales = [SREV Dispatch QRF]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\GSM\QRF
		lineageTag: 878264c3-1d5e-4fa2-bbbf-c5fb8e4dbe94

	measure 'GSM % SREV Dispatch vs QRF' =
			VAR act = [GSM % SREV Dispatch]
			VAR comp = [GSM % SREV Dispatch QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\GSM\QRF
		lineageTag: 776e9430-c896-494b-9372-de66e30953b0

	measure 'GSM Dispatch vs QRF %' =
			VAR act = [GSM Dispatch]
			VAR comp = [GSM Dispatch QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\GSM\QRF
		lineageTag: acb48148-8118-4fea-bb04-06cf15f238d5

	measure 'Buying Margin Dispatch QRF' =
			VAR cogs_inc_vat =
			    CALCULATE (
			        - [sum_Cost Of Goods Sold (Inc VAT) DispFor],
			        ForecastScenarios[Forecast Scenario] = "QRF"
			    )
			VAR bm_denom =
			    CALCULATE (
			        [sum_Buying Margin Denominator DispFor],
			        ForecastScenarios[Forecast Scenario] = "QRF"
			    )
			VAR result = bm_denom - cogs_inc_vat
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Buying Margin\QRF
		lineageTag: 97e18402-b225-4acc-b4bb-658439a4e933

	measure 'Buying Margin Dispatch vs QRF' =
			VAR act = [Buying Margin Dispatch]
			VAR comp = [Buying Margin Dispatch QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Buying Margin\QRF
		lineageTag: c5a78f9f-eeae-4ac6-adbd-ec496d1b64af

	measure 'Buying Margin % Dispatch QRF' =
			VAR metric = [Buying Margin Dispatch QRF]
			VAR sales =
			    CALCULATE (
			        [sum_Buying Margin Denominator DispFor],
			        ForecastScenarios[Forecast Scenario] = "QRF"
			    )
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Buying Margin\QRF
		lineageTag: d8b5c642-23aa-4073-b3d5-fbb6504bb4ad

	measure 'Buying Margin % Dispatch vs QRF' =
			VAR act = [Buying Margin % Dispatch]
			VAR comp = [Buying Margin % Dispatch QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Buying Margin\QRF
		lineageTag: bd1a6bcd-ccf1-4a1f-8e67-bf658e7f8400

	measure 'Buying Margin Dispatch vs QRF %' =
			VAR act = [Buying Margin Dispatch]
			VAR comp = [Buying Margin Dispatch QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Buying Margin\QRF
		lineageTag: 8fca8534-33e9-46ab-8dc2-7bb984c04132

	measure 'Markdown Dispatch QRF' =
			CALCULATE (
			    [sum_Markdown DispFor],
			    ForecastScenarios[Forecast Scenario] = "QRF"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Markdown\QRF
		lineageTag: 6c8750b5-81d3-4302-a1f0-9c8c71fd532f

	measure 'Markdown Dispatch vs QRF' =
			VAR act = [Markdown Dispatch]
			VAR comp = [Markdown Dispatch QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Markdown\QRF
		lineageTag: fa58726f-d60e-491c-b439-6dac1de29708

	measure 'Markdown % SRIV Dispatch QRF' =
			VAR metric = - [Markdown Dispatch QRF]
			VAR sales = [SRIV Dispatch QRF]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Markdown\QRF
		lineageTag: e8b2604d-a6f1-4b2c-8d8d-57a18cc7177b

	measure 'Markdown % SRIV Dispatch vs QRF' =
			VAR act = [Markdown % SRIV Dispatch]
			VAR comp = [Markdown % SRIV Dispatch QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Markdown\QRF
		lineageTag: d2e9efd3-6539-420b-b658-64660c064151

	measure 'Markdown Dispatch vs QRF %' =
			VAR act = [Markdown Dispatch]
			VAR comp = [Markdown Dispatch QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Markdown\QRF
		lineageTag: 2a990fc3-5c43-4b76-bd04-b7d3fea522de

	measure 'Promo Markdown Dispatch QRF' =
			CALCULATE (
			    [sum_Promo Markdown DispFor],
			    ForecastScenarios[Forecast Scenario] = "QRF"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Promo Markdown\QRF
		lineageTag: c3f0d90e-5e68-4564-bd6c-e09b202b01b7

	measure 'Promo Markdown Dispatch vs QRF' =
			VAR act = [Promo Markdown Dispatch]
			VAR comp = [Promo Markdown Dispatch QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Promo Markdown\QRF
		lineageTag: 1081d6fc-5bde-44ff-87ce-63e988822390

	measure 'Sale Markdown Dispatch QRF' =
			CALCULATE (
			    [sum_Sale Markdown DispFor],
			    ForecastScenarios[Forecast Scenario] = "QRF"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\QRF
		lineageTag: f4439e19-661b-444b-b4f8-6ad12a8ba37a

	measure 'Sale Markdown Dispatch vs QRF' =
			VAR act = [Sale Markdown Dispatch]
			VAR comp = [Sale Markdown Dispatch QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\QRF
		lineageTag: a5a25082-c6be-4ce8-b9fa-8472bf8e8959

	measure 'SIS Sold Through Dispatch QRF' =
			CALCULATE (
			    [sum_SIS Sold Through (Inc VAT) DispFor],
			    ForecastScenarios[Forecast Scenario] = "QRF"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\SIS Sold Through\QRF
		lineageTag: 44538173-555b-4c0c-a03e-b0d56725fa6f

	measure 'SIS Sold Through Dispatch vs QRF' =
			VAR act = [SIS Sold Through Dispatch]
			VAR comp = [SIS Sold Through Dispatch QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\SIS Sold Through\QRF
		lineageTag: a04b9606-c633-4291-8906-70ee83c14925

	measure 'Other GSM Adj Dispatch QRF' =
			CALCULATE (
			    [sum_Other Gross Selling Margin Adjustments DispFor],
			    ForecastScenarios[Forecast Scenario] = "QRF"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Other GSM Adj\QRF
		lineageTag: 942f34c3-d50f-4f6b-ad59-3411ac3414b6

	measure 'Other GSM Adj Dispatch vs QRF' =
			VAR act = [Other GSM Adj Dispatch]
			VAR comp = [Other GSM Adj Dispatch QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Other GSM Adj\QRF
		lineageTag: bcecc44e-a314-47f8-92fa-a04ef22f243f

	measure 'Depth Of Cut Dispatch QRF' =
			CALCULATE (
			    [sum_Depth Of Cut DispFor],
			    ForecastScenarios[Forecast Scenario] = "QRF"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Depth Of Cut\QRF
		lineageTag: b8c15d15-f1aa-420c-93c5-59a299334426

	measure 'Depth Of Cut Dispatch vs QRF' =
			VAR act = [Depth Of Cut Dispatch]
			VAR comp = [Depth Of Cut Dispatch QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Depth Of Cut\QRF
		lineageTag: 254fd64a-72de-447e-9137-9823ae0ff130

	measure 'Depth Of Cut % Dispatch QRF' =
			VAR metric = [Depth Of Cut Dispatch QRF]
			VAR sales = [SIS Sold Through Dispatch QRF]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Depth Of Cut\QRF
		lineageTag: 1df173b4-ee2d-46ae-b104-0f2cc279a05d

	measure 'SREV QRF' =
			//SelectedWeeks
			VAR firstweek_qtr = [SlctdFirstWeekQtrQRF]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [SREV],
			            [SREV Orders QRF]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV\QRF
		lineageTag: f3437bc4-3630-4baf-bbce-4700c8572b1d

	measure 'SREV vs QRF' =
			VAR act = [SREV]
			VAR comp = [SREV QRF]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV\QRF
		lineageTag: a5410bfa-7a2f-40b9-8dfa-bfdf40619503

	measure 'SREV vs QRF %' =
			VAR act = [SREV]
			VAR comp = [SREV QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SREV\QRF
		lineageTag: ca8bbb83-104e-4f39-a9b2-65dceed33081

	measure 'SREV Dispatch QRF' =
			CALCULATE (
			    [sum_Sales Revenue (Exc VAT) DispFor],
			    ForecastScenarios[Forecast Scenario] = "QRF"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SREV\QRF
		lineageTag: 91b6df4e-6834-4b21-8d25-9f114a134646

	measure 'SREV Dispatch vs QRF' =
			VAR act = [SREV Dispatch]
			VAR comp = [SREV Dispatch QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SREV\QRF
		lineageTag: 48ad364b-b008-4042-bca5-80f21a67d8da

	measure 'SREV Dispatch vs QRF %' =
			VAR act = [SREV Dispatch]
			VAR comp = [SREV Dispatch QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\SREV\QRF
		lineageTag: 6fb61603-82db-4913-9425-dc9db528c028

	measure 'Depth Of Cut % Dispatch vs BUD' =
			VAR act = [Depth Of Cut % Dispatch]
			VAR comp = [Depth Of Cut % Dispatch BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Depth Of Cut\BUD
		lineageTag: 660647b9-20d9-463f-aa58-1593e558f8e6

	measure 'Depth Of Cut % Dispatch vs FC' =
			VAR act = [Depth Of Cut % Dispatch]
			VAR comp = [Depth Of Cut % Dispatch FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Depth Of Cut\FC
		lineageTag: 75d4f11c-ab1b-41b6-9c12-2edb54f30c22

	measure 'Depth Of Cut % Dispatch vs QRF' =
			VAR act = [Depth Of Cut % Dispatch]
			VAR comp = [Depth Of Cut % Dispatch QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Depth Of Cut\QRF
		lineageTag: b54bd04d-deb1-4c6a-bbcc-0ed2c7a68213

	measure 'Buying Margin QRF' =
			//SelectedWeeks
			VAR firstweek_qtr = [SlctdFirstWeekQtrQRF]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [Buying Margin],
			            [Buying Margin Orders QRF]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Buying Margin\QRF
		lineageTag: 620c172b-e0bf-4ee5-9566-58edb68bacfe

	measure 'Buying Margin vs QRF' =
			VAR act = [Buying Margin]
			VAR comp = [Buying Margin QRF]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Buying Margin\QRF
		lineageTag: 74bea129-4464-495c-b212-4ef1a4f6e24d

	measure 'Buying Margin % QRF' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Buying Margin % Orders QRF],
			        "Dispatch", [Buying Margin % Dispatch QRF],
			        [Buying Margin % Orders QRF]
			    )
			RETURN
			    result
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Buying Margin\QRF
		lineageTag: dbf9db34-a372-4711-ae93-01b2eb2c2a8e

	measure 'Buying Margin % vs QRF' =
			VAR act = [Buying Margin %]
			VAR comp = [Buying Margin % QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Buying Margin\QRF
		lineageTag: ca7c2d04-54f3-421d-95f6-5b9a746ccab2

	measure 'Buying Margin vs QRF %' =
			VAR act = [Buying Margin]
			VAR comp = [Buying Margin QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Buying Margin\QRF
		lineageTag: 2f8dc14b-5514-4f6b-8fb9-54c40446738f

	measure 'Markdown QRF' =
			//SelectedWeeks
			VAR firstweek_qtr = [SlctdFirstWeekQtrQRF]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [Markdown],
			            [Markdown Orders QRF]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Markdown\QRF
		lineageTag: 250905fc-b12e-4af7-840e-39e4ffd4b25a

	measure 'Markdown vs QRF' =
			VAR act = [Markdown]
			VAR comp = [Markdown QRF]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Markdown\QRF
		lineageTag: f459f787-17c2-47de-9b18-3e84791717a2

	measure 'Markdown % SRIV QRF' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Markdown % SRIV Orders QRF],
			        "Dispatch", [Markdown % SRIV Dispatch QRF],
			        [Markdown % SRIV Orders QRF]
			    )
			RETURN
			    result
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Markdown\QRF
		lineageTag: 3868e5ff-ee11-48fa-902d-95bb5c9fecd2

	measure 'Markdown % SRIV vs QRF' =
			VAR act = [Markdown % SRIV]
			VAR comp = [Markdown % SRIV QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Markdown\QRF
		lineageTag: 094f74a1-6f54-4edd-a8cd-9159e2f7b99d

	measure 'Markdown vs QRF %' =
			VAR act = [Markdown]
			VAR comp = [Markdown QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Markdown\QRF
		lineageTag: 4c2d4c02-e70b-466e-907e-817242094c04

	measure tiMarginMetricSelection = [MMS_slctd_Metric]
		displayFolder: Dynamic Labels\MarginMeasureSelection
		lineageTag: fbfa7ae4-be4d-4f6c-9d4c-9929453f1a72

	measure tiMarginMetricSelectionByBU = [MMS_slctd_Metric] & " by BU"
		displayFolder: Dynamic Labels\MarginMeasureSelection
		lineageTag: 121556db-5bd5-463d-9f80-1f557914a08e

	measure tiMarginMetricSelectionByWeek = [MMS_slctd_Metric] & " by Week"
		displayFolder: Dynamic Labels\MarginMeasureSelection
		lineageTag: bd836006-b2e0-4b6b-b792-14c9620d6a87

	measure Stock =
			VAR Stock = [sum_fact_stock]
			RETURN
			    IF ( Stock = 0, BLANK (), Stock )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Stock\Closing Stk\Actual
		lineageTag: 87ba8194-a747-4688-8a42-12e5f0322ef8

	measure 'Stock LY' =
			CALCULATE (
			    [Stock],
			    USERELATIONSHIP ( factStock[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Stock\Closing Stk\LY
		lineageTag: 34127192-df2e-469c-bdad-73790433dc63

	measure 'Stock LY-1' =
			CALCULATE (
			    [Stock],
			    USERELATIONSHIP ( factStock[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Stock LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Stock\Closing Stk\LY-1
		lineageTag: 02502b75-517b-42c4-9254-8acb86779f3b

	measure 'Stock vs LY' =
			VAR act = [Stock]
			VAR comp = [Stock LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Stock\Closing Stk\LY
		lineageTag: 22d4244a-c4d0-47ab-a4b2-0543eb073285

	measure 'Stock vs LY-1' =
			VAR act = [Stock]
			VAR comp = [Stock LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Stock vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Stock\Closing Stk\LY-1
		lineageTag: 6e862cab-ec0b-4e1b-b3c1-4cec15aa3fb2

	measure 'Stock LW' =
			CALCULATE (
			    [Stock],
			    USERELATIONSHIP ( factStock[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Stock\Closing Stk\LW
		lineageTag: 600bd159-71f3-40e2-85d5-cf227678f851

	measure 'Stock vs LW' =
			VAR act = [Stock]
			VAR comp = [Stock LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Stock\Closing Stk\LW
		lineageTag: 78b04fba-3849-472e-8fa8-a527930e61ca

	measure 'Stock BUD' = CALCULATE ( [sum_amt_mp_stock], ForecastScenarios[Forecast Scenario] = "BUD" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Stock\Closing Stk\BUD
		lineageTag: 7b3d2acb-6da3-477a-b6ff-fd7ef8bc85ef

	measure 'Stock vs BUD' =
			VAR act = [Stock]
			VAR comp = [Stock BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Stock\Closing Stk\BUD
		lineageTag: b064b469-197f-4dd3-b4e9-873400859d43

	measure 'Stock FC' = CALCULATE ( [sum_amt_mp_stock], ForecastScenarios[Forecast Scenario] = "FC" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Stock\Closing Stk\FC
		lineageTag: 817a5734-cf22-4543-b39c-39cad0969671

	measure 'Stock vs FC' =
			VAR act = [Stock]
			VAR comp = [Stock FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Stock\Closing Stk\FC
		lineageTag: 83a4e66b-1c80-40dc-bc44-2158d2d94b84

	measure 'Stock QRF' = CALCULATE ( [sum_amt_mp_stock], ForecastScenarios[Forecast Scenario] = "QRF" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Stock\Closing Stk\QRF
		lineageTag: a5c76656-90a7-4ae4-956b-d47e6810be4c

	measure 'Stock vs QRF' =
			VAR act = [Stock]
			VAR comp = [Stock QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Stock\Closing Stk\QRF
		lineageTag: 4f8dc548-d924-4212-b450-a958b1a906bc

	measure 'Promo Mix %' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Promo Mix % Orders],
			        "Dispatch", [Promo Mix % Dispatch],
			        [Promo Mix % Orders]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\Promo\Actual
		lineageTag: 2f0eb2a6-3dd5-4cf6-a49a-88b48e4c0642

	measure 'Promo Mix % Dispatch LY' =
			CALCULATE (
			    [Promo Mix % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Sales Mix\Promo\LY
		lineageTag: 78f83b3d-fc58-4454-a668-3c2f0ad6f708

	measure 'Promo Mix % Dispatch LY-1' =
			CALCULATE (
			    [Promo Mix % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Promo Mix % Dispatch LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Sales Mix\Promo\LY-1
		lineageTag: 1348a39e-513f-444a-987c-cc81aaab6ee2

	measure 'Promo Mix % Dispatch' =
			VAR num = [P SRIV Dispatch]
			VAR denom = [FPP SRIV Dispatch]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Sales Mix\Promo\Actual
		lineageTag: 265879ed-56bc-4290-9183-1bf69df4df63

	measure 'Promo Mix % Dispatch vs LY' =
			VAR act = [Promo Mix % Dispatch]
			VAR comp = [Promo Mix % Dispatch LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Sales Mix\Promo\LY
		lineageTag: 2bfa410c-cb30-46eb-95cb-f5a459a06648

	measure 'Promo Mix % Dispatch vs LY-1' =
			VAR act = [Promo Mix % Dispatch]
			VAR comp = [Promo Mix % Dispatch LY-1]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		description: Two years ago equivalent of Promo Mix % Dispatch vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Sales Mix\Promo\LY-1
		lineageTag: 79738560-4bad-4663-af1a-600bdbfd8b89

	measure 'Promo Mix % Dispatch LW' =
			CALCULATE (
			    [Promo Mix % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Sales Mix\Promo\LW
		lineageTag: 5744ffb6-d04c-453d-abf7-513655e71c48

	measure 'Promo Mix % Dispatch vs LW' =
			VAR act = [Promo Mix % Dispatch]
			VAR comp = [Promo Mix % Dispatch LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Sales Mix\Promo\LW
		lineageTag: 77979af5-0159-4e60-bf44-25da2fef7073

	measure 'FPP Mix % Dispatch' =
			VAR num = [FPP SRIV Dispatch]
			VAR denom = [sum_Sales Revenue (Inc VAT)]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Sales Mix\FPP\Actual
		lineageTag: bb8117d8-da5a-4a17-98e3-90e38eda23d4

	measure 'FPP Mix % Dispatch LW' =
			CALCULATE (
			    [FPP Mix % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Sales Mix\FPP\LW
		lineageTag: 13122cb8-cb79-4253-b615-8f6947d4de52

	measure 'FPP Mix % Dispatch vs LW' =
			VAR act = [FPP Mix % Dispatch]
			VAR comp = [FPP Mix % Dispatch LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Sales Mix\FPP\LW
		lineageTag: b6d5c484-ceb6-4dae-ac03-1804d4e1c242

	measure 'FPP Mix % Dispatch LY' =
			CALCULATE (
			    [FPP Mix % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Sales Mix\FPP\LY
		lineageTag: a54833bd-600a-4945-847e-28d0c5a7344e

	measure 'FPP Mix % Dispatch LY-1' =
			CALCULATE (
			    [FPP Mix % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of FPP Mix % Dispatch LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Sales Mix\FPP\LY-1
		lineageTag: f5a602ba-be40-4fde-ac31-665e629c7cef

	measure 'FPP Mix % Dispatch vs LY' =
			VAR act = [FPP Mix % Dispatch]
			VAR comp = [FPP Mix % Dispatch LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Sales Mix\FPP\LY
		lineageTag: 44053d0e-60f6-44dd-9d91-e1e3e266c59f

	measure 'FPP Mix % Dispatch vs LY-1' =
			VAR act = [FPP Mix % Dispatch]
			VAR comp = [FPP Mix % Dispatch LY-1]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		description: Two years ago equivalent of FPP Mix % Dispatch vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Sales Mix\FPP\LY-1
		lineageTag: f1d4613c-0299-4289-b2cf-c4510843a06f

	measure 'Reduced Mix % Dispatch' =
			VAR num = [RP SRIV Dispatch]
			VAR denom = [sum_Sales Revenue (Inc VAT)]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Sales Mix\Reduced\Actual
		lineageTag: b18c2225-2a72-4dd2-9524-f32fcb0038fd

	measure 'Reduced Mix % Dispatch LW' =
			CALCULATE (
			    [Reduced Mix % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Sales Mix\Reduced\LW
		lineageTag: ea5c7f12-6e15-43e4-b053-9617a1838ea3

	measure 'Reduced Mix % Dispatch vs LW' =
			VAR act = [Reduced Mix % Dispatch]
			VAR comp = [Reduced Mix % Dispatch LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Sales Mix\Reduced\LW
		lineageTag: f24c50bb-7685-45b3-84be-85a670af7b6f

	measure 'Reduced Mix % Dispatch LY' =
			CALCULATE (
			    [Reduced Mix % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Sales Mix\Reduced\LY
		lineageTag: c02538ee-3edc-4969-9d69-6cd56a23538f

	measure 'Reduced Mix % Dispatch LY-1' =
			CALCULATE (
			    [Reduced Mix % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Reduced Mix % Dispatch LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Sales Mix\Reduced\LY-1
		lineageTag: 2a0106be-959f-4df8-8b63-656aaca9129d

	measure 'Reduced Mix % Dispatch vs LY' =
			VAR act = [Reduced Mix % Dispatch]
			VAR comp = [Reduced Mix % Dispatch LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Sales Mix\Reduced\LY
		lineageTag: 7becbeb1-e8db-490c-90c0-155a4f2c78d3

	measure 'Reduced Mix % Dispatch vs LY-1' =
			VAR act = [Reduced Mix % Dispatch]
			VAR comp = [Reduced Mix % Dispatch LY-1]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		description: Two years ago equivalent of Reduced Mix % Dispatch vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Sales Mix\Reduced\LY-1
		lineageTag: 0e9ee5d7-c293-4794-9671-e2fa1e484f8b

	measure 'Promo Mix % Orders' =
			VAR num =
			    CALCULATE ( [SRIV Orders], SalesType[fp_rp_ind] = "P" )
			VAR denom =
			    CALCULATE ( [SRIV Orders], SalesType[fp_rp_ind] IN { "P", "F" } )
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Sales Mix\Promo\Actual
		lineageTag: 3aaed4da-f7cc-4663-9ead-c7709800f80c

	measure 'Promo Mix % Orders LW' =
			CALCULATE (
			    [Promo Mix % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Sales Mix\Promo\LW
		lineageTag: 48350d4d-d591-49ae-a5bc-27e50da1f2aa

	measure 'Promo Mix % Orders vs LW' =
			VAR act = [Promo Mix % Orders]
			VAR comp = [Promo Mix % Orders LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Sales Mix\Promo\LW
		lineageTag: ec4c0084-83e1-4a5a-90ee-ab047a6c1764

	measure 'Promo Mix % Orders LY' =
			CALCULATE (
			    [Promo Mix % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Sales Mix\Promo\LY
		lineageTag: e6db3661-3229-4a21-a731-beef6603ad8c

	measure 'Promo Mix % Orders LY-1' =
			CALCULATE (
			    [Promo Mix % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Promo Mix % Orders LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Sales Mix\Promo\LY-1
		lineageTag: 33c4d2c2-aac3-478a-a54a-a85dbc85a3dd

	measure 'Promo Mix % Orders vs LY' =
			VAR act = [Promo Mix % Orders]
			VAR comp = [Promo Mix % Orders LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Sales Mix\Promo\LY
		lineageTag: 0adfbe23-609d-411b-95ea-d6c1ca38e2cc

	measure 'Promo Mix % Orders vs LY-1' =
			VAR act = [Promo Mix % Orders]
			VAR comp = [Promo Mix % Orders LY-1]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		description: Two years ago equivalent of Promo Mix % Orders vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Sales Mix\Promo\LY-1
		lineageTag: be049884-b613-47ae-b5c7-5549fba12bab

	measure 'FPP Mix % Orders' =
			VAR num =
			    CALCULATE ( [SRIV Orders], SalesType[fp_rp_ind] IN { "P", "F" } )
			VAR denom =
			    CALCULATE ( [SRIV Orders], ALL ( SalesType ) )
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Sales Mix\FPP\Actual
		lineageTag: 9eb0d007-5b16-471b-8f96-54339c0dbb81

	measure 'FPP Mix % Orders LW' =
			CALCULATE (
			    [FPP Mix % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Sales Mix\FPP\LW
		lineageTag: 298e0896-50b4-4f10-a108-ad0a5ee290a7

	measure 'FPP Mix % Orders vs LW' =
			VAR act = [FPP Mix % Orders]
			VAR comp = [FPP Mix % Orders LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Sales Mix\FPP\LW
		lineageTag: fb5575c8-75bd-452b-b07f-4b4ef014ac45

	measure 'FPP Mix % Orders LY' =
			CALCULATE (
			    [FPP Mix % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Sales Mix\FPP\LY
		lineageTag: 201c5988-ba87-47dd-9799-b4b6cd5f38c0

	measure 'FPP Mix % Orders LY-1' =
			CALCULATE (
			    [FPP Mix % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of FPP Mix % Orders LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Sales Mix\FPP\LY-1
		lineageTag: 0054f770-8599-4736-861a-8487efc69827

	measure 'FPP Mix % Orders vs LY' =
			VAR act = [FPP Mix % Orders]
			VAR comp = [FPP Mix % Orders LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Sales Mix\FPP\LY
		lineageTag: 39645894-ee48-4313-b1a0-e87a03c70ac4

	measure 'FPP Mix % Orders vs LY-1' =
			VAR act = [FPP Mix % Orders]
			VAR comp = [FPP Mix % Orders LY-1]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		description: Two years ago equivalent of FPP Mix % Orders vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Sales Mix\FPP\LY-1
		lineageTag: 70ce6781-0b84-44bb-a1cb-2f95681239df

	measure 'Reduced Mix % Orders' =
			VAR num =
			    CALCULATE ( [SRIV Orders], SalesType[fp_rp_ind] IN { "R" } )
			VAR denom =
			    CALCULATE ( [SRIV Orders], ALL ( SalesType ) )
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Sales Mix\Reduced\Actual
		lineageTag: 40f90008-18c9-4f7a-8171-c667aa58f1ed

	measure 'Reduced Mix % Orders LW' =
			CALCULATE (
			    [Reduced Mix % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Sales Mix\Reduced\LW
		lineageTag: 35fc4898-055c-43a9-b4d7-aa20632dd8dd

	measure 'Reduced Mix % Orders vs LW' =
			VAR act = [Reduced Mix % Orders]
			VAR comp = [Reduced Mix % Orders LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Sales Mix\Reduced\LW
		lineageTag: 75121efe-4b55-4a7b-a649-5692a0ded59d

	measure 'Reduced Mix % Orders LY' =
			CALCULATE (
			    [Reduced Mix % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Sales Mix\Reduced\LY
		lineageTag: 6e70ea0e-f261-44da-80eb-cabe73307029

	measure 'Reduced Mix % Orders LY-1' =
			CALCULATE (
			    [Reduced Mix % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Reduced Mix % Orders LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Sales Mix\Reduced\LY-1
		lineageTag: 7dddffeb-6b3b-4ff6-bcbd-544dc16da323

	measure 'Reduced Mix % Orders vs LY' =
			VAR act = [Reduced Mix % Orders]
			VAR comp = [Reduced Mix % Orders LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Sales Mix\Reduced\LY
		lineageTag: 41fe7c00-2968-4272-bc45-4b83ff6e91bc

	measure 'Reduced Mix % Orders vs LY-1' =
			VAR act = [Reduced Mix % Orders]
			VAR comp = [Reduced Mix % Orders LY-1]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		description: Two years ago equivalent of Reduced Mix % Orders vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Sales Mix\Reduced\LY-1
		lineageTag: 4fa8db80-4f78-4249-959a-fbc2ac41aa6c

	measure 'Promo Mix % LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Promo Mix % Orders LW],
			        "Dispatch", [Promo Mix % Dispatch LW],
			        [Promo Mix % Orders LW]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\Promo\LW
		lineageTag: d7d57b89-6df6-49f9-bdae-bf515882332f

	measure 'Promo Mix % LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Promo Mix % Orders LY],
			        "Dispatch", [Promo Mix % Dispatch LY],
			        [Promo Mix % Orders LY]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\Promo\LY
		lineageTag: 80d90e67-ddec-4360-abb8-b128340a353c

	measure 'Promo Mix % LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Promo Mix % Orders LY-1],
			        "Dispatch", [Promo Mix % Dispatch LY-1],
			        [Promo Mix % Orders LY-1]
			    )
			RETURN
			    result
		description: Two years ago equivalent of Promo Mix % LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\Promo\LY-1
		lineageTag: a194852d-76a6-4aeb-8a5b-27b604b1ac36

	measure 'Promo Mix % vs LW' =
			VAR act = [Promo Mix %]
			VAR comp = [Promo Mix % LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\Promo\LW
		lineageTag: cdca8e13-78f1-4ad6-864b-8ae438c19ac7

	measure 'Promo Mix % vs LY' =
			VAR act = [Promo Mix %]
			VAR comp = [Promo Mix % LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\Promo\LY
		lineageTag: 43fe3df7-4080-4141-b549-4d6198cf386c

	measure 'Promo Mix % vs LY-1' =
			VAR act = [Promo Mix %]
			VAR comp = [Promo Mix % LY-1]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		description: Two years ago equivalent of Promo Mix % vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\Promo\LY-1
		lineageTag: 13e6d338-6b41-4704-94af-0440cdb9ac25

	measure 'FPP Mix %' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [FPP Mix % Orders],
			        "Dispatch", [FPP Mix % Dispatch],
			        [FPP Mix % Orders]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\FPP\Actual
		lineageTag: 9d6068df-8060-4bc2-baa6-7476b36828f7

	measure 'FPP Mix % LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [FPP Mix % Orders LW],
			        "Dispatch", [FPP Mix % Dispatch LW],
			        [FPP Mix % Orders LW]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\FPP\LW
		lineageTag: 77aca2ad-2770-4b93-b09a-79bcb3bc6350

	measure 'FPP Mix % vs LW' =
			VAR act = [FPP Mix %]
			VAR comp = [FPP Mix % LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\FPP\LW
		lineageTag: b89cf9a4-0276-484b-8bbe-bdf1894c3d2f

	measure 'FPP Mix % LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [FPP Mix % Orders LY],
			        "Dispatch", [FPP Mix % Dispatch LY],
			        [FPP Mix % Orders LY]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\FPP\LY
		lineageTag: a9091e2c-bb43-4f78-822e-283d88417cce

	measure 'FPP Mix % LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [FPP Mix % Orders LY-1],
			        "Dispatch", [FPP Mix % Dispatch LY-1],
			        [FPP Mix % Orders LY-1]
			    )
			RETURN
			    result
		description: Two years ago equivalent of FPP Mix % LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\FPP\LY-1
		lineageTag: b1975a61-bbd7-4e32-acb1-0f1ebba13342

	measure 'FPP Mix % vs LY' =
			VAR act = [FPP Mix %]
			VAR comp = [FPP Mix % LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\FPP\LY
		lineageTag: e80109f0-b390-4d78-b2d2-277073fe7d18

	measure 'FPP Mix % vs LY-1' =
			VAR act = [FPP Mix %]
			VAR comp = [FPP Mix % LY-1]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		description: Two years ago equivalent of FPP Mix % vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\FPP\LY-1
		lineageTag: 57701984-0804-4924-9b23-2514c73cda04

	measure 'Reduced Mix %' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Reduced Mix % Orders],
			        "Dispatch", [Reduced Mix % Dispatch],
			        [Reduced Mix % Orders]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\Reduced\Actual
		lineageTag: 2a308ae7-fe70-48c7-9483-aaff812bab43

	measure 'Reduced Mix % LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Reduced Mix % Orders LW],
			        "Dispatch", [Reduced Mix % Dispatch LW],
			        [Reduced Mix % Orders LW]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\Reduced\LW
		lineageTag: d517320b-67fa-4563-ae3a-d45922c8fd57

	measure 'Reduced Mix % vs LW' =
			VAR act = [Reduced Mix %]
			VAR comp = [Reduced Mix % LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\Reduced\LW
		lineageTag: df5e7754-9d6e-4f45-a8b3-172ea500a561

	measure 'Reduced Mix % LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Reduced Mix % Orders LY],
			        "Dispatch", [Reduced Mix % Dispatch LY],
			        [Reduced Mix % Orders LY]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\Reduced\LY
		lineageTag: aa2d70fd-520d-4568-8816-5ed3f3737ca1

	measure 'Reduced Mix % LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Reduced Mix % Orders LY-1],
			        "Dispatch", [Reduced Mix % Dispatch LY-1],
			        [Reduced Mix % Orders LY-1]
			    )
			RETURN
			    result
		description: Two years ago equivalent of Reduced Mix % LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\Reduced\LY-1
		lineageTag: 4f68729d-c253-4941-af89-47ceb7e8b8bd

	measure 'Reduced Mix % vs LY' =
			VAR act = [Reduced Mix %]
			VAR comp = [Reduced Mix % LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\Reduced\LY
		lineageTag: cf9107d5-ad5c-44fb-9274-9c038dd5151b

	measure 'Reduced Mix % vs LY-1' =
			VAR act = [Reduced Mix %]
			VAR comp = [Reduced Mix % LY-1]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		description: Two years ago equivalent of Reduced Mix % vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\Reduced\LY-1
		lineageTag: c4108003-cea4-4fd7-91ee-d11b8ad4aab7

	measure LatestSalesOrdersFiscalWeek =
			CALCULATE (
			    MAX ( statsLatestData[latestFiscalWeek] ),
			    statsLatestData[dataSource] = "Sales Orders"
			)
		displayFolder: Metadata\Latest Data
		lineageTag: 09e93b1c-d38c-458b-beb9-55a93e18848a

	measure LatestSalesDispatchFiscalWeek =
			CALCULATE (
			    MAX ( statsLatestData[latestFiscalWeek] ),
			    statsLatestData[dataSource] = "Sales Dispatch"
			)
		displayFolder: Metadata\Latest Data
		lineageTag: 150f21df-39cc-433c-85fd-5e0f42ab30a1

	measure LatestSalesFiscalWeek =
			SWITCH (
			    [slctd_SalesRecognitionType],
			    "Order", [LatestSalesOrdersFiscalWeek],
			    "Dispatch", [LatestSalesDispatchFiscalWeek],
			    [LatestSalesOrdersFiscalWeek]
			)
		displayFolder: Metadata\Latest Data
		lineageTag: 908748c2-0e00-47d0-a99c-84a6a77abfd9

	measure 'SRIV Fwd View' =
			VAR projection_scenario = [slctd_Projection Scenario]
			VAR latest_actuals = [LatestSalesFiscalWeek]
			VAR salesTable =
			    ADDCOLUMNS (
			        VALUES ( 'Calendar'[fiscalWeek] ),
			        "Hybrid",
			            IF (
			                [fiscalWeek] <= latest_actuals,
			                [SRIV],
			                SWITCH (
			                    projection_scenario,
			                    "BUD", [SRIV Channel BUD],
			                    "FC", [SRIV Channel FC],
			                    "QRF", [SRIV Channel QRF],
			                    "LE", [SRIV Channel LE],
			                    [SRIV Channel BUD]
			                )
			            )
			    )
			RETURN
			    SUMX ( salesTable, [Hybrid] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV Fwd View\Actual
		lineageTag: 826e1aeb-fc63-4589-8ead-8b140ce164c5

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Stock vs LY %' =
			VAR act = [Stock]
			VAR comp = [Stock LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Stock\Closing Stk\LY
		lineageTag: 75744109-99c3-49d6-a306-f1e2a99e699a

	measure 'Stock vs LW %' =
			VAR act = [Stock]
			VAR comp = [Stock LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Stock\Closing Stk\LW
		lineageTag: ebf4c808-ffde-4f3e-b100-83add6d94dba

	measure 'Stock vs BUD %' =
			VAR act = [Stock]
			VAR comp = [Stock BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Stock\Closing Stk\BUD
		lineageTag: 81793e69-91ab-4dad-9c91-a53f8b011a81

	measure 'Stock vs FC %' =
			VAR act = [Stock]
			VAR comp = [Stock FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Stock\Closing Stk\FC
		lineageTag: 22572b06-d0be-4a3c-9a82-2dc41992e289

	measure 'Stock vs QRF %' =
			VAR act = [Stock]
			VAR comp = [Stock QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Stock\Closing Stk\QRF
		lineageTag: b0cc3eff-632a-4a31-af4e-e1ce1e9c8a47

	measure ABV =
			VAR num = [Sale Trans Value]
			VAR denom = [Transactions]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\ABV\Actual
		lineageTag: f6cff9bb-3a78-4b5b-8bf0-979b6db52726

	/// This measure is the sum of column 'factTransactions'[trans]
	measure Transactions =
			VAR channel =
			    SELECTEDVALUE ( ChannelControl[Channel] )
			VAR result =
			    SWITCH (
			        channel,
			        "Stores", [Store Transactions],
			        "Online", [factAdobe Orders],
			        "Total", [Store Transactions] + [factAdobe Orders],
			        BLANK ()
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Transactions\Actual
		lineageTag: 2bcf8e6b-7521-4115-b420-dbbd0aa79ad3

	/// This measure is the sum of column 'factTransactions'[items]
	measure Items = SUM ( 'factTransactions'[num_items] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Items\Actual
		lineageTag: 5f6ee260-0889-4c44-befc-f0bdee5ffcef

	measure 'Transactions LY' =
			VAR store =
			    CALCULATE (
			        [Store Transactions],
			        USERELATIONSHIP ( factTransactions[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			    )
			VAR online = [factAdobe Orders LY]
			VAR channel =
			    SELECTEDVALUE ( ChannelControl[Channel] )
			VAR result =
			    SWITCH (
			        channel,
			        "Stores", store,
			        "Online", online,
			        "Total", store + online,
			        BLANK ()
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Transactions\LY
		lineageTag: d75c2084-7ded-4b2f-b92f-2b5c0365b98a

	measure 'Transactions LY-1' =
			VAR store =
			    CALCULATE (
			        [Store Transactions],
			        USERELATIONSHIP ( factTransactions[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			    )
			VAR online = [factAdobe Orders LY-1]
			VAR channel =
			    SELECTEDVALUE ( ChannelControl[Channel] )
			VAR result =
			    SWITCH (
			        channel,
			        "Stores", store,
			        "Online", online,
			        "Total", store + online,
			        BLANK ()
			    )
			RETURN
			    result
		description: Two years ago equivalent of Transactions LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Transactions\LY-1
		lineageTag: 8e450ebf-e1bc-4330-848d-1f6226b20ab8

	measure 'Transactions LW' =
			VAR store =
			    CALCULATE (
			        [Store Transactions],
			        USERELATIONSHIP ( factTransactions[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			    )
			VAR online = [factAdobe Orders LW]
			VAR channel =
			    SELECTEDVALUE ( ChannelControl[Channel] )
			VAR result =
			    SWITCH (
			        channel,
			        "Stores", store,
			        "Online", online,
			        "Total", store + online,
			        BLANK ()
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Transactions\LW
		lineageTag: 171e6613-100e-4322-ab75-cf5f889be52d

	measure 'Transactions vs LY' =
			VAR act = [Transactions]
			VAR comp = [Transactions LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Transactions\LY
		lineageTag: 118292bd-0146-4536-9846-83d67c9a0d9e

	measure 'Transactions vs LY-1' =
			VAR act = [Transactions]
			VAR comp = [Transactions LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Transactions vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Transactions\LY-1
		lineageTag: 76a3684b-1a67-4d71-b766-2dfec36c184a

	measure 'Transactions vs LY %' =
			VAR act = [Transactions]
			VAR comp = [Transactions LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\Transactions\LY
		lineageTag: 4c0ed11b-6430-4e1c-b3c0-a09ce26e8534

	measure 'Transactions vs LW' =
			VAR act = [Transactions]
			VAR comp = [Transactions LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Transactions\LW
		lineageTag: d61ac387-a0a0-491e-960b-cf4ce66bc8cd

	measure 'Transactions vs LW %' =
			VAR act = [Transactions]
			VAR comp = [Transactions LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\Transactions\LW
		lineageTag: f5c99970-c561-4de9-8d51-f01d51af3c28

	measure 'Items LY' =
			CALCULATE (
			    [Items],
			    USERELATIONSHIP ( factTransactions[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Items\LY
		lineageTag: aa18f369-1b10-48d3-ad17-77486f2ae8bd

	measure 'Items LY-1' =
			CALCULATE (
			    [Items],
			    USERELATIONSHIP ( factTransactions[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Items LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Items\LY-1
		lineageTag: 8d9a60d4-ca60-4751-afb9-67cb1ae29b44

	measure 'Items vs LY' =
			VAR act = [Items]
			VAR comp = [Items LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Items\LY
		lineageTag: 307f8266-143f-49f3-9487-12f038281534

	measure 'Items vs LY-1' =
			VAR act = [Items]
			VAR comp = [Items LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Items vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Items\LY-1
		lineageTag: b1d9e5dd-8101-4055-ad40-0d719e44a273

	measure 'Items vs LY %' =
			VAR act = [Items]
			VAR comp = [Items LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\Items\LY
		lineageTag: 4a0d82d3-7607-44ef-803d-842901fd8abf

	measure 'Items LW' =
			CALCULATE (
			    [Items],
			    USERELATIONSHIP ( factTransactions[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Items\LW
		lineageTag: 5ece56e8-5e81-4406-9cf9-be384780cd87

	measure 'Items vs LW' =
			VAR act = [Items]
			VAR comp = [Items LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Items\LW
		lineageTag: 947410d9-853d-4e8f-bb3f-3380995346fb

	measure 'Items vs LW %' =
			VAR act = [Items]
			VAR comp = [Items LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\Items\LW
		lineageTag: a1c51c0b-ac59-498e-a255-0f79b258bab9

	measure 'ABV LY' =
			VAR num = [Sale Trans Value LY]
			VAR denom = [Transactions LY]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\ABV\LY
		lineageTag: b22263cd-48a0-472e-8592-db82b8392f88

	measure 'ABV LY-1' =
			VAR num = [Sale Trans Value LY-1]
			VAR denom = [Transactions LY-1]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
		description: Two years ago equivalent of ABV LY.
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\ABV\LY-1
		lineageTag: 718066fa-aa1f-4aa7-a892-bd0df87849c7

	measure 'ABV vs LY' =
			VAR act = [ABV]
			VAR comp = [ABV LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\ABV\LY
		lineageTag: 785a31e3-4eff-4a4f-b431-9aa6dfdae835

	measure 'ABV vs LY-1' =
			VAR act = [ABV]
			VAR comp = [ABV LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of ABV vs LY.
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\ABV\LY-1
		lineageTag: e2d66a3f-8b97-4254-85ad-0686be2a808b

	measure 'ABV vs LY %' =
			VAR act = [ABV]
			VAR comp = [ABV LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\ABV\LY
		lineageTag: 93d0beab-3d34-4827-9b29-84ba4f641bd1

	measure 'ABV LW' =
			VAR num = [Sale Trans Value LW]
			VAR denom = [Transactions LW]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\ABV\LW
		lineageTag: 2bd68421-02c7-4dd9-a878-f55e1ca233ab

	measure 'ABV vs LW' =
			VAR act = [ABV]
			VAR comp = [ABV LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\ABV\LW
		lineageTag: ce8dac66-ce43-455f-b5b1-647281258a38

	measure 'ABV vs LW %' =
			VAR act = [ABV]
			VAR comp = [ABV LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\ABV\LW
		lineageTag: 6d7c3470-3ad5-4531-9ff8-996ae237cbf4

	measure 'Basket Size' =
			VAR num = [Items]
			VAR denom = [Transactions]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\Basket Size\Actual
		lineageTag: 3fda3f0c-46ee-4b93-ab6b-5153b64015a2

	measure 'Basket Size LY' =
			VAR num = [Items LY]
			VAR denom = [Transactions LY]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\Basket Size\LY
		lineageTag: eec41c14-e7d3-4c3c-92ce-fcee1dda15c1

	measure 'Basket Size LY-1' =
			VAR num = [Items LY-1]
			VAR denom = [Transactions LY-1]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
		description: Two years ago equivalent of Basket Size LY.
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\Basket Size\LY-1
		lineageTag: 2991a58c-1925-4a22-aebe-4643eb4f7b35

	measure 'Basket Size vs LY' =
			VAR act = [Basket Size]
			VAR comp = [Basket Size LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\Basket Size\LY
		lineageTag: a0cb6423-4d3e-439e-875f-d6964e70eb49

	measure 'Basket Size vs LY-1' =
			VAR act = [Basket Size]
			VAR comp = [Basket Size LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Basket Size vs LY.
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\Basket Size\LY-1
		lineageTag: b993d30c-6e69-46c7-a665-06f9a0528d51

	measure 'Basket Size vs LY %' =
			VAR act = [Basket Size]
			VAR comp = [Basket Size LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\Basket Size\LY
		lineageTag: ed6d133d-1461-4b05-9bdd-e853d84b1838

	measure 'Basket Size LW' =
			VAR num = [Items LW]
			VAR denom = [Transactions LW]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\Basket Size\LW
		lineageTag: 16adf270-130c-4078-9a1d-6b4d5c262bdd

	measure 'Basket Size vs LW' =
			VAR act = [Basket Size]
			VAR comp = [Basket Size LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\Basket Size\LW
		lineageTag: f5a99cca-8372-4882-bdb3-eb4f681caa85

	measure 'Basket Size vs LW %' =
			VAR act = [Basket Size]
			VAR comp = [Basket Size LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\Basket Size\LW
		lineageTag: a150f198-0c7b-4945-b225-7905298418ca

	measure ASP =
			VAR num = [Sale Trans Value]
			VAR denom = [Items]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\ASP\Actual
		lineageTag: f77e865f-6dd6-4515-b3eb-75636ef16c4e

	measure 'ASP LY' =
			VAR num = [Sale Trans Value LY]
			VAR denom = [Items LY]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\ASP\LY
		lineageTag: c7a53939-d3b6-4db2-84eb-71a827f4fc68

	measure 'ASP LY-1' =
			VAR num = [Sale Trans Value LY-1]
			VAR denom = [Items LY-1]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
		description: Two years ago equivalent of ASP LY.
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\ASP\LY-1
		lineageTag: 0023719f-3906-4489-877f-541c4a5e06c6

	measure 'ASP vs LY' =
			VAR act = [ASP]
			VAR comp = [ASP LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\ASP\LY
		lineageTag: 2ea16c63-ed7d-42bb-b742-b4dde8ce5068

	measure 'ASP vs LY-1' =
			VAR act = [ASP]
			VAR comp = [ASP LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of ASP vs LY.
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\ASP\LY-1
		lineageTag: 36921187-ee70-48ab-b4ed-4bf0d39b00f8

	measure 'ASP vs LY %' =
			VAR act = [ASP]
			VAR comp = [ASP LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\ASP\LY
		lineageTag: 5f90fcd6-b63b-4315-bdbd-5b8e9b7c31e3

	measure 'ASP LW' =
			VAR num = [Sale Trans Value LW]
			VAR denom = [Items LW]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\ASP\LW
		lineageTag: 3ec0fa05-161e-4767-bc52-17d3cfe75565

	measure 'ASP vs LW' =
			VAR act = [ASP]
			VAR comp = [ASP LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\ASP\LW
		lineageTag: a714bbf9-f9d0-4c7b-a3bf-61234adcedc2

	measure 'ASP vs LW %' =
			VAR act = [ASP]
			VAR comp = [ASP LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\ASP\LW
		lineageTag: c7c11860-79de-4bf4-a5b0-e5fb377cf965

	measure Trans =
			VAR metric = [slctd_TransMetric]
			VAR result =
			    SWITCH (
			        metric,
			        "Visits", [Visits],
			        "Conversion", [Conversion %],
			        "Transactions", [Transactions],
			        "ABV/AOV", [ABV],
			        "Items", [Items],
			        "ASP", [ASP],
			        "Basket Size",[Basket Size]
			    )
			RETURN
			    result
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\Actual
		lineageTag: b612941f-383d-4fa8-890c-e4efee6d83c6

	measure 'Trans LY' =
			VAR metric = [slctd_TransMetric]
			VAR result =
			    SWITCH (
			        metric,
			        "Visits", [Visits LY],
			        "Conversion", [Conversion % LY],
			        "Transactions", [Transactions LY],
			        "ABV/AOV", [ABV LY],
			        "Items", [Items LY],
			        "ASP", [ASP LY],
			        "Basket Size", [Basket Size LY]
			    )
			RETURN
			    result
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\LY
		lineageTag: 25783498-afc1-461a-97e8-75d7603ade75

	measure 'Trans LY-1' =
			VAR metric = [slctd_TransMetric]
			VAR result =
			    SWITCH (
			        metric,
			        "Visits", [Visits LY-1],
			        "Conversion", [Conversion % LY-1],
			        "Transactions", [Transactions LY-1],
			        "ABV/AOV", [ABV LY-1],
			        "Items", [Items LY-1],
			        "ASP", [ASP LY-1],
			        "Basket Size", [Basket Size LY-1]
			    )
			RETURN
			    result
		description: Two years ago equivalent of Trans LY.
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\LY-1
		lineageTag: eb7260f5-4917-4436-8e45-cfa8cb7f0910

	measure 'Trans LW' =
			VAR metric = [slctd_TransMetric]
			VAR result =
			    SWITCH (
			        metric,
			        "Visits", [Visits LW],
			        "Conversion", [Conversion % LW],
			        "Transactions", [Transactions LW],
			        "ABV/AOV", [ABV LW],
			        "Items", [Items LW],
			        "ASP", [ASP LW]
			    )
			RETURN
			    result
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\LW
		lineageTag: 5f4b1ac0-bdd9-46d6-a283-99337398b09a

	measure 'Trans vs LY' =
			VAR act = [Trans]
			VAR comp = [Trans LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\LY
		lineageTag: 7e6444fb-c8d4-47c0-8004-9d4c9a7a4bcb

	measure 'Trans vs LY-1' =
			VAR act = [Trans]
			VAR comp = [Trans LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Trans vs LY.
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\LY-1
		lineageTag: ddaf2842-2338-492e-ae0a-bff7c01cc4e3

	measure 'Trans vs LY %' =
			VAR act = [Trans]
			VAR comp = [Trans LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\LY
		lineageTag: 798819d0-a154-4831-9157-a5aa4c87c6df

	measure 'Trans vs LW' =
			VAR act = [Trans]
			VAR comp = [Trans LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\LW
		lineageTag: d6ddb0ff-4823-4efa-98e8-6b75bd1cfe32

	measure 'Trans vs LW %' =
			VAR act = [Trans]
			VAR comp = [Trans LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\LW
		lineageTag: a54876bf-7cec-49d8-98b9-9148bace8e0d

	measure 'Stock Fwd Cover' =
			VAR sales_plan = [slctd_Projection MP Plan]
			VAR result =
			    CALCULATE (
			        [stock_fwd_cover_base],
			        ALL ( 'Time Period' ),
			        ALL ( ForecastScenarios ),
			        ALL ( BridgeMPPlan ),
			        FILTER ( ALL ( factForecast[plan] ), factForecast[plan] = sales_plan ),
			        FILTER ( ALL ( factMPStock[plan] ), factMPStock[plan] = "RF")
			    )
			RETURN
			    IF ( [is_channel_unfiltered], result, BLANK () )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Stock\Fwd Cover\Actual
		lineageTag: c4d22267-34e7-4842-ac31-f0acb2f2607c

	measure 'Stock Fwd Cover LY' =
			VAR sales_plan = "RF"
			VAR result =
			    CALCULATE (
			        [stock_fwd_cover_base],
			        ALL ( 'Time Period' ),
			        ALL ( ForecastScenarios ),
			        ALL ( BridgeMPPlan ),
			        FILTER ( ALL ( factForecast[plan] ), factForecast[plan] = sales_plan ),
			        FILTER ( ALL ( factMPStock[plan] ), factMPStock[plan] = "RF" ),
			        USERELATIONSHIP ( factMPStock[fiscalWeek], 'Calendar'[fiscalWeekLastYear] ),
			        USERELATIONSHIP ( factForecast[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			    )
			RETURN
			    IF ( [is_channel_unfiltered], result, BLANK () )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Stock\Fwd Cover\LY
		lineageTag: 18cabd55-f25b-4147-a47a-efc425d018f6

	measure 'Stock Fwd Cover LY-1' =
			VAR sales_plan = "RF"
			VAR result =
			    CALCULATE (
			        [stock_fwd_cover_base],
			        ALL ( 'Time Period' ),
			        ALL ( ForecastScenarios ),
			        ALL ( BridgeMPPlan ),
			        FILTER ( ALL ( factForecast[plan] ), factForecast[plan] = sales_plan ),
			        FILTER ( ALL ( factMPStock[plan] ), factMPStock[plan] = "RF" ),
			        USERELATIONSHIP ( factMPStock[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] ),
			        USERELATIONSHIP ( factForecast[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			    )
			RETURN
			    IF ( [is_channel_unfiltered], result, BLANK () )
		description: Two years ago equivalent of Stock Fwd Cover LY.
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Stock\Fwd Cover\LY-1
		lineageTag: 95384ef8-c5a6-4d47-9c90-6dc6eb973a59

	measure 'Stock Fwd Cover LW' =
			CALCULATE (
			    [Stock Fwd Cover],
			    USERELATIONSHIP ( factStock[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] ),
			    USERELATIONSHIP ( factForecast[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Stock\Fwd Cover\LW
		lineageTag: e91844a9-d2e0-482c-ac6f-fb726f34ac15

	measure 'Stock Fwd Cover BUD' =
			VAR sales_plan = [slctd_MP Plan]
			VAR result =
			    CALCULATE (
			        [stock_fwd_cover_base],
			        ALL ( 'Time Period' ),
			        FILTER (
			            ALL ( ForecastScenarios ),
			            ForecastScenarios[Forecast Scenario] = "BUD"
			        )
			    )
			RETURN
			    IF ( [is_channel_unfiltered], result, BLANK () )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Stock\Fwd Cover\BUD
		lineageTag: bb292ec1-0378-4221-83d8-a10ea15f514f

	measure 'Stock Fwd Cover FC' =
			VAR sales_plan = [slctd_MP Plan]
			VAR result =
			    CALCULATE (
			        [stock_fwd_cover_base],
			        ALL ( 'Time Period' ),
			        FILTER (
			            ALL ( ForecastScenarios ),
			            ForecastScenarios[Forecast Scenario] = "FC"
			        )
			    )
			RETURN
			    IF ( [is_channel_unfiltered], result, BLANK () )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Stock\Fwd Cover\FC
		lineageTag: 68350615-fc59-465f-8f66-507074ffe61c

	measure 'Stock Fwd Cover QRF' =
			
			VAR sales_plan = [slctd_MP Plan]
			VAR result =
			    CALCULATE (
			        [stock_fwd_cover_base],
			        ALL ( 'Time Period' ),
			        FILTER (
			            ALL ( ForecastScenarios ),
			            ForecastScenarios[Forecast Scenario] = "FC"
			        )
			    )
			RETURN
			    IF ( [is_channel_unfiltered], result, BLANK () )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Stock\Fwd Cover\QRF
		lineageTag: 5ab86f6a-08a3-4043-854a-deed82ad008d

	measure 'Stock Fwd Cover vs LY' =
			VAR act = [Stock Fwd Cover]
			VAR comp = [Stock Fwd Cover LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Stock\Fwd Cover\LY
		lineageTag: 7a008ff3-757c-4bd1-9c07-dfda8caaa62e

	measure 'Stock Fwd Cover vs LY-1' =
			VAR act = [Stock Fwd Cover]
			VAR comp = [Stock Fwd Cover LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Stock Fwd Cover vs LY.
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Stock\Fwd Cover\LY-1
		lineageTag: 3ad1dfa9-1f33-46e8-ab34-b883ace327a0

	measure 'Stock Fwd Cover vs LY %' =
			VAR act = [Stock Fwd Cover]
			VAR comp = [Stock Fwd Cover LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Stock\Fwd Cover\LY
		lineageTag: 6a545e69-163f-49ee-bd35-b59ae19c6f77

	measure 'Stock Fwd Cover vs LW' =
			VAR act = [Stock Fwd Cover]
			VAR comp = [Stock Fwd Cover LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Stock\Fwd Cover\LW
		lineageTag: 9efa678e-23b2-4e56-9c8b-4e14a53b7c0d

	measure 'Stock Fwd Cover vs LW %' =
			VAR act = [Stock Fwd Cover]
			VAR comp = [Stock Fwd Cover LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Stock\Fwd Cover\LW
		lineageTag: 63a14742-2cd8-4201-a2ea-05424d758f68

	measure 'Stock Fwd Cover vs BUD' =
			VAR act = [Stock Fwd Cover]
			VAR comp = [Stock Fwd Cover BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Stock\Fwd Cover\BUD
		lineageTag: bd861e45-f4b0-4de6-b8d6-bfdd8ca910a0

	measure 'Stock Fwd Cover vs BUD %' =
			VAR act = [Stock Fwd Cover]
			VAR comp = [Stock Fwd Cover BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Stock\Fwd Cover\BUD
		lineageTag: 87e139d4-db80-4afa-bf54-d85c76c08f2d

	measure 'Stock Fwd Cover vs FC' =
			VAR act = [Stock Fwd Cover]
			VAR comp = [Stock Fwd Cover FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Stock\Fwd Cover\FC
		lineageTag: 0cde863c-7b88-480d-807a-368daeb5e712

	measure 'Stock Fwd Cover vs FC %' =
			VAR act = [Stock Fwd Cover]
			VAR comp = [Stock Fwd Cover FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Stock\Fwd Cover\FC
		lineageTag: cd12b711-60d5-4b5c-b7bd-f0067010f568

	measure 'Stock Fwd Cover vs QRF' =
			VAR act = [Stock Fwd Cover]
			VAR comp = [Stock Fwd Cover QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Stock\Fwd Cover\QRF
		lineageTag: 7ed7339b-5b99-425f-aff7-9c1a3bc5f2d3

	measure 'Stock Fwd Cover vs QRF %' =
			VAR act = [Stock Fwd Cover]
			VAR comp = [Stock Fwd Cover QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Stock\Fwd Cover\QRF
		lineageTag: fb0dba87-9805-430b-aa62-0607307de122

	measure P&L =
			VAR metric = [slctd_MetricMasterPnL]
			VAR sale_recog = [slctd_SalesRecognitionType]
			VAR is_channel_unfiltered = [is_channel_unfiltered]
			VAR is_channel_available =
			    SELECTEDVALUE ( MetricMasterPnL[ActOrdersChannelAvailable] )
			VAR result =
			    SWITCH (
			        metric,
			        "Sales Revenue (Inc VAT)", [SRIV],
			        "Sales Revenue (Exc VAT)", [SREV],
			        "Discount Participation %", [Discount Participation %],
			        "Promo Mix %", [Promo Mix %],
			        "FPP Mix %", [FPP Mix %],
			        "Reduced Mix %", [Reduced Mix %],
			        "Returns", [Returns],
			        "Returns %", [Return rate %],
			        "Buying Margin %", [Buying Margin %],
			        "Markdown", [Markdown],
			        "Markdown %", [Markdown % SRIV],
			        "POS", [Promo Markdown],
			        "POS %", [Promo Markdown %],
			        "Sale Markdown", [Sale Markdown],
			        "Sale Markdown %", [Sale Markdown %],
			        "SIS Sold Through", [SIS Sold Through],
			        "Staff Discount & Loyalty", [Staff Discount & Loyalty],
			        "Depth Of Cut", [Depth Of Cut],
			        "Depth Of Cut %", [Depth Of Cut %],
			        "Other GSM Adj", [Other GSM Adj],
			        "GSM", [GSM],
			        "GSM %", [GSM % SREV],
			        BLANK ()
			    )
			RETURN
			        IF (
			        is_channel_unfiltered,
			        result,
			        IF ( is_channel_available, result, BLANK () )
			    )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: P&L\Actual
		lineageTag: 968a066d-dae8-4139-9900-fa22badbd2ac

	measure 'P&L LY' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR sale_recog = [slctd_SalesRecognitionType]
			VAR is_channel_unfiltered = [is_channel_unfiltered]
			VAR is_channel_available =
			    SELECTEDVALUE ( MetricMasterPnL[ActOrdersChannelAvailable] )
			VAR result =
			    SWITCH (
			        metric,
			        "Sales Revenue (Inc VAT)", [SRIV LY],
			        "Sales Revenue (Exc VAT)", [SREV LY],
			        "Discount Participation %", [Discount Participation % LY],
			        "Promo Mix %", [Promo Mix % LY],
			        "FPP Mix %", [FPP Mix % LY],
			        "Reduced Mix %", [Reduced Mix % LY],
			        "Returns", [Returns LY],
			        "Returns %", [Return rate % LY],
			        "Buying Margin %", [Buying Margin % LY],
			        "Markdown", [Markdown LY],
			        "Markdown %", [Markdown % SRIV LY],
			        "POS", [Promo Markdown LY],
			        "POS %", [Promo Markdown % LY],
			        "Sale Markdown", [Sale Markdown LY],
			        "Sale Markdown %", [Sale Markdown % LY],
			        "SIS Sold Through", [SIS Sold Through LY],
			        "Staff Discount & Loyalty", [Staff Discount & Loyalty LY],
			        "Depth Of Cut", [Depth Of Cut LY],
			        "Depth Of Cut %", [Depth Of Cut % LY],
			        "Other GSM Adj", [Other GSM Adj LY],
			        "GSM", [GSM LY],
			        "GSM %", [GSM % SREV LY],
			        BLANK ()
			    )
			RETURN
			    IF (
			        is_channel_unfiltered,
			        result,
			        IF ( is_channel_available, result, BLANK () )
			    )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: P&L\LY
		lineageTag: 82e6921b-37da-4c8f-a7dc-0290c8895bd2

	measure 'P&L LY-1' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR sale_recog = [slctd_SalesRecognitionType]
			VAR is_channel_unfiltered = [is_channel_unfiltered]
			VAR is_channel_available =
			    SELECTEDVALUE ( MetricMasterPnL[ActOrdersChannelAvailable] )
			VAR result =
			    SWITCH (
			        metric,
			        "Sales Revenue (Inc VAT)", [SRIV LY-1],
			        "Sales Revenue (Exc VAT)", [SREV LY-1],
			        "Discount Participation %", [Discount Participation % LY-1],
			        "Promo Mix %", [Promo Mix % LY-1],
			        "FPP Mix %", [FPP Mix % LY-1],
			        "Reduced Mix %", [Reduced Mix % LY-1],
			        "Returns", [Returns LY-1],
			        "Returns %", [Return rate % LY-1],
			        "Buying Margin %", [Buying Margin % LY-1],
			        "Markdown", [Markdown LY-1],
			        "Markdown %", [Markdown % SRIV LY-1],
			        "POS", [Promo Markdown LY-1],
			        "POS %", [Promo Markdown % LY-1],
			        "Sale Markdown", [Sale Markdown LY-1],
			        "Sale Markdown %", [Sale Markdown % LY-1],
			        "SIS Sold Through", [SIS Sold Through LY-1],
			        "Staff Discount & Loyalty", [Staff Discount & Loyalty LY-1],
			        "Depth Of Cut", [Depth Of Cut LY-1],
			        "Depth Of Cut %", [Depth Of Cut % LY-1],
			        "Other GSM Adj", [Other GSM Adj LY-1],
			        "GSM", [GSM LY-1],
			        "GSM %", [GSM % SREV LY-1],
			        BLANK ()
			    )
			RETURN
			    IF (
			        is_channel_unfiltered,
			        result,
			        IF ( is_channel_available, result, BLANK () )
			    )
		description: Two years ago equivalent of P&L LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: P&L\LY-1
		lineageTag: 8f3ffa11-a463-4e8e-ad74-087af329844e

	measure 'P&L vs LY' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR act = [P&L]
			VAR comp = [P&L LY]
			VAR result = act - comp
			VAR adj_result =
			    IF ( CONTAINSSTRING ( metric, "%" ), result * 1, result )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), adj_result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: P&L\LY
		lineageTag: b8804541-4663-4e2f-995d-7e0cc66d55cf

	measure 'P&L vs LY-1' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR act = [P&L]
			VAR comp = [P&L LY-1]
			VAR result = act - comp
			VAR adj_result =
			    IF ( CONTAINSSTRING ( metric, "%" ), result * 1, result )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), adj_result )
		description: Two years ago equivalent of P&L vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: P&L\LY-1
		lineageTag: d374441a-8ec0-4ff6-b95b-2e68dba82d5c

	measure 'Promo Markdown Orders' = ```
			
			-([GSRIV Orders] - [SRIV Orders])
			//SUM ( 'factSalesOrders'[stfdisc] ) + SUM ( 'factSalesOrders'[othdisc] )
			
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Promo Markdown\Actual
		lineageTag: c0d48451-aa79-4bdd-ad97-cebfe3752a6b

	measure 'Promo Markdown Orders LY' =
			CALCULATE (
			    [Promo Markdown Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Promo Markdown\LY
		lineageTag: 0ea81243-b2d0-4f83-84e4-c4c3c5b0723c

	measure 'Promo Markdown Orders LY-1' =
			CALCULATE (
			    [Promo Markdown Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Promo Markdown Orders LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Promo Markdown\LY-1
		lineageTag: c967b999-7795-4fbe-88eb-343c46413c85

	measure 'Promo Markdown Orders vs LY' =
			VAR act = [Promo Markdown Orders]
			VAR comp = [Promo Markdown Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Promo Markdown\LY
		lineageTag: c54e42e5-716b-43d1-9d6a-ac032064b2e0

	measure 'Promo Markdown Orders vs LY-1' =
			VAR act = [Promo Markdown Orders]
			VAR comp = [Promo Markdown Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Promo Markdown Orders vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Promo Markdown\LY-1
		lineageTag: 0c9a10b2-2394-4ed9-bcdc-d9462bde1b41

	measure 'Promo Markdown Orders LW' =
			CALCULATE (
			    [Promo Markdown Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Promo Markdown\LW
		lineageTag: afa380ea-3063-402c-9ec5-41272281c59c

	measure 'Promo Markdown Orders vs LW' =
			VAR act = [Promo Markdown Orders]
			VAR comp = [Promo Markdown Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Promo Markdown\LW
		lineageTag: d9c29062-cbc7-475b-bce8-3744e1d881f9

	measure 'Promo Markdown Orders BUD' = CALCULATE ( [sum_TotPromoActV], ForecastScenarios[Forecast Scenario] = "BUD" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Promo Markdown\BUD
		lineageTag: 83ce4e63-cd32-41f2-bb75-d11ce3e1c62b

	measure 'Promo Markdown Orders vs BUD' =
			VAR act = [Promo Markdown Orders]
			VAR comp = [Promo Markdown Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Promo Markdown\BUD
		lineageTag: 5252aa08-61ff-46be-8648-efdf8f426661

	measure 'Promo Markdown Orders FC' =
			
			VAR PlanVersion = [SlctdForecastVersion]
			RETURN
			CALCULATE ( [sum_TotPromoActV], factForecast[plan] = PlanVersion )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Promo Markdown\FC
		lineageTag: de675840-8e30-411a-b703-ed78131a0afa

	measure 'Promo Markdown Orders vs FC' =
			VAR act = [Promo Markdown Orders]
			VAR comp = [Promo Markdown Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Promo Markdown\FC
		lineageTag: 1b02369d-f76e-40d7-a19f-68071e198d22

	measure 'Promo Markdown Orders QRF' =
			
			VAR PlanVersion = [SlctdQRFVersion]
			RETURN
			CALCULATE ( [sum_TotPromoActV], factForecast[plan] = PlanVersion )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Promo Markdown\QRF
		lineageTag: 372bdda4-593b-4c9c-9e36-8a1bd80b831c

	measure 'Promo Markdown Orders vs QRF' =
			VAR act = [Promo Markdown Orders]
			VAR comp = [Promo Markdown Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Promo Markdown\QRF
		lineageTag: cb11cfe2-1816-4ade-ba32-a9fd2a257b66

	measure 'Sale Markdown Orders' = - SUM ( 'factSalesOrders'[rmiv] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\Actual
		lineageTag: af7d517c-a86f-468e-bb07-64fec41b5674

	measure 'Sale Markdown Orders LY' =
			CALCULATE (
			    [Sale Markdown Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\LY
		lineageTag: 4092daef-1b12-43ed-9869-545433c3c8d4

	measure 'Sale Markdown Orders LY-1' =
			CALCULATE (
			    [Sale Markdown Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Sale Markdown Orders LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\LY-1
		lineageTag: f7d031a2-ad15-470b-96c8-18de1f9db2b4

	measure 'Sale Markdown Orders vs LY' =
			VAR act = [Sale Markdown Orders]
			VAR comp = [Sale Markdown Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\LY
		lineageTag: 58df32b3-3725-4276-85a1-2a138f716169

	measure 'Sale Markdown Orders vs LY-1' =
			VAR act = [Sale Markdown Orders]
			VAR comp = [Sale Markdown Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Sale Markdown Orders vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\LY-1
		lineageTag: 6c03118d-bb4f-4a22-932e-38e09e69814c

	measure 'Staff Discount & Loyalty Orders LW' =
			CALCULATE (
			    [Staff Discount & Loyalty Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Staff Discount & Loyalty\LW
		lineageTag: 77f4dddd-8629-4975-8b8e-427432f613ea

	measure 'Staff Discount & Loyalty Orders vs LW' =
			VAR act = [Staff Discount & Loyalty Orders]
			VAR comp = [Staff Discount & Loyalty Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Staff Discount & Loyalty\LW
		lineageTag: 63a27594-93ef-48c5-ad6c-5733f7154f69

	measure 'Sale Markdown Orders BUD' = CALCULATE ( [sum_RealMDV], ForecastScenarios[Forecast Scenario] = "BUD" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\BUD
		lineageTag: a2ecc842-11a8-473b-a40f-56fae2066af9

	measure 'Sale Markdown Orders vs BUD' =
			VAR act = [Sale Markdown Orders]
			VAR comp = [Sale Markdown Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\BUD
		lineageTag: 1abdfbac-9a01-48c9-93ad-3f01fc90b82f

	measure 'Sale Markdown Orders FC' =
			
			VAR PlanVersion = [SlctdForecastVersion]
			Return
			CALCULATE ( [sum_RealMDV], factForecast[plan] = PlanVersion )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\FC
		lineageTag: 06c01181-b97d-456e-baee-76584dc4bce7

	measure 'Sale Markdown Orders vs FC' =
			VAR act = [Sale Markdown Orders]
			VAR comp = [Sale Markdown Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\FC
		lineageTag: d0fd5e61-2ef4-40bd-a160-5b28dd9772e1

	measure 'Sale Markdown Orders QRF' =
			
			VAR PlanVersion = [SlctdQRFVersion]
			Return
			CALCULATE ( [sum_RealMDV], factForecast[plan] = PlanVersion )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\QRF
		lineageTag: ac56ca04-f3f6-4bef-b388-e38cd1e9cc8e

	measure 'Sale Markdown Orders vs QRF' =
			VAR act = [Sale Markdown Orders]
			VAR comp = [Sale Markdown Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\QRF
		lineageTag: 5ed4baaf-d45f-4128-9643-0391053b2837

	measure 'SIS Sold Through Orders' = BLANK()
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\SIS Sold Through\Actual
		lineageTag: 2e6c3435-bf0b-4b26-b78a-3af56af19930

	measure 'SIS Sold Through Orders LY' =
			CALCULATE (
			    [SIS Sold Through Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\SIS Sold Through\LY
		lineageTag: 1e159415-e5e2-47fe-a057-1b4584fc20b6

	measure 'SIS Sold Through Orders LY-1' =
			CALCULATE (
			    [SIS Sold Through Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of SIS Sold Through Orders LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\SIS Sold Through\LY-1
		lineageTag: 897b036e-d42a-4495-a027-34971b7c7467

	measure 'SIS Sold Through Orders vs LY' =
			VAR act = [SIS Sold Through Orders]
			VAR comp = [SIS Sold Through Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\SIS Sold Through\LY
		lineageTag: f26a1e29-207a-4cb8-b6b8-987b040708c3

	measure 'SIS Sold Through Orders vs LY-1' =
			VAR act = [SIS Sold Through Orders]
			VAR comp = [SIS Sold Through Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of SIS Sold Through Orders vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\SIS Sold Through\LY-1
		lineageTag: c116f939-6a41-496c-a49b-a00742c01e59

	measure 'SIS Sold Through Orders LW' =
			CALCULATE (
			    [SIS Sold Through Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\SIS Sold Through\LW
		lineageTag: deb47a3d-86cc-4512-8742-728f7d2869ba

	measure 'SIS Sold Through Orders vs LW' =
			VAR act = [SIS Sold Through Orders]
			VAR comp = [SIS Sold Through Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\SIS Sold Through\LW
		lineageTag: 7d545b9c-ac33-46e9-b7c4-8d4e5898e436

	measure 'SIS Sold Through Orders BUD' = CALCULATE ( [sum_SST], ForecastScenarios[Forecast Scenario] = "BUD" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\SIS Sold Through\BUD
		lineageTag: 2cfd3d70-e1ac-4851-8684-9bea7a39466d

	measure 'SIS Sold Through Orders vs BUD' =
			VAR act = [SIS Sold Through Orders]
			VAR comp = [SIS Sold Through Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\SIS Sold Through\BUD
		lineageTag: 255915da-b45b-4fe1-8990-07aab4f35ffd

	measure 'SIS Sold Through Orders FC' =
			
			VAR PlanVersion = [SlctdForecastVersion]
			Return
			CALCULATE ( [sum_SST], factForecast[plan] = PlanVersion )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\SIS Sold Through\FC
		lineageTag: a302392a-8770-4884-b889-f37ad2500864

	measure 'SIS Sold Through Orders vs FC' =
			VAR act = [SIS Sold Through Orders]
			VAR comp = [SIS Sold Through Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\SIS Sold Through\FC
		lineageTag: 5136cd24-c0ca-4bc4-a231-7626d1d8aca6

	measure 'SIS Sold Through Orders QRF' =
			
			VAR PlanVersion = [SlctdQRFVersion]
			Return
			CALCULATE ( [sum_SST], factForecast[plan] = PlanVersion )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\SIS Sold Through\QRF
		lineageTag: 27a393e6-003a-4abb-9f10-212c88567652

	measure 'SIS Sold Through Orders vs QRF' =
			VAR act = [SIS Sold Through Orders]
			VAR comp = [SIS Sold Through Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\SIS Sold Through\QRF
		lineageTag: ec2f0a13-11ae-463e-a674-5b0ca3203f44

	measure 'Staff Discount & Loyalty Orders' = SUM ( 'factSalesOrders'[stfdisc] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Staff Discount & Loyalty\Actual
		lineageTag: e7c005ee-de74-42e0-b27f-2026d80457af

	measure 'Staff Discount & Loyalty Orders LY' =
			CALCULATE (
			    [Staff Discount & Loyalty Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Staff Discount & Loyalty\LY
		lineageTag: 41c5f35d-321e-4c63-aa6a-b29efc8eb019

	measure 'Staff Discount & Loyalty Orders LY-1' =
			CALCULATE (
			    [Staff Discount & Loyalty Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Staff Discount & Loyalty Orders LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Staff Discount & Loyalty\LY-1
		lineageTag: e1f7b92e-44cd-4c06-81b0-895be9ba476a

	measure 'Staff Discount & Loyalty Orders vs LY' =
			VAR act = [Staff Discount & Loyalty Orders]
			VAR comp = [Staff Discount & Loyalty Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Staff Discount & Loyalty\LY
		lineageTag: 4b238691-2043-47db-bfb3-f4483095b12e

	measure 'Staff Discount & Loyalty Orders vs LY-1' =
			VAR act = [Staff Discount & Loyalty Orders]
			VAR comp = [Staff Discount & Loyalty Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Staff Discount & Loyalty Orders vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Staff Discount & Loyalty\LY-1
		lineageTag: 37118c7b-50d3-4316-901f-e1da23bf564c

	measure 'Staff Discount & Loyalty Orders BUD' = CALCULATE ( [sum_TotStDV], ForecastScenarios[Forecast Scenario] = "BUD" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Staff Discount & Loyalty\BUD
		lineageTag: 1b39da69-b674-448b-bf6e-fa78ba54f48e

	measure 'Staff Discount & Loyalty Orders vs BUD' =
			VAR act = [Staff Discount & Loyalty Orders]
			VAR comp = [Staff Discount & Loyalty Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Staff Discount & Loyalty\BUD
		lineageTag: 1e3506d4-6bc7-4bbb-912f-c354f21b5823

	measure 'Staff Discount & Loyalty Orders FC' =
			
			VAR PlanVersion = [SlctdForecastVersion]
			Return
			CALCULATE ( [sum_TotStDV], factForecast[plan] = PlanVersion)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Staff Discount & Loyalty\FC
		lineageTag: 5e085443-69fc-4ead-b21e-6085e6ee5247

	measure 'Staff Discount & Loyalty Orders vs FC' =
			VAR act = [Staff Discount & Loyalty Orders]
			VAR comp = [Staff Discount & Loyalty Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Staff Discount & Loyalty\FC
		lineageTag: 4e70b430-fc80-4cc7-8de1-ea8b59a4698c

	measure 'Staff Discount & Loyalty Orders QRF' =
			
			VAR PlanVersion = [SlctdQRFVersion]
			Return
			CALCULATE ( [sum_TotStDV], factForecast[plan] = PlanVersion)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Staff Discount & Loyalty\QRF
		lineageTag: eeaed12b-e086-4e35-baf9-94bcd97d8e5c

	measure 'Staff Discount & Loyalty Orders vs QRF' =
			VAR act = [Staff Discount & Loyalty Orders]
			VAR comp = [Staff Discount & Loyalty Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Staff Discount & Loyalty\QRF
		lineageTag: 7f4a46bb-e920-422d-bc28-ca3b963f2cb1

	measure 'Depth Of Cut Orders' = BLANK()
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Depth Of Cut\Actual
		lineageTag: f2ff09df-b8a4-4b5a-812e-3f89202eac1e

	measure 'Depth Of Cut Orders LY' =
			CALCULATE (
			    [Depth Of Cut Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Depth Of Cut\LY
		lineageTag: 91e61173-c7e4-46aa-9fca-44c2ded9daab

	measure 'Depth Of Cut Orders LY-1' =
			CALCULATE (
			    [Depth Of Cut Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Depth Of Cut Orders LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Depth Of Cut\LY-1
		lineageTag: d09696ae-c792-4e6b-af05-4d4871ef1a4d

	measure 'Depth Of Cut Orders vs LY' =
			VAR act = [Depth Of Cut Orders]
			VAR comp = [Depth Of Cut Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Depth Of Cut\LY
		lineageTag: 7b03e622-b37a-4c7a-8208-41cc1b840701

	measure 'Depth Of Cut Orders vs LY-1' =
			VAR act = [Depth Of Cut Orders]
			VAR comp = [Depth Of Cut Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Depth Of Cut Orders vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Depth Of Cut\LY-1
		lineageTag: f86744e6-59a3-4b33-ae87-938d0c828a2f

	measure 'Sale Markdown Orders LW' =
			CALCULATE (
			    [Sale Markdown Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\LW
		lineageTag: 775c6b11-a70d-4a24-bba2-4f831dfc09ec

	measure 'Sale Markdown Orders vs LW' =
			VAR act = [Sale Markdown Orders]
			VAR comp = [Sale Markdown Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\LW
		lineageTag: 2a7415e4-a31d-4b92-9927-54c9be5dd1ae

	measure 'Depth Of Cut Orders LW' =
			CALCULATE (
			    [Depth Of Cut Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Depth Of Cut\LW
		lineageTag: 85910549-36ff-4e7c-b618-7f99614b1b06

	measure 'Depth Of Cut Orders vs LW' =
			VAR act = [Depth Of Cut Orders]
			VAR comp = [Depth Of Cut Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Depth Of Cut\LW
		lineageTag: 4941a28f-e99f-4476-b958-3bb57608f250

	measure 'Depth Of Cut Orders BUD' = CALCULATE ( [sum_DoC], ForecastScenarios[Forecast Scenario] = "BUD" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Depth Of Cut\BUD
		lineageTag: 659c74eb-9d1b-4aeb-b3f7-9039a206c5a4

	measure 'Depth Of Cut Orders vs BUD' =
			VAR act = [Depth Of Cut Orders]
			VAR comp = [Depth Of Cut Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Depth Of Cut\BUD
		lineageTag: 70f0d18c-cd92-443c-8742-6595c77a007c

	measure 'Depth Of Cut Orders FC' = ```
			
			VAR PlanVersion = [SlctdForecastVersion]
			return 
			CALCULATE ( [sum_DoC], factForecast[plan] = PlanVersion )
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Depth Of Cut\FC
		lineageTag: 95ca25ef-8c92-48e9-8df8-d97453328dd7

	measure 'Depth Of Cut Orders vs FC' =
			VAR act = [Depth Of Cut Orders]
			VAR comp = [Depth Of Cut Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Depth Of Cut\FC
		lineageTag: 8ea85a5a-f639-4b31-82d1-21da51e9630d

	measure 'Depth Of Cut Orders QRF' = ```
			
			VAR PlanVersion = [SlctdQRFVersion]
			return 
			CALCULATE ( [sum_DoC], factForecast[plan] = PlanVersion )
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Depth Of Cut\QRF
		lineageTag: 1f5b2c8f-8cd4-4e7d-ad73-a08897ebbc08

	measure 'Depth Of Cut Orders vs QRF' =
			VAR act = [Depth Of Cut Orders]
			VAR comp = [Depth Of Cut Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Depth Of Cut\QRF
		lineageTag: d8334d02-ba9c-4c34-b375-fa93fdcfc073

	measure 'Promo Markdown % Orders' =
			VAR metric = - [Promo Markdown Orders]
			VAR sales =
			    - [Promo Markdown Orders]
			        + CALCULATE ( [SRIV Orders], SalesType[SalesType] = "FP&P" )
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Promo Markdown\Actual
		lineageTag: 9e9ad879-a059-42a8-98ef-d3b949785598

	measure 'Promo Markdown % Orders LY' =
			CALCULATE (
			    [Promo Markdown % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Promo Markdown\LY
		lineageTag: 758992b7-219b-49a7-b7ba-30b82eb923cf

	measure 'Promo Markdown % Orders LY-1' =
			CALCULATE (
			    [Promo Markdown % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Promo Markdown % Orders LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Promo Markdown\LY-1
		lineageTag: 6fa9350e-d888-4895-b9cb-6db2fc47ebd7

	measure 'Promo Markdown % Orders vs LY' =
			VAR act = [Promo Markdown % Orders]
			VAR comp = [Promo Markdown % Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Promo Markdown\LY
		lineageTag: 5d2d19cc-6cd8-4d78-b897-897c52204891

	measure 'Promo Markdown % Orders vs LY-1' =
			VAR act = [Promo Markdown % Orders]
			VAR comp = [Promo Markdown % Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Promo Markdown % Orders vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Promo Markdown\LY-1
		lineageTag: 95c6e378-5d6e-44ab-ae09-a942ecf35b02

	measure 'Promo Markdown % Orders LW' =
			CALCULATE (
			    [Promo Markdown % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Promo Markdown\LW
		lineageTag: bf71104d-7a9a-4be4-9d39-383488fe3238

	measure 'Promo Markdown % Orders vs LW' =
			VAR act = [Promo Markdown % Orders]
			VAR comp = [Promo Markdown % Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Promo Markdown\LW
		lineageTag: a2e63bbc-7bc0-4505-adae-ebcda3ac4611

	measure 'Promo Markdown % Orders BUD' =
			VAR metric = - [Promo Markdown Orders BUD]
			VAR sales =
			    CALCULATE (
			        - [sum_TotPromoActV] + [sum_FPPSlsV],
			        ForecastScenarios[Forecast Scenario] = "BUD"
			    )
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Promo Markdown\BUD
		lineageTag: 554cdada-764e-41ff-b6af-cde7b2bde9ad

	measure 'Promo Markdown % Orders vs BUD' =
			VAR act = [Promo Markdown % Orders]
			VAR comp = [Promo Markdown % Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Promo Markdown\BUD
		lineageTag: 126370bc-31c6-4193-9fb9-499251c6727e

	measure 'Promo Markdown % Orders FC' =
			VAR metric = - [Promo Markdown Orders FC]
			VAR sales =
			    CALCULATE (
			        - [sum_TotPromoActV] + [sum_FPPSlsV],
			        ForecastScenarios[Forecast Scenario] = "FC"
			    )
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Promo Markdown\FC
		lineageTag: 56e3a0e4-e29c-4d3c-a18f-1d742e7977c6

	measure 'Promo Markdown % Orders vs FC' =
			VAR act = [Promo Markdown % Orders]
			VAR comp = [Promo Markdown % Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Promo Markdown\FC
		lineageTag: 39986a0c-8986-453f-a3ce-e2759ee8dac8

	measure 'Promo Markdown % Orders QRF' =
			VAR metric = - [Promo Markdown Orders QRF]
			VAR sales =
			    CALCULATE (
			        - [sum_TotPromoActV] + [sum_FPPSlsV],
			        ForecastScenarios[Forecast Scenario] = "QRF"
			    )
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Promo Markdown\QRF
		lineageTag: 9a69856c-bb83-4834-aaa1-989bd4e34635

	measure 'Promo Markdown % Orders vs QRF' =
			VAR act = [Promo Markdown % Orders]
			VAR comp = [Promo Markdown % Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Promo Markdown\QRF
		lineageTag: 24a3a347-0e86-487b-a148-9bdf86f45dbc

	measure 'Sale Markdown % Orders' =
			VAR metric = - [Sale Markdown Orders]
			VAR sales =
			    - [Sale Markdown Orders]
			        + CALCULATE ( [SRIV Orders], SalesType[SalesType] = "Reduced" )
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\Actual
		lineageTag: 667ee2dc-9054-493d-a369-076c0bdb6846

	measure 'Sale Markdown % Orders LY' =
			CALCULATE (
			    [Sale Markdown % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\LY
		lineageTag: 5b47b5f8-ca45-48fd-8547-a98d6098b793

	measure 'Sale Markdown % Orders LY-1' =
			CALCULATE (
			    [Sale Markdown % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Sale Markdown % Orders LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\LY-1
		lineageTag: be9fb28e-6986-4a96-817b-06c3e9630f8d

	measure 'Sale Markdown % Orders vs LY' =
			VAR act = [Sale Markdown % Orders]
			VAR comp = [Sale Markdown % Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\LY
		lineageTag: 91800d2b-9721-4498-9853-ad378fef7896

	measure 'Sale Markdown % Orders vs LY-1' =
			VAR act = [Sale Markdown % Orders]
			VAR comp = [Sale Markdown % Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Sale Markdown % Orders vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\LY-1
		lineageTag: e465f704-23a6-425d-a6ea-2d395864e04c

	measure 'Sale Markdown % Orders LW' =
			CALCULATE (
			    [Sale Markdown % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\LW
		lineageTag: ccc8a514-6be8-42a4-bd31-5708f7ab2dac

	measure 'Sale Markdown % Orders vs LW' =
			VAR act = [Sale Markdown % Orders]
			VAR comp = [Sale Markdown % Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\LW
		lineageTag: 7649fef2-0183-484d-b0ee-542650cdd450

	measure 'Sale Markdown % Orders BUD' =
			VAR metric = - [Sale Markdown Orders BUD]
			VAR sales =
			    CALCULATE (
			        - [sum_RealMDV] + [sum_RedSlsV],
			        ForecastScenarios[Forecast Scenario] = "BUD"
			    )
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\BUD
		lineageTag: c8223660-d092-4cda-bf87-2ca2d30dd2e7

	measure 'Sale Markdown % Orders vs BUD' =
			VAR act = [Sale Markdown % Orders]
			VAR comp = [Sale Markdown % Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\BUD
		lineageTag: cfd68b99-fb6f-430d-a33d-9cd42fcde409

	measure 'Sale Markdown % Orders FC' =
			
			VAR PlanVersion = [SlctdForecastVersion]
			VAR metric = - [Sale Markdown Orders FC]
			VAR sales =
			    CALCULATE (
			        - [sum_RealMDV] + [sum_RedSlsV],
			        factForecast[plan] = PlanVersion
			    )
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\FC
		lineageTag: ebc11f1f-0a79-4e71-abe2-050fe0b3022a

	measure 'Sale Markdown % Orders vs FC' =
			VAR act = [Sale Markdown % Orders]
			VAR comp = [Sale Markdown % Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\FC
		lineageTag: 557f311c-fb2d-4da0-919d-e54330d8e516

	measure 'Sale Markdown % Orders QRF' =
			VAR metric = - [Sale Markdown Orders QRF]
			VAR sales =
			    CALCULATE (
			        - [sum_RealMDV] + [sum_RedSlsV],
			        ForecastScenarios[Forecast Scenario] = "QRF"
			    )
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\QRF
		lineageTag: c8becb64-0024-44e1-86fd-2d31cd4ba296

	measure 'Sale Markdown % Orders vs QRF' =
			VAR act = [Sale Markdown % Orders]
			VAR comp = [Sale Markdown % Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\QRF
		lineageTag: 6bf4dbd7-9d2a-4942-ae8a-a976f32245ad

	measure 'Promo Markdown % Dispatch' =
			VAR metric = - [Promo Markdown Dispatch]
			VAR sales = - [Promo Markdown Dispatch] + [FPP SRIV Dispatch]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Promo Markdown\Actual
		lineageTag: a992468b-8659-46a4-b269-8a23d0a04f85

	measure 'Promo Markdown % Dispatch LY' =
			CALCULATE (
			    [Promo Markdown % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Promo Markdown\LY
		lineageTag: 1ab4f62c-be62-4af4-b21a-f04203ca3e3d

	measure 'Promo Markdown % Dispatch LY-1' =
			CALCULATE (
			    [Promo Markdown % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Promo Markdown % Dispatch LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Promo Markdown\LY-1
		lineageTag: d8304711-891f-4bc5-8a99-81acb780fef5

	measure 'Promo Markdown % Dispatch vs LY' =
			VAR act = [Promo Markdown % Dispatch]
			VAR comp = [Promo Markdown % Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Promo Markdown\LY
		lineageTag: 3d5553a7-5faa-4859-a440-3062440a2e46

	measure 'Promo Markdown % Dispatch vs LY-1' =
			VAR act = [Promo Markdown % Dispatch]
			VAR comp = [Promo Markdown % Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Promo Markdown % Dispatch vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Promo Markdown\LY-1
		lineageTag: 0a5042c1-a075-42d0-9ea6-b74ee6406dc5

	measure 'Promo Markdown % Dispatch LW' =
			CALCULATE (
			    [Promo Markdown % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Promo Markdown\LW
		lineageTag: 29ac8c43-75a4-43f9-b0d4-2c30fd1a044b

	measure 'Promo Markdown % Dispatch vs LW' =
			VAR act = [Promo Markdown % Dispatch]
			VAR comp = [Promo Markdown % Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Promo Markdown\LW
		lineageTag: df0e5f63-8661-49ad-9634-63bdcdf7952a

	measure 'Promo Markdown % Dispatch BUD' =
			VAR metric = - [Promo Markdown Dispatch BUD]
			VAR sales = - [Promo Markdown Dispatch BUD] + [FPP SRIV Dispatch BUD]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Promo Markdown\BUD
		lineageTag: 35c00816-f775-480a-b40d-d3bfb28243cf

	measure 'Promo Markdown % Dispatch vs BUD' =
			VAR act = [Promo Markdown % Dispatch]
			VAR comp = [Promo Markdown % Dispatch BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Promo Markdown\BUD
		lineageTag: 3a0c1200-ca13-40ce-9213-552145e67b13

	measure 'Promo Markdown % Dispatch FC' =
			VAR metric = - [Promo Markdown Dispatch FC]
			VAR sales = - [Promo Markdown Dispatch FC] + [FPP SRIV Dispatch FC]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Promo Markdown\FC
		lineageTag: 9bc0119e-d513-4c34-bd90-0c315dd921c7

	measure 'Promo Markdown % Dispatch vs FC' =
			VAR act = [Promo Markdown % Dispatch]
			VAR comp = [Promo Markdown % Dispatch FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Promo Markdown\FC
		lineageTag: 81be12dd-fbea-4fba-a8f4-f1241f90f406

	measure 'Promo Markdown % Dispatch QRF' =
			VAR metric = - [Promo Markdown Dispatch QRF]
			VAR sales = - [Promo Markdown Dispatch QRF] + [FPP SRIV Dispatch QRF]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Promo Markdown\QRF
		lineageTag: 52025c79-5fce-4510-b48a-d364d7f337f0

	measure 'Promo Markdown % Dispatch vs QRF' =
			VAR act = [Promo Markdown % Dispatch]
			VAR comp = [Promo Markdown % Dispatch QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Promo Markdown\QRF
		lineageTag: 64cc26b3-85f6-4d65-a80e-542505cd224b

	measure 'Sale Markdown % Dispatch' =
			VAR metric = - [Sale Markdown Dispatch]
			VAR sales = - [Sale Markdown Dispatch] + [RP SRIV Dispatch]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\Actual
		lineageTag: d2c8d0b4-3c21-4a46-a3c9-b1587e29354a

	measure 'Sale Markdown % Dispatch LY' =
			CALCULATE (
			    [Sale Markdown % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\LY
		lineageTag: ab17d464-61f7-4254-a552-01a01c39c63a

	measure 'Sale Markdown % Dispatch LY-1' =
			CALCULATE (
			    [Sale Markdown % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Sale Markdown % Dispatch LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\LY-1
		lineageTag: 07e814ed-a912-4456-9c76-46e654bf70aa

	measure 'Sale Markdown % Dispatch vs LY' =
			VAR act = [Sale Markdown % Dispatch]
			VAR comp = [Sale Markdown % Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\LY
		lineageTag: eeca9577-6198-48ad-af30-bea8a4fcd685

	measure 'Sale Markdown % Dispatch vs LY-1' =
			VAR act = [Sale Markdown % Dispatch]
			VAR comp = [Sale Markdown % Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Sale Markdown % Dispatch vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\LY-1
		lineageTag: f6af7605-5bca-4b1d-b95d-82023d063178

	measure 'Sale Markdown % Dispatch LW' =
			CALCULATE (
			    [Sale Markdown % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\LW
		lineageTag: b3763517-2391-4ed2-b009-56cc9381e4c6

	measure 'Sale Markdown % Dispatch vs LW' =
			VAR act = [Sale Markdown % Dispatch]
			VAR comp = [Sale Markdown % Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\LW
		lineageTag: 937f346f-1035-4bb7-ab86-d676998eaaf0

	measure 'Sale Markdown % Dispatch BUD' =
			VAR metric = - [Sale Markdown Dispatch BUD]
			VAR sales = - [Sale Markdown Dispatch BUD] + [RP SRIV Dispatch BUD]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\BUD
		lineageTag: 9e6f2ccb-ac22-4210-9276-ce4b54e895a2

	measure 'Sale Markdown % Dispatch vs BUD' =
			VAR act = [Sale Markdown % Dispatch]
			VAR comp = [Sale Markdown % Dispatch BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\BUD
		lineageTag: faef7c33-9693-4fd1-902e-7846d999b466

	measure 'Sale Markdown % Dispatch FC' =
			VAR metric = - [Sale Markdown Dispatch FC]
			VAR sales = - [Sale Markdown Dispatch FC] + [RP SRIV Dispatch FC]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\FC
		lineageTag: 38e7b867-4a18-4b91-9247-1881fc2f33fe

	measure 'Sale Markdown % Dispatch vs FC' =
			VAR act = [Sale Markdown % Dispatch]
			VAR comp = [Sale Markdown % Dispatch FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\FC
		lineageTag: 0a78e99b-7267-489a-9e0b-95333073d0b5

	measure 'Sale Markdown % Dispatch QRF' =
			VAR metric = - [Sale Markdown Dispatch QRF]
			VAR sales = - [Sale Markdown Dispatch QRF] + [RP SRIV Dispatch QRF]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\QRF
		lineageTag: 4a313103-e475-4c9a-b5e6-6054f0e51fa5

	measure 'Sale Markdown % Dispatch vs QRF' =
			VAR act = [Sale Markdown % Dispatch]
			VAR comp = [Sale Markdown % Dispatch QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\QRF
		lineageTag: edb46c32-0a29-4a64-b19f-97d7ae3446b6

	measure 'Promo Markdown' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Promo Markdown Orders],
			        "Dispatch", [Promo Markdown Dispatch],
			        [Promo Markdown Orders]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Promo Markdown\Actual
		lineageTag: dbd80a9d-e7d3-42fa-9758-2d25392033f9

	measure 'Promo Markdown %' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Promo Markdown % Orders],
			        "Dispatch", [Promo Markdown % Dispatch],
			        [Promo Markdown % Orders]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Promo Markdown\Actual
		lineageTag: 64c4defa-7ad1-43bd-acf0-3cd53630df9a

	measure 'Promo Markdown LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Promo Markdown Orders LY],
			        "Dispatch", [Promo Markdown Dispatch LY],
			        [Promo Markdown Orders LY]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Promo Markdown\LY
		lineageTag: 8d7ff159-13b2-46c8-9e49-311c9673c814

	measure 'Promo Markdown LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Promo Markdown Orders LY-1],
			        "Dispatch", [Promo Markdown Dispatch LY-1],
			        [Promo Markdown Orders LY-1]
			    )
			RETURN
			    result
		description: Two years ago equivalent of Promo Markdown LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Promo Markdown\LY-1
		lineageTag: f928b080-0907-4696-bfd0-83fb8992fb3f

	measure 'Promo Markdown vs LY' =
			VAR act = [Promo Markdown]
			VAR comp = [Promo Markdown LY]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Promo Markdown\LY
		lineageTag: fcf59896-f16e-43d2-a87d-45099581eaf8

	measure 'Promo Markdown vs LY-1' =
			VAR act = [Promo Markdown]
			VAR comp = [Promo Markdown LY-1]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		description: Two years ago equivalent of Promo Markdown vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Promo Markdown\LY-1
		lineageTag: 284f0f17-c281-4863-abb2-b16b21eb70da

	measure 'Promo Markdown % LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Promo Markdown % Orders LY],
			        "Dispatch", [Promo Markdown % Dispatch LY],
			        [Promo Markdown % Orders LY]
			    )
			RETURN
			    result
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Promo Markdown\LY
		lineageTag: cd0e6df3-9399-434c-bbf9-346bcb085c5d

	measure 'Promo Markdown % LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Promo Markdown % Orders LY-1],
			        "Dispatch", [Promo Markdown % Dispatch LY-1],
			        [Promo Markdown % Orders LY-1]
			    )
			RETURN
			    result
		description: Two years ago equivalent of Promo Markdown % LY.
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Promo Markdown\LY-1
		lineageTag: b1c55258-da72-4736-bae3-4deda47cee2a

	measure 'Promo Markdown % vs LY' =
			VAR act = [Promo Markdown %]
			VAR comp = [Promo Markdown % LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Promo Markdown\LY
		lineageTag: 686dc9be-5fb8-40b8-a32f-c421d395427a

	measure 'Promo Markdown % vs LY-1' =
			VAR act = [Promo Markdown %]
			VAR comp = [Promo Markdown % LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Promo Markdown % vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Promo Markdown\LY-1
		lineageTag: cc7c7256-1d7a-4532-82eb-6ab13875d4c1

	measure 'Promo Markdown vs LY %' =
			VAR act = [Promo Markdown]
			VAR comp = [Promo Markdown LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Promo Markdown\LY
		lineageTag: 93352579-4d5e-462b-a8e4-9e13c3e05475

	measure 'Promo Markdown LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Promo Markdown Orders LW],
			        "Dispatch", [Promo Markdown Dispatch LW],
			        [Promo Markdown Orders LW]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Promo Markdown\LW
		lineageTag: e03e1885-f99e-4fae-8261-ea37e0167e03

	measure 'Promo Markdown vs LW' =
			VAR act = [Promo Markdown]
			VAR comp = [Promo Markdown LW]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Promo Markdown\LW
		lineageTag: a81bb32d-e3bb-45d1-8533-a0a7012c5d70

	measure 'Promo Markdown % LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Promo Markdown % Orders LW],
			        "Dispatch", [Promo Markdown % Dispatch LW],
			        [Promo Markdown % Orders LW]
			    )
			RETURN
			    result
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Promo Markdown\LW
		lineageTag: 0db21ab9-5be9-4e26-9a88-708e7824c235

	measure 'Promo Markdown % vs LW' =
			VAR act = [Promo Markdown %]
			VAR comp = [Promo Markdown % LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Promo Markdown\LW
		lineageTag: 510d6ceb-0321-4b4a-8b24-2194ec89ce44

	measure 'Promo Markdown vs LW %' =
			VAR act = [Promo Markdown]
			VAR comp = [Promo Markdown LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Promo Markdown\LW
		lineageTag: e025e672-db85-447e-8021-84eb3a3beeb1

	measure 'Promo Markdown BUD' = ```
			
			VAR firstweek_yr = [SlctdBudVersion]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    [fiscalWeek] <  firstweek_yr, 
			  [Promo Markdown],
			  [Promo Markdown Orders BUD]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
			 
			/*VAR result = [Promo Markdown Orders BUD]
			RETURN
			    result*/
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Promo Markdown\BUD
		lineageTag: c8c8f9a1-e678-4778-a0dc-230f57c09cad

	measure 'Promo Markdown vs BUD' =
			VAR act = [Promo Markdown]
			VAR comp = [Promo Markdown BUD]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Promo Markdown\BUD
		lineageTag: dca52645-1870-4d55-928f-2a9547d9e2f0

	measure 'Promo Markdown % BUD' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Promo Markdown % Orders BUD],
			        "Dispatch", [Promo Markdown % Dispatch BUD],
			        [Promo Markdown % Orders BUD]
			    )
			RETURN
			    result
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Promo Markdown\BUD
		lineageTag: 97325d52-225e-46f5-aea9-daa62acf0e16

	measure 'Promo Markdown % vs BUD' =
			VAR act = [Promo Markdown %]
			VAR comp = [Promo Markdown % BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Promo Markdown\BUD
		lineageTag: f203e65e-15fa-49e5-b644-1196f8848fad

	measure 'Promo Markdown vs BUD %' =
			VAR act = [Promo Markdown]
			VAR comp = [Promo Markdown BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Promo Markdown\BUD
		lineageTag: ea9e4494-e664-43cb-8684-6bea2f67e968

	measure 'Promo Markdown FC' =
			//SelectedWeeks
			VAR firstweek_qtr = [SlctdFirstWeekQtrFC]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [Promo Markdown],
			            [Promo Markdown Orders FC]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Promo Markdown\FC
		lineageTag: 58890ad8-bf74-4b9d-be4b-babaaf8fe2a2

	measure 'Promo Markdown vs FC' =
			VAR act = [Promo Markdown]
			VAR comp = [Promo Markdown FC]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Promo Markdown\FC
		lineageTag: 91dd1287-1d6c-4caa-b960-42e35189ca61

	measure 'Promo Markdown % FC' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Promo Markdown % Orders FC],
			        "Dispatch", [Promo Markdown % Dispatch FC],
			        [Promo Markdown % Orders FC]
			    )
			RETURN
			    result
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Promo Markdown\FC
		lineageTag: ff53c123-718e-40cc-adf7-cd0a3f666076

	measure 'Promo Markdown % vs FC' =
			VAR act = [Promo Markdown %]
			VAR comp = [Promo Markdown % FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Promo Markdown\FC
		lineageTag: 85b41dc3-eb4b-4ba8-8c54-517af7e9738c

	measure 'Promo Markdown vs FC %' =
			VAR act = [Promo Markdown]
			VAR comp = [Promo Markdown FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Promo Markdown\FC
		lineageTag: a98dab8e-5e08-4cf7-9d80-ebfa0322f951

	measure 'Promo Markdown QRF' =
			//SelectedWeeks
			VAR firstweek_qtr = [SlctdFirstWeekQtrQRF]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [Promo Markdown],
			            [Promo Markdown Orders QRF]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Promo Markdown\QRF
		lineageTag: 4a065a11-955d-496f-84d1-5a6aebe380c8

	measure 'Promo Markdown vs QRF' =
			VAR act = [Promo Markdown]
			VAR comp = [Promo Markdown QRF]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Promo Markdown\QRF
		lineageTag: aabf15eb-8d53-409f-9a9f-98766ca331af

	measure 'Promo Markdown % QRF' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Promo Markdown % Orders QRF],
			        "Dispatch", [Promo Markdown % Dispatch QRF],
			        [Promo Markdown % Orders QRF]
			    )
			RETURN
			    result
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Promo Markdown\QRF
		lineageTag: b5ef3112-4724-408b-bac2-ede6b60225c9

	measure 'Promo Markdown % vs QRF' =
			VAR act = [Promo Markdown %]
			VAR comp = [Promo Markdown % QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Promo Markdown\QRF
		lineageTag: 0a6f36d3-bcc0-4e32-9b26-3e08eceb5b43

	measure 'Promo Markdown vs QRF %' =
			VAR act = [Promo Markdown]
			VAR comp = [Promo Markdown QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Promo Markdown\QRF
		lineageTag: 075f01d8-4242-400a-ae0d-54bfd01c9cdb

	measure 'Sale Markdown' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown Orders],
			        "Dispatch", [Sale Markdown Dispatch],
			        [Sale Markdown Orders]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\Actual
		lineageTag: 6f285038-7945-4035-9c89-6e3c05149c6f

	measure 'Sale Markdown %' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown % Orders],
			        "Dispatch", [Sale Markdown % Dispatch],
			        [Sale Markdown % Orders]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\Actual
		lineageTag: 6e9033e8-2ae0-4afc-bc84-b422d025ca96

	measure 'Sale Markdown LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown Orders LY],
			        "Dispatch", [Sale Markdown Dispatch LY],
			        [Sale Markdown Orders LY]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\LY
		lineageTag: c2dd4cd5-23fd-4a26-ad13-6cabfb190382

	measure 'Sale Markdown LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown Orders LY-1],
			        "Dispatch", [Sale Markdown Dispatch LY-1],
			        [Sale Markdown Orders LY-1]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		description: Two years ago equivalent of Sale Markdown LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\LY-1
		lineageTag: 5d8cb9bd-f472-457d-8827-309f977c5c0e

	measure 'Sale Markdown vs LY' =
			VAR act = [Sale Markdown]
			VAR comp = [Sale Markdown LY]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\LY
		lineageTag: 9f168f81-5643-42f9-9b44-91cb076d4be5

	measure 'Sale Markdown vs LY-1' =
			VAR act = [Sale Markdown]
			VAR comp = [Sale Markdown LY-1]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		description: Two years ago equivalent of Sale Markdown vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\LY-1
		lineageTag: 91ac1363-8887-4de8-a2f2-7be8291022a4

	measure 'Sale Markdown % LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown % Orders LY],
			        "Dispatch", [Sale Markdown % Dispatch LY],
			        [Sale Markdown % Orders LY]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Sale Markdown\LY
		lineageTag: 06215431-d3f0-4e24-aa55-be8d98f50cb6

	measure 'Sale Markdown % LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown % Orders LY-1],
			        "Dispatch", [Sale Markdown % Dispatch LY-1],
			        [Sale Markdown % Orders LY-1]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		description: Two years ago equivalent of Sale Markdown % LY.
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Sale Markdown\LY-1
		lineageTag: 31ae3b22-0d18-4ed7-b35f-715e56096557

	measure 'Sale Markdown % vs LY' =
			VAR act = [Sale Markdown %]
			VAR comp = [Sale Markdown % LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\LY
		lineageTag: bd80f862-fb7a-4c68-b19c-c674099ee6ec

	measure 'Sale Markdown % vs LY-1' =
			VAR act = [Sale Markdown %]
			VAR comp = [Sale Markdown % LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Sale Markdown % vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\LY-1
		lineageTag: 1591be13-1533-4368-9165-1456464b2bab

	measure 'Sale Markdown vs LY %' =
			VAR act = [Sale Markdown]
			VAR comp = [Sale Markdown LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\LY
		lineageTag: 0b39fd01-74ef-424e-b838-b87d894f277b

	measure 'Sale Markdown LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown Orders LW],
			        "Dispatch", [Sale Markdown Dispatch LW],
			        [Sale Markdown Orders LW]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\LW
		lineageTag: 6d75c655-2cbf-4117-bd7f-cd80685b94aa

	measure 'Sale Markdown vs LW' =
			VAR act = [Sale Markdown]
			VAR comp = [Sale Markdown LW]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\LW
		lineageTag: c8a490dc-20c6-4005-938f-b3e5a7f12fce

	measure 'Sale Markdown % LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown % Orders LW],
			        "Dispatch", [Sale Markdown % Dispatch LW],
			        [Sale Markdown % Orders LW]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Sale Markdown\LW
		lineageTag: 4411f7ac-c91a-4f3d-9183-702eb60a69af

	measure 'Sale Markdown % vs LW' =
			VAR act = [Sale Markdown %]
			VAR comp = [Sale Markdown % LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\LW
		lineageTag: 644b052e-7b54-4aa5-ae3d-8f1d744d2a5b

	measure 'Sale Markdown vs LW %' =
			VAR act = [Sale Markdown]
			VAR comp = [Sale Markdown LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\LW
		lineageTag: 541a3903-eb79-4db9-b8e9-89d0e126dce5

	measure 'Sale Markdown BUD' = ```
			
			 VAR firstweek_yr = [SlctdBudVersion]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    [fiscalWeek] <  firstweek_yr,
			            [Sale Markdown],
			            [Sale Markdown Orders BUD]
			    )       )
			RETURN
			SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,SUMX ( salesTable, [Actualised] )) 
			 
			/*VAR result = [Sale Markdown Orders BUD]
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output*/
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\BUD
		lineageTag: 31673be6-c144-441b-bdfc-97840fa9dcfd

	measure 'Sale Markdown vs BUD' =
			VAR act = [Sale Markdown]
			VAR comp = [Sale Markdown BUD]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\BUD
		lineageTag: 094b8b57-a48f-4e78-8d6d-2cdde015d1fd

	measure 'Sale Markdown % BUD' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown % Orders BUD],
			        "Dispatch", [Sale Markdown % Dispatch BUD],
			        [Sale Markdown % Orders BUD]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Sale Markdown\BUD
		lineageTag: 16373158-dcdc-40c5-9faf-b9917174eec0

	measure 'Sale Markdown % vs BUD' =
			VAR act = [Sale Markdown %]
			VAR comp = [Sale Markdown % BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\BUD
		lineageTag: b4bfd2d2-1d56-426c-a859-e0e728694598

	measure 'Sale Markdown vs BUD %' =
			VAR act = [Sale Markdown]
			VAR comp = [Sale Markdown BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\BUD
		lineageTag: f41a1840-593c-45b3-a207-2c72ba94cc52

	measure 'Sale Markdown FC' =
			//SelectedWeeks
			VAR firstweek_qtr = [SlctdFirstWeekQtrFC]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [Sale Markdown],
			            [Sale Markdown Orders FC]
			    )       )
			RETURN
			SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,SUMX ( salesTable, [Actualised] ))
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\FC
		lineageTag: 7c09d12d-c5e1-4e36-9045-69820326983d

	measure 'Sale Markdown vs FC' =
			VAR act = [Sale Markdown]
			VAR comp = [Sale Markdown FC]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\FC
		lineageTag: 3a8f7ca1-cedc-4a13-bead-bcabc207a6ed

	measure 'Sale Markdown % FC' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown % Orders FC],
			        "Dispatch", [Sale Markdown % Dispatch FC],
			        [Sale Markdown % Orders FC]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Sale Markdown\FC
		lineageTag: 7c1951c8-9716-4251-baeb-c744e0401c5b

	measure 'Sale Markdown % vs FC' =
			VAR act = [Sale Markdown %]
			VAR comp = [Sale Markdown % FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\FC
		lineageTag: 54fc881a-dceb-4b79-94d8-053239c07cc1

	measure 'Sale Markdown vs FC %' =
			VAR act = [Sale Markdown]
			VAR comp = [Sale Markdown FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\FC
		lineageTag: 6e1cc7c9-1a9f-44a7-9525-3d58cc8efa7e

	measure 'Sale Markdown QRF' =
			//SelectedWeeks
			VAR firstweek_qtr = [SlctdFirstWeekQtrQRF]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [Sale Markdown],
			            [Sale Markdown Orders QRF]
			    )       )
			RETURN
			SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,SUMX ( salesTable, [Actualised] ))
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\QRF
		lineageTag: 8cd59a54-9080-4ae7-a7d9-66b3bbe5e08c

	measure 'Sale Markdown vs QRF' =
			VAR act = [Sale Markdown]
			VAR comp = [Sale Markdown QRF]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\QRF
		lineageTag: e8085ed6-48e5-4812-b4c8-8aa6421c0593

	measure 'Sale Markdown % QRF' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown % Orders QRF],
			        "Dispatch", [Sale Markdown % Dispatch QRF],
			        [Sale Markdown % Orders QRF]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Sale Markdown\QRF
		lineageTag: 38983291-f5f4-4726-8338-53ca1be4e780

	measure 'Sale Markdown % vs QRF' =
			VAR act = [Sale Markdown %]
			VAR comp = [Sale Markdown % QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\QRF
		lineageTag: 783cc8ce-cc22-4e1f-b01e-c5aedeba5918

	measure 'Sale Markdown vs QRF %' =
			VAR act = [Sale Markdown]
			VAR comp = [Sale Markdown QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\QRF
		lineageTag: 162ed95b-12fb-425d-a71d-55b21f161e86

	measure 'SIS Sold Through' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [SIS Sold Through Orders],
			        "Dispatch", [SIS Sold Through Dispatch],
			        [SIS Sold Through Orders]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\SIS Sold Through\Actual
		lineageTag: eba5ce29-85e1-4b24-b797-6962261f0480

	measure 'SIS Sold Through LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [SIS Sold Through Orders LY],
			        "Dispatch", [SIS Sold Through Dispatch LY],
			        [SIS Sold Through Orders LY]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\SIS Sold Through\LY
		lineageTag: 1cfcd8ac-b271-47ef-8744-9cb31c6fa1a2

	measure 'SIS Sold Through LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [SIS Sold Through Orders LY-1],
			        "Dispatch", [SIS Sold Through Dispatch LY-1],
			        [SIS Sold Through Orders LY-1]
			    )
			RETURN
			    result
		description: Two years ago equivalent of SIS Sold Through LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\SIS Sold Through\LY-1
		lineageTag: 095a5611-902e-462d-be6f-ae233a043a8b

	measure 'SIS Sold Through vs LY' =
			VAR act = [SIS Sold Through]
			VAR comp = [SIS Sold Through LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\SIS Sold Through\LY
		lineageTag: 8d5ffb84-cb9a-46f5-9f28-4095fae3965c

	measure 'SIS Sold Through vs LY-1' =
			VAR act = [SIS Sold Through]
			VAR comp = [SIS Sold Through LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of SIS Sold Through vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\SIS Sold Through\LY-1
		lineageTag: 4b07c97f-26d3-4e5d-9d84-00ec784aa6a7

	measure 'SIS Sold Through vs LY %' =
			VAR act = [SIS Sold Through]
			VAR comp = [SIS Sold Through LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\SIS Sold Through\LY
		lineageTag: 1f3c28d9-4012-4bb7-890f-0ac546c9c678

	measure 'SIS Sold Through LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [SIS Sold Through Orders LW],
			        "Dispatch", [SIS Sold Through Dispatch LW],
			        [SIS Sold Through Orders LW]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\SIS Sold Through\LW
		lineageTag: 04e6f135-03bb-4ada-b00f-6eaaf86f75e8

	measure 'SIS Sold Through vs LW' =
			VAR act = [SIS Sold Through]
			VAR comp = [SIS Sold Through LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\SIS Sold Through\LW
		lineageTag: 4e7f1247-053a-44e8-a807-297d25ff9566

	measure 'SIS Sold Through vs LW %' =
			VAR act = [SIS Sold Through]
			VAR comp = [SIS Sold Through LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\SIS Sold Through\LW
		lineageTag: 1cc2c73f-d9ba-431c-8133-73a80632ab34

	measure 'SIS Sold Through BUD' =
			
			VAR firstweek_yr = [SlctdBudVersion]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    [fiscalWeek] <  firstweek_yr,
			            [SIS Sold Through],
			            [SIS Sold Through Orders BUD]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
			
			/*VAR result = [SIS Sold Through Orders BUD]
			RETURN
			    result*/
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\SIS Sold Through\BUD
		lineageTag: b00052dd-6f53-4ee9-b414-fd9ed479b635

	measure 'SIS Sold Through vs BUD' =
			
			VAR act = [SIS Sold Through]
			VAR comp = [SIS Sold Through BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\SIS Sold Through\BUD
		lineageTag: 2f6ee6a1-088c-4555-9a2e-f618aeaed28d

	measure 'SIS Sold Through vs BUD %' =
			VAR act = [SIS Sold Through]
			VAR comp = [SIS Sold Through BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\SIS Sold Through\BUD
		lineageTag: 0541d565-1f96-47fd-99d9-db698d74e0e4

	measure 'SIS Sold Through FC' =
			//SelectedWeeks
			VAR firstweek_qtr = [SlctdFirstWeekQtrFC]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [SIS Sold Through],
			            [SIS Sold Through Orders FC]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\SIS Sold Through\FC
		lineageTag: 3f80d13f-5f8a-4a89-88a1-dfcfb4d9cb69

	measure 'SIS Sold Through vs FC' =
			VAR act = [SIS Sold Through]
			VAR comp = [SIS Sold Through FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\SIS Sold Through\FC
		lineageTag: d0529ade-af48-4ba0-b306-b80b55dd3996

	measure 'SIS Sold Through vs FC %' =
			VAR act = [SIS Sold Through]
			VAR comp = [SIS Sold Through FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\SIS Sold Through\FC
		lineageTag: c2a0265f-023f-498b-a9b8-0356c39b46b6

	measure 'SIS Sold Through QRF' =
			//SelectedWeeks
			VAR firstweek_qtr = [SlctdFirstWeekQtrQRF]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [SIS Sold Through],
			            [SIS Sold Through Orders QRF]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\SIS Sold Through\QRF
		lineageTag: 2385b930-7e17-4d6e-82d4-f09de3aaa797

	measure 'SIS Sold Through vs QRF' =
			VAR act = [SIS Sold Through]
			VAR comp = [SIS Sold Through QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\SIS Sold Through\QRF
		lineageTag: c2362a93-42f2-4703-9187-6370a06d5f09

	measure 'SIS Sold Through vs QRF %' =
			VAR act = [SIS Sold Through]
			VAR comp = [SIS Sold Through QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\SIS Sold Through\QRF
		lineageTag: 96807a6a-1793-4243-b156-a0e06b20ab6d

	measure 'Depth Of Cut' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Depth Of Cut Orders],
			        "Dispatch", [Depth Of Cut Dispatch],
			        [Depth Of Cut Orders]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Depth Of Cut\Actual
		lineageTag: 826b2cb5-3134-4571-8761-fa57da903171

	measure 'Depth Of Cut %' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Depth Of Cut % Orders],
			        "Dispatch", [Depth Of Cut % Dispatch],
			        [Depth Of Cut % Orders]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Depth Of Cut\Actual
		lineageTag: 2c51161d-0157-4fd2-a659-6f9880d75684

	measure 'Depth Of Cut LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Depth Of Cut Orders LY],
			        "Dispatch", [Depth Of Cut Dispatch LY],
			        [Depth Of Cut Orders LY]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Depth Of Cut\LY
		lineageTag: 38dfdb9d-31ec-45b4-836c-51f92a4c0b3b

	measure 'Depth Of Cut LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Depth Of Cut Orders LY-1],
			        "Dispatch", [Depth Of Cut Dispatch LY-1],
			        [Depth Of Cut Orders LY-1]
			    )
			RETURN
			    result
		description: Two years ago equivalent of Depth Of Cut LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Depth Of Cut\LY-1
		lineageTag: 8dd86473-b183-4067-a727-3176a942514f

	measure 'Depth Of Cut vs LY' =
			VAR act = [Depth Of Cut]
			VAR comp = [Depth Of Cut LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Depth Of Cut\LY
		lineageTag: b10dec9e-9000-4596-9d32-536f9f433349

	measure 'Depth Of Cut vs LY-1' =
			VAR act = [Depth Of Cut]
			VAR comp = [Depth Of Cut LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Depth Of Cut vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Depth Of Cut\LY-1
		lineageTag: 823bf888-3414-4c44-9c5f-461af0839612

	measure 'Depth Of Cut % LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Depth Of Cut % Orders LY],
			        "Dispatch", [Depth Of Cut % Dispatch LY],
			        [Depth Of Cut % Orders LY]
			    )
			RETURN
			    result
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Depth Of Cut\LY
		lineageTag: f71dfcb6-75c5-4d4f-869e-c3ad1912be72

	measure 'Depth Of Cut % LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Depth Of Cut % Orders LY-1],
			        "Dispatch", [Depth Of Cut % Dispatch LY-1],
			        [Depth Of Cut % Orders LY-1]
			    )
			RETURN
			    result
		description: Two years ago equivalent of Depth Of Cut % LY.
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Depth Of Cut\LY-1
		lineageTag: 831702b3-8723-4e5f-942f-19e24aedae0d

	measure 'Depth Of Cut % vs LY' =
			VAR act = [Depth Of Cut %]
			VAR comp = [Depth Of Cut % LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Depth Of Cut\LY
		lineageTag: 87f16fc5-9fde-4f11-82ea-2f8016d8cdd0

	measure 'Depth Of Cut % vs LY-1' =
			VAR act = [Depth Of Cut %]
			VAR comp = [Depth Of Cut % LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Depth Of Cut % vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Depth Of Cut\LY-1
		lineageTag: 7152bac6-56a5-4eee-8a52-9eb58cc0d102

	measure 'Depth Of Cut vs LY %' =
			VAR act = [Depth Of Cut]
			VAR comp = [Depth Of Cut LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Depth Of Cut\LY
		lineageTag: 9b3527c6-037e-4eab-bd8a-98967776cbbd

	measure 'Depth Of Cut LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Depth Of Cut Orders LW],
			        "Dispatch", [Depth Of Cut Dispatch LW],
			        [Depth Of Cut Orders LW]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Depth Of Cut\LW
		lineageTag: 5ffc3349-2380-4253-b4d7-b222363e4132

	measure 'Depth Of Cut vs LW' =
			VAR act = [Depth Of Cut]
			VAR comp = [Depth Of Cut LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Depth Of Cut\LW
		lineageTag: 67dc4a75-ae41-455c-b56a-cc2dea1e2242

	measure 'Depth Of Cut % LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Depth Of Cut % Orders LW],
			        "Dispatch", [Depth Of Cut % Dispatch LW],
			        [Depth Of Cut % Orders LW]
			    )
			RETURN
			    result
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Depth Of Cut\LW
		lineageTag: 267aef0e-7c37-40b2-9e96-e4a88de23a93

	measure 'Depth Of Cut % vs LW' =
			VAR act = [Depth Of Cut %]
			VAR comp = [Depth Of Cut % LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Depth Of Cut\LW
		lineageTag: 70bec181-7ab8-4fe3-9bdd-961e54dbbc69

	measure 'Depth Of Cut vs LW %' =
			VAR act = [Depth Of Cut]
			VAR comp = [Depth Of Cut LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Depth Of Cut\LW
		lineageTag: bb509ef0-112a-4df5-b7af-87922c63a8f1

	measure 'Depth Of Cut BUD' = ```
			
			VAR firstweek_yr = [SlctdBudVersion]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    [fiscalWeek] <  firstweek_yr,
			            [Depth Of Cut],
			            [Depth Of Cut Orders BUD]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] ) 
			 
			/*VAR result = [Depth Of Cut Orders BUD]
			RETURN
			    result*/
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Depth Of Cut\BUD
		lineageTag: a8330321-eb1f-458d-af4f-8f65ba45bbf7

	measure 'Depth Of Cut vs BUD' =
			VAR act = [Depth Of Cut]
			VAR comp = [Depth Of Cut BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Depth Of Cut\BUD
		lineageTag: 7305c736-0eb5-4532-91d9-9f07893f34f2

	measure 'Depth Of Cut % BUD' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Depth Of Cut % Orders FC],
			        "Dispatch", [Depth Of Cut % Dispatch BUD],
			        [Depth Of Cut % Orders FC]
			    )
			RETURN
			    result
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Depth Of Cut\BUD
		lineageTag: c05ae786-95fd-4d50-a25e-94b7d089c9ca

	measure 'Depth Of Cut % vs BUD' =
			VAR act = [Depth Of Cut %]
			VAR comp = [Depth Of Cut % BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Depth Of Cut\BUD
		lineageTag: a7bac6c3-4fb7-4f53-8c54-ab9d33032bbb

	measure 'Depth Of Cut vs BUD %' =
			VAR act = [Depth Of Cut]
			VAR comp = [Depth Of Cut BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Depth Of Cut\BUD
		lineageTag: 441f9bab-066b-4259-87de-77947788d57e

	measure 'Depth Of Cut FC' =
			//SelectedWeeks
			VAR firstweek_qtr = [SlctdFirstWeekQtrFC]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [Depth Of Cut],
			            [Depth Of Cut Orders FC]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Depth Of Cut\FC
		lineageTag: a4ca3c03-cd16-429a-90fe-8e10bcfbe9eb

	measure 'Depth Of Cut vs FC' =
			VAR act = [Depth Of Cut]
			VAR comp = [Depth Of Cut FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Depth Of Cut\FC
		lineageTag: 1fb4d4c0-0dbc-44bc-aa31-0f32d578b25c

	measure 'Depth Of Cut % FC' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Depth Of Cut % Orders FC],
			        "Dispatch", [Depth Of Cut % Dispatch FC],
			        [Depth Of Cut % Orders FC]
			    )
			RETURN
			    result
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Depth Of Cut\FC
		lineageTag: fddf779d-e0aa-478c-aedd-2c7f7b81f4c6

	measure 'Depth Of Cut % vs FC' =
			VAR act = [Depth Of Cut %]
			VAR comp = [Depth Of Cut % FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Depth Of Cut\FC
		lineageTag: dc5b83cd-7be8-4381-8aac-f93541b392e3

	measure 'Depth Of Cut vs FC %' =
			VAR act = [Depth Of Cut]
			VAR comp = [Depth Of Cut FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Depth Of Cut\FC
		lineageTag: fb55285b-706c-4a5b-9e97-63e068dd2c0c

	measure 'Depth Of Cut QRF' =
			//SelectedWeeks
			VAR firstweek_qtr = [SlctdFirstWeekQtrQRF]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [Depth Of Cut],
			            [Depth Of Cut Orders QRF]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Depth Of Cut\QRF
		lineageTag: d2e9a84d-ec1a-41b4-8b1d-57a4ed670b3e

	measure 'Depth Of Cut vs QRF' =
			VAR act = [Depth Of Cut]
			VAR comp = [Depth Of Cut QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Depth Of Cut\QRF
		lineageTag: ce60f9e4-1c1a-48e9-a928-cd33c97d1a1e

	measure 'Depth Of Cut % QRF' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Depth Of Cut % Orders QRF],
			        "Dispatch", [Depth Of Cut % Dispatch QRF],
			        [Depth Of Cut % Orders QRF]
			    )
			RETURN
			    result
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Depth Of Cut\QRF
		lineageTag: 9584a143-d005-4353-88f0-2fc80cb74ce5

	measure 'Depth Of Cut % vs QRF' =
			VAR act = [Depth Of Cut %]
			VAR comp = [Depth Of Cut % QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Depth Of Cut\QRF
		lineageTag: de96c325-731a-49b3-84cb-8456762610da

	measure 'Depth Of Cut vs QRF %' =
			VAR act = [Depth Of Cut]
			VAR comp = [Depth Of Cut QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Depth Of Cut\QRF
		lineageTag: 1f609a6e-4f69-4f58-a663-25a1a923c5bf

	measure 'Depth Of Cut % Orders' =
			VAR metric = [Depth Of Cut Orders]
			VAR sales = [SIS Sold Through Orders]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Depth Of Cut\Actual
		lineageTag: dffff4ec-359b-4f66-b88f-76c8e6888a15

	measure 'Depth Of Cut % Orders LY' =
			CALCULATE (
			    [Depth Of Cut % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Depth Of Cut\LY
		lineageTag: 966dac45-a6e4-4143-9c62-6e5a1e5511f9

	measure 'Depth Of Cut % Orders LY-1' =
			CALCULATE (
			    [Depth Of Cut % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Depth Of Cut % Orders LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Depth Of Cut\LY-1
		lineageTag: acaadc8c-1a2a-42a5-9517-a841685cc6de

	measure 'Depth Of Cut % Orders vs LY' =
			VAR act = [Depth Of Cut % Orders]
			VAR comp = [Depth Of Cut % Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Depth Of Cut\LY
		lineageTag: 5e289e81-fde0-4980-a7d2-b03de9a674b4

	measure 'Depth Of Cut % Orders vs LY-1' =
			VAR act = [Depth Of Cut % Orders]
			VAR comp = [Depth Of Cut % Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Depth Of Cut % Orders vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Depth Of Cut\LY-1
		lineageTag: 8e9ad3f9-096b-4ebf-83d5-02e554a63819

	measure 'Depth Of Cut % Orders LW' =
			CALCULATE (
			    [Depth Of Cut % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Depth Of Cut\LW
		lineageTag: 65778cc3-f50d-4a43-8e60-d3624628ee8d

	measure 'Depth Of Cut % Orders vs LW' =
			VAR act = [Depth Of Cut % Orders]
			VAR comp = [Depth Of Cut % Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Depth Of Cut\LW
		lineageTag: 9dac7908-1fe1-4726-894c-b4f277f82e83

	measure 'Depth Of Cut % Orders FC' =
			VAR metric = [Depth Of Cut Orders FC]
			VAR sales = [SIS Sold Through Orders FC]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Depth Of Cut\FC
		lineageTag: 3461af9b-811f-4914-8a47-354d81e0fe4b

	measure 'Depth Of Cut % Orders vs FC' =
			VAR act = [Depth Of Cut % Orders]
			VAR comp = [Depth Of Cut % Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Depth Of Cut\FC
		lineageTag: f6192826-7ffd-406d-885f-2721f46d4520

	measure 'Depth Of Cut % Orders BUD' =
			VAR metric = [Depth Of Cut Orders BUD]
			VAR sales = [SIS Sold Through Orders BUD]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Depth Of Cut\BUD
		lineageTag: 29818f66-f06c-47af-841f-912a34677dda

	measure 'Depth Of Cut % Orders vs BUD' =
			VAR act = [Depth Of Cut % Orders]
			VAR comp = [Depth Of Cut % Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Depth Of Cut\BUD
		lineageTag: 5ea67118-fc30-4610-a588-c807878dd66e

	measure 'Depth Of Cut % Orders QRF' =
			VAR metric = [Depth Of Cut Orders QRF]
			VAR sales = [SIS Sold Through Orders QRF]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Depth Of Cut\QRF
		lineageTag: 7365ead4-8d4d-4dd9-8f53-34b064e55d3f

	measure 'Depth Of Cut % Orders vs QRF' =
			VAR act = [Depth Of Cut % Orders]
			VAR comp = [Depth Of Cut % Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Depth Of Cut\QRF
		lineageTag: e2147cbd-6b4a-4872-be76-36ec9f37e48d

	measure 'Staff Discount & Loyalty' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Staff Discount & Loyalty Orders],
			        "Dispatch", [Staff Discount & Loyalty Dispatch],
			        [Staff Discount & Loyalty Orders]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Staff Discount & Loyalty\Actual
		lineageTag: d72bfbcc-140f-4851-ae74-9bc65f3fbd8f

	measure 'Staff Discount & Loyalty LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Staff Discount & Loyalty Orders LY],
			        "Dispatch", [Staff Discount & Loyalty Dispatch LY],
			        [Staff Discount & Loyalty Orders LY]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Staff Discount & Loyalty\LY
		lineageTag: 33995bbe-1fd3-46b2-a541-31b0bf1d31bc

	measure 'Staff Discount & Loyalty LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Staff Discount & Loyalty Orders LY-1],
			        "Dispatch", [Staff Discount & Loyalty Dispatch LY-1],
			        [Staff Discount & Loyalty Orders LY-1]
			    )
			RETURN
			    result
		description: Two years ago equivalent of Staff Discount & Loyalty LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Staff Discount & Loyalty\LY-1
		lineageTag: 5728019c-9648-4f16-85bd-e6f7e5234993

	measure 'Staff Discount & Loyalty vs LY' =
			VAR act = [Staff Discount & Loyalty]
			VAR comp = [Staff Discount & Loyalty LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Staff Discount & Loyalty\LY
		lineageTag: 014e69f6-9662-4c6f-a4da-1cf47d38f8a1

	measure 'Staff Discount & Loyalty vs LY-1' =
			VAR act = [Staff Discount & Loyalty]
			VAR comp = [Staff Discount & Loyalty LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Staff Discount & Loyalty vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Staff Discount & Loyalty\LY-1
		lineageTag: afbf65ac-3ee3-4822-b101-17845c408079

	measure 'Staff Discount & Loyalty vs LY %' =
			VAR act = [Staff Discount & Loyalty]
			VAR comp = [Staff Discount & Loyalty LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Staff Discount & Loyalty\LY
		lineageTag: 05a5d04e-148c-4712-80f4-74187c0e0682

	measure 'Staff Discount & Loyalty LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Staff Discount & Loyalty Orders LW],
			        "Dispatch", [Staff Discount & Loyalty Dispatch LW],
			        [Staff Discount & Loyalty Orders LW]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Staff Discount & Loyalty\LW
		lineageTag: 91cbf78e-ff84-4811-a0be-566c5ba52880

	measure 'Staff Discount & Loyalty vs LW' =
			VAR act = [Staff Discount & Loyalty]
			VAR comp = [Staff Discount & Loyalty LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Staff Discount & Loyalty\LW
		lineageTag: 745dc1a1-836a-4176-b38f-1a91d50b3b6b

	measure 'Staff Discount & Loyalty vs LW %' =
			VAR act = [Staff Discount & Loyalty]
			VAR comp = [Staff Discount & Loyalty LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Staff Discount & Loyalty\LW
		lineageTag: 46084a63-03f9-4365-8a10-bb8729d6696b

	measure 'Staff Discount & Loyalty BUD' =
			
			VAR firstweek_yr = [SlctdBudVersion]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    [fiscalWeek] <  firstweek_yr,
			
			            [Staff Discount & Loyalty],
			            [Staff Discount & Loyalty Orders BUD]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
			/*VAR result = [Staff Discount & Loyalty Orders BUD]
			RETURN
			    result*/
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Staff Discount & Loyalty\BUD
		lineageTag: ed2da936-961f-4566-9539-33e4cb39bdda

	measure 'Staff Discount & Loyalty vs BUD' =
			VAR act = [Staff Discount & Loyalty]
			VAR comp = [Staff Discount & Loyalty BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Staff Discount & Loyalty\BUD
		lineageTag: 3028cdcc-381e-414b-9108-3f9c39aa8205

	measure 'Staff Discount & Loyalty vs BUD %' =
			VAR act = [Staff Discount & Loyalty]
			VAR comp = [Staff Discount & Loyalty BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Staff Discount & Loyalty\BUD
		lineageTag: e602968e-9aff-43a7-8856-43ace9a41831

	measure 'Staff Discount & Loyalty FC' =
			//SelectedWeeks
			VAR firstweek_qtr = [SlctdFirstWeekQtrFC]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [Staff Discount & Loyalty],
			            [Staff Discount & Loyalty Orders FC]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Staff Discount & Loyalty\FC
		lineageTag: c5726e1e-1f36-4266-9de0-50315ddc0c12

	measure 'Staff Discount & Loyalty vs FC' =
			VAR act = [Staff Discount & Loyalty]
			VAR comp = [Staff Discount & Loyalty FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Staff Discount & Loyalty\FC
		lineageTag: 1d61eb86-1ca1-4ced-b985-47bde5b97146

	measure 'Staff Discount & Loyalty vs FC %' =
			VAR act = [Staff Discount & Loyalty]
			VAR comp = [Staff Discount & Loyalty FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Staff Discount & Loyalty\FC
		lineageTag: 094694bc-2626-45e5-abe8-365e01cefd8d

	measure 'Staff Discount & Loyalty QRF' =
			//SelectedWeeks
			VAR firstweek_qtr = [SlctdFirstWeekQtrQRF]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [Staff Discount & Loyalty],
			            [Staff Discount & Loyalty Orders QRF]
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Staff Discount & Loyalty\QRF
		lineageTag: 854cbc3e-1240-40f8-9205-92b4df3b9cc5

	measure 'Staff Discount & Loyalty vs QRF' =
			VAR act = [Staff Discount & Loyalty]
			VAR comp = [Staff Discount & Loyalty QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Staff Discount & Loyalty\QRF
		lineageTag: ca0f8090-741f-4654-ae8d-36afc754ce9f

	measure 'Staff Discount & Loyalty vs QRF %' =
			VAR act = [Staff Discount & Loyalty]
			VAR comp = [Staff Discount & Loyalty QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Staff Discount & Loyalty\QRF
		lineageTag: 5e8704c9-7f79-4e02-9f5b-91fff2c3711f

	measure 'Other GSM Adj' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", BLANK (),
			        "Dispatch", [Other GSM Adj Dispatch],
			        BLANK ()
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Other GSM Adj\Actual
		lineageTag: 38552b2e-b1e6-4b26-8e4f-318ab09f0787

	measure 'Other GSM Adj LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", BLANK (),
			        "Dispatch", [Other GSM Adj Dispatch LY],
			        BLANK ()
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Other GSM Adj\LY
		lineageTag: 20dd73ea-d80e-4b65-8ac6-dbcb0c58da7c

	measure 'Other GSM Adj LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", BLANK (),
			        "Dispatch", [Other GSM Adj Dispatch LY-1],
			        BLANK ()
			    )
			RETURN
			    result
		description: Two years ago equivalent of Other GSM Adj LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Other GSM Adj\LY-1
		lineageTag: 1673f32f-f82c-41fb-9abc-401ffa94b08e

	measure 'Other GSM Adj vs LY' =
			VAR act = [Other GSM Adj]
			VAR comp = [Other GSM Adj LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Other GSM Adj\LY
		lineageTag: 5c32e78e-2ff0-4bd8-89e1-b434c869f836

	measure 'Other GSM Adj vs LY-1' =
			VAR act = [Other GSM Adj]
			VAR comp = [Other GSM Adj LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Other GSM Adj vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Other GSM Adj\LY-1
		lineageTag: b0e3fe2a-a103-4d0a-b1c0-f72cdd806cbf

	measure 'Other GSM Adj vs LY %' =
			VAR act = [Other GSM Adj]
			VAR comp = [Other GSM Adj LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Other GSM Adj\LY
		lineageTag: 5db8ba25-578f-44dc-a596-cd2bb1ae7d98

	measure 'Other GSM Adj LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", BLANK (),
			        "Dispatch", [Other GSM Adj Dispatch LW],
			        BLANK ()
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Other GSM Adj\LW
		lineageTag: 73937a3d-b39d-48fd-a418-1c30edbdcfb6

	measure 'Other GSM Adj vs LW' =
			VAR act = [Other GSM Adj]
			VAR comp = [Other GSM Adj LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Other GSM Adj\LW
		lineageTag: 5b413267-a6fa-46a6-bbf3-ad2b302053c1

	measure 'Other GSM Adj vs LW %' =
			VAR act = [Other GSM Adj]
			VAR comp = [Other GSM Adj LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Other GSM Adj\LW
		lineageTag: 24c24e3b-7419-48c3-a114-3458ccfe8949

	measure 'Other GSM Adj BUD' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR firstweek_yr = [SlctdBudVersion]
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			 IF ([fiscalWeek] <  firstweek_yr,[Other GSM Adj],
			    SWITCH (
			        recog_type,
			        "Order", BLANK (),
			        "Dispatch", [Other GSM Adj Dispatch BUD],
			        BLANK ()
			    )))
			RETURN
			  SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Other GSM Adj\BUD
		lineageTag: 24fce31e-cb25-4975-a0ca-d7d46f678581

	measure 'Other GSM Adj vs BUD' =
			VAR act = [Other GSM Adj]
			VAR comp = [Other GSM Adj BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Other GSM Adj\BUD
		lineageTag: eff09ca1-b717-4e5f-bbf0-922f0a8ca072

	measure 'Other GSM Adj vs BUD %' =
			VAR act = [Other GSM Adj]
			VAR comp = [Other GSM Adj BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Other GSM Adj\BUD
		lineageTag: b1fc5ff9-4b7d-4ad1-9bbc-c9475145fc4e

	measure 'Other GSM Adj FC' =
			//SelectedWeeks
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR firstweek_qtr = [SlctdFirstWeekQtrFC]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [Other GSM Adj],
			            SWITCH (recog_type, "Order", Blank(), "Dispatch", [Other GSM Adj Dispatch FC], Blank())
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Other GSM Adj\FC
		lineageTag: bccad9cf-094d-4ab0-8e74-c6a92aa30e4c

	measure 'Other GSM Adj vs FC' =
			VAR act = [Other GSM Adj]
			VAR comp = [Other GSM Adj FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Other GSM Adj\FC
		lineageTag: 5ccefa95-d04f-4ffa-88ac-e2f9faf0e1f8

	measure 'Other GSM Adj vs FC %' =
			VAR act = [Other GSM Adj]
			VAR comp = [Other GSM Adj FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Other GSM Adj\FC
		lineageTag: 49b9ac16-57b4-44f6-9df4-8ac2aaf164da

	measure 'Other GSM Adj QRF' =
			//SelectedWeeks
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR firstweek_qtr = [SlctdFirstWeekQtrQRF]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [Other GSM Adj],
			            SWITCH (recog_type, "Order", Blank(), "Dispatch", [Other GSM Adj Dispatch QRF], Blank())
			    )       )
			RETURN
			    SUMX ( salesTable, [Actualised] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Other GSM Adj\QRF
		lineageTag: bfb686cf-0e73-4189-9072-00490c3f1028

	measure 'Other GSM Adj vs QRF' =
			VAR act = [Other GSM Adj]
			VAR comp = [Other GSM Adj QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Other GSM Adj\QRF
		lineageTag: 12f1141d-825a-4f94-8b20-1b036e36e432

	measure 'Other GSM Adj vs QRF %' =
			VAR act = [Other GSM Adj]
			VAR comp = [Other GSM Adj QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Other GSM Adj\QRF
		lineageTag: 2c9b3a24-d5f1-45b2-a18a-c19376d5fcad

	measure 'P&L vs LY %' =
			VAR act = [P&L]
			VAR comp = [P&L LY]
			VAR metric = [slctd_MetricMasterPnL]
			VAR divide_result =
			    DIVIDE ( act - comp, comp )
			VAR subtract_result = act - comp
			VAR adj_result =
			    IF ( CONTAINSSTRING ( metric, "%" ), subtract_result * 1, divide_result )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), adj_result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: P&L\LY
		lineageTag: dcb923ef-7f65-48f2-9f30-3ee29be9fd90

	measure 'P&L LW' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR sale_recog = [slctd_SalesRecognitionType]
			VAR is_channel_unfiltered = [is_channel_unfiltered]
			VAR is_channel_available =
			    SELECTEDVALUE ( MetricMasterPnL[ActOrdersChannelAvailable] )
			VAR result =
			    SWITCH (
			        metric,
			        "Sales Revenue (Inc VAT)", [SRIV LW],
			        "Sales Revenue (Exc VAT)", [SREV LW],
			        "Discount Participation %", [Discount Participation % LW],
			        "Promo Mix %", [Promo Mix % LW],
			        "FPP Mix %", [FPP Mix % LW],
			        "Reduced Mix %", [Reduced Mix % LW],
			        "Returns", [Returns LW],
			        "Returns %", [Return rate % LW],
			        "Buying Margin %", [Buying Margin % LW],
			        "Markdown", [Markdown LW],
			        "Markdown %", [Markdown % SRIV LW],
			        "POS", [Promo Markdown LW],
			        "POS %", [Promo Markdown % LW],
			        "Sale Markdown", [Sale Markdown LW],
			        "Sale Markdown %", [Sale Markdown % LW],
			        "SIS Sold Through", [SIS Sold Through LW],
			        "Staff Discount & Loyalty", [Staff Discount & Loyalty LW],
			        "Depth Of Cut", [Depth Of Cut LW],
			        "Depth Of Cut %", [Depth Of Cut % LW],
			        "Other GSM Adj", [Other GSM Adj LW],
			        "GSM", [GSM LW],
			        "GSM %", [GSM % SREV LW],
			        BLANK ()
			    )
			RETURN
			    IF (
			        is_channel_unfiltered,
			        result,
			        IF ( is_channel_available, result, BLANK () )
			    )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: P&L\LW
		lineageTag: e76f70eb-cbe6-423f-b9ee-1e2c990ee35c

	measure 'P&L vs LW' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR act = [P&L]
			VAR comp = [P&L LW]
			VAR result = act - comp
			VAR adj_result =
			    IF ( CONTAINSSTRING ( metric, "%" ), result * 1, result )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), adj_result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: P&L\LW
		lineageTag: ab9216f0-110b-4aea-84ae-aa9f2326379d

	measure 'P&L vs LW %' =
			VAR act = [P&L]
			VAR comp = [P&L LW]
			VAR metric = [slctd_MetricMasterPnL]
			VAR divide_result =
			    DIVIDE ( act - comp, comp )
			VAR subtract_result = act - comp
			VAR adj_result =
			    IF ( CONTAINSSTRING ( metric, "%" ), subtract_result * 1, divide_result )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), adj_result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: P&L\LW
		lineageTag: 70d86277-cae3-4070-a933-f866eeccbcf4

	measure 'P&L BUD' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR sale_recog = [slctd_SalesRecognitionType]
			VAR is_channel_unfiltered = [is_channel_unfiltered]
			VAR is_channel_available =
			    SELECTEDVALUE ( MetricMasterPnL[ActOrdersChannelAvailable] )
			VAR result =
			    SWITCH (
			        metric,
			        "Sales Revenue (Inc VAT)", [SRIV BUD],
			        "Sales Revenue (Exc VAT)", [SREV BUD],
			        "Discount Participation %", BLANK (),
			        "Promo Mix %", BLANK (),
			        "FPP Mix %", BLANK (),
			        "Reduced Mix %", BLANK (),
			        "Returns", BLANK (),
			        "Returns %", BLANK (),
			        "Buying Margin %", [Buying Margin % BUD],
			        "Markdown", [Markdown BUD],
			        "Markdown %", [Markdown % SRIV BUD],
			        "POS", [Promo Markdown BUD],
			        "POS %", [Promo Markdown % BUD],
			        "Sale Markdown", [Sale Markdown BUD],
			        "Sale Markdown %", [Sale Markdown % BUD],
			        "SIS Sold Through", [SIS Sold Through BUD],
			        "Staff Discount & Loyalty", [Staff Discount & Loyalty BUD],
			        "Depth Of Cut", [Depth Of Cut BUD],
			        "Depth Of Cut %", [Depth Of Cut % BUD],
			        "Other GSM Adj", [Other GSM Adj BUD],
			        "GSM", [GSM BUD],
			        "GSM %", [GSM % SREV BUD],
			        BLANK ()
			    )
			RETURN
			    IF (
			        is_channel_unfiltered,
			        result,
			        IF ( is_channel_available, result, BLANK () )
			    )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: P&L\BUD
		lineageTag: ca4147a0-0372-4035-88ef-8d303aed51af

	measure 'P&L vs BUD' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR act = [P&L]
			VAR comp = [P&L BUD]
			VAR result = act - comp
			VAR adj_result =
			    IF ( CONTAINSSTRING ( metric, "%" ), result * 1, result )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), adj_result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: P&L\BUD
		lineageTag: e2884d3f-2d22-4b76-b4f4-3eb724b656ca

	measure 'P&L vs BUD %' =
			VAR act = [P&L]
			VAR comp = [P&L BUD]
			VAR metric = [slctd_MetricMasterPnL]
			VAR divide_result =
			    DIVIDE ( act - comp, comp )
			VAR subtract_result = act - comp
			VAR adj_result =
			    IF ( CONTAINSSTRING ( metric, "%" ), subtract_result * 1, divide_result )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), adj_result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: P&L\BUD
		lineageTag: 15e1ff5a-3aa2-4f12-8d23-493d532925f2

	measure 'P&L FC' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR sale_recog = [slctd_SalesRecognitionType]
			VAR is_channel_unfiltered = [is_channel_unfiltered]
			VAR is_channel_available =
			    SELECTEDVALUE ( MetricMasterPnL[ActOrdersChannelAvailable] )
			VAR result =
			    SWITCH (
			        metric,
			        "Sales Revenue (Inc VAT)", [SRIV FC],
			        "Sales Revenue (Exc VAT)", [SREV FC],
			        "Discount Participation %", BLANK (),
			        "Promo Mix %", BLANK (),
			        "FPP Mix %", BLANK (),
			        "Reduced Mix %", BLANK (),
			        "Returns", BLANK (),
			        "Returns %", BLANK (),
			        "Buying Margin %", [Buying Margin % FC],
			        "Markdown", [Markdown FC],
			        "Markdown %", [Markdown % SRIV FC],
			        "POS", [Promo Markdown FC],
			        "POS %", [Promo Markdown % FC],
			        "Sale Markdown", [Sale Markdown FC],
			        "Sale Markdown %", [Sale Markdown % FC],
			        "SIS Sold Through", [SIS Sold Through FC],
			        "Staff Discount & Loyalty", [Staff Discount & Loyalty FC],
			        "Depth Of Cut", [Depth Of Cut FC],
			        "Depth Of Cut %", [Depth Of Cut % FC],
			        "Other GSM Adj", [Other GSM Adj FC],
			        "GSM", [GSM FC],
			        "GSM %", [GSM % SREV FC],
			        BLANK ()
			    )
			RETURN
			    IF (
			        is_channel_unfiltered,
			        result,
			        IF ( is_channel_available, result, BLANK () )
			    )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: P&L\FC
		lineageTag: 79903c67-a253-4d54-a263-3d39d8e7062e

	measure 'P&L vs FC' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR act = [P&L]
			VAR comp = [P&L FC]
			VAR result = act - comp
			VAR adj_result =
			    IF ( CONTAINSSTRING ( metric, "%" ), result * 1, result )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), adj_result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: P&L\FC
		lineageTag: c983355a-8c1c-43ed-a218-848248d6bf8f

	measure 'P&L vs FC %' =
			VAR act = [P&L]
			VAR comp = [P&L FC]
			VAR metric = [slctd_MetricMasterPnL]
			VAR divide_result =
			    DIVIDE ( act - comp, comp )
			VAR subtract_result = act - comp
			VAR adj_result =
			    IF ( CONTAINSSTRING ( metric, "%" ), subtract_result * 1, divide_result )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), adj_result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: P&L\FC
		lineageTag: 3bd9e516-d0b1-4e1e-a87c-3e3c373e0eec

	measure 'P&L QRF' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR sale_recog = [slctd_SalesRecognitionType]
			VAR is_channel_unfiltered = [is_channel_unfiltered]
			VAR is_channel_available =
			    SELECTEDVALUE ( MetricMasterPnL[ActOrdersChannelAvailable] )
			VAR result =
			    SWITCH (
			        metric,
			        "Sales Revenue (Inc VAT)", [SRIV QRF],
			        "Sales Revenue (Exc VAT)", [SREV QRF],
			        "Discount Participation %", BLANK (),
			        "Promo Mix %", BLANK (),
			        "FPP Mix %", BLANK (),
			        "Reduced Mix %", BLANK (),
			        "Returns", BLANK (),
			        "Returns %", BLANK (),
			        "Buying Margin %", [Buying Margin % QRF],
			        "Markdown", [Markdown QRF],
			        "Markdown %", [Markdown % SRIV QRF],
			        "POS", [Promo Markdown QRF],
			        "POS %", [Promo Markdown % QRF],
			        "Sale Markdown", [Sale Markdown QRF],
			        "Sale Markdown %", [Sale Markdown % QRF],
			        "SIS Sold Through", [SIS Sold Through QRF],
			        "Staff Discount & Loyalty", [Staff Discount & Loyalty QRF],
			        "Depth Of Cut", [Depth Of Cut QRF],
			        "Depth Of Cut %", [Depth Of Cut % QRF],
			        "Other GSM Adj", [Other GSM Adj QRF],
			        "GSM", [GSM QRF],
			        "GSM %", [GSM % SREV QRF],
			        BLANK ()
			    )
			RETURN
			    IF (
			        is_channel_unfiltered,
			        result,
			        IF ( is_channel_available, result, BLANK () )
			    )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: P&L\QRF
		lineageTag: 7618dd35-405b-4e22-8f4a-4c812500fcc1

	measure 'P&L vs QRF' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR act = [P&L]
			VAR comp = [P&L QRF]
			VAR result = act - comp
			VAR adj_result =
			    IF ( CONTAINSSTRING ( metric, "%" ), result * 1, result )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), adj_result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: P&L\QRF
		lineageTag: a58d35ab-4471-4dcb-88eb-ec1ab9c9aaf3

	measure 'P&L vs QRF %' =
			VAR act = [P&L]
			VAR comp = [P&L QRF]
			VAR metric = [slctd_MetricMasterPnL]
			VAR divide_result =
			    DIVIDE ( act - comp, comp )
			VAR subtract_result = act - comp
			VAR adj_result =
			    IF ( CONTAINSSTRING ( metric, "%" ), subtract_result * 1, divide_result )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), adj_result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: P&L\QRF
		lineageTag: 1ba0a2d9-d02c-46a0-ad5c-c4c0e70a06f5

	measure 'SRIV Fwd View vs LY' =
			VAR act = [SRIV Fwd View]
			VAR comp = [SRIV LY]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV Fwd View\LY
		lineageTag: 54a39f5a-4015-450f-b2ab-afe43d2c6577

	measure 'SRIV Fwd View vs LY-1' =
			VAR act = [SRIV Fwd View]
			VAR comp = [SRIV LY-1]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		description: Two years ago equivalent of SRIV Fwd View vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV Fwd View\LY-1
		lineageTag: 7ab1b859-9f06-4427-bd71-cd8ff349a8a1

	measure 'SRIV Fwd View vs LY %' =
			VAR act = [SRIV Fwd View]
			VAR comp = [SRIV LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV Fwd View\LY
		lineageTag: 10a73ba3-afbd-4697-ad24-74a1fa78660e

	measure 'SRIV Fwd View vs FC' =
			VAR act = [SRIV Fwd View]
			VAR comp = [SRIV Channel FC]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV Fwd View\FC
		lineageTag: c4171bda-e93c-41bf-99f7-e0052f4d0b75

	measure 'SRIV Fwd View vs FC %' =
			VAR act = [SRIV Fwd View]
			VAR comp = [SRIV Channel FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV Fwd View\FC
		lineageTag: e4740259-56f2-422e-afc1-37e23dbeaf0b

	measure 'SRIV Fwd View vs LW' =
			VAR act = [SRIV Fwd View]
			VAR comp = [SRIV Fwd View LW]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV Fwd View\LW
		lineageTag: aea6e3b1-86a9-43b0-93de-b808f05adacd

	measure 'SRIV Fwd View vs LW %' =
			VAR act = [SRIV Fwd View]
			VAR comp = [SRIV Fwd View LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV Fwd View\LW
		lineageTag: 8fbf4318-0a85-4f1d-ae52-bbfa3cb1f57c

	measure 'SRIV Fwd View vs BUD' =
			VAR act = [SRIV Fwd View]
			VAR comp = [SRIV Channel BUD]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV Fwd View\BUD
		lineageTag: a1553ac3-ca74-4f00-814b-c316f96a3029

	measure 'SRIV Fwd View vs BUD %' =
			VAR act = [SRIV Fwd View]
			VAR comp = [SRIV Channel BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV Fwd View\BUD
		lineageTag: 40e538be-af27-4d05-84f7-70810bb638d1

	measure 'SRIV Fwd View vs QRF' =
			VAR act = [SRIV Fwd View]
			VAR comp = [SRIV Channel QRF]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV Fwd View\QRF
		lineageTag: bd52ac71-47c4-4af5-b858-574ef58e9c75

	measure 'SRIV Fwd View vs QRF %' =
			VAR act = [SRIV Fwd View]
			VAR comp = [SRIV Channel QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV Fwd View\QRF
		lineageTag: 8732e2bc-31f5-4b98-ad34-f005a13b597e

	measure 'SRIV Fwd View LW' =
			
			VAR latest_actuals = [LatestSalesFiscalWeek]
			RETURN
			    CALCULATE (
			        [SRIV Fwd View for LW],
			        USERELATIONSHIP (factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek]),
			        USERELATIONSHIP (factDispatchForecast[FISCAL_WEEK], 'Calendar'[fiscalWeekLastWeek]),
			        USERELATIONSHIP (factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek]),
			        USERELATIONSHIP (factForecast[fiscalWeek], 'Calendar'[fiscalWeekLastWeek]),
			        USERELATIONSHIP (factSRIVOrdersChannelForecast[fiscalWeek], 'Calendar'[fiscalWeekLastWeek])
			    )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV Fwd View\LW
		lineageTag: ca181bb9-4dcf-452b-bff9-b3e5b0cee61e

	/// This measure is the sum of column 'factSalesOrders'[gsriv]
	measure 'GSRIV Orders' = SUM ( 'factSalesOrders'[gsriv] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\GSRIV\Actual
		lineageTag: 5056a921-2833-4441-b117-f783cb5c9d97

	measure 'GSRIV Orders LY' =
			CALCULATE (
			    [GSRIV Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\GSRIV\LY
		lineageTag: d6081398-532b-4f41-accf-7e992dd15c77

	measure 'GSRIV Orders LY-1' =
			CALCULATE (
			    [GSRIV Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of GSRIV Orders LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\GSRIV\LY-1
		lineageTag: 28a0a0ac-0765-41a3-bc85-bfa326c0c5a8

	measure 'GSRIV Orders vs LY' =
			VAR act = [GSRIV Orders]
			VAR comp = [GSRIV Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\GSRIV\LY
		lineageTag: 5dc0637d-eb95-4310-8235-bb6a4cf8eddc

	measure 'GSRIV Orders vs LY-1' =
			VAR act = [GSRIV Orders]
			VAR comp = [GSRIV Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of GSRIV Orders vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\GSRIV\LY-1
		lineageTag: 9bdcebe2-69ec-4f7d-8681-13e0cd382d58

	measure 'GSRIV Orders vs LY %' =
			VAR act = [GSRIV Orders]
			VAR comp = [GSRIV Orders LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\GSRIV\LY
		lineageTag: 3f9cf743-fd6a-4f3b-b809-4430005e92f5

	measure 'GSRIV Orders LW' =
			CALCULATE (
			    [GSRIV Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\GSRIV\LW
		lineageTag: 4f4f9b4a-d4ab-4cd3-b09f-e7ac2ea81310

	measure 'GSRIV Orders vs LW' =
			VAR act = [GSRIV Orders]
			VAR comp = [GSRIV Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\GSRIV\LW
		lineageTag: 86199d2d-278f-4593-80e8-77335977cdd1

	measure 'GSRIV Orders vs LW %' =
			VAR act = [GSRIV Orders]
			VAR comp = [GSRIV Orders LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\GSRIV\LW
		lineageTag: 06035eb2-473d-44a4-b008-91b7986f42a9

	measure Visits =
			VAR channel =
			    SELECTEDVALUE ( Channels[Channel] )
			VAR result =
			    SWITCH (
			        channel,
			        "Stores", [sum_footfall],
			        "Online", [Traffic],
			        BLANK ()
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Visits\Actual
		lineageTag: 97b6b3ca-7ce5-4020-b32c-0e179d30c9b3

	measure 'Visits LY' =
			VAR store =
			    CALCULATE (
			        [sum_footfall],
			        USERELATIONSHIP ( factFootfall[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			    )
			VAR channel =
			    SELECTEDVALUE ( Channels[Channel] )
			VAR result =
			    SWITCH ( channel, "Stores", store, "Online", [Traffic LY], BLANK () )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Visits\LY
		lineageTag: abefbb9b-562a-41fb-baf5-06078683162e

	measure 'Visits LY-1' =
			VAR store =
			    CALCULATE (
			        [sum_footfall],
			        USERELATIONSHIP ( factFootfall[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			    )
			VAR channel =
			    SELECTEDVALUE ( Channels[Channel] )
			VAR result =
			    SWITCH ( channel, "Stores", store, "Online", [Traffic LY-1], BLANK () )
			RETURN
			    result
		description: Two years ago equivalent of Visits LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Visits\LY-1
		lineageTag: 82ec8aae-09ce-460d-9cee-321d794839b9

	measure 'Visits vs LY' =
			VAR act = [Visits]
			VAR comp = [Visits LY]
			VAR result = act - comp
			RETURN result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Visits\LY
		lineageTag: bca8d004-d7da-4e44-b99d-afcef2f0bc30

	measure 'Visits vs LY-1' =
			VAR act = [Visits]
			VAR comp = [Visits LY-1]
			VAR result = act - comp
			RETURN result
		description: Two years ago equivalent of Visits vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Visits\LY-1
		lineageTag: f300b81d-253c-4824-962f-c47f077c79b2

	measure 'Visits vs LY %' = ```
			VAR act = [Visits]
			VAR comp = [Visits LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
			    
			```
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\Visits\LY
		lineageTag: 147d997d-57a3-4a1d-a3c1-bc3c49e1c365

	measure 'Visits LW' =
			VAR store =
			    CALCULATE (
			        [sum_footfall],
			        USERELATIONSHIP ( factFootfall[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			    )
			VAR channel =
			    SELECTEDVALUE ( Channels[Channel] )
			VAR result =
			    SWITCH ( channel, "Stores", store, "Online", [Traffic LW], BLANK () )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Visits\LW
		lineageTag: dd1eab84-92fa-444e-a084-6668e99cfc4c

	measure 'Visits vs LW' =
			VAR act = [Visits]
			VAR comp = [Visits LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Visits\LW
		lineageTag: 2dbb32b8-f3f3-4bc7-b8bf-b1c53b5995a4

	measure 'Visits vs LW %' =
			VAR act = [Visits]
			VAR comp = [Visits LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\Visits\LW
		lineageTag: 2fb56f1b-5c60-4962-8721-80e327e5a520

	measure 'Conversion %' =
			
			VAR metric = CALCULATE(SUM(factAdobe[ordersL2]),factAdobe[visitType] = 2)
			VAR denom = CALCULATE(SUM(factAdobe[visitsUnadjusted]),factAdobe[visitType] = 2)
			VAR result =
			    DIVIDE ( metric, denom )
			RETURN
			    IF ( OR ( metric = BLANK (), denom = BLANK () ), BLANK (), result )
			
			/*VAR metric = [Transactions]
			VAR denom = [Visits]
			VAR result =
			    DIVIDE ( metric, denom )
			RETURN
			    IF ( OR ( metric = BLANK (), denom = BLANK () ), BLANK (), result )*/
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\Conversion\Actual
		lineageTag: ed8f543d-762d-458d-9a4c-ddf888211c8e

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Conversion % LY' =
			
			VAR metric = CALCULATE(SUM(factAdobe[ordersL2]),factAdobe[visitType] = 2,USERELATIONSHIP(factAdobe[fiscalWeek],'Calendar'[fiscalWeekLastYear]))
			VAR denom = CALCULATE(SUM(factAdobe[visitsUnadjusted]),factAdobe[visitType] = 2,USERELATIONSHIP(factAdobe[fiscalWeek],'Calendar'[fiscalWeekLastYear]))
			VAR result =
			DIVIDE ( metric, denom )
			RETURN
			    IF ( OR ( metric = BLANK (), denom = BLANK () ), BLANK (), result )
			
			/*VAR metric = [Transactions LY]
			VAR denom = [Visits LY]
			VAR result =
			    DIVIDE ( metric, denom )
			RETURN
			    IF ( OR ( metric = BLANK (), denom = BLANK () ), BLANK (), result )*/
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\Conversion\LY
		lineageTag: c9686d4c-7c1d-44f7-8f78-81534188c4fa

	measure 'Conversion % LY-1' =
			
			VAR metric = CALCULATE(SUM(factAdobe[ordersL2]),factAdobe[visitType] = 2,USERELATIONSHIP(factAdobe[fiscalWeek],'Calendar'[fiscalWeekLastToLastyear]))
			VAR denom = CALCULATE(SUM(factAdobe[visitsUnadjusted]),factAdobe[visitType] = 2,USERELATIONSHIP(factAdobe[fiscalWeek],'Calendar'[fiscalWeekLastToLastyear]))
			VAR result =
			DIVIDE ( metric, denom )
			RETURN
			    IF ( OR ( metric = BLANK (), denom = BLANK () ), BLANK (), result )
			
			/*VAR metric = [Transactions LY-1]
			VAR denom = [Visits LY-1]
			VAR result =
			    DIVIDE ( metric, denom )
			RETURN
			    IF ( OR ( metric = BLANK (), denom = BLANK () ), BLANK (), result )*/
		description: Two years ago equivalent of Conversion % LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\Conversion\LY-1
		lineageTag: dd3d8d40-740e-4808-a1fa-bd2deecd8d24

	measure 'Conversion % vs LY' =
			VAR act = [Conversion %]
			VAR comp = [Conversion % LY]
			VAR result = FORMAT((act - comp)* 100, "#,##0.0ppt;(#,##0.0)ppt")
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\Conversion\LY
		lineageTag: 97129912-8ae6-4eef-b723-9c9114d5b818

	measure 'Conversion % vs LY-1' =
			VAR act = [Conversion %]
			VAR comp = [Conversion % LY-1]
			VAR result = FORMAT((act - comp)* 100, "#,##0.0ppt;(#,##0.0)ppt")
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Conversion % vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\Conversion\LY-1
		lineageTag: 9a7e8ff7-d313-4681-867c-48b3f0efc2a9

	measure 'Conversion % LW' =
			
			VAR metric = CALCULATE(SUM(factAdobe[ordersL2]),factAdobe[visitType] = 2,USERELATIONSHIP(factAdobe[fiscalWeek],'Calendar'[fiscalWeekLastWeek]))
			VAR denom = CALCULATE(SUM(factAdobe[visitsUnadjusted]),factAdobe[visitType] = 2,USERELATIONSHIP(factAdobe[fiscalWeek],'Calendar'[fiscalWeekLastWeek]))
			VAR result =
			    DIVIDE ( metric, denom )
			RETURN
			    IF ( OR ( metric = BLANK (), denom = BLANK () ), BLANK (), result )
			
			/*VAR metric = [Transactions LW]
			VAR denom = [Visits LW]
			VAR result =
			    DIVIDE ( metric, denom )
			RETURN
			    IF ( OR ( metric = BLANK (), denom = BLANK () ), BLANK (), result )*/
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\Conversion\LW
		lineageTag: c7f0673e-792c-4f50-848b-593416e7b9e9

	measure 'Conversion % vs LW' =
			VAR act = [Conversion %]
			VAR comp = [Conversion % LW]
			VAR result = FORMAT((act - comp)* 100, "#,##0.0ppt;(#,##0.0)ppt")
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\Conversion\LW
		lineageTag: 1169cc8d-50e4-4584-b570-244a78a0d751

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'FPP Intake Volume LW' =
			CALCULATE (
			    [FPP Intake Volume],
			    USERELATIONSHIP ( factForecast[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\LW
		lineageTag: 14c5cf59-fbfc-469b-b7d0-7d60c9979a75

	measure 'FPP Intake Volume vs LW' =
			VAR act = [FPP Intake Volume]
			VAR comp = [FPP Intake Volume LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\LW
		lineageTag: 409392f4-09b1-43b9-a642-215fe5b35055

	measure 'FPP Intake Volume' = CALCULATE ( [sum_fpp_rev_intake_units], factForecast[plan] = "RF" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\Actual
		lineageTag: bd189335-6435-456b-9f12-db3c50cdc0ca

	measure 'FPP Intake Volume LY' =
			CALCULATE (
			    [FPP Intake Volume],
			    USERELATIONSHIP ( factForecast[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\LY
		lineageTag: 801ffd80-5a50-4eb3-a3e3-6cd299c1b4f6

	measure 'FPP Intake Volume LY-1' =
			CALCULATE (
			    [FPP Intake Volume],
			    USERELATIONSHIP ( factForecast[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of FPP Intake Volume LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\LY-1
		lineageTag: a008d795-51a7-4fc5-bc2d-3bff95019122

	measure 'FPP Intake Volume vs LY' =
			VAR act = [FPP Intake Volume]
			VAR comp = [FPP Intake Volume LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\LY
		lineageTag: 1ac616a0-1b4a-4267-9564-640cd1095f82

	measure 'FPP Intake Volume vs LY-1' =
			VAR act = [FPP Intake Volume]
			VAR comp = [FPP Intake Volume LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of FPP Intake Volume vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\LY-1
		lineageTag: 1a63b691-423a-448b-9fe6-331ef771c142

	measure 'FPP Intake Volume BUD' =
			CALCULATE (
			    [sum_fpp_rev_intake_units],
			    ForecastScenarios[Forecast Scenario] = "BUD"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\BUD
		lineageTag: f435d890-9727-4df8-9534-4598fba26e74

	measure 'FPP Intake Volume vs BUD' =
			VAR act = [FPP Intake Volume]
			VAR comp = [FPP Intake Volume BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\BUD
		lineageTag: 4c8481ec-5495-47a0-9bd1-c058341fc4eb

	measure 'FPP Intake Volume FC' =
			CALCULATE (
			    [sum_fpp_rev_intake_units],
			    ForecastScenarios[Forecast Scenario] = "FC"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\FC
		lineageTag: 383e1ce8-ba39-4e7e-82a4-7172852d95cd

	measure 'FPP Intake Volume vs FC' =
			VAR act = [FPP Intake Volume]
			VAR comp = [FPP Intake Volume FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\FC
		lineageTag: 0e4a6890-9d5f-43c4-90fa-419a0fc3635e

	measure 'FPP Intake Volume QRF' =
			CALCULATE (
			    [sum_fpp_rev_intake_units],
			    ForecastScenarios[Forecast Scenario] = "QRF"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\QRF
		lineageTag: bb11d592-f146-4ee4-a44c-c7a4ad68ece8

	measure 'FPP Intake Volume vs QRF' =
			VAR act = [FPP Intake Volume]
			VAR comp = [FPP Intake Volume QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\QRF
		lineageTag: afedacb3-7702-42cb-9ed1-c3f81fac30a7

	measure 'SRIV Channel Orders LE' =
			CALCULATE (
			    [sum_sriv_factSRIVOrdersChannelForecast],
			    ForecastScenarios[Forecast Scenario] = "LE"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\LE
		lineageTag: ea605f8e-eb04-42a9-beda-6101f64375c3

	measure 'SRIV Channel Orders vs LE' =
			VAR act = [SRIV Orders]
			VAR comp = [SRIV Channel Orders LE]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\LE
		lineageTag: bfdd82a6-555e-4050-bbe9-f381a3e1a656

	measure 'SRIV Channel Orders vs LE %' =
			VAR act = [SRIV Orders]
			VAR comp = [SRIV Channel Orders LE]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\SRIV\LE
		lineageTag: f721f4ad-6f42-4655-9012-acea3c64559d

	measure 'SRIV Orders LE' =
			
			VAR TotPlan = CALCULATE ( [sum_TotSlsV], ForecastScenarios[Forecast Scenario] = "LE" )
			VAR FPPPlan = CALCULATE ( [sum_FPPSlsV], ForecastScenarios[Forecast Scenario] = "LE" )
			VAR RedPlan = CALCULATE ( [sum_RedSlsV], ForecastScenarios[Forecast Scenario] = "LE" )
			VAR result = SWITCH([slctd_SalesType],
			    "FP&P", FPPPlan,
			    "Reduced", RedPlan,
			    TotPlan)
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\LE
		lineageTag: fead1667-249e-4446-87f7-69b20fc1c169

	measure 'SRIV Orders vs LE' =
			VAR act = [SRIV Orders]
			VAR comp = [SRIV Orders LE]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SRIV\LE
		lineageTag: b5e88ed9-f8b5-40fe-a426-f5e4479877aa

	measure 'SRIV Orders vs LE %' =
			VAR act = [SRIV Orders]
			VAR comp = [SRIV Orders LE]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\SRIV\LE
		lineageTag: 2cce3a03-2bc0-4ab3-9960-c4e0da1507b8

	measure 'FPP SRIV Dispatch LE' =
			CALCULATE (
			    [sum_Full Price Sales Revenue (Inc VAT) DispFor],
			    ForecastScenarios[Forecast Scenario] = "LE"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP SRIV\LE
		lineageTag: 3326f00a-739e-49e3-a033-b6b6f1062830

	measure 'FPP SRIV Dispatch vs LE' =
			VAR act = [FPP SRIV Dispatch]
			VAR comp = [FPP SRIV Dispatch LE]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP SRIV\LE
		lineageTag: 640c7d13-483c-47a3-8ec2-1fa0d1f012b5

	measure 'FPP SRIV Dispatch vs LE % ' =
			VAR act = [FPP SRIV Dispatch]
			VAR comp = [FPP SRIV Dispatch LE]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\FPP SRIV\LE
		lineageTag: 29daf215-4a98-41f5-8b31-17875e70ae2e

	measure 'RP SRIV Dispatch LE' =
			CALCULATE (
			    [sum_Reduced Price Sales Revenue (Inc VAT) DispFor],
			    ForecastScenarios[Forecast Scenario] = "LE"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP SRIV\LE
		lineageTag: e0a82e53-e574-4dd9-8ab6-c660d16e04aa

	measure 'RP SRIV Dispatch vs LE' =
			VAR act = [RP SRIV Dispatch]
			VAR comp = [RP SRIV Dispatch LE]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP SRIV\LE
		lineageTag: 96200302-7c5e-44c7-8018-3d07621bfbc0

	measure 'RP SRIV Dispatch vs LE %' =
			VAR act = [RP SRIV Dispatch]
			VAR comp = [RP SRIV Dispatch LE]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\RP SRIV\LE
		lineageTag: ca4dfc30-5b11-4fe4-9830-e45383072f96

	measure 'SRIV Dispatch LE' =
			VAR is_channel_unfiltered = [is_channel_unfiltered]
			VAR sale_type = [slctd_SalesTypeLevelAware]
			VAR total_sales =
			    CALCULATE (
			        [sum_Sales Revenue (Inc VAT) DispFor],
			        ForecastScenarios[Forecast Scenario] = "LE"
			    )
			VAR result =
			    SWITCH (
			        sale_type,
			        "Total", total_sales,
			        "FP&P", [FPP SRIV Dispatch LE],
			        "Full Price", BLANK (),
			        "Promo", BLANK (),
			        "Reduced", [RP SRIV Dispatch LE],
			        total_sales
			    )
			RETURN
			    IF ( is_channel_unfiltered, result, BLANK () )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\LE
		lineageTag: 5f71c38a-a942-427a-90e5-e3d75a56d632

	measure 'SRIV Dispatch vs LE' =
			VAR act = [SRIV Dispatch]
			VAR comp = [SRIV Dispatch LE]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\LE
		lineageTag: 955b3ae1-3786-473f-b815-89c4058d5fd4

	measure 'SRIV Dispatch vs LE %' =
			VAR act = [SRIV Dispatch]
			VAR comp = [SRIV Dispatch LE]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\SRIV\LE
		lineageTag: 32c3d7a4-955b-4cf2-b49d-0384a6f6bc2f

	measure 'SRIV Channel LE' =
			
			VAR result = [SRIV Channel Orders LE]
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\LE
		lineageTag: e0581369-ba66-4632-b2be-01d5a3f12c78

	measure 'SRIV Channel vs LE' =
			VAR act = [SRIV]
			VAR comp = [SRIV Channel LE]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\LE
		lineageTag: e40aa28d-a190-43f9-b426-77c590270db0

	measure 'SRIV Channel vs LE %' =
			VAR act = [SRIV]
			VAR comp = [SRIV Channel LE]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV\LE
		lineageTag: c12956d7-4222-41b0-8c4f-0e5e8bfd24b9

	measure 'SRIV LE' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [SRIV Orders LE],
			        "Dispatch", [SRIV Dispatch LE],
			        [SRIV Orders LE]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\LE
		lineageTag: 8ac9a687-0648-460b-83bb-c3c7af477408

	measure 'SRIV vs LE' =
			VAR act = [SRIV]
			VAR comp = [SRIV LE]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV\LE
		lineageTag: 952399c0-e2a3-4fc9-98f0-c6487121b9f3

	measure 'SRIV vs LE %' =
			VAR act = [SRIV]
			VAR comp = [SRIV LE]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV\LE
		lineageTag: 1ea02ccc-824f-468a-b21c-c48d7d24af80

	measure 'SRIV Fwd View vs LE' =
			VAR act = [SRIV Fwd View]
			VAR comp = [SRIV Channel LE]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV Fwd View\LE
		lineageTag: 7818f64b-ac22-4c8f-85bd-89382b7f2837

	measure 'SRIV Fwd View vs LE %' =
			VAR act = [SRIV Fwd View]
			VAR comp = [SRIV Channel LE]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV Fwd View\LE
		lineageTag: c44df869-4ebd-43e8-895e-50120304c9fb

	measure IsLatestFiscalWeek =
			VAR latest_week = [LatestSalesFiscalWeek]
			VAR slctd_week =
			    SELECTEDVALUE ( 'Calendar'[fiscalWeek] )
			RETURN
			    IF ( slctd_week = latest_week, 1, BLANK () )
		displayFolder: Metadata\Latest Data
		lineageTag: f07269a6-754e-473e-8dd7-4e2c8b88a6d0

	measure 'GSM Fwd View' =
			VAR projection_scenario = [slctd_Projection Scenario]
			VAR latest_actuals = [LatestSalesFiscalWeek]
			VAR salesTable =
			    ADDCOLUMNS (
			        VALUES ( 'Calendar'[fiscalWeek] ),
			        "Hybrid",
			            IF (
			                [fiscalWeek] <= latest_actuals,
			                [GSM],
			                SWITCH (
			                    projection_scenario,
			                    "BUD", [GSM BUD],
			                    "FC", [GSM FC],
			                    "QRF", [GSM QRF],
			                    "LE", [GSM LE],
			                    [GSM BUD]
			                )
			            )
			    )
			RETURN
			    SUMX ( salesTable, [Hybrid] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM Fwd View\Actual
		lineageTag: ab35d36d-3480-4a26-b3dd-0ace16b43d8a

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'GSM Fwd View vs LY' =
			VAR act = [GSM Fwd View]
			VAR comp = [GSM LY]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM Fwd View\LY
		lineageTag: fe3d8420-16c7-4088-94db-5db6e9f83ace

	measure 'GSM Fwd View vs LY-1' =
			VAR act = [GSM Fwd View]
			VAR comp = [GSM LY-1]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		description: Two years ago equivalent of GSM Fwd View vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM Fwd View\LY-1
		lineageTag: d296cf03-ee49-446d-b4b2-ee1365393db2

	measure 'GSM Fwd View vs LY %' =
			VAR act = [GSM Fwd View]
			VAR comp = [GSM LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM Fwd View\LY
		lineageTag: 39fd8de9-f271-4eb4-a428-ec342dbc7d1c

	measure 'GSM Fwd View vs FC' =
			VAR act = [GSM Fwd View]
			VAR comp = [GSM FC]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM Fwd View\FC
		lineageTag: dd11f84f-3bc7-43bd-b0a5-c6e51af242c7

	measure 'GSM Fwd View vs FC %' =
			VAR act = [GSM Fwd View]
			VAR comp = [GSM FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM Fwd View\FC
		lineageTag: 5174bfc0-b322-40d4-b878-3c9964ff572c

	measure 'GSM Fwd View vs LW' =
			VAR act = [GSM Fwd View]
			VAR comp = [GSM Fwd View LW]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM Fwd View\LW
		lineageTag: 0133471e-818d-4364-ae0e-257f746725d8

	measure 'GSM Fwd View vs LW %' =
			VAR act = [GSM Fwd View]
			VAR comp = [GSM Fwd View LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM Fwd View\LW
		lineageTag: c320571e-c6dc-4673-af97-cbf7139a0fb5

	measure 'GSM Fwd View LW' =
			CALCULATE (
			    [GSM Fwd View],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] ),
			    USERELATIONSHIP ( factDispatchForecast[FISCAL_WEEK], 'Calendar'[fiscalWeekLastWeek] ),
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] ),
			    USERELATIONSHIP ( factForecast[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM Fwd View\LW
		lineageTag: 75ada8b1-04f4-4aae-8c30-76b4092782bf

	measure 'GSM Fwd View vs BUD' =
			VAR act = [GSM Fwd View]
			VAR comp = [GSM BUD]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM Fwd View\BUD
		lineageTag: 13b0526a-3909-45e2-aeb5-7252f9197dac

	measure 'GSM Fwd View vs BUD %' =
			VAR act = [GSM Fwd View]
			VAR comp = [GSM BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM Fwd View\BUD
		lineageTag: e97df9dc-dd0b-45d3-8378-bbfdc740d5b5

	measure 'GSM Fwd View vs QRF' =
			VAR act = [GSM Fwd View]
			VAR comp = [GSM QRF]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM Fwd View\QRF
		lineageTag: 6cb4ae75-a371-4d7e-81d6-4facd37d8df0

	measure 'GSM Fwd View vs QRF %' =
			VAR act = [GSM Fwd View]
			VAR comp = [GSM QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM Fwd View\QRF
		lineageTag: fcb76013-0ad2-411c-a25d-280750f51725

	measure 'GSM Fwd View vs LE' =
			VAR act = [GSM Fwd View]
			VAR comp = [GSM LE]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM Fwd View\LE
		lineageTag: 861ab5a4-ae7d-4c63-9a21-41e048111bea

	measure 'GSM Fwd View vs LE %' =
			VAR act = [GSM Fwd View]
			VAR comp = [GSM LE]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM Fwd View\LE
		lineageTag: 7b217663-c6fe-4b58-845e-ab1cab1f3e7a

	measure 'GSM Orders LE' =
			VAR Tot_mp_plan =  CALCULATE ( [sum_TotGSMV], ForecastScenarios[Forecast Scenario] = "LE" )
			VAR FPP_mp_plan =  CALCULATE ( [sum_FPPGSMV], ForecastScenarios[Forecast Scenario] = "LE" )
			VAR RP_mp_plan =  CALCULATE ( [sum_RedGSMV], ForecastScenarios[Forecast Scenario] = "LE" )
			VAR result =    SWITCH([slctd_SalesType],
			                "FP&P", FPP_mp_plan,
			                "Reduced", RP_mp_plan,
			                Tot_mp_plan)
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\GSM\LE
		lineageTag: 07b26c49-4a15-4120-ac5d-d62a5d3fbfb4

	measure 'GSM Orders vs LE' =
			VAR act = [GSM Orders]
			VAR comp = [GSM Orders LE]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\GSM\LE
		lineageTag: 2c1fdc48-3bcd-4202-92e1-c9b8a1f65e8a

	measure 'GSM % SREV Orders LE' =
			VAR metric = [GSM Orders LE]
			VAR sales = [SREV Orders LE]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\GSM\LE
		lineageTag: 76b3f422-3c00-4109-a340-1faf4b229566

	measure 'GSM % SREV Orders vs LE' =
			VAR act = [GSM % SREV Orders]
			VAR comp = [GSM % SREV Orders LE]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\GSM\LE
		lineageTag: d8ff7eda-cd62-4495-8d77-86e12fb8479f

	measure 'GSM Orders vs LE %' =
			VAR act = [GSM Orders]
			VAR comp = [GSM Orders LE]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\GSM\LE
		lineageTag: 33150be3-1845-476f-8437-b98e44c09e39

	measure 'SREV Orders vs LE' =
			VAR act = [SREV Orders]
			VAR comp = [SREV Orders LE]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SREV\LE
		lineageTag: 1681d274-fa0a-4e08-a4b1-13325fb1a760

	measure 'SREV Orders vs LE %' =
			VAR act = [SREV Orders]
			VAR comp = [SREV Orders LE]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\SREV\LE
		lineageTag: 49c280ef-b059-4093-bb67-467873af71a5

	measure 'SREV Orders LE' = ```
			
			VAR Tot_mp_plan =  CALCULATE ( [sum_TotSlsxV], ForecastScenarios[Forecast Scenario] = "LE" )
			VAR FPP_mp_plan =  CALCULATE ( [sum_FPPSlsxV], ForecastScenarios[Forecast Scenario] = "LE" )
			VAR RP_mp_plan =  CALCULATE ( [sum_TotSlsxV] - [sum_FPPSlsxV], ForecastScenarios[Forecast Scenario] = "LE" )
			VAR result =    SWITCH([slctd_SalesType],
			                "FP&P", FPP_mp_plan,
			                "Reduced", RP_mp_plan,
			                Tot_mp_plan)
			RETURN
			    result
			
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\SREV\LE
		lineageTag: d49aed28-bb0c-449d-99f6-2cdd4c62873e

	measure 'SREV Dispatch LE' =
			CALCULATE (
			    [sum_Sales Revenue (Exc VAT) DispFor],
			    ForecastScenarios[Forecast Scenario] = "LE"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SREV\LE
		lineageTag: b6e766b2-a287-4b0c-80d3-dfc0772b764e

	measure 'SREV Dispatch vs LE' =
			VAR act = [SREV Dispatch]
			VAR comp = [SREV Dispatch LE]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SREV\LE
		lineageTag: e48bff19-6466-4d86-9c6f-658195b93b6b

	measure 'SREV Dispatch vs LE %' =
			VAR act = [SREV Dispatch]
			VAR comp = [SREV Dispatch LE]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\SREV\LE
		lineageTag: 9d8dfb85-4860-4cec-bbb4-99b18f777e27

	measure 'SREV LE' =
			VAR result = [SREV Orders LE]
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV\LE
		lineageTag: 721790e8-bbdb-4d87-a7e2-99b0b30ef3e9

	measure 'SREV vs LE' =
			VAR act = [SREV]
			VAR comp = [SREV LE]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV\LE
		lineageTag: e93ff600-d0a5-41c0-b92d-1874d953bbb4

	measure 'SREV vs LE %' =
			VAR act = [SREV]
			VAR comp = [SREV LE]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SREV\LE
		lineageTag: 847c5942-73f5-49fc-b958-4de67cb332fd

	measure 'GSM Dispatch LE' =
			CALCULATE (
			    [sum_Gross Selling Margin DispFor],
			    ForecastScenarios[Forecast Scenario] = "LE"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\GSM\LE
		lineageTag: a5ebe93e-816d-493e-83d9-f9abc7f21bdd

	measure 'GSM Dispatch vs LE' =
			VAR act = [GSM Dispatch]
			VAR comp = [GSM Dispatch LE]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\GSM\LE
		lineageTag: 02ae505a-690e-4f78-a80a-9551296d2423

	measure 'GSM % SREV Dispatch LE' =
			VAR metric = [GSM Dispatch LE]
			VAR sales = [SREV Dispatch LE]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\GSM\LE
		lineageTag: e8240dd1-0d49-4d5b-823d-e1b8b24ab8d8

	measure 'GSM % SREV Dispatch vs LE' =
			VAR act = [GSM % SREV Dispatch]
			VAR comp = [GSM % SREV Dispatch LE]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\GSM\LE
		lineageTag: cc815e3d-4de8-4c28-8eed-5936b150473b

	measure 'GSM Dispatch vs LE %' =
			VAR act = [GSM Dispatch]
			VAR comp = [GSM Dispatch LE]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\GSM\LE
		lineageTag: a97f9d93-2d75-4880-b431-20f19a985894

	measure 'GSM LE' =
			VAR result = [GSM Orders LE]
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM\LE
		lineageTag: 365d5bc3-b336-4234-a54e-ee251d9e44db

	measure 'GSM vs LE' =
			VAR act = [GSM]
			VAR comp = [GSM LE]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM\LE
		lineageTag: acaf7be0-cf9b-48e2-b8f3-d4289c34fdd5

	/// This measure is column [GSM Orders LW] as a % of SREV
	measure 'GSM % SREV LE' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [GSM % SREV Orders LE],
			        "Dispatch", [GSM % SREV Orders LE],
			        [GSM % SREV Orders LE]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\LE
		lineageTag: 53c22034-e00d-4085-9977-58b404e1ea18

	measure 'GSM % SREV vs LE' =
			VAR act = [GSM % SREV]
			VAR comp = [GSM % SREV LE]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\LE
		lineageTag: 4647d20a-830d-4e9e-a70c-05577818f7a5

	measure 'GSM vs LE %' =
			VAR act = [GSM]
			VAR comp = [GSM LE]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\LE
		lineageTag: 82ded5e4-abd5-493b-bfa5-b29c149101c7

	measure 'SREV Fwd View' =
			VAR projection_scenario = [slctd_Projection Scenario]
			VAR latest_actuals = [LatestSalesFiscalWeek]
			VAR salesTable =
			    ADDCOLUMNS (
			        VALUES ( 'Calendar'[fiscalWeek] ),
			        "Hybrid",
			            IF (
			                [fiscalWeek] <= latest_actuals,
			                [SREV],
			                SWITCH (
			                    projection_scenario,
			                    "BUD", [SREV BUD],
			                    "FC", [SREV FC],
			                    "QRF", [SREV QRF],
			                    "LE", [SREV LE],
			                    [SREV BUD]
			                )
			            )
			    )
			RETURN
			    SUMX ( salesTable, [Hybrid] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV Fwd View\Actual
		lineageTag: 3d470092-f74c-4f7e-91cd-1fd1fdfd7677

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'SREV Fwd View vs LY' =
			VAR act = [SREV Fwd View]
			VAR comp = [SREV LY]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV Fwd View\LY
		lineageTag: 90342581-1e74-4a5f-a2af-48ac1eaefeec

	measure 'SREV Fwd View vs LY-1' =
			VAR act = [SREV Fwd View]
			VAR comp = [SREV LY-1]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		description: Two years ago equivalent of SREV Fwd View vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV Fwd View\LY-1
		lineageTag: 86e4b12c-37f1-437c-9dad-5dc784481127

	measure 'SREV Fwd View vs LY %' =
			VAR act = [SREV Fwd View]
			VAR comp = [SREV LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SREV Fwd View\LY
		lineageTag: 2c9647d1-c112-4f99-abfb-c615dcc446f7

	measure 'SREV Fwd View vs FC' =
			VAR act = [SREV Fwd View]
			VAR comp = [SREV FC]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV Fwd View\FC
		lineageTag: af3ea61e-050e-471e-a14c-773c9edffe17

	measure 'SREV Fwd View vs FC %' =
			VAR act = [SREV Fwd View]
			VAR comp = [SREV FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SREV Fwd View\FC
		lineageTag: d4b643b1-d095-4207-b259-ac148248c05a

	measure 'SREV Fwd View vs LW' =
			VAR act = [SREV Fwd View]
			VAR comp = [SREV Fwd View LW]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV Fwd View\LW
		lineageTag: 980521eb-1136-4f89-bf79-dfe6cb5cef1a

	measure 'SREV Fwd View vs LW %' =
			VAR act = [SREV Fwd View]
			VAR comp = [SREV Fwd View LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SREV Fwd View\LW
		lineageTag: c2709bec-592a-4c3d-9156-5f876862ccc7

	measure 'SREV Fwd View LW' =
			CALCULATE (
			    [SREV Fwd View],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] ),
			    USERELATIONSHIP ( factDispatchForecast[FISCAL_WEEK], 'Calendar'[fiscalWeekLastWeek] ),
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] ),
			    USERELATIONSHIP ( factForecast[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV Fwd View\LW
		lineageTag: f500885c-8d89-47ac-8199-028faf46cf09

	measure 'SREV Fwd View vs BUD' =
			VAR act = [SREV Fwd View]
			VAR comp = [SREV BUD]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV Fwd View\BUD
		lineageTag: 9d2b8872-e88b-4a88-8cfd-4ef986ccab84

	measure 'SREV Fwd View vs BUD %' =
			VAR act = [SREV Fwd View]
			VAR comp = [SREV BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SREV Fwd View\BUD
		lineageTag: 34e42950-e662-4c1e-8b6f-072f49e4b456

	measure 'SREV Fwd View vs QRF' =
			VAR act = [SREV Fwd View]
			VAR comp = [SREV QRF]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV Fwd View\QRF
		lineageTag: 82e376d5-525a-4499-bf43-dbdac766e382

	measure 'SREV Fwd View vs QRF %' =
			VAR act = [SREV Fwd View]
			VAR comp = [SREV QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SREV Fwd View\QRF
		lineageTag: 93351e0a-3683-4905-a4f5-fbf959a79ec9

	measure 'SREV Fwd View vs LE' =
			VAR act = [SREV Fwd View]
			VAR comp = [SREV LE]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SREV Fwd View\LE
		lineageTag: 1b59b5b8-156f-4139-8cb5-c715aaa5231b

	measure 'SREV Fwd View vs LE %' =
			VAR act = [SREV Fwd View]
			VAR comp = [SREV LE]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SREV Fwd View\LE
		lineageTag: aec299b9-99bf-4730-ab0b-d74cd4c48ccb

	/// This measure is column [GSM Orders] as a % of SREV
	measure 'GSM % SREV Fwd View' =
			VAR metric = [GSM Fwd View]
			VAR sales = [SREV Fwd View]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM Fwd View\Actual
		lineageTag: 664ac4e5-f0d3-40eb-8fd4-48d73d589e65

	measure 'GSM % SREV Fwd View vs LY' =
			VAR act = [GSM % SREV Fwd View]
			VAR comp = [GSM % SREV LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM Fwd View\LY
		lineageTag: 08a1c225-7c90-46f3-afb5-8ace1ee08185

	measure 'GSM % SREV Fwd View vs LY-1' =
			VAR act = [GSM % SREV Fwd View]
			VAR comp = [GSM % SREV LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of GSM % SREV Fwd View vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM Fwd View\LY-1
		lineageTag: c848074e-0570-4e15-b299-1e83a663df42

	/// This measure is column [GSM Orders LW] as a % of SREV
	measure 'GSM % SREV Fwd View LW' =
			VAR metric = [GSM Fwd View LW]
			VAR sales = [SREV Fwd View LW]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM Fwd View\LW
		lineageTag: cbb7c826-b341-49fb-aadd-a6245b536c40

	measure 'GSM % SREV Fwd View vs LW' =
			VAR act = [GSM % SREV Fwd View]
			VAR comp = [GSM % SREV Fwd View LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM Fwd View\LW
		lineageTag: c8a0968f-5b92-4e14-96e4-973a5cbc646f

	measure 'GSM % SREV Fwd View vs BUD' =
			VAR act = [GSM % SREV Fwd View]
			VAR comp = [GSM % SREV BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM Fwd View\BUD
		lineageTag: f8195363-5d50-4db9-8ab2-77dd253c2e91

	measure 'GSM % SREV Fwd View vs FC' =
			VAR act = [GSM % SREV Fwd View]
			VAR comp = [GSM % SREV FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM Fwd View\FC
		lineageTag: 3ec3c83f-c352-4f0d-b19d-66ee98482016

	measure 'GSM % SREV Fwd View vs QRF' =
			VAR act = [GSM % SREV Fwd View]
			VAR comp = [GSM % SREV QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM Fwd View\QRF
		lineageTag: d381b7e0-df18-451c-8982-c7703bfac505

	measure 'GSM % SREV Fwd View vs LE' =
			VAR act = [GSM % SREV Fwd View]
			VAR comp = [GSM % SREV LE]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM Fwd View\LE
		lineageTag: 63b71e59-2fd6-4ef8-980c-f1886e206977

	measure MbrComp06_VAT = DIVIDE ( [MbrComp01_SRIVMainchain], [MbrComp05_SREVMainchain] ) - 1
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: 79c14c12-9570-42d3-8463-d9ba09b5c318

	measure MbrComp07_POS =
			DIVIDE(-[MbrComp12_POS],([MbrComp02_SRIVFPP]-[MbrComp12_POS]))
			
			/*
			VAR comp = [slctd_MarginBridgeComparator]
			VAR result =
			    SWITCH (
			        comp,
			        "ACT", CALCULATE([Promo Markdown %], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "LW", CALCULATE([Promo Markdown % LW], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "QRF", CALCULATE([Promo Markdown % QRF], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "FC", CALCULATE([Promo Markdown % FC], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "BUD", CALCULATE([Promo Markdown % BUD], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "LY", CALCULATE([Promo Markdown % LY], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other")
			    )
			RETURN
			    result
			    */
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: 14c6af73-b257-4125-ada4-230a38fae0ee

	measure MbrComp08_SaleMDPct =
			Divide(-[MbrComp09_SaleMD],([MbrComp03_SRIVRP]-[MbrComp09_SaleMD]))
			/* VAR comp = [slctd_MarginBridgeComparator]
			VAR result =
			    SWITCH (
			        comp,
			        "ACT", CALCULATE([Sale Markdown %], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "LW", CALCULATE([Sale Markdown % LW], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "QRF", CALCULATE([Sale Markdown % QRF], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "FC", CALCULATE([Sale Markdown % FC], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "BUD", CALCULATE([Sale Markdown % BUD], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "LY", CALCULATE([Sale Markdown % LY], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other")
			    )
			RETURN
			    result */
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: ba9e0884-f305-4f10-b277-46f607be6667

	measure 'SRIV Channel Dispatch BUD' =
			VAR mp_plan =
			    CALCULATE (
			        [sum_sriv_factSRIVDispatchChannelForecast],
			        ForecastScenarios[Forecast Scenario] = "BUD"
			    )
			VAR derisk = [sum_SRIV_derisk_FC]
			VAR result = mp_plan + derisk
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\BUD
		lineageTag: 6a9d1a32-63bd-4a63-9b26-50329ef0dabe

	measure 'SRIV Channel Dispatch vs BUD' =
			VAR act = [SRIV Dispatch]
			VAR comp = [SRIV Channel Dispatch BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\BUD
		lineageTag: 4d3de997-db8b-4a70-8e5a-79d4438c4d3d

	measure 'SRIV Channel Dispatch vs BUD %' =
			VAR act = [SRIV Dispatch]
			VAR comp = [SRIV Channel Dispatch BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\SRIV\BUD
		lineageTag: 614cf22b-b08b-4030-9bae-89d093d55200

	measure 'SRIV Channel Dispatch FC' =
			VAR mp_plan =
			    CALCULATE (
			        [sum_sriv_factSRIVDispatchChannelForecast],
			        ForecastScenarios[Forecast Scenario] = "FC"
			    )
			VAR derisk = [sum_SRIV_derisk_FC]
			VAR result = mp_plan + derisk
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\FC
		lineageTag: 2dd95080-72de-4beb-9ef5-9d630069d606

	measure 'SRIV Channel Dispatch vs FC' =
			VAR act = [SRIV Dispatch]
			VAR comp = [SRIV Channel Dispatch FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\FC
		lineageTag: 25b19888-d3f2-4d49-a310-0c06859be143

	measure 'SRIV Channel Dispatch vs FC %' =
			VAR act = [SRIV Dispatch]
			VAR comp = [SRIV Channel Dispatch FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\SRIV\FC
		lineageTag: 6d0e5080-360c-459c-aa8b-67faff26aa73

	measure 'SRIV Channel Dispatch QRF' =
			CALCULATE (
			    [sum_sriv_factSRIVDispatchChannelForecast],
			    ForecastScenarios[Forecast Scenario] = "QRF"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\QRF
		lineageTag: 77d1963b-ef2a-42c7-ac35-4acdcfc4ed1c

	measure 'SRIV Channel Dispatch vs QRF' =
			VAR act = [SRIV Dispatch]
			VAR comp = [SRIV Channel Dispatch QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\QRF
		lineageTag: 4004651f-6a58-4990-8445-adeba503b963

	measure 'SRIV Channel Dispatch vs QRF %' =
			VAR act = [SRIV Dispatch]
			VAR comp = [SRIV Channel Dispatch QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\SRIV\QRF
		lineageTag: f03adf4b-94a5-443e-8373-959c3bee2ade

	measure 'SRIV Channel Dispatch LE' =
			CALCULATE (
			    [sum_sriv_factSRIVDispatchChannelForecast],
			    ForecastScenarios[Forecast Scenario] = "LE"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\LE
		lineageTag: 3d2f8d70-39b1-4809-b602-28709bab771b

	measure 'SRIV Channel Dispatch vs LE' =
			VAR act = [SRIV Dispatch]
			VAR comp = [SRIV Channel Dispatch LE]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\SRIV\LE
		lineageTag: 8e12ff0d-f20e-4647-936c-459caa6d2d53

	measure 'SRIV Channel Dispatch vs LE %' =
			VAR act = [SRIV Dispatch]
			VAR comp = [SRIV Channel Dispatch LE]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\SRIV\LE
		lineageTag: 55e68f17-6135-4ef6-b191-eb42a0db5393

	/// This measure is the sum of column 'factSalesDispatch[Sales Revenue (Exc VAT)]'
	measure 'Gross SRIV' = [SRIV] - [Returns]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\Actual
		lineageTag: a055d4c3-73a8-4445-84a4-bb918e8d5ce0

	/// This measure is the sum of column 'factSalesDispatch[Sales Revenue (Exc VAT)]'
	measure 'Gross SRIV LY' = [SRIV LY] - [Returns LY]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\LY
		lineageTag: 879d8139-8ca0-4f2d-88a8-e4fc64520eae

	measure 'Gross SRIV LY-1' = [SRIV LY-1] - [Returns LY-1]
		description: Two years ago equivalent of Gross SRIV LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\LY-1
		lineageTag: 3e1dfe4a-4979-4d8a-ad6f-132d50decfa1

	/// This measure is the sum of column 'factSalesDispatch[Sales Revenue (Exc VAT)]'
	measure 'Gross SRIV LW' = [SRIV LW] - [Returns LW]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\LW
		lineageTag: 70e6d7d3-e074-436b-b241-0ce3072be21b

	measure 'Gross SRIV vs LY' =
			VAR act = [Gross SRIV]
			VAR comp = [Gross SRIV LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\LY
		lineageTag: 9b01f1a7-8017-4cb2-8cad-45431a9323fb

	measure 'Gross SRIV vs LY-1' =
			VAR act = [Gross SRIV]
			VAR comp = [Gross SRIV LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Gross SRIV vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\LY-1
		lineageTag: 3242de4e-b8c5-4e39-8b2b-f36894cf32c5

	measure 'Gross SRIV vs LW' =
			VAR act = [Gross SRIV]
			VAR comp = [Gross SRIV LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\LW
		lineageTag: e779dd66-dd64-48dc-a7eb-e46c84f02053

	measure SelectedBU = SELECTEDVALUE ( Products[BU] )
		displayFolder: Dynamic Labels
		lineageTag: b50ef162-51f7-4af1-b906-53a20db604fd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Return rate % vs LW' = [Return rate %] - [Return rate % LW]
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\LW
		lineageTag: b0bff92e-3b57-4dba-939e-35333aab65d1

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Return rate % vs LY' = [Return rate %] - [Return rate % LY]
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\LY
		lineageTag: 41f71899-2b2e-4ecd-878b-455b9391eaa4

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Return rate % vs LY-1' = [Return rate %] - [Return rate % LY-1]
		description: Two years ago equivalent of Return rate % vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\LY-1
		lineageTag: 0f959f6e-82f5-45dd-8ed5-44f66e5cc659

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'SRIV Full Price' = CALCULATE ( [SRIV], 'SalesType'[SubSalesType] = "Full Price" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 209066d5-6782-475f-9c3d-0c248ba68810

	measure 'SRIV Promo' = CALCULATE ( [SRIV], 'SalesType'[SubSalesType] = "Promo" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: a753adaf-509f-4d0b-b9d6-bb5c218a4455

	measure 'SRIV Reduced' = CALCULATE ( [SRIV], 'SalesType'[SubSalesType] = "Reduced" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 874fc4fe-b250-4148-a563-b7bf41ea6612

	measure 'SRIV FPP' = CALCULATE ( [SRIV], 'SalesType'[SalesType] = "FP&P" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 10e140cd-8db7-4d80-8644-6e77e0e83d66

	measure 'SRIV Stores' = CALCULATE ( [SRIV], 'Channels'[Channel] = "Stores" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: ac100f85-5366-404f-8061-2330ba683cc1

	measure 'SRIV Online' = CALCULATE ( [SRIV], 'Channels'[Channel] = "Online" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 78e55d2e-6fac-470b-977e-e9c77f6bd69d

	measure 'SRIV FPP BUD' = CALCULATE ( [SRIV Channel BUD], 'SalesType'[SalesType] = "FP&P" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 17b7d352-60de-4bc6-a670-2911bd9e7775

	measure 'SRIV Full Price BUD' = CALCULATE ( [sum_FPSlsV], ForecastScenarios[Forecast Scenario] = "BUD" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: c719a9e6-7ee9-4ac4-902d-1fe8641cd6c8

	measure 'SRIV Online BUD' = CALCULATE ( [SRIV Channel BUD], 'Channels'[Channel] = "Online" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 53c34b6d-f321-4d66-b1cf-6d62acb811a6

	measure 'SRIV Promo BUD' = CALCULATE ( [sum_PrSlsV], ForecastScenarios[Forecast Scenario] = "BUD" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 6c2318f4-da2d-468f-82fd-ef84aa35633e

	measure 'SRIV Reduced BUD' = CALCULATE ( [sum_RedSlsV], ForecastScenarios[Forecast Scenario] = "BUD" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 59184326-c476-4a36-819f-2a7c9ca8e56f

	measure 'SRIV Stores BUD' = CALCULATE ( [SRIV Channel BUD], 'Channels'[Channel] = "Stores" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 510c199d-fb74-4c62-afe3-70a6f1097a00

	measure 'SRIV FPP vs BUD' = [SRIV FPP] - [SRIV FPP BUD]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: e9b4dd12-d9a8-45eb-b2c7-68a6c55ccfba

	measure 'SRIV Full Price vs BUD' = [SRIV Full Price] - [SRIV Full Price BUD]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 8b1c6b4d-342f-463d-9fd3-61f53f916251

	measure 'SRIV Online vs BUD' = [SRIV Online] - [SRIV Online BUD]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: c55a678f-aa21-48f1-9dd0-76c21d978f2c

	measure 'SRIV Promo vs BUD' = [SRIV Promo] - [SRIV Promo BUD]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 1ef980f1-d552-487c-a757-639ff5f9db73

	measure 'SRIV Reduced vs BUD' = [SRIV Reduced] - [SRIV Reduced BUD]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: e7423eb0-3e27-47ca-81ae-61e196fecd74

	measure 'SRIV Stores vs BUD' = [SRIV Stores] - [SRIV Stores BUD]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: e5051c7a-a4a6-4107-9c09-2ab0b9c3241c

	measure 'SRIV FPP LW' = CALCULATE ( [SRIV LW], 'SalesType'[SalesType] = "FP&P" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: aeda0686-a741-4815-bcbc-aadd85929cb5

	measure 'SRIV Full Price LW' = CALCULATE ( [SRIV LW], 'SalesType'[SubSalesType] = "Full Price" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: ee6a8d7d-6493-4345-8e99-cfd70c0755f7

	measure 'SRIV Online LW' = CALCULATE ( [SRIV LW], 'Channels'[Channel] = "Online" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 5776d7f7-0811-4b68-97a7-132a5c8f6926

	measure 'SRIV Promo LW' = CALCULATE ( [SRIV LW], 'SalesType'[SubSalesType] = "Promo" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 099f3ab9-6df5-400c-ab11-9ba0b7300133

	measure 'SRIV Reduced LW' = CALCULATE ( [SRIV LW], 'SalesType'[SubSalesType] = "Reduced" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: ce0fa366-8b60-452a-99ef-490562d8b5ba

	measure 'SRIV Stores LW' = CALCULATE ( [SRIV LW], 'Channels'[Channel] = "Stores" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 623dd6c2-5333-474c-bfb9-5b833a5ba32f

	measure 'SRIV FPP vs LW %' =
			VAR act = [SRIV FPP]
			VAR comp = [SRIV FPP LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 7d0dc20e-d25c-4be4-a3d7-3d83dd3096fd

	measure 'SRIV Full Price vs LW %' =
			VAR act = [SRIV Full Price]
			VAR comp = [SRIV Full Price LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 7374da66-2536-42e5-a58b-f26ffe75cfe4

	measure 'SRIV Online vs LW %' =
			VAR act = [SRIV Online]
			VAR comp = [SRIV Online LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV RG Measures
		lineageTag: eedfbf0b-0218-4f14-b54a-2b48b5e29ee6

	measure 'SRIV Promo vs LW %' =
			VAR act = [SRIV Promo]
			VAR comp = [SRIV Promo LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 0ec2a9dc-d54a-495a-9fc4-b96b1b8d689f

	measure 'SRIV Reduced vs LW %' =
			VAR act = [SRIV Reduced]
			VAR comp = [SRIV Reduced LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV RG Measures
		lineageTag: d39a7c14-e345-4c4d-843b-fced4138c719

	measure 'SRIV Stores vs LW %' =
			VAR act = [SRIV Stores]
			VAR comp = [SRIV Stores LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV RG Measures
		lineageTag: d751220d-0c0e-42bc-9bad-7a0c294ddc77

	measure 'SRIV FPP LY' = CALCULATE ( [SRIV LY], 'SalesType'[SalesType] = "FP&P" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 669559ce-1dde-4454-917a-659ee209470e

	measure 'SRIV FPP LY-1' = CALCULATE ( [SRIV LY-1], 'SalesType'[SalesType] = "FP&P" )
		description: Two years ago equivalent of SRIV FPP LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 5728b333-417d-4f94-8e72-e4d0e4b80070

	measure 'SRIV Full Price LY' = CALCULATE ( [SRIV LY], 'SalesType'[SubSalesType] = "Full Price" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 5f1bcf51-b289-447d-b2e2-44d438b7475c

	measure 'SRIV Full Price LY-1' = CALCULATE ( [SRIV LY-1], 'SalesType'[SubSalesType] = "Full Price" )
		description: Two years ago equivalent of SRIV Full Price LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 3df56c66-2a90-40cb-bfea-4fdb7d94a15b

	measure 'SRIV Online LY' = CALCULATE ( [SRIV LY], 'Channels'[Channel] = "Online" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 10e94082-d04a-4a0c-a9eb-5eff81720112

	measure 'SRIV Online LY-1' = CALCULATE ( [SRIV LY-1], 'Channels'[Channel] = "Online" )
		description: Two years ago equivalent of SRIV Online LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 003ebdee-9383-4534-9b8c-de0dbdb0e00c

	measure 'SRIV Promo LY' = CALCULATE ( [SRIV LY], 'SalesType'[SubSalesType] = "Promo" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 9630c4bb-4e5c-4550-970c-8fbb6cc46bbd

	measure 'SRIV Promo LY-1' = CALCULATE ( [SRIV LY-1], 'SalesType'[SubSalesType] = "Promo" )
		description: Two years ago equivalent of SRIV Promo LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: d38f1124-8a61-48b2-9773-b78dc326827f

	measure 'SRIV Reduced LY' = CALCULATE ( [SRIV LY], 'SalesType'[SubSalesType] = "Reduced" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 199d6ad3-3ca9-4dfe-a210-24ba75f12b05

	measure 'SRIV Reduced LY-1' = CALCULATE ( [SRIV LY-1], 'SalesType'[SubSalesType] = "Reduced" )
		description: Two years ago equivalent of SRIV Reduced LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: f4894c0a-90e4-4315-a673-bb54049e0e1e

	measure 'SRIV Stores LY' = CALCULATE ( [SRIV LY], 'Channels'[Channel] = "Stores" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 49243305-0f60-4963-9650-9fe8245a000b

	measure 'SRIV Stores LY-1' = CALCULATE ( [SRIV LY-1], 'Channels'[Channel] = "Stores" )
		description: Two years ago equivalent of SRIV Stores LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 3e3dbced-4ff4-4b17-93cc-ec28566eeace

	measure 'SRIV FPP vs LY %' =
			VAR act = [SRIV FPP]
			VAR comp = [SRIV FPP LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 0603d34a-0750-4942-8ca0-18d66fde7370

	measure 'SRIV Full Price vs LY %' =
			VAR act = [SRIV Full Price]
			VAR comp = [SRIV Full Price LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 86d292f3-dda0-4885-a185-3ead68a34714

	measure 'SRIV Online vs LY %' =
			VAR act = [SRIV Online]
			VAR comp = [SRIV Online LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 03e1dd37-e34b-4619-8d24-e0aa7532de44

	measure 'SRIV Promo vs LY %' =
			VAR act = [SRIV Promo]
			VAR comp = [SRIV Promo LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV RG Measures
		lineageTag: cfbbf9ac-a24b-427f-9607-26a674110f0f

	measure 'SRIV Reduced vs LY %' =
			VAR act = [SRIV Reduced]
			VAR comp = [SRIV Reduced LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV RG Measures
		lineageTag: c8ba09ae-efad-48ff-bff7-420491d3036c

	measure 'SRIV Stores vs LY %' =
			VAR act = [SRIV Stores]
			VAR comp = [SRIV Stores LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 0d0742dd-ba10-4329-abc2-6aa71d9d8e89

	measure 'Returns Online' = CALCULATE ( [Returns], 'Channels'[Channel] = "Online" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: aedfc49f-9a40-4492-8ab3-fec961e47164

	measure 'Returns Online %' = DIVIDE ( - [Returns Online], [SRIV Online] - [Returns Online], 0 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 8db01bca-f4f2-4c15-860b-d701c5021688

	measure 'Returns Online LY' = CALCULATE ( [Returns LY], 'Channels'[Channel] = "Online" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: fb240fb4-0616-4bcb-a39b-33ae5f02a717

	measure 'Returns Online LY-1' = CALCULATE ( [Returns LY-1], 'Channels'[Channel] = "Online" )
		description: Two years ago equivalent of Returns Online LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 2779943a-48bd-432e-afb4-48e3e09e2cca

	measure 'Returns Online LY %' = DIVIDE ( - [Returns Online LY], [SRIV Online LY] - [Returns Online LY], 0 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 08374a7b-dc1c-496a-954f-38a4eda420b8

	measure 'Returns Online vs LY %' = [Returns Online %] - [Returns Online LY %]
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 8ab7a7ec-10ba-47be-a732-ae3041f5f21a

	measure 'Returns Stores' = CALCULATE ( [Returns], 'Channels'[Channel] = "Stores" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: db82c75c-a8e4-493b-8f73-04c6ec88ad21

	measure 'Returns Stores %' = DIVIDE ( - [Returns Stores], [SRIV Stores] - [Returns Stores], 0 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 26f7aaeb-0836-4ed4-b88d-207446a8e5e0

	measure 'Returns Stores LY' = CALCULATE ( [Returns LY], 'Channels'[Channel] = "Stores" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 298f1a09-852d-46bf-a69e-63a2d8090e5d

	measure 'Returns Stores LY-1' = CALCULATE ( [Returns LY-1], 'Channels'[Channel] = "Stores" )
		description: Two years ago equivalent of Returns Stores LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: b7031bca-f5dd-4f5d-82dc-594814b74483

	measure 'Returns Stores LY %' = DIVIDE ( - [Returns Stores LY], [SRIV Stores LY] - [Returns Stores LY], 0 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV RG Measures
		lineageTag: d82400e7-5fbf-4760-997d-d6894980606c

	measure 'Returns Stores vs LY %' = [Returns Stores %] - [Returns Stores LY %]
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 38c4ef8c-2ead-4da1-8f4e-367fed5b2477

	measure 'Sales BU Mix %' =
			VAR filtered_sales = [SRIV]
			VAR bu_total =
			    CALCULATE ( [SRIV], ALLEXCEPT ( Products, Products[BU] ) )
			VAR result =
			    DIVIDE ( filtered_sales, bu_total )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\BU\Actual
		lineageTag: 76b49d65-5b69-40eb-8ed6-95d082489cc1

	measure 'Sales BU Mix % LW' =
			VAR filtered_sales = [SRIV LW]
			VAR bu_total =
			    CALCULATE ( [SRIV LW], ALLEXCEPT ( Products, Products[BU] ) )
			VAR result =
			    DIVIDE ( filtered_sales, bu_total )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\BU\LW
		lineageTag: 2731c0ff-acb1-4104-b4b7-6454cec67436

	measure 'Sales BU Mix % vs LW' =
			VAR act = [Sales BU Mix %]
			VAR comp = [Sales BU Mix % LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\BU\LW
		lineageTag: ae5e91a4-a562-4e42-b794-10f6a0081ac4

	measure 'Sales BU Mix % LY' =
			VAR filtered_sales = [SRIV LY]
			VAR bu_total =
			    CALCULATE ( [SRIV LY], ALLEXCEPT ( Products, Products[BU] ) )
			VAR result =
			    DIVIDE ( filtered_sales, bu_total )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\BU\LY
		lineageTag: 07af1125-01bc-4566-a3af-f3896228e253

	measure 'Sales BU Mix % LY-1' =
			VAR filtered_sales = [SRIV LY-1]
			VAR bu_total =
			    CALCULATE ( [SRIV LY-1], ALLEXCEPT ( Products, Products[BU] ) )
			VAR result =
			    DIVIDE ( filtered_sales, bu_total )
			RETURN
			    result
		description: Two years ago equivalent of Sales BU Mix % LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\BU\LY-1
		lineageTag: 5f60bdc8-c3c7-4da8-ba6b-e112189263bb

	measure 'Sales BU Mix % vs LY' =
			VAR act = [Sales BU Mix %]
			VAR comp = [Sales BU Mix % LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\BU\LY
		lineageTag: df47ca92-4b2a-4c09-ae19-835a044b3158

	measure 'Sales BU Mix % vs LY-1' =
			VAR act = [Sales BU Mix %]
			VAR comp = [Sales BU Mix % LY-1]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		description: Two years ago equivalent of Sales BU Mix % vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Sales Mix\BU\LY-1
		lineageTag: bbffc43c-5421-45d9-8aae-aafa9f53a991

	measure 'Stock BU Mix %' =
			VAR filtered_sales = [Stock]
			VAR bu_total =
			    CALCULATE ( [Stock], ALLEXCEPT ( Products, Products[BU] ) )
			VAR result =
			    DIVIDE ( filtered_sales, bu_total )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Stock\Stock Mix\BU\Actual
		lineageTag: d05384fb-1abd-47ce-a6f0-c53d3fec15e7

	measure 'Stock BU Mix % LW' =
			VAR filtered_sales = [Stock LW]
			VAR bu_total =
			    CALCULATE ( [Stock LW], ALLEXCEPT ( Products, Products[BU] ) )
			VAR result =
			    DIVIDE ( filtered_sales, bu_total )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Stock\Stock Mix\BU\LW
		lineageTag: d33437d1-d7b6-4c43-8d89-2d110dbf1c3b

	measure 'Stock BU Mix % vs LW' =
			VAR act = [Stock BU Mix %]
			VAR comp = [Stock BU Mix % LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Stock\Stock Mix\BU\LW
		lineageTag: 6f756b8f-6890-4851-a11d-fe036b3b5416

	measure 'Stock BU Mix % LY' =
			VAR filtered_sales = [Stock LY]
			VAR bu_total =
			    CALCULATE ( [Stock LY], ALLEXCEPT ( Products, Products[BU] ) )
			VAR result =
			    DIVIDE ( filtered_sales, bu_total )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Stock\Stock Mix\BU\LY
		lineageTag: 6c1f070e-4be2-44c5-87b5-ea0795d1c5d6

	measure 'Stock BU Mix % LY-1' =
			VAR filtered_sales = [Stock LY-1]
			VAR bu_total =
			    CALCULATE ( [Stock LY-1], ALLEXCEPT ( Products, Products[BU] ) )
			VAR result =
			    DIVIDE ( filtered_sales, bu_total )
			RETURN
			    result
		description: Two years ago equivalent of Stock BU Mix % LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Stock\Stock Mix\BU\LY-1
		lineageTag: c11dbaa7-c282-4e8b-b172-3e4956f8ef52

	measure 'Stock BU Mix % vs LY' =
			VAR act = [Stock BU Mix %]
			VAR comp = [Stock BU Mix % LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Stock\Stock Mix\BU\LY
		lineageTag: fbc3464e-6564-430a-ba57-1e8ff1cdb787

	measure 'Stock BU Mix % vs LY-1' =
			VAR act = [Stock BU Mix %]
			VAR comp = [Stock BU Mix % LY-1]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		description: Two years ago equivalent of Stock BU Mix % vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Stock\Stock Mix\BU\LY-1
		lineageTag: fc44a7ff-136d-4c56-9341-9f9bbbece3d0

	measure 'SRIV FPP FC' = CALCULATE ( [SRIV Channel FC], 'SalesType'[SalesType] = "FP&P" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: c307ef34-bb98-4ebb-bf29-2d1caf31f9b7

	measure 'SRIV Full Price FC' =
			VAR PlanVersion = [SlctdForecastVersion]
			Return
			CALCULATE ( [sum_FPSlsV], factForecast[plan] = PlanVersion )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: d667ebf4-2504-4f3d-a9e0-05f4c42f423f

	measure 'SRIV FPP vs FC' = [SRIV FPP] - [SRIV FPP FC]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 323fedf7-d491-447d-8944-98924cfaf07d

	measure 'SRIV Full Price vs FC' = [SRIV Full Price] - [SRIV Full Price FC]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 9fce352f-03f6-4a77-a897-59dff5761e1c

	measure 'SRIV Online FC' = CALCULATE ( [SRIV Channel FC], 'Channels'[Channel] = "Online" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: a11a464d-e674-4c3f-90c4-adcb0a89f8c5

	measure 'SRIV Online vs FC' = [SRIV Online] - [SRIV Online FC]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 83dd8982-e6ac-447d-b364-e16faef93223

	measure 'SRIV Promo FC' =
			VAR PlanVersion = [SlctdForecastVersion]
			Return
			CALCULATE ( [sum_PrSlsV], factForecast[plan] = PlanVersion )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 06e4f213-d1fe-439a-84d0-8dc1566b51e5

	measure 'SRIV Promo vs FC' = [SRIV Promo] - [SRIV Promo FC]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 77b12e11-5052-4113-81e8-62258099baca

	measure 'SRIV Reduced FC' =
			VAR PlanVersion = [SlctdForecastVersion]
			Return
			CALCULATE ( [sum_RedSlsV], factForecast[plan] = PlanVersion )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: e867d8c7-3f2b-4f01-91f2-95b4ebe69537

	measure 'SRIV Reduced vs FC' = [SRIV Reduced] - [SRIV Reduced FC]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 4f894b67-d6fa-41e9-9dac-b5e763a7d6a2

	measure 'SRIV Stores FC' = CALCULATE ( [SRIV Channel FC], 'Channels'[Channel] = "Stores" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: e0275385-7330-4c48-a725-53a30ef348dc

	measure 'SRIV Stores vs FC' = [SRIV Stores] - [SRIV Stores FC]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 56b4a2d0-105e-4ea0-bd36-41e261e56459

	measure 'SRIV FPP QRF' = CALCULATE ( [SRIV Channel QRF], 'SalesType'[SalesType] = "FP&P" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: dd4e7ea7-8c1d-4b6b-89dc-814d76562cdd

	measure 'SRIV FPP vs QRF' = [SRIV FPP] - [SRIV FPP QRF]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 4bbfc734-39fd-4dab-9c81-c41202d7ae5c

	measure 'SRIV Full Price QRF' =
			VAR PlanVersion = [SlctdQRFVersion]
			Return
			CALCULATE ( [sum_FPSlsV], factForecast[plan] = PlanVersion )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: c3a71987-d985-4a51-b04e-4f18368d6042

	measure 'SRIV Full Price vs QRF' = [SRIV Full Price] - [SRIV Full Price QRF]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 2f53046c-92c8-4634-803e-5e20e5492827

	measure 'SRIV Online QRF' = CALCULATE ( [SRIV Channel QRF], 'Channels'[Channel] = "Online" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 80540f82-4fe8-4e78-9717-1c74d3bab30d

	measure 'SRIV Online vs QRF' = [SRIV Online] - [SRIV Online QRF]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: cf601ce8-1ac7-4110-ba17-f24d34a2bea0

	measure 'SRIV Promo QRF' =
			VAR PlanVersion = [SlctdQRFVersion]
			Return
			CALCULATE ( [sum_PrSlsV], factForecast[plan] = PlanVersion )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: a0fe9552-122f-4606-b835-c5b274f6372b

	measure 'SRIV Promo vs QRF' = [SRIV Promo] - [SRIV Promo QRF]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 71e2c94a-e6a5-4fe6-8ca2-f4ae580d756c

	measure 'SRIV Reduced QRF' =
			VAR PlanVersion = [SlctdQRFVersion]
			Return
			CALCULATE ( [sum_RedSlsV], factForecast[plan] = PlanVersion )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: a833427c-9c95-4f3d-86f5-d49561644ea6

	measure 'SRIV Reduced vs QRF' = [SRIV Reduced] - [SRIV Reduced QRF]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 3e11bdfd-82a6-49ff-8aca-30146cd0ac15

	measure 'SRIV Stores QRF' = CALCULATE ( [SRIV Channel QRF], 'Channels'[Channel] = "Stores" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 2a3f247f-ad93-47e7-a505-867afb787146

	measure 'SRIV Stores vs QRF' = [SRIV Stores] - [SRIV Stores QRF]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 650def32-3409-495a-a5a5-f373eddf1578

	measure 'SRIV FPP LE' = CALCULATE ( [SRIV Channel LE], 'SalesType'[SalesType] = "FP&P" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: e6152f87-abc1-420f-9f27-f33737f62344

	measure 'SRIV FPP vs LE' = [SRIV FPP] - [SRIV FPP LE]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 0d549782-79af-459d-8d7f-689aff9b92e4

	measure 'SRIV Full Price LE' = CALCULATE ( [sum_FPSlsV], ForecastScenarios[Forecast Scenario] = "LE" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: d22a0034-0b5a-4fa9-8813-2475dbf9627d

	measure 'SRIV Full Price vs LE' = [SRIV Full Price] - [SRIV Full Price LE]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 6c825093-7fb5-425a-9e1a-efd1a9316472

	measure 'SRIV Online LE' = CALCULATE ( [SRIV Channel LE], 'Channels'[Channel] = "Online" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 426be23e-e8b9-40b1-bd79-0a466c4f439a

	measure 'SRIV Online vs LE' = [SRIV Online] - [SRIV Online LE]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: efd5e740-9f44-4d11-b000-1362b603c336

	measure 'SRIV Promo LE' = CALCULATE ( [sum_PrSlsV], ForecastScenarios[Forecast Scenario] = "LE" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 6c7d653d-ef8e-4a32-b801-f2acec8f1400

	measure 'SRIV Promo vs LE' = [SRIV Promo] - [SRIV Promo LE]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 83717542-5fea-43b9-ba73-4b5c56cd9248

	measure 'SRIV Reduced LE' = CALCULATE ( [sum_RedSlsV], ForecastScenarios[Forecast Scenario] = "LE" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 03d447ea-0562-4789-b367-eab02cc38c62

	measure 'SRIV Reduced vs LE' = [SRIV Reduced] - [SRIV Reduced LE]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: e0821786-b3f1-491d-b654-6aba3a54e86e

	measure 'SRIV Stores LE' = CALCULATE ( [SRIV Channel LE], 'Channels'[Channel] = "Stores" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: d80b1b09-126a-45f6-88e1-641bc0c37c66

	measure 'SRIV Stores vs LE' = [SRIV Stores] - [SRIV Stores LE]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\SRIV RG Measures
		lineageTag: 48838d7d-87a9-480f-8645-cc2d67ff5b01

	measure bu_total = CALCULATE ( [SRIV], ALLEXCEPT ( Products, Products[BU] ) )
		lineageTag: 9ab54efa-ac20-47c8-9473-da3ba3f90be3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure tiHeadlinesHeader = [tiWeekNo] & " | " & [tiProduct] & " | " & [tiChannel] & " | " & [tiSalesType] & " | " & [tiSalesRecogType]
		displayFolder: Dynamic Labels
		lineageTag: b1adfb06-f3a2-4b16-b89f-f729a9b1459d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'P&L vs BUD Colour' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR val = [P&L vs BUD]
			RETURN
			    SWITCH ( metric, "Markdown %", - val, val )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: P&L\BUD
		lineageTag: 01ab0873-7e43-4501-8a91-44f49f5d3190

	measure 'P&L vs BUD % Colour' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR val = [P&L vs BUD %]
			RETURN
			    SWITCH ( metric, "Markdown %", - val, val )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: P&L\BUD
		lineageTag: b176df1a-6822-45dc-85cc-12c3df48e6f7

	measure 'P&L vs FC Colour' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR val = [P&L vs FC]
			RETURN
			    SWITCH ( metric, "Markdown %", - val, val )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: P&L\FC
		lineageTag: 65a3aea6-fb5f-4346-b449-378a17e2fe69

	measure 'P&L vs FC % Colour' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR val = [P&L vs FC %]
			RETURN
			    SWITCH ( metric, "Markdown %", - val, val )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: P&L\FC
		lineageTag: c3d452b4-da72-4e8e-86de-cdce40a9dff1

	measure 'P&L vs LW Colour' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR val = [P&L vs LW]
			RETURN
			    SWITCH ( metric, "Markdown %", - val, val )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: P&L\LW
		lineageTag: be5afac5-98c0-44b1-b6ba-f6ef77f49a13

	measure 'P&L vs LW % Colour' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR val = [P&L vs LW %]
			RETURN
			    SWITCH ( metric, "Markdown %", - val, val )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: P&L\LW
		lineageTag: 97d3e5f8-3331-4335-baeb-06a2602b270e

	measure 'P&L vs LY Colour' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR val = [P&L vs LY]
			RETURN
			    SWITCH ( metric, "Markdown %", - val, val )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: P&L\LY
		lineageTag: 58889920-55f7-4428-9521-e2783379fc88

	measure 'P&L vs LY % Colour' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR val = [P&L vs LY %]
			RETURN
			    SWITCH ( metric, "Markdown %", - val, val )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: P&L\LY
		lineageTag: 187491f4-7316-49d6-a1ed-7ac984b139ba

	measure 'P&L vs QRF Colour' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR val = [P&L vs QRF]
			RETURN
			    SWITCH ( metric, "Markdown %", - val, val )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: P&L\QRF
		lineageTag: b143dbc0-3f12-43d4-84e5-8aa913eadebf

	measure 'P&L vs QRF % Colour' =
			VAR metric = [slctd_MetricMasterPnL]
			VAR val = [P&L vs QRF %]
			RETURN
			    SWITCH ( metric, "Markdown %", - val, val )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: P&L\QRF
		lineageTag: 16aaca95-0c07-46f6-b803-5276c425227a

	/// This measure is the sum of column 'factSalesOrders'[qty]
	measure 'Volume Orders' = CALCULATE(SUM ('factOrderVol'[qty] ), Filter(Products, Products[BU] <> "Other" && Products[BU] <> "GM Other"))
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\Volume\Actual
		lineageTag: b6079b7f-5f70-4fc9-9c33-d61c14a1e04f

	measure tiIncExOutlets =
			
			IF (
			IF (    SELECTEDVALUE ( OutletsControl[Ex Outlets/Outlets], "" ) = "M&S Ex Outlets", "M&S Ex Outlets", "Multi") = "M&S Ex Outlets",
			        IF (SELECTEDVALUE ( Channels[Channel], "" ) = "Stores", "Mainchain", SELECTEDVALUE ( Channels[Channel], "Mainchain & Online" )),
			        IF (
			                SELECTEDVALUE ( Channels[Channel], "All Channels" ) = "Stores",
			                SELECTEDVALUE ( Channels[Channel Detail], "Mainchain & Outlets" ),
			                SELECTEDVALUE ( Channels[Channel], "All Channels" )
			            )
			    )
		displayFolder: Dynamic Labels
		lineageTag: f77d3965-4234-4ea8-a2ba-bd89cb982298

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This measure is column [GSM Orders LW] as a % of SREV
	measure 'RP GSM % SREV BUD' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [GSM % SREV Orders BUD],
			        "Dispatch", [GSM % SREV Orders BUD],
			        [GSM % SREV Orders BUD]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\BUD RP
		lineageTag: 03260570-da42-4a35-a112-7c6ad70e0c7e

	measure 'RP GSM % SREV vs BUD' =
			VAR act = [GSM % SREV]
			VAR comp = [GSM % SREV BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\BUD RP
		lineageTag: 3994bfe0-e955-4368-af2e-619aa47c696a

	measure 'RP GSM BUD' =
			VAR result = [GSM Orders BUD]
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM\BUD RP
		lineageTag: 02ff6d38-5ba6-4432-a3ee-d51dbae78a4d

	measure 'RP GSM vs BUD' =
			VAR act = [GSM]
			VAR comp = [GSM BUD]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\GSM\BUD RP
		lineageTag: 7915cfc1-79ba-492b-b7f5-ee9e2edad979

	measure 'RP GSM vs BUD %' =
			VAR act = [GSM]
			VAR comp = [GSM BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\GSM\BUD RP
		lineageTag: 3f70148b-d4cb-415e-8e60-ffc58f8242af

	measure 'Reduced Markdown' = [Markdown]-[Promo Markdown]
		formatString: " #,##0,,.0;(#,##0,,.0)"
		displayFolder: Margin\Red Markdown\Actual
		lineageTag: 75b569b1-ae90-4102-9884-d424286e0cea

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Reduced Markdown BUD' = [Markdown BUD]-[Promo Markdown BUD]
		displayFolder: Margin\Red Markdown\BUD
		lineageTag: 3dc295d6-5751-4be9-8176-7e1b95dd49fb

	measure 'Reduced Markdown vs BUD' =
			VAR act = [Reduced Markdown]
			VAR comp = [Reduced Markdown BUD]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Red Markdown\BUD
		lineageTag: adcc657b-fbca-41d5-b741-3b30a6a18719

	measure 'Reduced Markdown %' = ```
			
			// [Markdown % SRIV]-[Promo Markdown %]
			
			VAR num = [Reduced Markdown]
			    
			VAR denom = [Reduced Markdown] - [SRIV Reduced]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
			
			```
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Red Markdown\Actual
		lineageTag: ca3b15cb-e22e-4a7e-a67d-d851bde3a6d9

	measure 'Reduced Markdown % BUD' = ```
			
			//[Markdown % SRIV BUD]-[Promo Markdown % BUD]
			
			VAR num = [Reduced Markdown BUD]
			    
			VAR denom = [Reduced Markdown BUD] - [SRIV Reduced BUD]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
			
			```
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Red Markdown\BUD
		lineageTag: 3e323870-55bc-4e95-b2ba-a0b5b9b2ec2a

	measure 'Reduced Markdown % vs BUD' =
			VAR act = [Reduced Markdown %]
			VAR comp = [Reduced Markdown % BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Red Markdown\BUD
		lineageTag: 90ce9c68-40d5-44b1-848d-1c884ed42c87

	measure 'Reduced Markdown vs BUD %' =
			VAR act = [Reduced Markdown]
			VAR comp = [Reduced Markdown BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Red Markdown\BUD
		lineageTag: 5edeee09-138d-4034-9149-ca7c9d6c949f

	measure 'Reduced Markdown LY' = [Markdown LY]-[Promo Markdown LY]
		displayFolder: Margin\Red Markdown\LY
		lineageTag: b07b18ea-1f7f-4531-9e2d-cbcf02e8107f

	measure 'Reduced Markdown LY-1' = [Markdown LY-1]-[Promo Markdown LY-1]
		displayFolder: Margin\Red Markdown\LY-1
		lineageTag: 268945a8-0a59-4994-a846-317ff2bb42f5

		description: Two years ago equivalent of Reduced Markdown LY.

	measure 'Reduced Markdown vs LY' =
			VAR act = [Reduced Markdown]
			VAR comp = [Reduced Markdown LY]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Red Markdown\LY
		lineageTag: 4a3c994a-c9ae-4281-99aa-9c9b58886daf

	measure 'Reduced Markdown vs LY-1' =
			VAR act = [Reduced Markdown]
			VAR comp = [Reduced Markdown LY-1]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		description: Two years ago equivalent of Reduced Markdown vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Red Markdown\LY-1
		lineageTag: e432f743-520e-4d8e-986a-5bcbf9451aee

	measure 'Reduced Markdown % LY' = ```
			
			//[Markdown % SRIV LY]-[Promo Markdown % LY]
			VAR num = [Reduced Markdown LY]
			    
			VAR denom = [Reduced Markdown LY] - [SRIV Reduced LY]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
			
			```
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Red Markdown\LY
		lineageTag: 431fd526-62a5-4fa4-968d-a302bbe8c3e1

	measure 'Reduced Markdown % LY-1' = ```
			
			//[Markdown % SRIV LY-1]-[Promo Markdown % LY-1]
			VAR num = [Reduced Markdown LY-1]
			    
			VAR denom = [Reduced Markdown LY-1] - [SRIV Reduced LY-1]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
			
			```
		description: Two years ago equivalent of Reduced Markdown % LY.
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Red Markdown\LY-1
		lineageTag: bfc017fa-20d0-47d3-88dd-ee309464bbab

	measure 'Reduced Markdown % vs LY' =
			VAR act = [Reduced Markdown %]
			VAR comp = [Reduced Markdown % LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Red Markdown\LY
		lineageTag: 4768294f-5622-4983-89ce-c4d57690f096

	measure 'Reduced Markdown % vs LY-1' =
			VAR act = [Reduced Markdown %]
			VAR comp = [Reduced Markdown % LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Reduced Markdown % vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Red Markdown\LY-1
		lineageTag: 340baf5d-92dc-4ad0-9bbd-c7f94cfed4fa

	measure 'Reduced Markdown vs LY %' =
			VAR act = [Reduced Markdown]
			VAR comp = [Reduced Markdown LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Red Markdown\LY
		lineageTag: ea348b1e-a858-4bca-a912-9d4594233fa0

	measure 'Reduced Markdown LW' = [Markdown LW]-[Promo Markdown LW]
		displayFolder: Margin\Red Markdown\LW
		lineageTag: 2b20ec95-82be-458e-bb54-19ac20444c52

	measure 'Reduced Markdown vs LW' =
			VAR act = [Reduced Markdown]
			VAR comp = [Reduced Markdown LW]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Red Markdown\LW
		lineageTag: a2460e74-4e61-457c-bf72-662b950d1ca8

	measure 'Reduced Markdown % LW' = ```
			
			 //[Markdown % SRIV LW]-[Promo Markdown % LW]
			
			VAR num = [Reduced Markdown LW]
			    
			VAR denom = [Reduced Markdown LW] - [SRIV Reduced LW]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
			
			```
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Red Markdown\LW
		lineageTag: fb2d8a83-68e4-467e-a3a5-5d9d8f010a07

	measure 'Reduced Markdown % vs LW' =
			VAR act = [Reduced Markdown %]
			VAR comp = [Reduced Markdown % LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Red Markdown\LW
		lineageTag: 62c919d7-f6fe-4e80-aef9-c65e4e44ae3c

	measure 'Reduced Markdown vs LW %' =
			VAR act = [Reduced Markdown]
			VAR comp = [Reduced Markdown LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Red Markdown\LW
		lineageTag: 6a2af566-c707-4854-bb9f-28d6e4783d10

	measure 'Reduced Markdown FC' = [Markdown FC]-[Promo Markdown FC]
		displayFolder: Margin\Red Markdown\FC
		lineageTag: bc1653d8-36d8-41a4-87c9-c3cafd85d997

	measure 'Reduced Markdown vs FC' =
			VAR act = [Reduced Markdown]
			VAR comp = [Reduced Markdown FC]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Red Markdown\FC
		lineageTag: 23fec532-87fc-45c9-bc93-073c818c1409

	measure 'Reduced Markdown % FC' = ```
			
			//[Markdown % SRIV FC]-[Promo Markdown % FC]
			
			VAR num = [Reduced Markdown FC]
			    
			VAR denom = [Reduced Markdown FC] - [SRIV Reduced FC]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
			
			```
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Red Markdown\FC
		lineageTag: 3d54e2ac-6382-402a-815c-784f9fb98a1b

	measure 'Reduced Markdown % vs FC' =
			VAR act = [Reduced Markdown %]
			VAR comp = [Reduced Markdown % FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Red Markdown\FC
		lineageTag: fc008db4-dad6-4bc0-90ee-ed2123c12477

	measure 'Reduced Markdown vs FC %' =
			VAR act = [Reduced Markdown]
			VAR comp = [Reduced Markdown FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Red Markdown\FC
		lineageTag: a45baf01-fcbd-4b69-8d0c-5babb8c70c91

	measure 'Reduced Markdown QRF' = [Markdown QRF]-[Promo Markdown QRF]
		displayFolder: Margin\Red Markdown\QRF
		lineageTag: eb4ae419-76f6-490b-8025-b79dcb7fa583

	measure 'Reduced Markdown vs QRF' =
			VAR act = [Reduced Markdown]
			VAR comp = [Reduced Markdown QRF]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Red Markdown\QRF
		lineageTag: 23a2e65b-8193-4f38-9a91-b90462987e0d

	measure 'Reduced Markdown % QRF' = [Markdown % SRIV QRF]-[Promo Markdown % QRF]
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Red Markdown\QRF
		lineageTag: 57d72ee2-0ac6-4429-944b-c63451071e47

	measure 'Reduced Markdown % vs QRF' =
			VAR act = [Reduced Markdown %]
			VAR comp = [Reduced Markdown % QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Red Markdown\QRF
		lineageTag: 17b03d11-68a5-44c1-9dfc-e9f69f6eddd4

	measure 'Reduced Markdown vs QRF %' =
			VAR act = [Reduced Markdown]
			VAR comp = [Reduced Markdown QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Red Markdown\QRF
		lineageTag: e9b37381-4be6-4b4a-86fc-2e8883754ee9

	measure ReturnsVolWorkings =
			
			VAR GrossSRIV_TY_PN =
			    DIVIDE (
			        [Gross SRIV],
			        CALCULATE ( [Gross SRIV], ALL ( Products[BU Code] ), ALL ( Products[BU] ) )
			    )
			VAR GrossSRIV_LY_Total =
			    CALCULATE ( [Gross SRIV LY], ALL ( Products[BU Code] ), ALL ( Products[BU] ) )
			VAR GrossSRIV_Mix = GrossSRIV_TY_PN * GrossSRIV_LY_Total //Works individually as a BU, doesn't work at total, doesn't cast because of calc
			VAR Returns_Mix =
			    SUMX (
			        SUMMARIZE ( Products, Products[Dept Code] ),
			        GrossSRIV_Mix * [Return rate %]
			    )
			VAR Returns_Mix_RR =
			    DIVIDE ( Returns_Mix, GrossSRIV_Mix )
			RETURN
			    Returns_Mix_RR
		formatString: 0.00
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: d8dd4fc4-c4f7-46ad-acb1-c61e1a160dd3

	measure ReturnsMixImpact =
			
			VAR ReturnsMix = SUMX(VALUES(Products[Dept]),[ReturnsVolWorkings])
			RETURN
			    ReturnsMix
			/*
			VAR GrossSRIV_LY_PN = DIVIDE(
			        [Gross SRIV LY],
			        CALCULATE ( [Gross SRIV LY], ALL ( Products[BU Code] ), ALL ( Products[BU] ) )
			    )
			VAR GrossSRIV_TY_Total =
			    CALCULATE ( [Gross SRIV], ALL ( Products[BU Code] ), ALL ( Products[BU] ) )
			VAR GrossSRIV_Mix = GrossSRIV_LY_PN * GrossSRIV_TY_Total
			Return [Return rate %] - Divide(ReturnsMix,GrossSRIV_Mix) */
		formatString: 0.00
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: a8aaf5c4-0eb0-4ba0-a544-5327f73ebd5c

	measure ReturnsRateWorkings = ```
			
			// Total TY Sales (ex Brands/Other)
			VAR GrossSRIV_TY_Total = CALCULATE ([Gross SRIV],ALL(Products[Dept]),FILTER(Products, Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			//TY Sales by Dept (ex Brands/Other)
			VAR GrossSRIVExBrands = CALCULATE ([Gross SRIV],FILTER(Products, Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			// TY PN of Total TY Sales by BU (ex Brands/Other)
			VAR GrossSRIV_TY_PN = DIVIDE(GrossSRIVExBrands,GrossSRIV_TY_Total)
			// Total LY Sales (ex Brands/Other)
			VAR GrossSRIV_LY_Total = CALCULATE ([Gross SRIV LY],ALL(Products[Dept]),FILTER(Products, Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			// LY Sales at TY Mix
			VAR GrossSRIV_Mix = GrossSRIV_TY_PN * GrossSRIV_LY_Total
			// LY Returns Rate * LY Sales at TY Mix
			VAR Returns_atLYRate = SUMX(SUMMARIZE(Products,Products[Dept]),GrossSRIV_Mix * [Return rate % LY])
			// Rate Percentage
			VAR ReturnsRatePct = DIVIDE(Returns_atLYRate,SUMX(SUMMARIZE(Products,Products[Dept]),GrossSRIV_Mix))
			RETURN 
			ReturnsRatePct
			```
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 3e5a0bc6-34c2-4a1a-a2d1-6b5f8481e4a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ReturnsRateImpact = [ReturnsRateWorkings] - [ReturnsVolImpact]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 4f04f0ff-2386-4690-904e-cff85bae95b4

	measure ReturnsOtherImpact = [Return rate %] - [ReturnsMixImpact] - [ReturnsRateImpact] - [Return rate % LY]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 4b8b38b9-defa-4cb0-b32e-b7ecaa2f03af

	measure HeadlineCommentary = ```
			
			Var Positive = ""
			Var Negative = ""
			
			// Sales Measures
			Var SalesValue  = FORMAT(DIVIDE([SRIV],1000000),"0.0m;-0.0m;0.0m;")
			Var SalesvsLW   = FORMAT([SRIV vs LW %], "+0.0%;-0.0%;0.0%")
			Var SalesvsLY   = if ([SRIV vs LY %] >= 0, Positive, Negative) & FORMAT([SRIV vs LY %], "+0.0%;-0.0%;0.0%")
			Var SalesvsBud  = FORMAT(DIVIDE([SRIV vs BUD],1000000),"+0.0m;-0.0m;0.0m;")
			Var SalesvsFC   = if ([SRIV vs FC] >= 0, Positive, Negative) & FORMAT(DIVIDE([SRIV vs FC],1000000),"+0.0m;-0.0m;0.0m;")
			Var SalesComp   = SWITCH([slctd_ComparatorMaster],
			                    "BUD", SalesvsBud & " vs BUD, ",
			                    "FC", SalesvsFC & " vs FC, ",
			                    SalesvsFC & " vs FC, " & SalesvsBud & " vs BUD, ")
			Var CommSales   = "Sales of " & SalesValue & ", " & SalesComp & SalesvsLW & " vs LW, " & SalesvsLY & " vs LY. "
			
			// GSM Measures
			Var GSMValue    = FORMAT(DIVIDE([GSM],1000000),"0.0m;-0.0m;0.0m;")
			Var GSMvsLW     = FORMAT([GSM vs LW %], "+0.0%;-0.0%;0.0%")
			Var GSMvsLY     = if ([GSM vs LY %] >= 0, Positive, Negative) & FORMAT([GSM vs LY %], "+0.0%;-0.0%;0.0%")
			Var GSMvsBud    = FORMAT(DIVIDE([GSM vs BUD],1000000),"+0.0m;-0.0m;0.0m;")
			Var GSMvsFC     = if ([GSM vs FC] >= 0, Positive, Negative) & FORMAT(DIVIDE([GSM vs FC],1000000),"+0.0m;-0.0m;0.0m;")
			Var GSMComp     = SWITCH([slctd_ComparatorMaster],
			                    "BUD", GSMvsBud & " vs BUD. ",
			                    "FC", GSMvsFC & " vs FC. ",
			                    GSMvsFC & " vs FC, " & GSMvsBud & " vs BUD. ")
			Var CommGSM     = "GSM was " & GSMValue & ", " & GSMComp
			
			// GSM % Measures
			Var GSMPCValue  = FORMAT([GSM % SREV], "0.0%;-0.0%;0.0%")
			Var GSMPCvsBUD  = if ([GSM % SREV vs BUD] >= 0, Positive, Negative) & FORMAT([GSM % SREV vs BUD] * 10000, "+0bps;-0bps;0bps")
			Var GSMPCvsFC   = FORMAT([GSM % SREV vs FC] * 10000, "+0bps;-0bps;0bps")
			Var GSMPCComp   = SWITCH([slctd_ComparatorMaster],
			                    "BUD", GSMPCvsBUD & " vs BUD. ",
			                    "FC", GSMPCvsFC & " vs FC. ",
			                    GSMPCvsFC & " vs FC, " & GSMPCvsBUD & " vs BUD. ")
			Var CommGSMPC   = "GSM % was " & GSMPCValue & ", " & GSMPCComp
			
			// FPP Measures
			Var FPP         = FORMAT(DIVIDE([SRIV FPP],1000000),"0.0m;-0.0m;0.0m;")
			Var FPPvsBUD    = FORMAT(DIVIDE([SRIV FPP vs BUD],1000000),"+0.0m;-0.0m;0.0m;")
			Var FPPvsFC     = if ([SRIV FPP vs FC] >= 0, Positive, Negative) & FORMAT(DIVIDE([SRIV FPP vs FC],1000000),"+0.0m;-0.0m;0.0m;")
			Var FPPvsLY     = if ([SRIV FPP vs LY %] >= 0, Positive, Negative) & FORMAT([SRIV FPP vs LY %], "+0.0%;-0.0%;0.0%")
			Var FPPComp     = SWITCH([slctd_ComparatorMaster],
			                    "BUD", FPPvsBUD & " vs BUD, ",
			                    "FC", FPPvsFC & " vs FC, ",
			                    FPPvsFC & " vs FC, " & FPPvsBUD & " vs BUD, ")
			Var CommFPP     = "FP&P Sales of " & FPP & ", " & FPPComp & FPPvsLY & " vs LY. "
			
			// RP Measures
			Var RP          = FORMAT(DIVIDE([SRIV Reduced],1000000),"0.0m;-0.0m;0.0m;")
			Var RPvsBUD     = FORMAT(DIVIDE([SRIV Reduced vs BUD],1000000),"+0.0m;-0.0m;0.0m;")
			Var RPvsFC      = if ([SRIV Reduced vs FC] >= 0, Positive, Negative) & FORMAT(DIVIDE([SRIV Reduced vs FC],1000000),"+0.0m;-0.0m;0.0m;")
			Var RPvsLY      = if ([SRIV Reduced vs LY %] >= 0, Positive, Negative) & FORMAT([SRIV Reduced vs LY %], "+0.0%;-0.0%;0.0%")
			Var RPComp      = SWITCH([slctd_ComparatorMaster],
			                    "BUD", RPvsBUD & " vs BUD, ",
			                    "FC", RPvsFC & " vs FC, ",
			                    RPvsFC & " vs FC, " & RPvsBUD & " vs BUD, ")
			Var CommRP     = "Reduced Sales of " & RP & ", " & FPPComp & RPvsLY & " vs LY. "
			
			Return 
			CommSales
			& UNICHAR(10) & " "
			& CommGSM & CommGSMPC
			& UNICHAR(10) & " "
			& CommFPP
			& UNICHAR(10) & " "
			& CommRP
			```
		displayFolder: Commentary
		lineageTag: 11ac439e-f858-49b1-9328-5e6ba7de76ba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DepartmentCommentary = ```
			
			---------------------
			-- BU Level Tables --
			---------------------
			VAR SummaryTable =
			    FILTER (
			        SUMMARIZE (
			            Products,
			            Products[BU],
			            "SRIVValue", [SRIV],
			            "SRIVvsFC", [SRIV vs FC],
			            "SRIVvsBUD", [SRIV vs BUD],
			            "SRIVvsLY%", [SRIV vs LY %]
			        ),
			        Products[BU] <> "Other"
			     && Products[BU] <> "Forecast Adj"
			     && Products[BU] <> "GM Other"
			     && Products[BU] <> "GM Non Core"
			     && Products[BU] <> "Energy"
			     && Products[BU] <> "Clothing Other"
			)
			
			VAR Ranked = ADDCOLUMNS (SummaryTable,
			                    "RankCol", RANK ( DENSE, SummaryTable, ORDERBY ( SWITCH([slctd_ComparatorMaster],"BUD",[SRIVvsBUD],"FC",[SRIVvsFC],[SRIVvsFC]), DESC )))
			
			VAR MaxNoRows = TOPN(1,SUMMARIZE ( Ranked, [RankCol] ),[RankCol], desc)
			
			-----------------------
			-- Dept Level Tables --
			-----------------------
			VAR SummaryTableDept =
			        SUMMARIZE (
			            Products,
			            Products[BU],
			            Products[Dept],
			            "SRIVValue", [SRIV],
			            "SRIVvsFC", [SRIV vs FC],
			            "SRIVvsBUD", [SRIV vs BUD],
			            "SRIVvsLY%", [SRIV vs LY %]
			        )
			
			-------------------------
			-- Commentary Workings --
			-------------------------
			// Top BU
			Var BULine1 = FILTER(Ranked,[RankCol] = 1)
			Var BU1Name = SUMMARIZE(BULine1,[BU])
			Var BU1SRIV = FORMAT(DIVIDE(SUMMARIZE(BULine1,[SRIVValue]),1000000),"0.0m;-0.0m;0.0m;")
			Var BU1vsBUD = FORMAT(DIVIDE(SUMMARIZE(BULine1,[SRIVvsBUD]),1000000),"+0.0m;-0.0m;0.0m;")
			Var BU1vsFC = FORMAT(DIVIDE(SUMMARIZE(BULine1,[SRIVvsFC]),1000000),"+0.0m;-0.0m;0.0m;")
			Var BU1vsLY = FORMAT(SUMMARIZE(BULine1,[SRIVvsLY%]), "+0.0%;-0.0%;0.0%")
			Var BU1Comp = SWITCH([slctd_ComparatorMaster],"FC", BU1vsFC & " vs FC ","BUD", BU1vsBUD & " vs BUD ",BU1vsFC & " vs FC, " & BU1vsBUD & " vs BUD ")
			Var BU1Commentary = "1. " & BU1Name & ", with sales of " & BU1SRIV & ", " & BU1Comp & " and "  & BU1vsLY & " vs LY."
			
			// 2nd BU
			Var BULine2 = FILTER(Ranked,[RankCol] = 2)
			Var BU2Name = SUMMARIZE(BULine2,[BU])
			Var BU2SRIV = FORMAT(DIVIDE(SUMMARIZE(BULine2,[SRIVValue]),1000000),"0.0m;-0.0m;0.0m;")
			Var BU2vsBUD = FORMAT(DIVIDE(SUMMARIZE(BULine2,[SRIVvsBUD]),1000000),"+0.0m;-0.0m;0.0m;")
			Var BU2vsFC = FORMAT(DIVIDE(SUMMARIZE(BULine2,[SRIVvsFC]),1000000),"+0.0m;-0.0m;0.0m;")
			Var BU2vsLY = FORMAT(SUMMARIZE(BULine2,[SRIVvsLY%]), "+0.0%;-0.0%;0.0%")
			Var BU2Comp = SWITCH([slctd_ComparatorMaster],"FC", BU2vsFC & " vs FC ","BUD", BU2vsBUD & " vs BUD ",BU2vsFC & " vs FC, " & BU2vsBUD & " vs BUD ")
			Var BU2Commentary = "2. " & BU2Name & ", with sales of " & BU2SRIV & ", " & BU2Comp & " and "  & BU2vsLY & " vs LY."
			
			// 3rd BU
			Var BULine3 = FILTER(Ranked,[RankCol] = 3)
			Var BU3Name = SUMMARIZE(BULine3,[BU])
			Var BU3SRIV = FORMAT(DIVIDE(SUMMARIZE(BULine3,[SRIVValue]),1000000),"0.0m;-0.0m;0.0m;")
			Var BU3vsBUD = FORMAT(DIVIDE(SUMMARIZE(BULine3,[SRIVvsBUD]),1000000),"+0.0m;-0.0m;0.0m;")
			Var BU3vsFC = FORMAT(DIVIDE(SUMMARIZE(BULine3,[SRIVvsFC]),1000000),"+0.0m;-0.0m;0.0m;")
			Var BU3vsLY = FORMAT(SUMMARIZE(BULine3,[SRIVvsLY%]), "+0.0%;-0.0%;0.0%")
			Var BU3Comp = SWITCH([slctd_ComparatorMaster],"FC", BU3vsFC & " vs FC ","BUD", BU3vsBUD & " vs BUD ",BU3vsFC & " vs FC, " & BU3vsBUD & " vs BUD ")
			Var BU3Commentary = "3. " & BU3Name & ", with sales of " & BU3SRIV & ", " & BU3Comp & " and "  & BU3vsLY & " vs LY."
			
			// Bottom BU
			Var BULine6 = FILTER(Ranked,[RankCol] = MaxNoRows)
			Var BU6Name = SUMMARIZE(BULine6,[BU])
			Var BU6SRIV = FORMAT(DIVIDE(SUMMARIZE(BULine6,[SRIVValue]),1000000),"0.0m;-0.0m;0.0m;")
			Var BU6vsBUD = FORMAT(DIVIDE(SUMMARIZE(BULine6,[SRIVvsBUD]),1000000),"+0.0m;-0.0m;0.0m;")
			Var BU6vsFC = FORMAT(DIVIDE(SUMMARIZE(BULine6,[SRIVvsFC]),1000000),"+0.0m;-0.0m;0.0m;")
			Var BU6vsLY = FORMAT(SUMMARIZE(BULine6,[SRIVvsLY%]), "+0.0%;-0.0%;0.0%")
			Var BU6Comp = SWITCH([slctd_ComparatorMaster],"FC", BU6vsFC & " vs FC ","BUD", BU6vsBUD & " vs BUD ",BU6vsFC & " vs FC, " & BU6vsBUD & " vs BUD ")
			Var BU6Commentary = "1. " & BU6Name & ", with sales of " & BU6SRIV & ", " & BU6Comp & " and "  & BU6vsLY & " vs LY."
			
			// Bottom BU -1
			Var BULine5 = FILTER(Ranked,[RankCol] = MaxNoRows - 1)
			Var BU5Name = SUMMARIZE(BULine5,[BU])
			Var BU5SRIV = FORMAT(DIVIDE(SUMMARIZE(BULine5,[SRIVValue]),1000000),"0.0m;-0.0m;0.0m;")
			Var BU5vsBUD = FORMAT(DIVIDE(SUMMARIZE(BULine5,[SRIVvsBUD]),1000000),"+0.0m;-0.0m;0.0m;")
			Var BU5vsFC = FORMAT(DIVIDE(SUMMARIZE(BULine5,[SRIVvsFC]),1000000),"+0.0m;-0.0m;0.0m;")
			Var BU5vsLY = FORMAT(SUMMARIZE(BULine5,[SRIVvsLY%]), "+0.0%;-0.0%;0.0%")
			Var BU5Comp = SWITCH([slctd_ComparatorMaster],"FC", BU5vsFC & " vs FC ","BUD", BU5vsBUD & " vs BUD ",BU5vsFC & " vs FC, " & BU5vsBUD & " vs BUD ")
			Var BU5Commentary = "2. " & BU5Name & ", with sales of " & BU5SRIV & ", " & BU5Comp & " and "  & BU5vsLY & " vs LY."
			
			// Bottom BU -2
			Var BULine4 = FILTER(Ranked,[RankCol] = MaxNoRows - 2)
			Var BU4Name = SUMMARIZE(BULine4,[BU])
			Var BU4SRIV = FORMAT(DIVIDE(SUMMARIZE(BULine4,[SRIVValue]),1000000),"0.0m;-0.0m;0.0m;")
			Var BU4vsBUD = FORMAT(DIVIDE(SUMMARIZE(BULine4,[SRIVvsBUD]),1000000),"+0.0m;-0.0m;0.0m;")
			Var BU4vsFC = FORMAT(DIVIDE(SUMMARIZE(BULine4,[SRIVvsFC]),1000000),"+0.0m;-0.0m;0.0m;")
			Var BU4vsLY = FORMAT(SUMMARIZE(BULine4,[SRIVvsLY%]), "+0.0%;-0.0%;0.0%")
			Var BU4Comp = SWITCH([slctd_ComparatorMaster],"FC", BU4vsFC & " vs FC ","BUD", BU4vsBUD & " vs BUD ",BU4vsFC & " vs FC, " & BU4vsBUD & " vs BUD ")
			Var BU4Commentary = "3. " & BU4Name & ", with sales of " & BU4SRIV & ", " & BU4Comp & " and "  & BU4vsLY & " vs LY."
			
			------------------------------
			-- Dept Commentary Workings --
			------------------------------
			// Top Dept
			Var Dept1Table = FILTER(SummaryTableDept, [BU] = BU1Name ) // Filter on BU, and Rank Table based on best/worst dept
			Var Dept1Rank = ADDCOLUMNS (Dept1Table,"BURankCol", RANK (DENSE, Dept1Table, ORDERBY ( SWITCH([slctd_ComparatorMaster],"BUD",[SRIVvsBUD],"FC",[SRIVvsFC],[SRIVvsFC]), DESC)))
			Var Dept1Line = FILTER(Dept1Rank,[BURankCol] = 1)
			Var Dept1Name = SUMMARIZE(Dept1Line,[Dept])
			Var Dept1SRIV = FORMAT(DIVIDE(SUMMARIZE(Dept1Line,[SRIVValue]),1000000),"0.0m;-0.0m;0.0m;")
			Var Dept1vsBUD = FORMAT(DIVIDE(SUMMARIZE(Dept1Line,[SRIVvsBUD]),1000000),"+0.0m;-0.0m;0.0m;")
			Var Dept1vsFC = FORMAT(DIVIDE(SUMMARIZE(Dept1Line,[SRIVvsFC]),1000000),"+0.0m;-0.0m;0.0m;")
			Var Dept1vsLY = FORMAT(SUMMARIZE(Dept1Line,[SRIVvsLY%]), "+0.0%;-0.0%;0.0%")
			Var Dept1Comp = SWITCH([slctd_ComparatorMaster],"FC", Dept1vsFC & " vs FC ","BUD", Dept1vsBUD & " vs BUD ",Dept1vsFC & " vs FC, " & Dept1vsBUD & " vs BUD ")
			Var Dept1Commentary = "(" & Dept1Name & ", with sales of " & Dept1SRIV & ", " & Dept1Comp & " and " & Dept1vsLY & " vs LY)"
			
			// Bottom Dept
			Var Dept6Table = FILTER(SummaryTableDept, [BU] = BU6Name ) // Filter on BU, and Rank Table based on best/worst dept
			Var Dept6Rank = ADDCOLUMNS (Dept6Table,"BURankCol", RANK (DENSE, Dept6Table, ORDERBY ( SWITCH([slctd_ComparatorMaster],"BUD",[SRIVvsBUD],"FC",[SRIVvsFC],[SRIVvsFC]), ASC)))
			Var Dept6Line = FILTER(Dept6Rank,[BURankCol] = 1)
			Var Dept6Name = SUMMARIZE(Dept6Line,[Dept])
			Var Dept6SRIV = FORMAT(DIVIDE(SUMMARIZE(Dept6Line,[SRIVValue]),1000000),"0.0m;-0.0m;0.0m;")
			Var Dept6vsBUD = FORMAT(DIVIDE(SUMMARIZE(Dept6Line,[SRIVvsBUD]),1000000),"+0.0m;-0.0m;0.0m;")
			Var Dept6vsFC = FORMAT(DIVIDE(SUMMARIZE(Dept6Line,[SRIVvsFC]),1000000),"+0.0m;-0.0m;0.0m;")
			Var Dept6vsLY = FORMAT(SUMMARIZE(Dept6Line,[SRIVvsLY%]), "+0.0%;-0.0%;0.0%")
			Var Dept6Comp = SWITCH([slctd_ComparatorMaster],"FC", Dept6vsFC & " vs FC ","BUD", Dept6vsBUD & " vs BUD ",Dept6vsFC & " vs FC, " & Dept6vsBUD & " vs BUD ")
			Var Dept6Commentary = "(" & Dept6Name & ", with sales of " & Dept6SRIV & ", " & Dept6Comp & " and " & Dept6vsLY & " vs LY)"
			
			------------
			-- Output --
			------------
			Return
			"Top BU Areas: "
			& UNICHAR(10) & " " &
			BU1Commentary
			& UNICHAR(10) & " " &
			Dept1Commentary
			& UNICHAR(10) & " " &
			BU2Commentary
			& UNICHAR(10) & " " 
			& UNICHAR(10) & " " &
			"Bottom BU Areas: "
			& UNICHAR(10) & " " &
			BU6Commentary
			& UNICHAR(10) & " " &
			Dept6Commentary
			& UNICHAR(10) & " " &
			BU5Commentary
			```
		displayFolder: Commentary
		lineageTag: 5c03d8d5-2e37-400c-ac02-9a8102b76d55

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross SRIV Mix %' =
			VAR line = [Gross SRIV]
			VAR parent_total = [Gross SRIV ProductParent]
			VAR result =
			    DIVIDE ( line, parent_total )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: d3851f4c-0110-4850-ac96-48873a8b3312

	measure 'Gross SRIV Mix % LY' =
			VAR line = [Gross SRIV LY]
			VAR parent_total = [Gross SRIV ProductParent LY]
			VAR result =
			    DIVIDE ( line, parent_total )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: 5e7add22-44fd-415b-ba6d-7aa21fa6b9eb

	measure 'Gross SRIV Mix % LY-1' =
			VAR line = [Gross SRIV LY-1]
			VAR parent_total = [Gross SRIV ProductParent LY-1]
			VAR result =
			    DIVIDE ( line, parent_total )
			RETURN
			    result
		description: Two years ago equivalent of Gross SRIV Mix % LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: 62a68935-e43a-4dee-9ed4-ff4d73b3c94d

	measure 'Gross SRIV Mix % vs LY' = [Gross SRIV Mix %] - [Gross SRIV Mix % LY]
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: 0877e664-2f4d-4952-9c41-280393fbd5ae

	measure 'Gross SRIV Mix % vs LY-1' = [Gross SRIV Mix %] - [Gross SRIV Mix % LY-1]
		description: Two years ago equivalent of Gross SRIV Mix % vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: 95f3a455-c624-431b-89de-8eeb981e9d0d

	measure gsriv_at_ly_mix_pct =
			VAR result =
			    SUMX ( VALUES ( Products[Dept] ), [Gross SRIV Mix % LY] * [Gross SRIV ProductParent] )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: 705f3ea4-267e-457e-a055-86f13100b938

	measure 'Gross SRIV ProductParent' =
			
			VAR total_bu =
			    CALCULATE (
			        [Gross SRIV]
			        ,REMOVEFILTERS ( Products[Dept], Products[Dept Code] )
			    )
			VAR total_all_products =
			    CALCULATE ( [Gross SRIV], ALLSELECTED ( Products ) )
			VAR parent_total =
			    SWITCH ( TRUE (), ISINSCOPE ( Products[Dept] ), total_bu, total_all_products )
			RETURN
			    parent_total
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: 181bf35b-b812-4589-9faf-7162ea745893

	measure 'Gross SRIV ProductParent LY' =
			VAR total_bu =
			    CALCULATE (
			        [Gross SRIV LY],
			        REMOVEFILTERS ( Products[Dept], Products[Dept Code] )
			    )
			VAR total_all_products =
			    CALCULATE ( [Gross SRIV LY], ALLSELECTED ( Products ) )
			VAR parent_total =
			    SWITCH ( TRUE (), ISINSCOPE ( Products[Dept] ), total_bu, total_all_products )
			RETURN
			    parent_total
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: 8814397d-a277-4dc1-944c-7dfe25ec8e99

	measure 'Gross SRIV ProductParent LY-1' =
			VAR total_bu =
			    CALCULATE (
			        [Gross SRIV LY-1],
			        REMOVEFILTERS ( Products[Dept], Products[Dept Code] )
			    )
			VAR total_all_products =
			    CALCULATE ( [Gross SRIV LY-1], ALLSELECTED ( Products ) )
			VAR parent_total =
			    SWITCH ( TRUE (), ISINSCOPE ( Products[Dept] ), total_bu, total_all_products )
			RETURN
			    parent_total
		description: Two years ago equivalent of Gross SRIV ProductParent LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: 084db406-8399-4f52-bc36-f2cb798ee8ea

	measure calc_gsriv_mix_at_ty_return_rate =
			VAR result =
			    SUMX ( VALUES ( Products[Dept] ), [Return Rate %] * [gsriv_at_ly_mix_pct] )
			RETURN
			    - result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: a2e8885c-4d90-4254-a4aa-4fa440bbce92

	measure calc_mix_return_rate =
			VAR result = DIVIDE ( [calc_gsriv_mix_at_ty_return_rate], [gsriv_at_ly_mix_pct] )
			RETURN - result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: 5e1bb06e-299c-4ca8-9e2e-5e9b232f992b

	measure 'RR Mix Impact %' = [Return rate %] - [calc_mix_return_rate]
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: 2f880663-b59a-49a9-97c4-be599ca7177f

	measure gsriv_at_ly_return_rate =
			VAR result =
			    SUMX ( VALUES ( Products[Dept] ), [Gross SRIV] * [Return rate % LY] )
			RETURN
			    - result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: f261326c-3d7b-488a-87ba-6f524286a3e0

	measure calc_rate_return_rate =
			VAR result = DIVIDE ( [gsriv_at_ly_return_rate], [Gross SRIV] )
			RETURN - result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: ee2efa19-a138-438f-b310-f6838525cbe8

	measure 'RR Rate Impact %' = [Return rate %] - [calc_rate_return_rate]
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: 2457bfc3-2e9a-40d9-a8c7-a700fdcb7f7d

	measure 'RR Other Impact %' =
			VAR delta = [Return rate %] - [Return rate % LY]
			VAR explained = [Rbr10_RRRateImpact] + [Rbr11_RRMixImpact]
			VAR remainder = delta - explained
			RETURN
			    remainder
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: 22612c49-89a4-4d76-af0a-def3935954a4

	measure 'RR Brands Impact %' =
			VAR delta_inc_brands = [Return rate % vs LY]
			VAR delta_ex_brands =
			    CALCULATE (
			        [Return rate % vs LY],
			        FILTER ( Products, Products[BU] <> "Brands" )
			    )
			VAR result = delta_inc_brands - delta_ex_brands
			RETURN
			    switch(result=0,true(),blank(),result)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: c2d60e6b-4bc1-4a99-9d27-ce07adf9702d

	measure 'RR Rate Impact % ex Brands' = CALCULATE ( [RR Rate Impact %], FILTER ( Products, Products[BU] <> "Brands" ) )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: 59752e52-c310-4e8c-abe8-cea38de6bf41

	measure 'RR Mix Impact % ex Brands' = CALCULATE ( [RR Mix Impact %], FILTER ( Products, Products[BU] <> "Brands" ) )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: f32433b5-9cbd-44fc-99da-20d468fea37f

	measure 'RR Other Impact % ex Brands' = ROUND(CALCULATE ( [RR Other Impact %], FILTER ( Products, Products[BU] <> "Brands" ) ),4)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: 78a5b6e4-823e-4100-bf10-0d2d4e3c8a55

	measure 'ReturnsBridge Value 2' =
			VAR _walk =
			    SELECTEDVALUE ( ReturnsBridgeWalk[WalkSort] )
			VAR result =
			    SWITCH (
			        _walk,
			        1,
			            SWITCH (
			                SELECTEDVALUE ( ReturnsBridge[Item] ),
			                "Brands", -[RR Brands Impact %],
			                "Rate", -[RR Rate Impact % ex Brands],
			                "Mix", -[RR Mix Impact % ex Brands],
			                "Other", -[RR Other Impact % ex Brands],
			                [Return rate % LY]
			            ),
			        2,
			            SWITCH (
			                SELECTEDVALUE ( ReturnsBridge[Item] ),
			                "Brands", 0,
			                "Rate", 0,
			                "Mix", 0,
			                "Other", 0,
			                [Return rate %]
			            )
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: 9f572b09-2cdd-4702-ad00-d9cf508f40a4

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'ReturnsBridge Value' =
			
			VAR _item =
			    SELECTEDVALUE ( 'ReturnsBridge'[Item] )
			VAR SelectedChannel = [Slctd_Channel]
			VAR result =
			    SWITCH (
			        _item,
			        "LY", [Return rate % LY],
			        "Brands", switch([RR Brands Impact %]=0,true(),blank(),[RR Brands Impact %]),
			        "Channel Mix", SWITCH(SelectedChannel,"Total",[RBR_ChMx_Var],blank()),
			        "Product Mix", [Rbr11_RRMixImpact] - SWITCH(SelectedChannel,"Total",[RBR_ChMx_Var],0),
			        "Rate", [Rbr10_RRRateImpact],
			        "Other", [RR Other Impact % ex Brands],
			        "TY", [Return rate %]
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: fa007f3e-d1d6-4001-bc29-53a3d9092a90

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure Mbr06_VAT =
			VAR comp_metric = [slctd_Variable]
			RETURN
			    IF ( comp_metric = "VAT", DIVIDE ( [Mbr01_SRIVMainchain], [Mbr05_SREVMainchainTrue] ) - 1 , [MbrComp06_VAT])
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Calculations
		lineageTag: 651e704f-e377-4caf-b03d-ed9601f27df0

	measure Mbr07_POS =
			VAR comp_metric = [slctd_Variable]
			VAR pos_pct =
			    SWITCH (
			        comp_metric,
			        "Vol", [MbrComp07_POS],
			        "FP&P Mix", [MbrComp07_POS],
			        "BIM", [MbrComp07_POS],
			        CALCULATE([Promo Markdown %], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			    )
			VAR sales = DIVIDE ( [Mbr02_SRIVFPP], 1 - pos_pct )
			RETURN
			    pos_pct * sales
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations
		lineageTag: b82cccaa-6aed-4e2b-8b9b-296ca683b0d5

	measure Mbr08_POSPct = DIVIDE ( [Mbr07_POS], [Mbr02_SRIVFPP] + [Mbr07_POS] )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Calculations
		lineageTag: 184ee34f-651a-49ee-96c4-f5b0c1383bcc

	measure Mbr09_SaleMD =
			VAR comp_metric = [slctd_Variable]
			VAR md_pct =
			    SWITCH (
			        comp_metric,
			        "Vol", [MbrComp08_SaleMDPct],
			        "FP&P Mix", [MbrComp08_SaleMDPct],
			        "BIM", [MbrComp08_SaleMDPct],
			        "POS", [MbrComp08_SaleMDPct],
			        CALCULATE([Sale Markdown %], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			    )
			RETURN
			    DIVIDE ( [Mbr03_SRIVRP], ( 1 - md_pct ) ) - [Mbr03_SRIVRP]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations
		lineageTag: 3c08be0c-76a5-4577-b12d-351eec1701cc

	measure MbrComp10_SaleMDExVAT =
			
			VAR comp = [slctd_MarginBridgeComparator]
			VAR result =
			    SWITCH (
			        comp,
			        "ACT", CALCULATE([Sale Markdown XV], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "LW", CALCULATE([Sale Markdown XV LW], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "QRF", CALCULATE([Sale Markdown XV QRF], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "FC", CALCULATE([Sale Markdown XV FC], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets",FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "BUD", CALCULATE([Sale Markdown XV BUD], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "LY", CALCULATE([Sale Markdown XV LY], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: 492ac7c4-0f9e-48c4-9366-de3a62be94f6

	measure Mbr10_SaleMDVAT = DIVIDE ( [Mbr09_SaleMD], [Mbr10_SaleMDExVAT] ) - 1
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Calculations
		lineageTag: 2d537a4c-4f56-4cc7-b0c6-2da817a000e1

	measure Mbr10_SaleMDExVAT =
			VAR comp_metric = [slctd_Variable]
			VAR vat_rate =
			    IF (
			        comp_metric = "VAT" && SELECTEDVALUE(SalesRecognitionType[SalesRecognitionType]) = "Orders",
			        CALCULATE (
			            [MbrComp11_SaleMDVAT],
			            ALL ( ComparatorMaster[Comparator] ),
			            MarginBridgeComparator[Comparator] = "ACT"
			        ),
			        [MbrComp11_SaleMDVAT]
			    )
			VAR ex_vat =
			    DIVIDE ( [Mbr09_SaleMD], ( 1 + vat_rate ) )
			RETURN
			    ex_vat
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations
		lineageTag: b5bbe1cf-21a9-4c40-a5ad-d572e30a99bd

		annotation PBI_FormatHint = {"isCustom":true}

	measure Mbr14_DOCPct2 = DIVIDE ( [Mbr09_SaleMD], [Mbr09_SaleMD] + [Mbr03_SRIVRP] )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Calculations
		lineageTag: b39c48ea-cc01-4384-9914-d466b8ff708d

	measure Mbr11_SaleMDPct = DIVIDE ( [Mbr09_SaleMD], [Mbr01_SRIVMainchain] )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Calculations
		lineageTag: 97396dcf-18b0-4176-87fa-412a20d7828c

	measure Mbr12_TotalMD = [Mbr07_POS] + [Mbr09_SaleMD]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations
		lineageTag: 7cdd5e4c-80f9-404b-bb12-09bb9a6c7a62

	measure Mbr13_MDPct = DIVIDE ( [Mbr12_TotalMD], [Mbr01_SRIVMainchain] )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Calculations
		lineageTag: 1d9f079f-f2cf-41bf-b83e-099a147c8c9c

	measure Mbr14_DOCPct = DIVIDE ( [Mbr12_TotalMD], [Mbr12_TotalMD] + [Mbr01_SRIVMainchain] )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Calculations
		lineageTag: 33551a2e-51bb-4c67-8821-1daef68ae41a

	measure Mbr15_GrossSRIV = [Mbr01_SRIVMainchain] + [Mbr12_TotalMD]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations
		lineageTag: 7a73d6b2-0862-41dd-857f-8d83d2d98663

	measure MbrComp14_GrossSREV =
			
			([MbrComp04_SRIV] - [MbrComp09_SaleMD] - [MbrComp12_POS])/(1+[MbrComp06_VAT])
			/*
			VAR FCVersion = [SlctdForecastVersion]
			VAR QRFVersions = [SlctdQRFVersion]
			VAR comp = [slctd_MarginBridgeComparator]
			VAR result =
			    SWITCH (
			        comp,
			        "ACT", CALCULATE ( [calc_TotGSlsxV] , factForecast[plan] = "RF", OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other" ),
			        "LW",
			            CALCULATE (
			                [calc_TotGSlsxV],
			                factForecast[plan] = "RF",
			                OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets",
			                Products[BU] <> "Other" && Products[BU] <> "GM Other",
			                USERELATIONSHIP ( factForecast[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			            ),
			        "QRF", CALCULATE ( [calc_TotGSlsxV], factForecast[plan] = QRFVersions  ,OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "FC", CALCULATE ( [calc_TotGSlsxV], factForecast[plan] = FCVersion  ,OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "BUD", CALCULATE ( [calc_TotGSlsxV], ForecastScenarios[Forecast Scenario] = "BUD" ,OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "LY",
			            CALCULATE (
			                [calc_TotGSlsxV],
			                factForecast[plan] = "RF",
			                OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets",
			                Products[BU] <> "Other" && Products[BU] <> "GM Other",
			                USERELATIONSHIP ( factForecast[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			            )
			    )
			RETURN
			    result
			*/
		formatString: #,##0,,.000;(#,##0,,.000)
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: 1bdd13a4-b16d-4b4d-aa22-a3ccdbcd2601

		annotation PBI_FormatHint = {"isCustom":true}

	measure Mbr16_GrossSREV = ```
			VAR comp_metric = [slctd_Variable]
			VAR at_comp_vat_rate =
			    DIVIDE ( [Mbr15_GrossSRIV], ( 1 + [MbrComp15_GrossVAT] ) )
			
			/* NOT REALLY WORKING!!
			VAR at_act_vat_rate =
			    DIVIDE (
			        calculate([Mbr15_GrossSRIV], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        (
			            1
			                + if(SELECTEDVALUE(SalesRecognitionType[SalesRecognitionType])="Order",
			                CALCULATE (
			                    [MbrComp15_GrossVAT],
			                    ALL ( ComparatorMaster[Comparator] ),
			                    MarginBridgeComparator[Comparator] = "ACT",
			                    OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", 
			                    FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")
			                ),
			                CALCULATE([MbrComp15_GrossVAT], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")))
			        )
			    )
			*/
			VAR at_act_vat_rate =
			    DIVIDE (
			        [Mbr15_GrossSRIV],
			        (
			            1
			                + if(SELECTEDVALUE(SalesRecognitionType[SalesRecognitionType])="Order",
			                CALCULATE (
			                    [MbrComp15_GrossVAT],
			                    ALL ( ComparatorMaster[Comparator] ),
			                    MarginBridgeComparator[Comparator] = "ACT"
			                ),
			                [MbrComp15_GrossVAT])
			        )
			    )
			VAR result =
			    SWITCH (
			        comp_metric,
			        "Vol", [MbrComp14_GrossSREV] * DIVIDE ( [Mbr01_SRIVMainchain], [MbrComp01_SRIVMainchain] ),
			        "FP&P Mix", at_comp_vat_rate,
			        "BIM", at_comp_vat_rate,
			        "POS", at_comp_vat_rate,
			        "DoC", at_comp_vat_rate,
			        "VAT", at_act_vat_rate
			    )
			RETURN
			    result
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations
		lineageTag: cfc22bb4-b93b-423c-8d58-f7aca8d05936

	measure MbrComp15_GrossVAT = DIVIDE ( [MbrComp13_GrossSRIV], [MbrComp14_GrossSREV]  ) - 1
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: 9088373e-f4e7-4580-bea2-693c51e2c81c

	measure MbrComp09_SaleMD =
			
			VAR comp = [slctd_MarginBridgeComparator]
			VAR result =
			    SWITCH (
			        comp,
			        "ACT", CALCULATE([Sale Markdown], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "LW", CALCULATE([Sale Markdown LW], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "QRF", CALCULATE([Sale Markdown QRF], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "FC", CALCULATE([Sale Markdown FC], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "BUD", CALCULATE([Sale Markdown BUD], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "LY", CALCULATE([Sale Markdown LY], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: d58baf7b-282a-4cb1-9b11-4b7306cce1bc

	measure MbrComp12_POS =
			VAR comp = [slctd_MarginBridgeComparator]
			VAR result =
			    SWITCH (
			        comp,
			        "ACT", CALCULATE([Promo Markdown], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "LW", CALCULATE([Promo Markdown LW], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "QRF", CALCULATE([Promo Markdown QRF], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "FC", CALCULATE([Promo Markdown FC], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "BUD", CALCULATE([Promo Markdown BUD], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "LY", CALCULATE([Promo Markdown LY], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			    )
			RETURN
			    SWITCH(SELECTEDVALUE(SalesType[SalesType]),"Reduced",0,result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: 8f78bde6-638b-44de-8e8a-93d72b74ff64

	measure MbrComp13_GrossSRIV = [MbrComp01_SRIVMainchain] - [MbrComp12_POS] - [MbrComp09_SaleMD]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: d5b99447-9c00-44b6-874f-54c819212173

	measure Mbr17_GrossVAT =
			
			VAR comp_metric = [slctd_Variable]
			RETURN
			    IF (
			        comp_metric = "VAT" && SELECTEDVALUE(SalesRecognitionType[SalesRecognitionType]) = "Orders",
			        CALCULATE (
			            [MbrComp15_GrossVAT],
			            ALL ( ComparatorMaster[Comparator] ),
			            MarginBridgeComparator[Comparator] = "ACT"
			        ),
			        [MbrComp15_GrossVAT]
			    )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Calculations
		lineageTag: e4ce3cf1-e836-45d3-8926-4edbca7695b3

	measure MbrComp17_COGS = -([MbrComp05_SREVMainchain] - [MbrComp18_GSM])
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: 530e89a4-f8e4-441f-b637-35474d801d39

	measure Mbr18_COGS =
			VAR comp_metric = [slctd_Variable]
			VAR at_comp_bim_rate = [Mbr16_GrossSREV] * ( 1 - [MbrComp16_BIMPct] )
			VAR at_act_bim_rate = [Mbr16_GrossSREV] * ( 1 - [Mbr18_BIMPct] )
			VAR result =
			    SWITCH (
			        comp_metric,
			        "Vol", -[MbrComp17_COGS] * DIVIDE ( [Mbr05_SREVMainchain], [MbrComp05_SREVMainchain] ),
			        "FP&P Mix", at_comp_bim_rate,
			        "BIM", at_act_bim_rate,
			        "POS", at_act_bim_rate,
			        "DoC", at_act_bim_rate,
			        "VAT", at_act_bim_rate
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations
		lineageTag: 5a86e376-b8d1-407f-b947-f6a5e4474313

	measure MbrComp16_BIMPct =
			1-(DIVIDE(-[MbrComp17_COGS],[MbrComp14_GrossSREV]))
			
			/* VAR comp = [slctd_MarginBridgeComparator]
			VAR result =
			    SWITCH (
			        comp,
			        "ACT", CALCULATE([Buying Margin %], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "LW", CALCULATE([Buying Margin % LW], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "QRF", CALCULATE([Buying Margin % QRF], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "FC", CALCULATE([Buying Margin % FC], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "BUD", CALCULATE([Buying Margin % BUD], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "LY", CALCULATE([Buying Margin % LY], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other")
			    )
			RETURN
			    result */
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: 7d6b7109-5263-4e3f-92fd-2bef7dbbeaa9

	measure Mbr19_GSM =
			
			[Mbr05_SREVMainchain] - [Mbr18_COGS]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations
		lineageTag: 4b1b06e1-f622-4d0c-9e79-2ffafc6ec38d

	measure Mbr20_GSMPct = DIVIDE ( [Mbr19_GSM], [Mbr05_SREVMainchain] )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Calculations
		lineageTag: b2b089fa-c77b-420d-baea-681357a9b0e9

	measure spacer = "-----"
		lineageTag: 1dff2c67-abe6-440e-9cc9-90336a1b0cac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MbrComp11_SaleMDVAT = DIVIDE ( [MbrComp09_SaleMD], [MbrComp10_SaleMDExVAT] ) - 1
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: beaad27d-c4a2-40f1-a541-259fc3df008e

	measure slctd_ComparatorMaster = SELECTEDVALUE(ComparatorMaster[Comparator],"Multi")
		displayFolder: Commentary
		lineageTag: 40a34d20-34e2-4fec-84fc-1d21120198c9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Combined Commentary' = [HeadlineCommentary] & UNICHAR(10) & " " & UNICHAR(10) & " " & [DepartmentCommentary]
		displayFolder: Commentary
		lineageTag: ffdd3628-1c42-49d3-acda-536967fe1e71

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MbrComp19_GSMPct =
			DIVIDE([MbrComp18_GSM],[MbrComp05_SREVMainchain])
			
			/*
			VAR comp = [slctd_MarginBridgeComparator]
			VAR result =
			    SWITCH (
			        comp,
			        "ACT", CALCULATE([GSM % SREV], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "LW", CALCULATE([GSM % SREV LW], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "QRF", CALCULATE([GSM % SREV QRF], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "FC", CALCULATE([GSM % SREV FC], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "BUD", CALCULATE([GSM % SREV BUD], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "LY", CALCULATE([GSM % SREV LY], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			    )
			RETURN
			    result
			    */
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: 4dde0e3f-a0e6-430f-962f-d25031271fbc

	measure tiMarginMetricSelectionVsComparator = "vs " & [MMS_slctd_Comparator]
		displayFolder: Dynamic Labels\MarginMeasureSelection
		lineageTag: b34c9ad9-f172-48e2-a406-a2c02657aed4

	measure tiVsLY = "vs LY"
		displayFolder: Dynamic Labels
		lineageTag: e7392573-872b-4916-a6ee-a87a07f0f968

	measure MbrComp18_GSM =
			VAR comp = [slctd_MarginBridgeComparator]
			VAR result =
			    SWITCH (
			        comp,
			        "ACT", CALCULATE([GSM], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "LW", CALCULATE([GSM LW], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "QRF", CALCULATE([GSM QRF], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "FC", CALCULATE([GSM FC], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "BUD", CALCULATE([GSM BUD], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "LY", CALCULATE([GSM LY], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			    )
			RETURN
			    result
		formatString: #,##0,,.000;(#,##0,,.000)
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: 9763c707-add6-4248-b9eb-61b554926a1a

		annotation PBI_FormatHint = {"isCustom":true}

	measure tiMarginBridgeVsComparator = "Margin Bridge vs " & SELECTEDVALUE ( MarginBridgeComparator[Comparator] )
		displayFolder: Dynamic Labels
		lineageTag: d0a8d636-f359-40bb-9b40-bc56e82e349a

	measure brands_rr_test = CALCULATE ( [Return rate % vs LY], FILTER(Products, Products[BU] <> "Brands" ))
		formatString: #,##0.0%;(#,##0.0)%
		lineageTag: c17fbfb7-e768-4968-ac44-3d4de9524cc0

		annotation PBI_FormatHint = {"isCustom":true}

	measure Volume =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Volume Orders],
			        "Dispatch", [Volume Dispatch],
			        [Volume Orders]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Volume\Actual
		lineageTag: 0537f4e5-7740-414e-b9ec-8e214d6e82ea

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Volume LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Volume Orders LY],
			        "Dispatch", [Volume Dispatch LY],
			        [Volume Orders LY]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Volume\LY
		lineageTag: 0fd7baf8-ef5c-48ca-8214-cef6f39e3735

	measure 'Volume LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Volume Orders LY-1],
			        "Dispatch", [Volume Dispatch LY-1],
			        [Volume Orders LY-1]
			    )
			RETURN
			    result
		description: Two years ago equivalent of Volume LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Volume\LY-1
		lineageTag: 8eb8b446-d1bc-4173-9b1a-971df6198bd2

	measure 'Volume vs LY' =
			VAR act = [Volume]
			VAR comp = [Volume LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Volume\LY
		lineageTag: 0ed982cd-a68a-43f1-ad70-9fd25b6d62b1

	measure 'Volume vs LY-1' =
			VAR act = [Volume]
			VAR comp = [Volume LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Volume vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Volume\LY-1
		lineageTag: 6fcda15d-b719-4a00-bb01-810f028ec3cf

	measure 'Volume vs LY %' =
			VAR act = [Volume]
			VAR comp = [Volume LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Volume\LY
		lineageTag: d8054c66-80cb-4a91-8b2c-1a5809ed709e

	measure 'Volume LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Volume Orders LW],
			        "Dispatch", [Volume Dispatch LW],
			        [Volume Orders LW]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Volume\LW
		lineageTag: 48016485-13c4-40ad-a752-8ffc0fc96883

	measure 'Volume vs LW' =
			VAR act = [Volume]
			VAR comp = [Volume LW]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Volume\LW
		lineageTag: b333ff84-c5ed-48c0-8d36-87326f9e4a9a

	measure 'Volume vs LW %' =
			VAR act = [Volume]
			VAR comp = [Volume LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Volume\LW
		lineageTag: 108f7790-1597-4c06-af20-ce4a7d4b4c23

	measure 'Volume Orders LY' =
			CALCULATE (
			    [Volume Orders],
			    USERELATIONSHIP ( factOrderVol[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\Volume\LY
		lineageTag: 33442499-a341-429c-ad0f-c035cb440fac

	measure 'Volume Orders LY-1' =
			CALCULATE (
			    [Volume Orders],
			    USERELATIONSHIP ( factOrderVol[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Volume Orders LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\Volume\LY-1
		lineageTag: 4de5edbd-4a6f-42ce-9784-a3586d4eab6a

	measure 'Volume Orders vs LY' =
			VAR act = [Volume Orders]
			VAR comp = [Volume Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\Volume\LY
		lineageTag: ce30d217-e6cc-41c5-8f51-4391d36596b6

	measure 'Volume Orders vs LY-1' =
			VAR act = [Volume Orders]
			VAR comp = [Volume Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Volume Orders vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\Volume\LY-1
		lineageTag: 55bf36e5-7db3-4b3c-808c-93e75dfd46f9

	measure 'Volume Orders vs LY %' =
			VAR act = [Volume Orders]
			VAR comp = [Volume Orders LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Volume\LY
		lineageTag: c48786cf-5522-4008-bbb9-1d69c9d39c93

	measure 'Volume Orders LW' =
			CALCULATE (
			    [Volume Orders],
			    USERELATIONSHIP ( factOrderVol[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\Volume\LW
		lineageTag: bee2dad4-d2fd-4800-bd77-0cf5a1488974

	measure 'Volume Orders vs LW' =
			VAR act = [Volume Orders]
			VAR comp = [Volume Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Orders\Volume\LW
		lineageTag: 17c752ad-7ec2-4757-a6ef-cc8350b69bc8

	measure 'Volume Orders vs LW %' =
			VAR act = [Volume Orders]
			VAR comp = [Volume Orders LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Orders\Volume\LW
		lineageTag: 8178d90b-091b-4245-95e0-52e945d35dec

	/// This measure is the sum of column 'factSalesDispatch[Full Price Sales (Inc VAT)]'
	measure 'FPP Volume Dispatch' = CALCULATE(SUM ( factSalesDispatch[Net Full Price Volume] ), Filter(Products, Products[BU] <> "Other" && Products[BU] <> "GM Other"))
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP Volume\Actual
		lineageTag: 990a03b4-a6eb-4a8d-afc7-878729dd049b

	measure 'FPP Volume Dispatch LY' =
			CALCULATE (
			    [FPP Volume Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP Volume\LY
		lineageTag: 8061b7f7-a256-4817-b16b-da9b97818f75

	measure 'FPP Volume Dispatch LY-1' =
			CALCULATE (
			    [FPP Volume Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of FPP Volume Dispatch LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP Volume\LY-1
		lineageTag: b6325a63-7a41-4eef-b37b-17fe29ec252c

	measure 'FPP Volume Dispatch vs LY' =
			VAR act = [FPP Volume Dispatch]
			VAR comp = [FPP Volume Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP Volume\LY
		lineageTag: c72a2875-c47d-48f9-9a8f-a41522de14ec

	measure 'FPP Volume Dispatch vs LY-1' =
			VAR act = [FPP Volume Dispatch]
			VAR comp = [FPP Volume Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of FPP Volume Dispatch vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP Volume\LY-1
		lineageTag: 24f349a3-e9f2-4452-8ff2-0d6c3e723f1a

	measure 'FPP Volume Dispatch vs LY %' =
			VAR act = [FPP Volume Dispatch]
			VAR comp = [FPP Volume Dispatch LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\FPP Volume\LY
		lineageTag: eb9b90b1-0da1-42a7-a947-81469d7af703

	measure 'FPP Volume Dispatch LW' =
			CALCULATE (
			    [FPP Volume Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP Volume\LW
		lineageTag: 7726439b-dc7f-4566-a15f-f7bd29e22dcf

	measure 'FPP Volume Dispatch vs LW' =
			VAR act = [FPP Volume Dispatch]
			VAR comp = [FPP Volume Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\FPP Volume\LW
		lineageTag: 89602ded-c2d3-42b8-8af9-0c9a82c207c6

	measure 'FPP Volume Dispatch vs LW %' =
			VAR act = [FPP Volume Dispatch]
			VAR comp = [FPP Volume Dispatch LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\FPP Volume\LW
		lineageTag: adb1da36-e7e8-4820-bafa-cd123e5738cf

	/// This measure is the sum of column 'factSalesDispatch[Reduced Price Sales (Inc VAT)]'
	measure 'RP Volume Dispatch' = CALCULATE( SUM ( factSalesDispatch[Net Reduced Price Volume] ), Filter(Products, Products[BU] <> "Other" && Products[BU] <> "GM Other"))
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP Volume\Actual
		lineageTag: fffed468-9304-4e68-b933-37acc760c1c0

	measure 'RP Volume Dispatch LY' =
			CALCULATE (
			    [RP Volume Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP Volume\LY
		lineageTag: 66d503b4-32bd-41ee-afff-3c437b2164b4

	measure 'RP Volume Dispatch LY-1' =
			CALCULATE (
			    [RP Volume Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of RP Volume Dispatch LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP Volume\LY-1
		lineageTag: db096f4a-e630-4665-9639-e84bb921d9f9

	measure 'RP Volume Dispatch vs LY' =
			VAR act = [RP Volume Dispatch]
			VAR comp = [RP Volume Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP Volume\LY
		lineageTag: 45324fff-879e-4738-b6b9-4ea46b4fbe00

	measure 'RP Volume Dispatch vs LY-1' =
			VAR act = [RP Volume Dispatch]
			VAR comp = [RP Volume Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of RP Volume Dispatch vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP Volume\LY-1
		lineageTag: b90da9ba-8968-4e5f-ad55-8b9ba4dc2668

	measure 'RP Volume Dispatch vs LY %' =
			VAR act = [RP Volume Dispatch]
			VAR comp = [RP Volume Dispatch LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\RP Volume\LY
		lineageTag: a1247f74-2abc-4e91-ba5c-0c490b1f290b

	measure 'RP Volume Dispatch LW' =
			CALCULATE (
			    [RP Volume Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP Volume\LW
		lineageTag: ddf88879-8fc0-4296-930a-d7c98a481138

	measure 'RP Volume Dispatch vs LW' =
			VAR act = [RP Volume Dispatch]
			VAR comp = [RP Volume Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\RP Volume\LW
		lineageTag: 52324946-4289-42c8-83ec-6078b3046be0

	measure 'RP Volume Dispatch vs LW %' =
			VAR act = [RP Volume Dispatch]
			VAR comp = [RP Volume Dispatch LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\RP Volume\LW
		lineageTag: 522a4e07-aea3-47b4-8f78-05d0a3082d1e

	/// This measure is the sum of column 'factSalesDispatch[Sales Revenue (Inc VAT)]'
	measure 'Volume Dispatch' =
			VAR sale_type = [slctd_SalesTypeLevelAware]
			VAR result =
			    SWITCH (
			        sale_type,
			        "Total", [sum_Total Net Volume],
			        "FP&P", [FPP Volume Dispatch],
			        "Full Price", BLANK (),
			        "Promo", BLANK (),
			        "Reduced", [RP Volume Dispatch],
			        [sum_Total Net Volume]
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\Volume\Actual
		lineageTag: 9986d2c2-6a76-4c6b-b3cd-49f69831f7f1

	measure 'Volume Dispatch LY' =
			CALCULATE (
			    [Volume Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\Volume\LY
		lineageTag: f64f5684-8c69-4943-a578-b7c0666b9fb8

	measure 'Volume Dispatch LY-1' =
			CALCULATE (
			    [Volume Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Volume Dispatch LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\Volume\LY-1
		lineageTag: db12c375-5ad2-41d8-af23-a6eb4539f38c

	measure 'Volume Dispatch vs LY' =
			VAR act = [Volume Dispatch]
			VAR comp = [Volume Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\Volume\LY
		lineageTag: 38559ac2-5af7-4d08-bd48-739ecbb3b276

	measure 'Volume Dispatch vs LY-1' =
			VAR act = [Volume Dispatch]
			VAR comp = [Volume Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Volume Dispatch vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\Volume\LY-1
		lineageTag: db846953-8f43-4828-9b34-0f74a375640b

	measure 'Volume Dispatch vs LY %' =
			VAR act = [Volume Dispatch]
			VAR comp = [Volume Dispatch LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Volume\LY
		lineageTag: 207ccede-4646-4eef-b485-ec6f06f12278

	measure 'Volume Dispatch LW' =
			CALCULATE (
			    [Volume Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\Volume\LW
		lineageTag: fe22e1be-aa52-4c8e-b5fa-1ca5b931f61c

	measure 'Volume Dispatch vs LW' =
			VAR act = [Volume Dispatch]
			VAR comp = [Volume Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Dispatch\Volume\LW
		lineageTag: ff8153f2-dc45-49fb-9fed-9a76c0d7361b

	measure 'Volume Dispatch vs LW %' =
			VAR act = [Volume Dispatch]
			VAR comp = [Volume Dispatch LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\Dispatch\Volume\LW
		lineageTag: 41a04469-dcea-4d76-be32-efb557208041

	measure 'FPP Intake Value' = CALCULATE ( [sum_fpp_rev_intake_val], factForecast[plan] = "RF" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\Actual
		lineageTag: fe148362-bc06-489a-b6da-28c258b71f32

	measure 'FPP Intake Value LY' =
			CALCULATE (
			    [FPP Intake Value],
			    USERELATIONSHIP ( factForecast[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\LY
		lineageTag: 8dd6629c-1b0c-4d02-bd4b-b54b5b7b3fa7

	measure 'FPP Intake Value LY-1' =
			CALCULATE (
			    [FPP Intake Value],
			    USERELATIONSHIP ( factForecast[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of FPP Intake Value LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\LY-1
		lineageTag: 26948d09-18dd-4b18-aaf0-e1ea9a0cacf8

	measure 'FPP Intake Value vs LY' =
			VAR act = [FPP Intake Value]
			VAR comp = [FPP Intake Value LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\LY
		lineageTag: e93f2a30-d6a9-4aaa-a441-0d7d887f4890

	measure 'FPP Intake Value vs LY-1' =
			VAR act = [FPP Intake Value]
			VAR comp = [FPP Intake Value LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of FPP Intake Value vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\LY-1
		lineageTag: bc71d2d1-a3af-4b67-a32d-442f3eaf39e3

	measure 'FPP Intake Value BUD' =
			CALCULATE (
			    [sum_fpp_rev_intake_val],
			    ForecastScenarios[Forecast Scenario] = "BUD"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\BUD
		lineageTag: 2f8e0ca3-f552-48cc-be47-bdc3d313ccbe

	measure 'FPP Intake Value vs BUD' =
			VAR act = [FPP Intake Value]
			VAR comp = [FPP Intake Value BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\BUD
		lineageTag: 59773b58-fa9f-4e9b-bedf-cc0d70d9e88b

	measure 'FPP Intake Value FC' =
			CALCULATE (
			    [sum_fpp_rev_intake_val],
			    ForecastScenarios[Forecast Scenario] = "FC"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\FC
		lineageTag: bf5a1bf0-d5f3-4dc9-80b4-dd7a0ba2b702

	measure 'FPP Intake Value vs FC' =
			VAR act = [FPP Intake Value]
			VAR comp = [FPP Intake Value FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\FC
		lineageTag: 52533cfb-19e0-44f6-bf8c-6374014048db

	measure 'FPP Intake Value QRF' =
			CALCULATE (
			    [sum_fpp_rev_intake_val],
			    ForecastScenarios[Forecast Scenario] = "QRF"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\QRF
		lineageTag: e51b1e6a-8c03-4963-9a33-0afda5f35eb0

	measure 'FPP Intake Value vs QRF' =
			VAR act = [FPP Intake Value]
			VAR comp = [FPP Intake Value QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\QRF
		lineageTag: a65f2c45-24d5-40eb-adcf-7ce41d8db20b

	measure 'FPP Intake Value vs LY %' =
			VAR act = [FPP Intake Value]
			VAR comp = [FPP Intake Value LY]
			VAR result = DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Intake\LY
		lineageTag: df295d43-3388-4104-93d1-aa84a58a6a8b

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'FPP Intake Volume vs LY %' =
			VAR act = [FPP Intake Volume]
			VAR comp = [FPP Intake Volume LY]
			VAR result = DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Intake\LY
		lineageTag: 24160826-86e1-42b0-b89b-1ff9b14ff7bf

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'FPP Intake Value vs QRF %' =
			VAR act = [FPP Intake Value]
			VAR comp = [FPP Intake Value QRF]
			VAR result = DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Intake\QRF
		lineageTag: a85c5138-94cc-406c-9cd5-fdb3f742b538

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'FPP Intake Volume vs QRF %' =
			VAR act = [FPP Intake Volume]
			VAR comp = [FPP Intake Volume QRF]
			VAR result = DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Intake\QRF
		lineageTag: 07db262f-d737-41ae-99c0-7a66af1dec69

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'ASP (SRIV)' = DIVIDE( [SRIV], [Volume], 0 )
		displayFolder: Sales\ASP
		lineageTag: e84cb7e7-ad34-418c-84ec-0bd5d6357333

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ASP LY (SRIV)' = DIVIDE( [SRIV LY], [Volume LY], 0 )
		displayFolder: Sales\ASP
		lineageTag: 317e0d22-2499-44ea-9be2-1511615a8300

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ASP (SRIV) (Based on LY)' = ```
			
			VAR PRODUCT_SCOPE = ISINSCOPE(Products[Dept]) || ISINSCOPE(Products[Dept Code])
			
			RETURN
			IF( PRODUCT_SCOPE = TRUE(), BLANK(),
			    
			    DIVIDE( [SRIV] , [Volume (Agg ASP CALC)], 0)
			    )
			```
		displayFolder: Sales\ASP
		lineageTag: 1cfe68cc-01e3-423d-9f92-5b46a0319538

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Volume (ASP CALC)' = DIVIDE([SRIV], [ASP LY (SRIV)], 0 )
		displayFolder: Sales\ASP
		lineageTag: aebb6e8a-770d-4735-80fa-4742c6bd1515

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Volume (Agg ASP CALC)' =
			
			SUMX(Products, [Volume (ASP CALC)])
		displayFolder: Sales\ASP
		lineageTag: 5c102789-fd06-4ada-a971-b7c1009935f3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ASP vs LY % (SRIV)' =
			
			VAR BLANKTEST = ISBLANK( [ASP (SRIV)] ) || ISBLANK( [ASP LY (SRIV)] )
			VAR RESULT = DIVIDE([ASP (SRIV)], [ASP LY (SRIV)], 0)-1
			RETURN
			    IF( BLANKTEST = FALSE(), RESULT, BLANK())
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\ASP
		lineageTag: 069debbd-88a7-4355-8e62-714bbf957a85

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'ASP (SRIV) % Increase (Mix)' =
			
			VAR BLANKTEST = ISBLANK( [ASP (SRIV) (Based on LY)]) || ISBLANK( [ASP LY (SRIV)])
			VAR RESULT = DIVIDE([ASP (SRIV) (Based on LY)], [ASP LY (SRIV)], 0)-1
			RETURN
			    IF( BLANKTEST = FALSE(), RESULT, BLANK())
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\ASP
		lineageTag: 2d914af0-572d-401d-95d8-a0e3f74ac58f

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'ASP (SRIV) % Increase (Price)' =
			
			VAR BLANKTEST = ISBLANK( [ASP (SRIV) % Increase (Mix)]) || ISBLANK( [ASP vs LY % (SRIV)] )
			VAR RESULT = [ASP vs LY % (SRIV)] - [ASP (SRIV) % Increase (Mix)]
			RETURN
			    IF( BLANKTEST = FALSE(), RESULT, BLANK())
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\ASP
		lineageTag: 344dfae4-e172-4565-b53a-5a6348fb3e63

		annotation PBI_FormatHint = {"isCustom":true}

	measure RBR_ChMx_Str_PN_TY =
			
			//Var Numerator = CALCULATE([Gross SRIV], ALL(ChannelControl),ALL(Channels),ChannelControl[Channel] = "Stores", OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets")
			//Var Denominator = CALCULATE([Gross SRIV], ALL(ChannelControl),ALL(Channels), OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets")
			//Var Denominator = [Gross SRIV]
			Var Numerator = CALCULATE([Gross SRIV], ALLSELECTED(ChannelControl),ALLSELECTED(Channels),ChannelControl[Channel] = "Stores")
			Var Denominator = CALCULATE([Gross SRIV], ALLSELECTED(ChannelControl),ALLSELECTED(Channels))
			Return
			DIVIDE(Numerator,Denominator,blank())
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: 8a7daac6-8986-4795-853f-04ba9491242a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RBR_ChMx_Str_PN_LY =
			
			//Var Numerator = CALCULATE([Gross SRIV LY], ALL(ChannelControl),ALL(Channels),ChannelControl[Channel] = "Stores", OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets")
			//Var Denominator = CALCULATE([Gross SRIV LY], ALL(ChannelControl),ALL(Channels), OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets")
			//Var Denominator = [Gross SRIV LY]
			Var Numerator = CALCULATE([Gross SRIV LY], ALLSELECTED(ChannelControl),ALLSELECTED(Channels),ChannelControl[Channel] = "Stores")
			Var Denominator = CALCULATE([Gross SRIV LY], ALLSELECTED(ChannelControl),ALLSELECTED(Channels))
			
			Return
			DIVIDE(Numerator,Denominator,blank())
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: e691543a-7312-4775-be2c-7704196111fa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RBR_ChMx_Web_PN_TY =
			
			SWITCH(AND(AND(ISBLANK([Gross SRIV]),ISBLANK([Returns])),AND(ISBLANK([Gross SRIV LY]),ISBLANK([Returns LY])))
			,TRUE(),Blank(),
			1-[RBR_ChMx_Str_PN_TY])
			//SWITCH(ISBLANK([RBR_ChMx_Str_PN_TY]),TRUE(),BLANK(),1-[RBR_ChMx_Str_PN_TY])
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: c2b6ad74-c2fb-46c0-817c-3d5e46c17172

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RBR_ChMx_Web_PN_LY =
			
			SWITCH(AND(ISBLANK([Gross SRIV LY]),ISBLANK([Returns LY]))
			,TRUE(),Blank(),
			1-[RBR_ChMx_Str_PN_LY])
			//SWITCH(ISBLANK([RBR_ChMx_Str_PN_LY]),TRUE(),BLANK(),1-[RBR_ChMx_Str_PN_LY])
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: 1bb6b119-ddca-4f4a-95e8-b3b6ba5c8df1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RBR_ChMx_Str_TY_at_LY_Mix =
			
			//Var TotSls = CALCULATE([Gross SRIV], ALL(ChannelControl),ALL(Channels), OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets")
			//Var TotSls = CALCULATE([Gross SRIV], ALLSELECTED(ChannelControl),ALLSELECTED(Channels))
			Var tbl = ADDCOLUMNS(VALUES(Products[Dept]),"Output",CALCULATE([Gross SRIV], ALLSELECTED(ChannelControl),ALLSELECTED(Channels)) * [RBR_ChMx_Str_PN_LY])
			Return
			Sumx(tbl,[Output])
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: c9a02670-d06f-4f10-aeaf-cbd29a1d6f2e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RBR_ChMx_Web_TY_at_LY_Mix =
			//Var TotSls = CALCULATE([Gross SRIV], ALLSELECTED(ChannelControl),ALLSELECTED(Channels))
			//Return
			//TotSls * [RBR_ChMx_Web_PN_LY]
			Var tbl = ADDCOLUMNS(VALUES(Products[Dept]),"Output",CALCULATE([Gross SRIV], ALLSELECTED(ChannelControl),ALLSELECTED(Channels)) * [RBR_ChMx_Web_PN_LY])
			Return
			Sumx(tbl,[Output])
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: 23dff75c-1849-41f2-bd61-6bf0a8401f1d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RBR_ChMx_StrRtn_at_TY_rate = ```
			
			//Var ReturnRate = Calculate([Return rate %],all(ChannelControl),all(Channels),ChannelControl[Channel] = "Stores", OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets")
			//Var ReturnRate = Calculate([Return rate %],ALLSELECTED(ChannelControl),ALLSELECTED(Channels),ChannelControl[Channel] = "Stores")
			//Return 
			//ReturnRate * [RBR_ChMx_Str_TY_at_LY_Mix]
			Var tbl = ADDCOLUMNS(VALUES(Products[Dept]),"Output",Calculate([Return rate %],ALLSELECTED(ChannelControl),ALLSELECTED(Channels),ChannelControl[Channel] = "Stores") * [RBR_ChMx_Str_TY_at_LY_Mix])
			Return
			Sumx(tbl,[Output])
			```
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: e8b93aa8-c074-4e5d-af13-6a8933cbffa6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RBR_ChMx_WebRtn_at_TY_rate = ```
			
			//Var ReturnRate = Calculate([Return rate %],all(ChannelControl),all(Channels),ChannelControl[Channel] = "Online", OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets")
			//Var ReturnRate = Calculate([Return rate %],ALLSELECTED(ChannelControl),ALLSELECTED(Channels),ChannelControl[Channel] = "Online")
			//Return 
			//ReturnRate * [RBR_ChMx_Web_TY_at_LY_Mix]
			Var tbl = ADDCOLUMNS(VALUES(Products[Dept]),"Output",Calculate([Return rate %],ALLSELECTED(ChannelControl),ALLSELECTED(Channels),ChannelControl[Channel] = "Online") * [RBR_ChMx_Web_TY_at_LY_Mix])
			Return
			Sumx(tbl,[Output])
			```
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: e6af188f-58bc-4341-968c-073d31d7a987

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RBR_ChMx_Tot_ReworkedSales = CALCULATE([RBR_ChMx_Str_TY_at_LY_Mix]+[RBR_ChMx_Web_TY_at_LY_Mix], Products[BU] <> "Brands")
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: ce901e6a-8195-4ebe-a334-b1b634ef1594

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RBR_ChMx_Tot_Returns = CALCULATE([RBR_ChMx_StrRtn_at_TY_rate] + [RBR_ChMx_WebRtn_at_TY_rate], Products[BU] <> "Brands")
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: a4086196-f8d9-44df-898a-2147c185161d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure RBR_ChMx_Rate = ```
			
			Var Tbl = ADDCOLUMNS(VALUES(Products[Dept]),"Sales",[RBR_ChMx_Tot_ReworkedSales],"Returns",[RBR_ChMx_Tot_Returns])
			RETURN 
			DIVIDE(SUMX(Tbl,[Returns]),SUMX(Tbl,[Sales]),0)
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: 61111e72-99b8-4a75-a036-0726fd72d6e8

	measure RBR_ChMx_Var = ```
			
			VAR delta_ex_brands =
			    CALCULATE (
			        [Return rate % LY],
			        FILTER ( Products, Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other")
			    )
			RETURN
			[RBR_ChMx_Rate] - delta_ex_brands
			
			//OldTests
			//Var tbl = ADDCOLUMNS(FILTER(VALUES(Products),Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other"),"Gross SRIV LY",[Gross SRIV LY],"Returns LY", -[Returns LY])
			//DIVIDE(Sumx(tbl,[Returns LY]),SUMX(tbl,[Gross SRIV LY]),0) - [RBR_ChMx_Rate] 
			//CALCULATE([Return rate % LY], Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other") - [RBR_ChMx_Rate]
			//[Return rate % LY] - [RBR_ChMx_Rate] 
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales\Returns\Returns Mix
		lineageTag: 3a1c5c10-b459-492d-bc75-59bd700b4b10

	measure 'FPP SRIV vs LY %' =
			VAR act = CALCULATE([SRIV], SalesType[SalesType] = "FP&P")
			VAR comp = CALCULATE([SRIV LY], SalesType[SalesType] = "FP&P")
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Sales\SRIV\LY
		lineageTag: 632bcc96-0317-465b-b37b-ce0ff19afda2

		annotation PBI_FormatHint = {"isCustom":true}

	measure ReturnsMixWorkings =
			
			VAR LYSales = SUMX(SUMMARIZE(Products,Products[Dept]),CALCULATE([Gross SRIV LY],FILTER(Products,Products[BU]<>"Brands" && Products[BU]<>"Other" && Products[BU]<>"GM Other")))
			VAR LYReturns = SUMX(SUMMARIZE(Products,Products[Dept]),CALCULATE([Returns LY],FILTER(Products,Products[BU]<>"Brands" && Products[BU]<>"Other" && Products[BU]<>"GM Other")))
			Return
			DIVIDE(LYReturns,LYSales)
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 0f0621ab-40ac-4c05-a966-dc5033e9103f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ReturnsVolImpact = [ReturnsVolWorkings] - [ReturnsRateExBrandsOther]
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: b5683896-ffa6-4fbb-9e44-7109ba07e748

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ReturnsRateExBrandsOther = CALCULATE([Return rate %],FILTER(Products,Products[BU]<>"Brands" && Products[BU]<>"Other" && Products[BU]<>"GM Other"))
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: b573295b-a9dd-422e-889e-deae0c3b2326

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RR Vol 1 Total TY Sales' =
			
			// Total TY Sales (ex Brands/Other)
			VAR GrossSRIV_TY_Total = CALCULATE ([Gross SRIV], All(Products),Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other")
			//TY Sales by Dept (ex Brands/Other)
			VAR GrossSRIVExBrands = CALCULATE ([Gross SRIV],FILTER(Products, Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			// TY PN of Total TY Sales by BU (ex Brands/Other)
			VAR GrossSRIV_TY_PN = DIVIDE(GrossSRIVExBrands,GrossSRIV_TY_Total)
			// Total LY Sales (ex Brands/Other)
			VAR GrossSRIV_LY_Total = CALCULATE ([Gross SRIV LY],All(Products),Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other")
			// LY Sales at TY Mix
			VAR GrossSRIV_Mix = GrossSRIV_TY_PN * GrossSRIV_LY_Total
			// Iterative Sum of Returns by Department
			VAR ReturnsTbl = ADDCOLUMNS(VALUES(Products[Dept]), "Returns", [Return rate %] * GrossSRIV_Mix)
			// Returns Rate
			Var Returns = SUMX(ReturnsTbl,[Returns])
			VAR Returns_Vol_RR = DIVIDE(Returns, GrossSRIV_Mix)
			VAR TestReturns = GrossSRIV_Mix
			RETURN GrossSRIV_TY_Total
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: eb0e4c31-97cb-4a64-95d2-0c3e88eb6706

	measure 'RR Vol 2 SRIV by Dept' =
			
			// Total TY Sales (ex Brands/Other)
			VAR GrossSRIV_TY_Total = CALCULATE ([Gross SRIV], All(Products),Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other")
			//TY Sales by Dept (ex Brands/Other)
			VAR GrossSRIVExBrands = CALCULATE ([Gross SRIV],FILTER(Products, Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			// TY PN of Total TY Sales by BU (ex Brands/Other)
			VAR GrossSRIV_TY_PN = DIVIDE(GrossSRIVExBrands,GrossSRIV_TY_Total)
			// Total LY Sales (ex Brands/Other)
			VAR GrossSRIV_LY_Total = CALCULATE ([Gross SRIV LY],All(Products),Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other")
			// LY Sales at TY Mix
			VAR GrossSRIV_Mix = GrossSRIV_TY_PN * GrossSRIV_LY_Total
			// Iterative Sum of Returns by Department
			VAR ReturnsTbl = ADDCOLUMNS(VALUES(Products[Dept]), "Returns", [Return rate %] * GrossSRIV_Mix)
			// Returns Rate
			Var Returns = SUMX(ReturnsTbl,[Returns])
			VAR Returns_Vol_RR = DIVIDE(Returns, GrossSRIV_Mix)
			VAR TestReturns = GrossSRIV_Mix
			RETURN GrossSRIVExBrands
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 674a9951-bc71-42f8-a153-79fe2e8af427

	measure 'RR Vol 3 PN of Sales' =
			
			// Total TY Sales (ex Brands/Other)
			VAR GrossSRIV_TY_Total = CALCULATE ([Gross SRIV], All(Products),Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other")
			//TY Sales by Dept (ex Brands/Other)
			VAR GrossSRIVExBrands = CALCULATE ([Gross SRIV],FILTER(Products, Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			// TY PN of Total TY Sales by BU (ex Brands/Other)
			VAR GrossSRIV_TY_PN = DIVIDE(GrossSRIVExBrands,GrossSRIV_TY_Total)
			// Total LY Sales (ex Brands/Other)
			VAR GrossSRIV_LY_Total = CALCULATE ([Gross SRIV LY],All(Products),Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other")
			// LY Sales at TY Mix
			VAR GrossSRIV_Mix = GrossSRIV_TY_PN * GrossSRIV_LY_Total
			// Iterative Sum of Returns by Department
			VAR ReturnsTbl = ADDCOLUMNS(VALUES(Products[Dept]), "Returns", [Return rate %] * GrossSRIV_Mix)
			// Returns Rate
			Var Returns = SUMX(ReturnsTbl,[Returns])
			VAR Returns_Vol_RR = DIVIDE(Returns, GrossSRIV_Mix)
			VAR TestReturns = GrossSRIV_Mix
			RETURN GrossSRIV_TY_PN
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: a7b8d8cb-dac5-45a2-8aed-71ff4efde6fd

	measure 'RR Vol 4 LY Sales' =
			
			// Total TY Sales (ex Brands/Other)
			VAR GrossSRIV_TY_Total = CALCULATE ([Gross SRIV], All(Products),Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other")
			//TY Sales by Dept (ex Brands/Other)
			VAR GrossSRIVExBrands = CALCULATE ([Gross SRIV],FILTER(Products, Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			// TY PN of Total TY Sales by BU (ex Brands/Other)
			VAR GrossSRIV_TY_PN = DIVIDE(GrossSRIVExBrands,GrossSRIV_TY_Total)
			// Total LY Sales (ex Brands/Other)
			VAR GrossSRIV_LY_Total = CALCULATE ([Gross SRIV LY],All(Products),Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other")
			// LY Sales at TY Mix
			VAR GrossSRIV_Mix = GrossSRIV_TY_PN * GrossSRIV_LY_Total
			// Iterative Sum of Returns by Department
			VAR ReturnsTbl = ADDCOLUMNS(VALUES(Products[Dept]), "Returns", [Return rate %] * GrossSRIV_Mix)
			// Returns Rate
			Var Returns = SUMX(ReturnsTbl,[Returns])
			VAR Returns_Vol_RR = DIVIDE(Returns, GrossSRIV_Mix)
			VAR TestReturns = GrossSRIV_Mix
			RETURN GrossSRIV_LY_Total
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: e07607c8-0a49-4a5c-a1f4-c0d2a583840d

	measure 'RR Vol 5 LY Sales TY Mix' =
			
			// Total TY Sales (ex Brands/Other)
			VAR GrossSRIV_TY_Total = CALCULATE ([Gross SRIV], All(Products),Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other")
			//TY Sales by Dept (ex Brands/Other)
			VAR GrossSRIVExBrands = CALCULATE ([Gross SRIV],FILTER(Products, Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			// TY PN of Total TY Sales by BU (ex Brands/Other)
			VAR GrossSRIV_TY_PN = DIVIDE(GrossSRIVExBrands,GrossSRIV_TY_Total)
			// Total LY Sales (ex Brands/Other)
			VAR GrossSRIV_LY_Total = CALCULATE ([Gross SRIV LY],All(Products),Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other")
			// LY Sales at TY Mix
			VAR GrossSRIV_Mix = GrossSRIV_TY_PN * GrossSRIV_LY_Total
			// Iterative Sum of Returns by Department
			VAR ReturnsTbl = ADDCOLUMNS(VALUES(Products[Dept]), "Returns", [Return rate %] * GrossSRIV_Mix)
			// Returns Rate
			Var Returns = SUMX(ReturnsTbl,[Returns])
			VAR Returns_Vol_RR = DIVIDE(Returns, GrossSRIV_Mix)
			VAR TestReturns = GrossSRIV_Mix
			RETURN GrossSRIV_Mix
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 00425cbc-da38-437c-a49d-3c13ffe8fe1d

	measure 'RR Vol 6 returns at ty rate' =
			
			// Total TY Sales (ex Brands/Other)
			VAR GrossSRIV_TY_Total = CALCULATE ([Gross SRIV], All(Products),Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other")
			//TY Sales by Dept (ex Brands/Other)
			VAR GrossSRIVExBrands = CALCULATE ([Gross SRIV],FILTER(Products, Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			// TY PN of Total TY Sales by BU (ex Brands/Other)
			VAR GrossSRIV_TY_PN = DIVIDE(GrossSRIVExBrands,GrossSRIV_TY_Total)
			// Total LY Sales (ex Brands/Other)
			VAR GrossSRIV_LY_Total = CALCULATE ([Gross SRIV LY],All(Products),Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other")
			// LY Sales at TY Mix
			VAR GrossSRIV_Mix = GrossSRIV_TY_PN * GrossSRIV_LY_Total
			// Iterative Sum of Returns by Department
			VAR ReturnsTbl = ADDCOLUMNS(VALUES(Products[Dept]), "TblSRIV", GrossSRIV_Mix, "TblRR", [Return rate %], "TblReturns", GrossSRIV_Mix * [Return rate %])
			// Returns Rate
			Var Returns =  SUMX(ReturnsTbl,[TblReturns])
			VAR Returns_Vol_RR = DIVIDE(Returns, GrossSRIV_Mix)
			VAR TestReturns = GrossSRIV_Mix
			RETURN Returns
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 854365cf-5e36-4f4e-8a63-d90994d28b95

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'RR Vol 7 returns rate' =
			
			// Total TY Sales (ex Brands/Other)
			VAR GrossSRIV_TY_Total = CALCULATE ([Gross SRIV], All(Products),Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other")
			//TY Sales by Dept (ex Brands/Other)
			VAR GrossSRIVExBrands = CALCULATE ([Gross SRIV],FILTER(Products, Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			// TY PN of Total TY Sales by BU (ex Brands/Other)
			VAR GrossSRIV_TY_PN = DIVIDE(GrossSRIVExBrands,GrossSRIV_TY_Total)
			// Total LY Sales (ex Brands/Other)
			VAR GrossSRIV_LY_Total = CALCULATE ([Gross SRIV LY],All(Products),Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other")
			// LY Sales at TY Mix
			VAR GrossSRIV_Mix = GrossSRIV_TY_PN * GrossSRIV_LY_Total
			// Iterative Sum of Returns by Department
			VAR ReturnsTbl = ADDCOLUMNS(VALUES(Products[Dept]), "Returns", [Return rate %] * GrossSRIV_Mix)
			// Returns Rate
			Var Returns = SUMX(ReturnsTbl,[Returns])
			VAR Returns_Vol_RR = DIVIDE(Returns, GrossSRIV_Mix)
			VAR TestReturns = GrossSRIV_Mix
			RETURN Returns_Vol_RR
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 8a4a7a23-5d3e-4ef5-963b-a5d22265b672

	measure 'RR VolNewtest' =
			
			VAR Allrows = All(Products[Dept])
			VAR Tbl = ADDCOLUMNS(Allrows,"TblTY",[Gross SRIV],"TblLY", [Gross SRIV LY], "TblRetTY", [Returns], "TblRetLY", [Returns LY])
			// Total TY Sales (ex Brands/Other)
			VAR GrossSRIV_TY_Total = CALCULATE(SUMX(Tbl, [TblTY]))
			//TY Sales by Dept (ex Brands/Other)
			VAR GrossSRIVExBrands = CALCULATE ([Gross SRIV],FILTER(Products, Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			// TY PN of Total TY Sales by BU (ex Brands/Other)
			VAR GrossSRIV_TY_PN = DIVIDE(GrossSRIVExBrands,GrossSRIV_TY_Total)
			// Total LY Sales (ex Brands/Other)
			VAR GrossSRIV_LY_Total = CALCULATE ([Gross SRIV LY],All(Products),Products[BU] <> "Brands" && Products[BU] <> "Other" && Products[BU] <> "GM Other")
			// LY Sales at TY Mix
			VAR GrossSRIV_Mix = GrossSRIV_TY_PN * GrossSRIV_LY_Total
			// Iterative Sum of Returns by Department
			VAR ReturnsTbl = ADDCOLUMNS(VALUES(Products[Dept]), "Returns", [Return rate %] * GrossSRIV_Mix)
			// Returns Rate
			Var Returns = SUMX(ReturnsTbl,[Returns])
			VAR Returns_Vol_RR = DIVIDE(Returns, GrossSRIV_Mix)
			VAR TestReturns = GrossSRIV_Mix
			RETURN GrossSRIV_TY_Total
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 14868463-74f4-4d79-8a54-4b1e5b530bff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FPP Intake Value Comparator' = ```
			
			        SWITCH('ProjectionScenario'[slctd_Projection Scenario],
			        "BUD", [FPP Intake Value vs BUD],
			        "FC", [FPP Intake Value vs FC],
			       // "LE", [FPP Intake Value vs BUD],
			        "QRF", [FPP Intake Value vs QRF],
			        [FPP Intake Value vs BUD]
			        )
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\Comp
		lineageTag: 5f58cd58-08b8-4926-bd00-a78dab58f9f5

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'FPP Intake Volume Comparator' = ```
			
			        SWITCH('ProjectionScenario'[slctd_Projection Scenario],
			        "BUD", [FPP Intake Volume vs BUD],
			        "FC", [FPP Intake Volume vs FC],
			       // "LE", [FPP Intake Value vs BUD],
			        "QRF", [FPP Intake Volume vs QRF],
			        [FPP Intake Volume vs BUD]
			        )
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\Comp
		lineageTag: bd800ee6-0135-4bdd-bd0f-fede6602a5dd

		annotation PBI_FormatHint = {"isCustom":true}

	measure Placeholder = BLANK()
		lineageTag: 71b25076-ec18-4395-9bc0-97e363852537

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rbr01_TYMixLYSales =
			
			Var SalesTbl = ADDCOLUMNS(VALUES(Products[Dept]),"Sls",[Rbr01_Precalc])
			Return
			SUMX(SalesTbl,[Sls])
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 972da7c3-6d60-4a96-9c4b-acd880ffb382

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rbr02_TYMixLYSales_x_TYRate =
			
			Var ReturnsTbl = ADDCOLUMNS(VALUES(Products[Dept]),"Ret",[Rbr02_Precalc])
			Return
			SUMX(ReturnsTbl,[Ret])
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 10cc29d0-6740-4926-bb22-9ac4c1ebd653

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rbr03_VolumeRR =
			
			Var Returns = [Rbr02_TYMixLYSales_x_TYRate]
			Var Sales = [Rbr01_TYMixLYSales]
			Var tbl = ADDCOLUMNS(VALUES(Products[Dept]), "Returns", Returns, "Sales", Sales)
			RETURN
			//DIVIDE(Returns,Sales)
			Divide(SUMX(tbl,[Returns]),SUMX(tbl,[Sales]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: e3954593-0e88-475f-8090-a5be7b4af255

	measure Rbr04_TYMixLYSales_x_LYRR =
			
			Var ReturnsTbl = ADDCOLUMNS(VALUES(Products[Dept]),"Ret",[Rbr04_Precalc])
			Return
			SUMX(ReturnsTbl,[Ret])
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 517cac04-d09f-4ec2-b69d-866b2f41d71c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rbr05_RateRR =
			
			Var Returns = [Rbr04_TYMixLYSales_x_LYRR]
			Var Sales = [Rbr01_TYMixLYSales]
			Var tbl = ADDCOLUMNS(VALUES(Products[Dept]), "Returns", Returns, "Sales", Sales)
			RETURN
			//DIVIDE(Returns,Sales)
			Divide(SUMX(tbl,[Returns]),SUMX(tbl,[Sales]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 67823ff9-0292-40fd-abef-b7d587e68f87

	measure Rbr08_LYRRExBrands = DIVIDE([Rbr07_LYReturnsExBrands],[Rbr06_LYSalesExBrands])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 88f9ab36-0b5c-41d2-90a6-d627b34835da

	measure Rbr06_LYSalesExBrands = ```
			
			Var SlsTbl = ADDCOLUMNS(VALUES(Products[Dept]),"Sls",[Rbr06_Precalc])
			Return
			SUMX(SlsTbl,[Sls])
			
			```
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 541ba06e-618c-4b65-9a7d-b2b80d5cdc49

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rbr07_LYReturnsExBrands =
			
			Var ReturnsTbl = ADDCOLUMNS(VALUES(Products[Dept]),"Ret",-[Rbr07_Precalc])
			Return
			SUMX(ReturnsTbl,[Ret])
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: a56c7007-7b51-4f44-aabd-aee92d6ccc6b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rbr09_RRVolImpact = [Rbr03_VolumeRR] - [Rbr08_LYRRExBrands]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: a129604c-dce5-4d46-bb46-c0c1a2ca0636

	measure Rbr10_RRRateImpact = -([Rbr05_RateRR] - [Rbr03_VolumeRR])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 2cab03bf-2977-49ef-9e19-4c5c9a9c8562

	measure Rbr11_RRMixImpact = -([Rbr08_LYRRExBrands]-[Rbr05_RateRR])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 020013eb-0457-4a5e-ba8a-bc1d7d8ea8e2

	measure Rbr04_Precalc =
			
			Var NewMix = [Rbr01_TYMixLYSales]
			Var Rate = [Return rate % LY]
			Var returns = NewMix * Rate
			Return
			returns
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: a923c994-5bb4-485d-a312-d32910c009f0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rbr02_Precalc =
			
			Var NewMix = [Rbr01_TYMixLYSales]
			Var Rate = [Return rate %]
			Return
			NewMix * Rate
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 84158808-a0ab-4730-b2e2-3cac13eeb15a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rbr01_Precalc =
			
			Var TYTotal = CALCULATE([Gross SRIV],       All(Products), Products[BU] <> "Brands",  Products[BU] <> "Other", Products[BU] <> "GM Other")
			Var LYTotal = CALCULATE([Gross SRIV LY],    All(Products), Products[BU] <> "Brands",  Products[BU] <> "Other", Products[BU] <> "GM Other")
			Var TYExBrands = CALCULATE([Gross SRIV],    Products[BU] <> "Brands",  Products[BU] <> "Other", Products[BU] <> "GM Other")
			Var LYatTYMix = (TYExBrands/TYTotal)*LYTotal
			RETURN
			LYatTYMix
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 9538e454-4d0d-4db0-9e2d-ad5d79212a06

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rbr06_Precalc = CALCULATE([Gross SRIV LY], Products[BU] <> "Brands", Products[BU] <> "Other", Products[BU] <> "GM Other")
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 40afa5bd-035a-4f09-be0b-74a173725a13

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rbr07_Precalc = CALCULATE([Returns LY], Products[BU] <> "Brands", Products[BU] <> "Other", Products[BU] <> "GM Other")
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 0513c8cf-dd40-42e8-a3f9-fd1be8a46e06

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rbr99_ReturnsBridge =
			
			VAR _item =
			    SELECTEDVALUE ( 'ReturnsBridge'[Item] )
			VAR SelectedChannel = [Slctd_Channel]
			VAR result =
			    SWITCH (
			        _item,
			        "LY", [Return rate % LY],
			        "Brands", switch(round([RR Brands Impact %],4)=0,true(),blank(),[RR Brands Impact %]),
			        "Channel Mix", SWITCH(SelectedChannel,"Total",[RBR_ChMx_Var],blank()),
			        "Product Mix", SWITCH(True(),OR(ISINSCOPE(Products[Dept]),ISFILTERED(Products[Dept])),blank(),[Rbr11_RRMixImpact] - SWITCH(SelectedChannel,"Total",[RBR_ChMx_Var],0)),
			        "Rate", [Rbr10_RRRateImpact] + SWITCH(True(),OR(ISINSCOPE(Products[Dept]),ISFILTERED(Products[Dept])),[Rbr11_RRMixImpact] - SWITCH(SelectedChannel,"Total",[RBR_ChMx_Var],0),blank()),
			        "Other", switch([RR Other Impact % ex Brands]=0,true(),blank(),[RR Other Impact % ex Brands]),
			        "TY", [Return rate %]
			    )
			RETURN
			    result
		formatString: 0.0%;(0.0)%;0.0%
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 87a95ff4-b2b2-4781-8652-3719babe2946

	measure Rbr98_ProductMix = [Rbr11_RRMixImpact] - SWITCH([Slctd_Channel],"Total",[RBR_ChMx_Var],0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: fa10b088-929f-403d-b576-32337a73eab9

	measure MbrComp02_SRIVFPP = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"Reduced",0,CALCULATE ( [MbrComp01_SRIVMainchain], SalesType[SalesType] = "FP&P" ))
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: 382915b9-9500-431f-a6a1-50bbfb7e8c52

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Mbr01_SRIVMainchain = CALCULATE([SRIV], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other"))
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations
		lineageTag: 901bbf35-9d7c-4165-8408-9db9caf066c6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MbrComp01_SRIVMainchain =
			
			VAR comp = [slctd_MarginBridgeComparator]
			VAR result =
			    SWITCH (
			        comp,
			        "ACT", CALCULATE([SRIV], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "LW", CALCULATE([SRIV LW], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "QRF", CALCULATE([SRIV QRF], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        //"QRF", CALCULATE([SRIV QRF], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "FC", CALCULATE([SRIV FC], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "BUD", CALCULATE([SRIV BUD], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "LY", CALCULATE([SRIV LY], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: cb815a6e-bbf5-44aa-bd5e-0d908cee8527

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Mbr02_SRIVFPP =
			
			VAR comp_metric = [slctd_Variable]
			VAR result_for_vol =
			    DIVIDE ( [MbrComp02_SRIVFPP], [MbrComp01_SRIVMainchain] ) * [Mbr01_SRIVMainchain]
			RETURN
			SWITCH(SELECTEDVALUE(SalesType[SalesType]),"Reduced",0,
			    IF (
			        comp_metric = "Vol",
			        result_for_vol,
			        CALCULATE ( [Mbr01_SRIVMainchain], SalesType[SalesType] = "FP&P" )
			    ))
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations
		lineageTag: 4dc5322c-798e-473c-9f14-473a2f302b2b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MbrComp03_SRIVRP = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,CALCULATE ( [MbrComp01_SRIVMainchain], SalesType[SalesType] = "Reduced" ))
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: 7def3973-f626-4d91-81e4-e38a5ad8427e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Mbr03_SRIVRP =
			
			VAR comp_metric = [slctd_Variable]
			VAR result_for_vol =
			    DIVIDE ( [MbrComp03_SRIVRP], [MbrComp01_SRIVMainchain] ) * [Mbr01_SRIVMainchain]
			RETURN
			    IF (
			        comp_metric = "Vol",
			        result_for_vol,
			        SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,CALCULATE ( [Mbr01_SRIVMainchain], SalesType[SalesType] = "Reduced" ))
			    )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations
		lineageTag: 71033bf2-a4fe-465d-afc7-f2a6b5edd62c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Mbr04_SRIV = [Mbr02_SRIVFPP] + [Mbr03_SRIVRP]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations
		lineageTag: 233d1490-3b3d-47c5-bee8-1441e0a53520

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MbrComp04_SRIV = [MbrComp02_SRIVFPP] + [MbrComp03_SRIVRP]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: 06475cc5-2385-4584-9509-00265ac33906

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Mbr05_SREVMainchain = [Mbr04_SRIV]/ (1+ [Mbr06_VAT])
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations
		lineageTag: a3b04821-04d1-4dbb-87f7-020b1584ff8b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MbrComp05_SREVMainchain =
			
			VAR comp = [slctd_MarginBridgeComparator]
			VAR result =
			    SWITCH (
			        comp,
			        "ACT", CALCULATE([SREV], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "LW", CALCULATE([SREV LY], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "QRF", CALCULATE([SREV QRF], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "FC", CALCULATE([SREV FC], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "BUD", CALCULATE([SREV BUD], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")),
			        "LY", CALCULATE([SREV LY], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			    )
			RETURN
			    result
		formatString: #,##0,,.000;(#,##0,,.000)
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: baed4865-2241-4b29-9a7a-371f3b8a4afc

		annotation PBI_FormatHint = {"isCustom":true}

	measure MbrVis03_Walk% = ```
			
			VAR SelectedComp = [slctd_MarginBridgeComparator]
			VAR Selectedcompresult =
			    SWITCH (
			        SelectedComp,
			        "ACT", CALCULATE([GSM % SREV], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "LW", CALCULATE([GSM % SREV LW], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "QRF", CALCULATE([GSM % SREV QRF], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "FC", CALCULATE([GSM % SREV FC], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "BUD", CALCULATE([GSM % SREV BUD], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "LY", CALCULATE([GSM % SREV LY], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets")
			    )
			VAR RealComp =
			    SWITCH (
			        SelectedComp,
			        "ACT", [GSM % SREV],
			        "LW", [GSM % SREV LW],
			        "QRF", [GSM % SREV QRF],
			        "FC", [GSM % SREV FC], 
			        "BUD", [GSM % SREV BUD], 
			        "LY", [GSM % SREV LY]
			    )
			VAR Comp = Selectedcompresult
			VAR Vol = CALCULATE([Mbr20_GSMPct], All(MarginBridgeVariable), MarginBridgeVariable[Variable] = "Vol")
			Var FPP = CALCULATE([Mbr20_GSMPct], All(MarginBridgeVariable), MarginBridgeVariable[Variable] = "FP&P Mix")
			Var BIM = CALCULATE([Mbr20_GSMPct], All(MarginBridgeVariable), MarginBridgeVariable[Variable] = "BIM")
			Var POS = CALCULATE([Mbr20_GSMPct], All(MarginBridgeVariable), MarginBridgeVariable[Variable] = "POS")
			Var DOC = CALCULATE([Mbr20_GSMPct], All(MarginBridgeVariable), MarginBridgeVariable[Variable] = "DOC")
			Var VAT = CALCULATE([Mbr20_GSMPct], All(MarginBridgeVariable), MarginBridgeVariable[Variable] = "VAT")
			Var Act = CALCULATE([GSM % SREV], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets")
			Var VolVar = 0
			Var FPPVar = FPP - Vol
			Var BIMVar = BIM - FPP
			Var POSVar = POS - BIM
			Var DOCVar = DOC - POS
			Var VatVar = VAT - DOC
			Var OtherVar = Act - VatVar - DOCVar - POSVar - BIMVar - FPPVar - VolVar - Comp
			Var RealAct = [GSM % SREV]
			RETURN
			SWITCH(
			    SELECTEDVALUE(MarginBridgeWalk[Step])
			    ,"Comp", RealComp
			    ,"Vol", VolVar
			    ,"FP&P Mix", FPPVar
			    ,"BIM", BIMVar
			    ,"POS", POSVar
			    ,"DOC", DOCVar
			    ,"VAT", VatVar
			    ,"Other", OtherVar
			    ,"Outlets",[MbrVis02_OutletGSMVar]
			    ,"Actual", RealAct
			    )
			
			```
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Presentation
		lineageTag: 321ac2ec-9add-4ee0-a365-deff8e862cf5

	measure MbrComp20_OutletsGSMVar =
			
			VAR comp = [slctd_MarginBridgeComparator]
			VAR result =
			    SWITCH (
			        comp,
			        "LW", CALCULATE([GSM % SREV vs LW], OutletsControl[Ex Outlets/Outlets] = "Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "QRF", CALCULATE([GSM % SREV vs QRF], OutletsControl[Ex Outlets/Outlets] = "Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "FC", CALCULATE([GSM % SREV vs FC], OutletsControl[Ex Outlets/Outlets] = "Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "BUD", CALCULATE([GSM % SREV vs BUD], OutletsControl[Ex Outlets/Outlets] = "Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "LY", CALCULATE([GSM % SREV vs LY], OutletsControl[Ex Outlets/Outlets] = "Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other")
			    )
			RETURN
			    result
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: c3087d00-1709-4931-b910-05068bfc0fa1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MbrVis01_MainchainGSMVar =
			
			VAR comp = [slctd_MarginBridgeComparator]
			VAR result =
			    SWITCH (
			        comp,
			        "LW", CALCULATE([GSM % SREV vs LW], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "QRF", CALCULATE([GSM % SREV vs QRF], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "FC", CALCULATE([GSM % SREV vs FC], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "BUD", CALCULATE([GSM % SREV vs BUD], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "LY", CALCULATE([GSM % SREV vs LY], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets")
			    )
			RETURN
			    result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Presentation
		lineageTag: 9583a71c-9a9a-4434-87b8-5b5363580869

	measure MbrVis02_OutletGSMVar = ```
			
			VAR comp = [slctd_MarginBridgeComparator]
			VAR result =
			    SWITCH (
			        comp,
			        "LW", [GSM % SREV vs LW],
			        "QRF", [GSM % SREV vs QRF],
			        "FC", [GSM % SREV vs FC],
			        "BUD", [GSM % SREV vs BUD],
			        "LY", [GSM % SREV vs LY]
			    )
			RETURN
			    result - [MbrVis01_MainchainGSMVar] 
			```
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Presentation
		lineageTag: a68b6393-5e0b-4c61-b8fa-f1c180cc19c9

	measure MbrVis04_MainchainGSMVarCash =
			
			VAR comp = [slctd_MarginBridgeComparator]
			VAR result =
			    SWITCH (
			        comp,
			        "LW", CALCULATE(    [GSM vs LW] , OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "QRF", CALCULATE(   [GSM vs QRF], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "FC", CALCULATE(    [GSM vs FC] , OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "BUD", CALCULATE(   [GSM vs BUD], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "LY", CALCULATE(    [GSM vs LY] , OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets")
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Presentation
		lineageTag: 274a75f3-b19a-4a96-9d25-f6a468f5168a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MbrVis05_OutletsGSMVarCash = ```
			
			/*
			VAR comp = [slctd_MarginBridgeComparator]
			VAR result =
			    SWITCH (
			        comp,
			        "LW", CALCULATE(    [GSM vs LW] , OutletsControl[Ex Outlets/Outlets] = "Outlets"),
			        "QRF", CALCULATE(   [GSM vs QRF], OutletsControl[Ex Outlets/Outlets] = "Outlets"),
			        "FC", CALCULATE(    [GSM vs FC] , OutletsControl[Ex Outlets/Outlets] = "Outlets"),
			        "BUD", CALCULATE(   [GSM vs BUD], OutletsControl[Ex Outlets/Outlets] = "Outlets"),
			        "LY", CALCULATE(    [GSM vs LY] , OutletsControl[Ex Outlets/Outlets] = "Outlets")
			    )
			RETURN
			    result
			    */
			VAR comp = [slctd_MarginBridgeComparator]
			VAR result =
			    SWITCH (
			        comp,
			        "LW", [GSM vs LW],
			        "QRF", [GSM vs QRF],
			        "FC", [GSM vs FC],
			        "BUD", [GSM vs BUD],
			        "LY", [GSM vs LY]
			    )
			RETURN
			    result - [MbrVis04_MainchainGSMVarCash] 
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Presentation
		lineageTag: f0f8f800-769c-464a-a11c-6e519f744c28

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MbrVis06_Walk = ```
			
			VAR SelectedComp = [slctd_MarginBridgeComparator]
			VAR Selectedcompresult =
			    SWITCH (
			        SelectedComp,
			        "ACT", CALCULATE([GSM], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "LW", CALCULATE([GSM LW], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "QRF", CALCULATE([GSM QRF], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "FC", CALCULATE([GSM FC], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "BUD", CALCULATE([GSM BUD], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "LY", CALCULATE([GSM LY], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets")
			    )
			VAR RealComp =
			    SWITCH (
			        SelectedComp,
			        "ACT", [GSM],
			        "LW", [GSM LW],
			        "QRF", [GSM QRF],
			        "FC", [GSM FC], 
			        "BUD", [GSM BUD], 
			        "LY", [GSM LY]
			    )
			VAR Comp = Selectedcompresult
			VAR Vol = CALCULATE([Mbr19_GSM], All(MarginBridgeVariable), MarginBridgeVariable[Variable] = "Vol")
			Var FPP = CALCULATE([Mbr19_GSM], All(MarginBridgeVariable), MarginBridgeVariable[Variable] = "FP&P Mix")
			Var BIM = CALCULATE([Mbr19_GSM], All(MarginBridgeVariable), MarginBridgeVariable[Variable] = "BIM")
			Var POS = CALCULATE([Mbr19_GSM], All(MarginBridgeVariable), MarginBridgeVariable[Variable] = "POS")
			Var DOC = CALCULATE([Mbr19_GSM], All(MarginBridgeVariable), MarginBridgeVariable[Variable] = "DOC")
			Var VAT = CALCULATE([Mbr19_GSM], All(MarginBridgeVariable), MarginBridgeVariable[Variable] = "VAT")
			Var Act = CALCULATE([GSM], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets")
			Var VolVar = Vol - Comp
			Var FPPVar = FPP - Vol
			Var BIMVar = BIM - FPP
			Var POSVar = POS - BIM
			Var DOCVar = DOC - POS
			Var VatVar = VAT - DOC
			Var OtherVar = Act - VatVar - DOCVar - POSVar - BIMVar - FPPVar - VolVar - Comp
			Var RealAct = [GSM]
			RETURN
			SWITCH(
			    SELECTEDVALUE(MarginBridgeWalk[Step])
			    ,"Comp", RealComp
			    ,"Vol", VolVar
			    ,"FP&P Mix", FPPVar
			    ,"BIM", BIMVar
			    ,"POS", POSVar
			    ,"DOC", DOCVar
			    ,"VAT", VatVar
			    ,"Other", OtherVar
			    ,"Outlets",[MbrVis05_OutletsGSMVarCash]
			    ,"Actual", RealAct
			    )
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Presentation
		lineageTag: 9269eb43-af75-432a-8c04-b73845b10742

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MbrComp08_SaleMD%SRIV = DIVIDE([MbrComp09_SaleMD],[MbrComp01_SRIVMainchain] )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: 2f8aa23e-a548-4d4a-9257-ea062a0deb9f

	measure Mbr05_SREVMainchainTrue = CALCULATE([SREV], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other"))
		displayFolder: Margin\Bridge\Calculations
		lineageTag: 72284f2d-334a-46e3-b1ef-1e58f904eea3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Mbr99_GrossSREV =
			VAR comp_metric = [slctd_Variable]
			VAR at_comp_vat_rate =
			    DIVIDE ( [Mbr15_GrossSRIV], ( 1 + [MbrComp15_GrossVAT] ) )
			VAR at_act_vat_rate =
			    DIVIDE (
			        [Mbr15_GrossSRIV],
			        (
			            1
			                + if(SELECTEDVALUE(SalesRecognitionType[SalesRecognitionType])="Order",
			                CALCULATE (
			                    [MbrComp15_GrossVAT],
			                    ALL ( ComparatorMaster[Comparator] ),
			                    MarginBridgeComparator[Comparator] = "ACT"
			                ),
			                [MbrComp15_GrossVAT])
			        )
			    )
			VAR result =
			    SWITCH (
			        comp_metric,
			//       "Vol", [MbrComp14_GrossSREV] * DIVIDE ( [Mbr01_SRIVMainchain], [MbrComp01_SRIVMainchain] ),
			        "Vol", [MbrComp14_GrossSREV],
			        "FP&P Mix", at_comp_vat_rate,
			        "BIM", at_comp_vat_rate,
			        "POS", at_comp_vat_rate,
			        "DoC", at_comp_vat_rate,
			        "VAT", at_act_vat_rate
			    )
			RETURN
			    result
		displayFolder: Margin\Bridge\Calculations
		lineageTag: cbb707b2-83bb-48a5-bcee-cffbb71b5556

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Mbr18_BIMPct =
			
			Var SRIV = CALCULATE([SRIV], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			Var SREV = CALCULATE([SREV], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			Var GSM = CALCULATE([GSM], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			Var COGS = SREV - GSM
			Var Realised = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,-CALCULATE([Sale Markdown], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")))
			Var POS = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"Reduced",0,-CALCULATE([Promo Markdown], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other")))
			Var OtherBIM = CALCULATE([Buying Margin %], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other"))
			Var Result = 1 - COGS / ((SRIV + POS + Realised)/(SRIV/SREV))
			Return
			Result
			//OtherBIM
			//Fails on Memory SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",ReducedBIMPct,OtherBIM)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Margin\Bridge\Calculations
		lineageTag: 80e5943b-1d27-4727-8046-0830ffce2502

	measure 'Measure 2' = ```
			BLANK() 
			```
		lineageTag: 490d18ac-49b4-4820-a277-f88343be569b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure R_FPPIntakeValue =
			
			Var RollingDates = ([Slctd_WeeksRolling] * 7)-1
			VAR SelectedWeek = MAX('Calendar'[fiscalWeekEndingDate])
			RETURN
			    CALCULATE(
			        AVERAGEX(
			            FILTER(
			                ALL('Calendar'),
			                'Calendar'[fiscalWeekEndingDate] >= SelectedWeek - RollingDates &&
			                'Calendar'[fiscalWeekEndingDate] <= SelectedWeek
			            ),
			            [FPP Intake Value]
			        ),
			        ALL('Time Period')
			    )
		displayFolder: Intake\Rolling Intake\RollingCalcs
		lineageTag: 65efd68a-f7de-48f4-bedd-14705d94fc0e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rolling_FPPIntakeValue =
			
			Var Tbl = ADDCOLUMNS(VALUES('Calendar'[fiscalWeekEndingDate]),"Rolling",[R_FPPIntakeValue])
			RETURN
			SUMX(Tbl,[Rolling])
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\Rolling Intake
		lineageTag: b8b04308-3994-4df6-80c4-fbcf6aa4af2e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure FPPIntakeValueComp = ```
			
			        SWITCH([slctd_ComparatorMaster],
			        "BUD", [FPP Intake Value BUD],
			        "FC", [FPP Intake Value FC],
			        "QRF", [FPP Intake Value QRF],
			        [FPP Intake Value BUD]
			        )
			```
		displayFolder: Intake\Comp
		lineageTag: ef6cd393-9b49-4ea2-b0df-6dfea2d370a5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure FPPIntakeVolComp = ```
			
			        SWITCH([slctd_ComparatorMaster],
			        "BUD", [FPP Intake Volume BUD],
			        "FC", [FPP Intake Volume FC],
			        "QRF", [FPP Intake Volume QRF],
			        [FPP Intake Volume BUD]
			        )
			```
		displayFolder: Intake\Comp
		lineageTag: 73041777-dcff-4914-84ba-e38da0fdecd9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure R_FPPIntakeVolume =
			
			Var RollingDates = ([Slctd_WeeksRolling] * 7)-1
			VAR SelectedWeek = MAX('Calendar'[fiscalWeekEndingDate])
			RETURN
			    CALCULATE(
			        AVERAGEX(
			            FILTER(
			                ALL('Calendar'),
			                'Calendar'[fiscalWeekEndingDate] >= SelectedWeek - RollingDates &&
			                'Calendar'[fiscalWeekEndingDate] <= SelectedWeek
			            ),
			            [FPP Intake Volume]
			        ),
			        ALL('Time Period')
			    )
		displayFolder: Intake\Rolling Intake\RollingCalcs
		lineageTag: 333d64b0-9a5c-4c2c-ac12-e9ff1f890c13

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rolling_FPPIntakeVolume =
			
			Var Tbl = ADDCOLUMNS(VALUES('Calendar'[fiscalWeekEndingDate]),"Rolling",[R_FPPIntakeVolume])
			RETURN
			SUMX(Tbl,[Rolling])
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\Rolling Intake
		lineageTag: 051d0006-a87d-4e63-a2ae-e3968b2b94cb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure R_FPP_SRIV =
			
			Var RollingDates = ([Slctd_WeeksRolling] * 7)-1
			VAR SelectedWeek = MAX('Calendar'[fiscalWeekEndingDate])
			RETURN
			    CALCULATE(
			        AVERAGEX(
			            FILTER(
			                ALL('Calendar'),
			                'Calendar'[fiscalWeekEndingDate] >= SelectedWeek - RollingDates &&
			                'Calendar'[fiscalWeekEndingDate] <= SelectedWeek
			            ),
			            [R_FPPFwdView]
			        ),
			        ALL('Time Period')
			    )
		displayFolder: Intake\Rolling Intake\RollingCalcs
		lineageTag: 2fe3d2db-5ab2-4ee3-8983-5ed81941364d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rolling_FPPSRIV =
			
			Var Tbl = ADDCOLUMNS(VALUES('Calendar'[fiscalWeekEndingDate]),"Rolling",[R_FPP_SRIV])
			RETURN
			SUMX(Tbl,[Rolling])
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\Rolling Intake
		lineageTag: 8b8fd236-0a3e-4fbd-9e55-4e1e86718e31

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure R_FPPFwdView = CALCULATE ( [SRIV Fwd View], 'SalesType'[SalesType] = "FP&P" )
		displayFolder: Intake\Rolling Intake\RollingCalcs
		lineageTag: b89a347f-c80c-44cf-adc1-20e483f03e99

	measure R_FPPIntakeValueComp =
			
			Var RollingDates = ([Slctd_WeeksRolling] * 7)-1
			VAR SelectedWeek = MAX('Calendar'[fiscalWeekEndingDate])
			RETURN
			    CALCULATE(
			        AVERAGEX(
			            FILTER(
			                ALL('Calendar'),
			                'Calendar'[fiscalWeekEndingDate] >= SelectedWeek - RollingDates &&
			                'Calendar'[fiscalWeekEndingDate] <= SelectedWeek
			            ),
			            [FPPIntakeValueComp]
			        ),
			        ALL('Time Period')
			    )
		displayFolder: Intake\Rolling Intake\RollingCalcs
		lineageTag: 746315f6-8295-4019-899c-001a13e0c436

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure R_FPPIntakeVolumeComp =
			
			Var RollingDates = ([Slctd_WeeksRolling] * 7)-1
			VAR SelectedWeek = MAX('Calendar'[fiscalWeekEndingDate])
			RETURN
			    CALCULATE(
			        AVERAGEX(
			            FILTER(
			                ALL('Calendar'),
			                'Calendar'[fiscalWeekEndingDate] >= SelectedWeek - RollingDates &&
			                'Calendar'[fiscalWeekEndingDate] <= SelectedWeek
			            ),
			            [FPPIntakeVolComp]
			        ),
			        ALL('Time Period')
			    )
		displayFolder: Intake\Rolling Intake\RollingCalcs
		lineageTag: edce2b23-af8b-44cc-8350-1c1ca3b1e14f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rolling_FPPIntakeValueComp =
			
			Var Tbl = ADDCOLUMNS(VALUES('Calendar'[fiscalWeekEndingDate]),"Rolling",[R_FPPIntakeValueComp])
			RETURN
			SUMX(Tbl,[Rolling])
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\Rolling Intake
		lineageTag: 522d1d7f-f47f-4319-ad05-bac8465a0e17

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rolling_FPPIntakeVolumeComp =
			
			Var Tbl = ADDCOLUMNS(VALUES('Calendar'[fiscalWeekEndingDate]),"Rolling",[R_FPPIntakeVolumeComp])
			RETURN
			SUMX(Tbl,[Rolling])
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\Rolling Intake
		lineageTag: 2557c0f3-dfe0-4f49-bc36-37252c5b85d3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rolling_FPPIntakeValuevsComp = [Rolling_FPPIntakeValue]-[Rolling_FPPIntakeValueComp]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\Rolling Intake
		lineageTag: 911c9f16-8c8e-4ecd-b93c-a40844659ebd

	measure Rolling_FPPIntakeValuevsComp% = divide([Rolling_FPPIntakeValue],[Rolling_FPPIntakeValueComp])-1
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Intake\Rolling Intake
		lineageTag: 8d41d9f1-cfe1-4b93-95a7-8632679474b0

	measure Rolling_FPPIntakeVolumevsComp = [Rolling_FPPIntakeVolume] - [Rolling_FPPIntakeVolumeComp]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\Rolling Intake
		lineageTag: 03638544-d3e2-4f97-a177-b0a9f9a6036c

	measure Rolling_FPPIntakeVolumevsComp% = divide([Rolling_FPPIntakeVolume],[Rolling_FPPIntakeVolumeComp])-1
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Intake\Rolling Intake
		lineageTag: 6998bf90-3a44-4444-859a-7fa092c9b915

	measure R_FPPSRIVCompCalc = ```
			 SWITCH([slctd_ComparatorMaster],
			        "BUD", CALCULATE ( [SRIV BUD], 'SalesType'[SalesType] = "FP&P" ),
			        "FC", CALCULATE ( [SRIV FC], 'SalesType'[SalesType] = "FP&P" ),
			        "QRF", CALCULATE ( [SRIV QRF], 'SalesType'[SalesType] = "FP&P" ),
			        "LY", CALCULATE ( [SRIV LY], 'SalesType'[SalesType] = "FP&P" ),
			        "LE", CALCULATE ( [SRIV LE], 'SalesType'[SalesType] = "FP&P" ),
			        [SRIV QRF])
			        
			```
		displayFolder: Intake\Rolling Intake\RollingCalcs
		lineageTag: 20a6765a-d50b-4ee7-a0ce-ff1ba1fb49bf

	measure R_FPP_SRIVComp =
			
			Var RollingDates = ([Slctd_WeeksRolling] * 7)-1
			VAR SelectedWeek = MAX('Calendar'[fiscalWeekEndingDate])
			RETURN
			    CALCULATE(
			        AVERAGEX(
			            FILTER(
			                ALL('Calendar'),
			                'Calendar'[fiscalWeekEndingDate] >= SelectedWeek - RollingDates &&
			                'Calendar'[fiscalWeekEndingDate] <= SelectedWeek
			            ),
			            [R_FPPSRIVCompCalc]
			        ),
			        ALL('Time Period')
			    )
		displayFolder: Intake\Rolling Intake\RollingCalcs
		lineageTag: a3bf0990-9fb7-462e-8438-6c4f7e16bfbb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rolling_FPPSRIVComp =
			
			Var Tbl = ADDCOLUMNS(VALUES('Calendar'[fiscalWeekEndingDate]),"Rolling",[R_FPP_SRIVComp])
			RETURN
			SUMX(Tbl,[Rolling])
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\Rolling Intake
		lineageTag: a45d485f-54d5-43a9-a357-dc33ae3b6a23

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rolling_FPPSRIVvsComp = [Rolling_FPPSRIV]-[Rolling_FPPSRIVComp]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Intake\Rolling Intake
		lineageTag: 4b3c8514-ee1d-435c-af77-783f09606382

	measure Rolling_FPPSRIVvsComp% = divide([Rolling_FPPSRIV],[Rolling_FPPSRIVComp])-1
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Intake\Rolling Intake
		lineageTag: 320a30e6-9eb3-4f2b-8fad-8206376b970a

	measure 'Sale Markdown XV Dispatch' = Divide([Sale Markdown Dispatch],[Sale Markdown VAT Orders])
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\Actual
		lineageTag: de3b60c0-ffb3-48a8-b7f8-6be9705a4b41

	measure 'Sale Markdown XV % Dispatch' =
			VAR metric = - [Sale Markdown XV Dispatch]
			VAR sales = - [Sale Markdown XV Dispatch] + Divide([RP SRIV Dispatch], [Sale Markdown VAT Orders])
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\Actual
		lineageTag: 901311f2-8005-4f6c-83b1-9492f6057788

	measure 'Sale Markdown XV Dispatch LY' =
			CALCULATE (
			    [Sale Markdown XV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\LY
		lineageTag: cdc54203-c5bd-4221-8eaa-fb3ee5bd405a

	measure 'Sale Markdown XV Dispatch LY-1' =
			CALCULATE (
			    [Sale Markdown XV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Sale Markdown XV Dispatch LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\LY-1
		lineageTag: d776157f-c186-4304-a8ae-5d22fcbe1468

	measure 'Sale Markdown XV Dispatch vs LY' =
			VAR act = [Sale Markdown XV Dispatch]
			VAR comp = [Sale Markdown XV Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\LY
		lineageTag: a11a76dc-2a20-4f24-9134-e4961c81131d

	measure 'Sale Markdown XV Dispatch vs LY-1' =
			VAR act = [Sale Markdown XV Dispatch]
			VAR comp = [Sale Markdown XV Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Sale Markdown XV Dispatch vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\LY-1
		lineageTag: b6363064-712f-4da6-a64d-80914086d146

	measure 'Sale Markdown XV % Dispatch LY' =
			CALCULATE (
			    [Sale Markdown XV % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\LY
		lineageTag: 4fe7c7e1-4211-4eb1-8b42-a1a30ada7e35

	measure 'Sale Markdown XV % Dispatch LY-1' =
			CALCULATE (
			    [Sale Markdown XV % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Sale Markdown XV % Dispatch LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\LY-1
		lineageTag: 14d5ce5a-7228-4fe4-ba6a-b847f59a648f

	measure 'Sale Markdown XV % Dispatch vs LY' =
			VAR act = [Sale Markdown XV % Dispatch]
			VAR comp = [Sale Markdown XV % Dispatch LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\LY
		lineageTag: 8cea2be8-a57a-47fa-aa42-d79d431c3816

	measure 'Sale Markdown XV % Dispatch vs LY-1' =
			VAR act = [Sale Markdown XV % Dispatch]
			VAR comp = [Sale Markdown XV % Dispatch LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Sale Markdown XV % Dispatch vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\LY-1
		lineageTag: e6e1895f-ad11-4f9b-b301-28330b536c1f

	measure 'Sale Markdown XV Dispatch LW' =
			CALCULATE (
			    [Sale Markdown XV Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\LW
		lineageTag: 4c530879-9716-470e-9e29-8deff91b1133

	measure 'Sale Markdown XV Dispatch vs LW' =
			VAR act = [Sale Markdown XV Dispatch]
			VAR comp = [Sale Markdown XV Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\LW
		lineageTag: 979690f7-1fd4-4a46-9944-3a4e24d74f99

	measure 'Sale Markdown XV % Dispatch LW' =
			CALCULATE (
			    [Sale Markdown XV % Dispatch],
			    USERELATIONSHIP ( factSalesDispatch[Fiscal Week], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\LW
		lineageTag: 0cd81e8a-3fa9-4c89-a86f-948c39977a12

	measure 'Sale Markdown XV % Dispatch vs LW' =
			VAR act = [Sale Markdown XV % Dispatch]
			VAR comp = [Sale Markdown XV % Dispatch LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\LW
		lineageTag: e8bde542-5be0-4197-9d19-9e8c479e61bc

	measure 'Sale Markdown XV Dispatch BUD' =
			CALCULATE (
			    [sum_Sale Markdown XV DispFor],
			    ForecastScenarios[Forecast Scenario] = "BUD"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\BUD
		lineageTag: 086d6724-77f4-4818-86e7-e176c804aecb

	measure 'Sale Markdown XV Dispatch vs BUD' =
			VAR act = [Sale Markdown XV Dispatch]
			VAR comp = [Sale Markdown XV Dispatch BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\BUD
		lineageTag: b6c89a38-634d-4aa1-bfb2-b75cbd7679d9

	measure 'Sale Markdown XV % Dispatch BUD' =
			VAR metric = - [Sale Markdown XV Dispatch BUD]
			VAR sales = - [Sale Markdown XV Dispatch BUD] + [RP SRIV Dispatch BUD]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\BUD
		lineageTag: ed4fb975-0a29-4e17-93d2-e9612af3ce59

	measure 'Sale Markdown XV % Dispatch vs BUD' =
			VAR act = [Sale Markdown XV % Dispatch]
			VAR comp = [Sale Markdown XV % Dispatch BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\BUD
		lineageTag: bddfa77d-1d59-4712-9e76-58c2cff9d156

	measure 'Sale Markdown XV Dispatch FC' =
			CALCULATE (
			    [sum_Sale Markdown XV DispFor],
			    ForecastScenarios[Forecast Scenario] = "FC"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\FC
		lineageTag: d64bd1cc-66da-4712-af61-da44fe098421

	measure 'Sale Markdown XV Dispatch vs FC' =
			VAR act = [Sale Markdown XV Dispatch]
			VAR comp = [Sale Markdown XV Dispatch FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\FC
		lineageTag: 42bc32e6-d589-4486-9764-bc43f98735cb

	measure 'Sale Markdown XV % Dispatch FC' =
			VAR metric = - [Sale Markdown XV Dispatch FC]
			VAR sales = - [Sale Markdown XV Dispatch FC] + [RP SRIV Dispatch FC]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\FC
		lineageTag: 6678df0c-ac72-43c5-a95e-c54560e917fc

	measure 'Sale Markdown XV % Dispatch vs FC' =
			VAR act = [Sale Markdown XV % Dispatch]
			VAR comp = [Sale Markdown XV % Dispatch FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\FC
		lineageTag: 107a0dc5-c69e-441b-b4fe-ed7fe80975d7

	measure 'Sale Markdown XV Dispatch QRF' =
			CALCULATE (
			    [sum_Sale Markdown XV DispFor],
			    ForecastScenarios[Forecast Scenario] = "QRF"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\QRF
		lineageTag: 22d1839a-8a62-4f2e-9402-6a9c4462113c

	measure 'Sale Markdown XV Dispatch vs QRF' =
			VAR act = [Sale Markdown XV Dispatch]
			VAR comp = [Sale Markdown XV Dispatch QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Dispatch\Sale Markdown\QRF
		lineageTag: 64fe6af2-4e81-46c7-9f08-28f3c97877c9

	measure 'Sale Markdown XV % Dispatch QRF' =
			VAR metric = - [Sale Markdown XV Dispatch QRF]
			VAR sales = - [Sale Markdown XV Dispatch QRF] + [RP SRIV Dispatch QRF]
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\QRF
		lineageTag: 8a9bb01a-604f-4954-bacc-5058aa0771cd

	measure 'Sale Markdown XV % Dispatch vs QRF' =
			VAR act = [Sale Markdown XV % Dispatch]
			VAR comp = [Sale Markdown XV % Dispatch QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Dispatch\Sale Markdown\QRF
		lineageTag: da98e538-2b47-48f5-9174-0e5710c7ecb4

	measure 'Sale Markdown XV Orders' = SUM ( 'factSalesOrders'[rmev] )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\Actual
		lineageTag: e0bd13c7-1b11-4445-a55b-6a956bf7865a

	measure 'Sale Markdown XV % Orders' =
			VAR metric = - [Sale Markdown XV Orders]
			VAR sales =
			    - [Sale Markdown XV Orders]
			        + CALCULATE ( [SREV Orders], SalesType[SalesType] = "Reduced" )
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\Actual
		lineageTag: 251b000b-a937-4910-8715-25de70521a85

	measure 'Sale Markdown XV Orders LY' =
			CALCULATE (
			    [Sale Markdown XV Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\LY
		lineageTag: 5ae7eca1-1ad1-4f61-bcaa-8a02a7f9531e

	measure 'Sale Markdown XV Orders LY-1' =
			CALCULATE (
			    [Sale Markdown XV Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Sale Markdown XV Orders LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\LY-1
		lineageTag: c71fcea3-6f6c-477f-ac83-5a812dad990d

	measure 'Sale Markdown XV Orders vs LY' =
			VAR act = [Sale Markdown XV Orders]
			VAR comp = [Sale Markdown XV Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\LY
		lineageTag: 4ca265c9-4ae3-4b19-83b4-2dd78546cd44

	measure 'Sale Markdown XV Orders vs LY-1' =
			VAR act = [Sale Markdown XV Orders]
			VAR comp = [Sale Markdown XV Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Sale Markdown XV Orders vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\LY-1
		lineageTag: e660d5f1-a62f-440a-8b05-cd38328feffa

	measure 'Sale Markdown XV % Orders LY' =
			CALCULATE (
			    [Sale Markdown XV % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\LY
		lineageTag: aaef1d57-5c71-44cc-8edb-48dc8f8ee9b7

	measure 'Sale Markdown XV % Orders LY-1' =
			CALCULATE (
			    [Sale Markdown XV % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of Sale Markdown XV % Orders LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\LY-1
		lineageTag: a2b54f69-9bda-4062-965a-3c0591aac8e8

	measure 'Sale Markdown XV % Orders vs LY' =
			VAR act = [Sale Markdown XV % Orders]
			VAR comp = [Sale Markdown XV % Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\LY
		lineageTag: cd1d8a13-21b0-4e00-9062-0d925aa5ad05

	measure 'Sale Markdown XV % Orders vs LY-1' =
			VAR act = [Sale Markdown XV % Orders]
			VAR comp = [Sale Markdown XV % Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Sale Markdown XV % Orders vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\LY-1
		lineageTag: d219ea92-3515-463c-9b44-0e9e2569c4c4

	measure 'Sale Markdown XV Orders BUD' = CALCULATE ( [sum_RealMDV], ForecastScenarios[Forecast Scenario] = "BUD" )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\BUD
		lineageTag: c70ac903-fce3-473e-81c7-1c579b851d9a

	measure 'Sale Markdown XV Orders vs BUD' =
			VAR act = [Sale Markdown XV Orders]
			VAR comp = [Sale Markdown XV Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\BUD
		lineageTag: 4c76ca87-ff2f-4dbe-980e-99400baff64d

	measure 'Sale Markdown XV % Orders BUD' =
			VAR metric = - [Sale Markdown XV Orders BUD]
			VAR sales =
			    CALCULATE (
			        - [sum_RealMDV] + [sum_RedSlsV],
			        ForecastScenarios[Forecast Scenario] = "BUD"
			    )
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\BUD
		lineageTag: a2df26ed-5779-4906-ab5c-3d0ed2298043

	measure 'Sale Markdown XV % Orders vs BUD' =
			VAR act = [Sale Markdown XV % Orders]
			VAR comp = [Sale Markdown XV % Orders BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\BUD
		lineageTag: 5bddd27a-0f06-472f-8b2c-3306bb885583

	measure 'Sale Markdown XV Orders FC' =
			
			VAR PlanVersion = [SlctdForecastVersion]
			Return
			CALCULATE ( [sum_RealMDV], factForecast[plan] = PlanVersion )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\FC
		lineageTag: 1c4773f5-039e-4e8e-b8dd-db01781d739d

	measure 'Sale Markdown XV Orders vs FC' =
			VAR act = [Sale Markdown XV Orders]
			VAR comp = [Sale Markdown XV Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\FC
		lineageTag: 2457f4ea-3964-4304-83d1-fe1951ebc4de

	measure 'Sale Markdown XV % Orders FC' =
			
			VAR PlanVersion = [SlctdForecastVersion]
			VAR metric = - [Sale Markdown XV Orders FC]
			VAR sales =
			    CALCULATE (
			        - [sum_RealMDV] + [sum_RedSlsV],
			        factForecast[plan] = PlanVersion
			    )
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\FC
		lineageTag: 349f0c60-c49b-4e81-aeb6-72e099b8a4da

	measure 'Sale Markdown XV % Orders vs FC' =
			VAR act = [Sale Markdown XV % Orders]
			VAR comp = [Sale Markdown XV % Orders FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\FC
		lineageTag: e807cd5b-a26c-41fa-89a7-55d4befdaaf3

	measure 'Sale Markdown XV Orders QRF' =
			
			VAR PlanVersion = [SlctdQRFVersion]
			Return
			CALCULATE ( [sum_RealMDV], factForecast[plan] = PlanVersion )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\QRF
		lineageTag: bf62f76b-a3a6-4952-b0d5-c8d769d57cd6

	measure 'Sale Markdown XV Orders vs QRF' =
			VAR act = [Sale Markdown XV Orders]
			VAR comp = [Sale Markdown XV Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\QRF
		lineageTag: e18d6539-6c47-428a-89cd-7d49ac272171

	measure 'Sale Markdown XV % Orders QRF' =
			VAR metric = - [Sale Markdown XV Orders QRF]
			VAR sales =
			    CALCULATE (
			        - [sum_RealMDV] + [sum_RedSlsV],
			        ForecastScenarios[Forecast Scenario] = "QRF"
			    )
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\QRF
		lineageTag: 8322ee10-0970-49fe-a3a1-0371a7e01fb5

	measure 'Sale Markdown XV % Orders vs QRF' =
			VAR act = [Sale Markdown XV % Orders]
			VAR comp = [Sale Markdown XV % Orders QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\QRF
		lineageTag: 29aa4c89-e29a-4777-9bf0-d16299bbd32e

	measure 'Sale Markdown XV Orders LW' =
			CALCULATE (
			    [Sale Markdown XV Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\LW
		lineageTag: bd629cd4-d3de-4a0f-aa82-f743ecfc2344

	measure 'Sale Markdown XV Orders vs LW' =
			VAR act = [Sale Markdown XV Orders]
			VAR comp = [Sale Markdown XV Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Orders\Sale Markdown\LW
		lineageTag: d22359dd-6c9d-4145-809d-1573650051c2

	measure 'Sale Markdown XV % Orders LW' =
			CALCULATE (
			    [Sale Markdown XV % Orders],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\LW
		lineageTag: ce4734aa-7621-4e77-9f8d-1e9564b225ba

	measure 'Sale Markdown XV % Orders vs LW' =
			VAR act = [Sale Markdown XV % Orders]
			VAR comp = [Sale Markdown XV % Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Orders\Sale Markdown\LW
		lineageTag: b86e8667-8f44-4fcf-a691-bccc9250da26

	measure 'Sale Markdown XV' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown XV Orders],
			        "Dispatch", [Sale Markdown XV Dispatch],
			        [Sale Markdown XV Orders]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\Actual
		lineageTag: 63de8bae-877d-4cb2-9611-8c8b00514a4a

	measure 'Sale Markdown XV %' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown XV % Orders],
			        "Dispatch", [Sale Markdown XV % Dispatch],
			        [Sale Markdown XV % Orders]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\Actual
		lineageTag: 4c594665-aabd-4bb4-a442-5708ae5a3a84

	measure 'Sale Markdown XV LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown XV Orders LY],
			        "Dispatch", [Sale Markdown XV Dispatch LY],
			        [Sale Markdown XV Orders LY]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\LY
		lineageTag: a07e051b-8790-402f-9645-655ba3c6299a

	measure 'Sale Markdown XV LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown XV Orders LY-1],
			        "Dispatch", [Sale Markdown XV Dispatch LY-1],
			        [Sale Markdown XV Orders LY-1]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		description: Two years ago equivalent of Sale Markdown XV LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\LY-1
		lineageTag: 4ff9323b-69c8-4bcb-a722-98b7793f86f7

	measure 'Sale Markdown XV vs LY' =
			VAR act = [Sale Markdown XV]
			VAR comp = [Sale Markdown XV LY]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\LY
		lineageTag: 6c925033-1eed-4274-9724-1414bd549981

	measure 'Sale Markdown XV vs LY-1' =
			VAR act = [Sale Markdown XV]
			VAR comp = [Sale Markdown XV LY-1]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		description: Two years ago equivalent of Sale Markdown XV vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\LY-1
		lineageTag: 7f387fdd-b1e5-4742-8d27-b3136a687931

	measure 'Sale Markdown XV % LY' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown XV % Orders LY],
			        "Dispatch", [Sale Markdown XV % Dispatch LY],
			        [Sale Markdown XV % Orders LY]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Sale Markdown\LY
		lineageTag: 5b350630-bf2e-44b0-820d-fa718135b359

	measure 'Sale Markdown XV % LY-1' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown XV % Orders LY-1],
			        "Dispatch", [Sale Markdown XV % Dispatch LY-1],
			        [Sale Markdown XV % Orders LY-1]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		description: Two years ago equivalent of Sale Markdown XV % LY.
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Sale Markdown\LY-1
		lineageTag: eccbc695-aeec-49ce-8863-ebdba8f27bc7

	measure 'Sale Markdown XV % vs LY' =
			VAR act = [Sale Markdown XV %]
			VAR comp = [Sale Markdown XV % LY]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\LY
		lineageTag: a6dd3a92-8021-4468-a5cc-8558a130a0f1

	measure 'Sale Markdown XV % vs LY-1' =
			VAR act = [Sale Markdown XV %]
			VAR comp = [Sale Markdown XV % LY-1]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		description: Two years ago equivalent of Sale Markdown XV % vs LY.
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\LY-1
		lineageTag: 840dc244-feb7-4ece-9440-95894d9ae57f

	measure 'Sale Markdown XV vs LY %' =
			VAR act = [Sale Markdown XV]
			VAR comp = [Sale Markdown XV LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\LY
		lineageTag: 4367d99e-7c89-4fdc-a67c-1b0d9ca95730

	measure 'Sale Markdown XV LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown XV Orders LW],
			        "Dispatch", [Sale Markdown XV Dispatch LW],
			        [Sale Markdown XV Orders LW]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\LW
		lineageTag: b78a87f9-27ea-4b1b-bf0e-27d7125512f9

	measure 'Sale Markdown XV vs LW' =
			VAR act = [Sale Markdown XV]
			VAR comp = [Sale Markdown XV LW]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\LW
		lineageTag: 0dbb900c-1ec7-4a5b-b8d6-aa73d375b34b

	measure 'Sale Markdown XV % LW' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown XV % Orders LW],
			        "Dispatch", [Sale Markdown XV % Dispatch LW],
			        [Sale Markdown XV % Orders LW]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Sale Markdown\LW
		lineageTag: c1a144b2-e4ca-433e-8f2c-86c0161a3e2d

	measure 'Sale Markdown XV % vs LW' =
			VAR act = [Sale Markdown XV %]
			VAR comp = [Sale Markdown XV % LW]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\LW
		lineageTag: db4c92cc-0979-46b2-862b-01372f38390d

	measure 'Sale Markdown XV vs LW %' =
			VAR act = [Sale Markdown XV]
			VAR comp = [Sale Markdown XV LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\LW
		lineageTag: 7dde66d5-b290-42e0-b635-534ad2b046cc

	measure 'Sale Markdown XV BUD' = ```
			
			 VAR firstweek_yr = [SlctdBudVersion]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    [fiscalWeek] <  firstweek_yr,
			            [Sale Markdown XV],
			            [Sale Markdown XV Orders BUD]
			    )       )
			RETURN
			SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,SUMX ( salesTable, [Actualised] ))  
			/*VAR result = [Sale Markdown XV Orders BUD]
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output*/
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\BUD
		lineageTag: c0f6a6db-b85d-47c7-9916-6650623c705e

	measure 'Sale Markdown XV vs BUD' =
			VAR act = [Sale Markdown XV]
			VAR comp = [Sale Markdown XV BUD]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\BUD
		lineageTag: 02ec54a8-c978-47fc-be99-0f1bc511893c

	measure 'Sale Markdown XV % BUD' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown XV % Orders BUD],
			        "Dispatch", [Sale Markdown XV % Dispatch BUD],
			        [Sale Markdown XV % Orders BUD]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Sale Markdown\BUD
		lineageTag: b6631483-9645-4dd5-a3e7-d78582eea7e4

	measure 'Sale Markdown XV % vs BUD' =
			VAR act = [Sale Markdown XV %]
			VAR comp = [Sale Markdown XV % BUD]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\BUD
		lineageTag: 31625d5d-754f-411e-b22d-3aa98845c32f

	measure 'Sale Markdown XV vs BUD %' =
			VAR act = [Sale Markdown XV]
			VAR comp = [Sale Markdown XV BUD]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\BUD
		lineageTag: 11df74d9-4f3d-45a7-a03e-b236fb2046ec

	measure 'Sale Markdown XV FC' =
			//SelectedWeeks
			VAR firstweek_qtr = [SlctdFirstWeekQtrFC]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [Sale Markdown XV],
			            [Sale Markdown XV Orders FC]
			    )       )
			RETURN
			SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,SUMX ( salesTable, [Actualised] ))
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\FC
		lineageTag: bf17e6f1-bb1b-471c-b9f1-7f46a29913e4

	measure 'Sale Markdown XV vs FC' =
			VAR act = [Sale Markdown XV]
			VAR comp = [Sale Markdown XV FC]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\FC
		lineageTag: 14b88a35-9986-4235-8994-c4b135f53c10

	measure 'Sale Markdown XV % FC' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown XV % Orders FC],
			        "Dispatch", [Sale Markdown XV % Dispatch FC],
			        [Sale Markdown XV % Orders FC]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Sale Markdown\FC
		lineageTag: 070cbc09-ce6d-44cf-b369-3aad5f91c37e

	measure 'Sale Markdown XV % vs FC' =
			VAR act = [Sale Markdown XV %]
			VAR comp = [Sale Markdown XV % FC]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\FC
		lineageTag: da832bc4-63ee-4e9f-acc2-ee81704aa4eb

	measure 'Sale Markdown XV vs FC %' =
			VAR act = [Sale Markdown XV]
			VAR comp = [Sale Markdown XV FC]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\FC
		lineageTag: 8260a3c6-6157-4dd3-8901-cc393572775b

	measure 'Sale Markdown XV QRF' =
			//SelectedWeeks
			VAR firstweek_qtr = [SlctdFirstWeekQtrQRF]
			VAR firstweek_yr = [slctdFirstWeekYr]
			//Generate Temp Table
			VAR salesTable =
			ADDCOLUMNS  (
			    VALUES ( 'Calendar'[fiscalWeek] ),
			    "Actualised",
			    IF (    AND([fiscalWeek] < firstweek_qtr, [fiscalWeek] >= firstweek_yr),
			            [Sale Markdown XV],
			            [Sale Markdown XV Orders QRF]
			    )       )
			RETURN
			SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,SUMX ( salesTable, [Actualised] ))
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\QRF
		lineageTag: f48c4e20-8df2-49fa-913d-b91c63db3402

	measure 'Sale Markdown XV vs QRF' =
			VAR act = [Sale Markdown XV]
			VAR comp = [Sale Markdown XV QRF]
			VAR result = act - comp
			RETURN
			    If(AND(Act = Blank(), Comp = Blank()), blank(), result)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Sale Markdown\QRF
		lineageTag: 591f0d4a-1d7a-4086-a72f-401f05e7e9fb

	measure 'Sale Markdown XV % QRF' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Sale Markdown XV % Orders QRF],
			        "Dispatch", [Sale Markdown XV % Dispatch QRF],
			        [Sale Markdown XV % Orders QRF]
			    )
			Var Output = SWITCH(SELECTEDVALUE(SalesType[SalesType]),"FP&P",0,result)
			RETURN
			    Output
		formatString: 0.0%;(0.0)%
		displayFolder: Margin\Sale Markdown\QRF
		lineageTag: dc1ce6ce-17dc-4a75-8771-d7ca915a1f3b

	measure 'Sale Markdown XV % vs QRF' =
			VAR act = [Sale Markdown XV %]
			VAR comp = [Sale Markdown XV % QRF]
			VAR result = act - comp
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result * 1 )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\QRF
		lineageTag: 13b4f399-7158-42dc-9a16-499b7d1fff53

	measure 'Sale Markdown XV vs QRF %' =
			VAR act = [Sale Markdown XV]
			VAR comp = [Sale Markdown XV QRF]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Sale Markdown\QRF
		lineageTag: 5943842a-35b7-4a24-960a-73c24c95e12b

	measure 'Sale Markdown VAT Orders' = Divide([Sale Markdown Orders],[Sale Markdown XV Orders])
		displayFolder: Margin\Orders\Sale Markdown\Actual
		lineageTag: d7a3573b-52c3-440e-9f23-fe7a4ba2c08b

	measure 'Sale Markdown VAT Orders LY' = Divide([Sale Markdown Orders LY],[Sale Markdown XV Orders LY])
		displayFolder: Margin\Orders\Sale Markdown\LY
		lineageTag: 5f692cbf-92b9-41f1-b656-98acf2d5b1fa

	measure 'Sale Markdown VAT Orders LY-1' = Divide([Sale Markdown Orders LY-1],[Sale Markdown XV Orders LY-1])
		displayFolder: Margin\Orders\Sale Markdown\LY-1
		lineageTag: 6edc2dea-56b9-46c2-8ca9-4652096cac90

		description: Two years ago equivalent of Sale Markdown VAT Orders LY.

	measure 'Sale Markdown VAT Orders BUD' = Divide([Sale Markdown Orders BUD],[Sale Markdown XV Orders BUD])
		displayFolder: Margin\Orders\Sale Markdown\BUD
		lineageTag: eda2f42d-d01a-46a2-b17a-d69ffc4e5c23

	measure 'Sale Markdown VAT Orders FC' = Divide([Sale Markdown Orders FC],[Sale Markdown XV Orders FC])
		displayFolder: Margin\Orders\Sale Markdown\FC
		lineageTag: 2b729025-7e0c-4d69-b488-1aa2a134f542

	measure 'Sale Markdown VAT Orders QRF' = Divide([Sale Markdown Orders QRF],[Sale Markdown XV Orders QRF])
		displayFolder: Margin\Orders\Sale Markdown\QRF
		lineageTag: b8ca8f82-7f89-4168-82a7-0cb20129c935

	measure 'Sale Markdown VAT Orders LW' = Divide([Sale Markdown Orders LW],[Sale Markdown XV Orders LW])
		displayFolder: Margin\Orders\Sale Markdown\LW
		lineageTag: 988454d9-eed9-4251-9d91-887deff5591e

	measure Mbr98_CalculatedCOGS = CALCULATE([SREV] - [GSM], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", FILTER(Products,Products[BU] <> "Other" && Products[BU] <> "GM Other"))
		displayFolder: Margin\Bridge\Calculations
		lineageTag: 4a7d7d15-cd2a-4e46-aa33-248b7ec0d7f4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MbrComp17_COGSOld =
			
			VAR FCVersion = [SlctdForecastVersion]
			VAR QRFVersions = [SlctdQRFVersion]
			VAR comp = [slctd_MarginBridgeComparator]
			VAR result =
			    SWITCH (
			        comp,
			        "ACT", CALCULATE ( [sum_TotSlsC], factForecast[plan] = "RF" ,OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "LW",
			            CALCULATE (
			                [sum_TotSlsC],
			                factForecast[plan] = "RF",
			                OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets",
			                Products[BU] <> "Other" && Products[BU] <> "GM Other",
			                USERELATIONSHIP ( factForecast[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			            ),
			        "QRF", CALCULATE ( [sum_TotSlsC], factForecast[plan] = QRFVersions ,OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "FC", CALCULATE ( [sum_TotSlsC], factForecast[plan] = FCVersion ,OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "BUD", CALCULATE ( [sum_TotSlsC], ForecastScenarios[Forecast Scenario] = "BUD" ,OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets", Products[BU] <> "Other" && Products[BU] <> "GM Other"),
			        "LY",
			            CALCULATE (
			                [sum_TotSlsC],
			                factForecast[plan] = "RF",
			                OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets",
			                Products[BU] <> "Other" && Products[BU] <> "GM Other",
			                USERELATIONSHIP ( factForecast[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			            )
			    )
			RETURN
			    result
		displayFolder: Margin\Bridge\Comp Metrics
		lineageTag: c8aa7a7a-296a-4ff2-a6a5-b44290195706

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rbr99_InscopeTest = ISFILTERED(Products[Dept])
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 6555f175-9af2-4b09-9b7d-e913f701c8e2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rbr90_BrandsImpact = switch(round([RR Brands Impact %],4)=0,true(),blank(),[RR Brands Impact %])
		formatString: 0.0%;(0.0)%;0.0%
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: a62c1588-02dc-4a9a-976f-bbc59a44a2b6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rbr91_ChannelMix =
			VAR SelectedChannel = [Slctd_Channel]
			Return
			SWITCH(SelectedChannel,"Total",[RBR_ChMx_Var],blank())
		formatString: 0.0%;(0.0)%;0.0%
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 65066fd4-2ce2-4ed1-84f5-ec89ac80e9fb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Rbr92_ProductMix =
			VAR SelectedChannel = [Slctd_Channel]
			Return
			SWITCH(True(),OR(ISINSCOPE(Products[Dept]),ISFILTERED(Products[Dept])),blank(),[Rbr11_RRMixImpact] - SWITCH(SelectedChannel,"Total",[RBR_ChMx_Var],0))
		formatString: 0.0%;(0.0)%;0.0%
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: fec44d51-7e07-4334-9cc1-0516b73ddd14

	measure Rbr93_Rate =
			VAR SelectedChannel = [Slctd_Channel]
			RETURN
			[Rbr10_RRRateImpact] + SWITCH(True(),OR(ISINSCOPE(Products[Dept]),ISFILTERED(Products[Dept])),[Rbr11_RRMixImpact] - SWITCH(SelectedChannel,"Total",[RBR_ChMx_Var],0),blank())
		formatString: 0.0%;(0.0)%;0.0%
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 93923618-0ff9-4b3e-afcc-28ca70a237b8

	measure Rbr94_Other = ```
			switch([RR Other Impact % ex Brands]=0,true(),blank(),[RR Other Impact % ex Brands])
			
			```
		formatString: 0.0%;(0.0)%;0.0%
		displayFolder: Sales\Returns\Returns Bridge
		lineageTag: 6c5c6ebb-4779-4090-bc57-d047f6eb5365

	measure Mbr_BUMix01_TYSlsLYMix
		displayFolder: Presentation
		lineageTag: 5b69449f-a90d-4c3e-a7b1-089f54b3562e

	measure MbrMix01_FPPSales =
			
			//Var tbl = ADDCOLUMNS(VALUES(Products[Dept]),"CompFPP",[MbrComp02_SRIVFPP],"CompTot",[MbrComp01_SRIVMainchain],"ActTot",[Mbr01_SRIVMainchain])
			Var tbl = ADDCOLUMNS(VALUES(Products[Dept]),"CompFPP",DIVIDE([Mbr02_SRIVFPP],[Mbr01_SRIVMainchain])*[MbrMix00_SRIV])
			Var Result = SUMX(tbl,[CompFPP])
			RETURN
			Result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixProduct
		lineageTag: 805d447d-5fd6-4ee6-aad9-ed7f7983d9a3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MbrMix02_RPSales =
			
			/*
			VAR tbl =
			    ADDCOLUMNS (
			        VALUES ( Products[Dept] ),
			        "ActFPP", [MbrMix01_FPPSales],
			        "ActTot", [MbrMix00_SRIV]
			    )
			VAR Result =
			    SUMX ( tbl, [ActTot] ) - SUMX ( tbl, [ActFPP] )
			RETURN
			*/
			    [MbrMix00_SRIV] - [MbrMix01_FPPSales]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixProduct
		lineageTag: 3be01fcc-9304-473d-80db-2ce3793e8537

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MbrMix03_SREV = ```
			VAR tbl =
			    ADDCOLUMNS (
			        VALUES ( Products[Dept] ),
			        "ActTot", [Mbr01_SRIVMainchain],
			        "CompSRIV",[MbrComp01_SRIVMainchain],
			        "CompSREV",[MbrComp05_SREVMainchain]
			    )
			VAR Result = 
			DIVIDE (
			    SUMX(tbl, [ActTot]),
			    DIVIDE(SUMX(tbl, [CompSRIV]),SUMX(tbl, [CompSREV]))
			)
			RETURN
			Result
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixProduct
		lineageTag: ae7c05f2-35e1-4dad-8be0-d1925d1dd111

	measure MbrMix04_POS = ```
			VAR tbl =
			    ADDCOLUMNS (
			        VALUES ( Products[Dept] ),
			        "POSCalc",DIVIDE(
			                    [MbrMix01_FPPSales] * DIVIDE (-[MbrComp12_POS], [MbrComp02_SRIVFPP] - [MbrComp12_POS]),
			                    1-DIVIDE (-[MbrComp12_POS], [MbrComp02_SRIVFPP] - [MbrComp12_POS]))
			    )
			VAR Result = 
			    SUMX(tbl, [POSCalc])
			RETURN
			Result
			/* calculation to match excel margin bridge
			DIVIDE(
			                    [MbrMix01_FPPSales] * DIVIDE (-[MbrComp12_POS], [MbrComp02_SRIVFPP] - [MbrComp12_POS]),
			                    1-DIVIDE (-[MbrComp12_POS], [MbrComp02_SRIVFPP] - [MbrComp12_POS]))
			*/
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixProduct
		lineageTag: 0356b0d0-e35c-47e4-b44f-a7dda4545b3a

	measure MbrMix05_Realised = ```
			VAR tbl =
			    ADDCOLUMNS (
			        VALUES ( Products[Dept] ),
			        "Calc", Divide(
			                    Divide(-[MbrComp09_SaleMD], [MbrComp03_SRIVRP] -[MbrComp09_SaleMD]  ) * [MbrMix02_RPSales],
			                    1-Divide(-[MbrComp09_SaleMD], [MbrComp03_SRIVRP] -[MbrComp09_SaleMD]  ) 
			                       )
			                )
			VAR Result = 
			    SUMX(tbl, [Calc])
			RETURN
			Result
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixProduct
		lineageTag: 2708d5f2-8e91-461f-9472-ac6305129f5d

	measure MbrMix06_RealisedExVAT = ```
			VAR tbl =
			    ADDCOLUMNS (
			        VALUES ( Products[Dept] ),
			        "Calc",     DIVIDE (
			                            [MbrMix05_Realised],
			                            DIVIDE ( [MbrComp09_SaleMD], [MbrComp10_SaleMDExVAT] )
			                            )
			                )
			VAR Result = 
			    SUMX(tbl, [Calc])
			RETURN
			Result
			
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixProduct
		lineageTag: 95bfbcab-6b73-41c9-85b6-f12a0dfcec9f

	measure MbrMix07_GSRIV = [MbrMix00_SRIV] + [MbrMix04_POS] + [MbrMix05_Realised]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixProduct
		lineageTag: 937e6d49-8f5b-4df3-9e83-42ef39e70431

	measure MbrMix08_GSREV =
			[MbrMix03_SREV] + [MbrMix06_RealisedExVAT]
			    + DIVIDE (
			        [MbrMix04_POS],
			        DIVIDE ( [MbrMix01_FPPSales] + [MbrMix02_RPSales], [MbrMix03_SREV] )
			    )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixProduct
		lineageTag: 90b79b46-f4f5-4b60-b96e-e777a09fabdd

	measure MbrMix09_COGS = ```
			VAR tbl =
			    ADDCOLUMNS (
			        VALUES ( Products[Dept] ),
			        "Calc",     (1-[MbrComp16_BIMPct]) * [MbrMix08_GSREV]
			                )
			VAR Result = 
			    SUMX(tbl, [Calc])
			RETURN
			Result
			
			```
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixProduct
		lineageTag: 6b572072-eea5-4573-92f2-39a1d2f51233

	measure MbrMix10_GSM = [MbrMix03_SREV] - [MbrMix09_COGS]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixProduct
		lineageTag: d8a07045-ef11-4d0d-aff9-33b9e1d40d19

	measure MbrMix11_GSMPercent =
			Var tbl = ADDCOLUMNS(VALUES(Products[Dept]),"TblGSM",[MbrMix10_GSM],"TblSREV",[MbrMix03_SREV])
			Var Result = DIVIDE(SUMX(tbl,[TblGSM]),SUMX(tbl,[TblSREV]),BLANK())
			RETURN
			Result
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Calculations\MbrMixProduct
		lineageTag: c54bf203-c5ae-4155-807e-4059997d2314

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MbrMix12_GSMValue =
			Var tbl = ADDCOLUMNS(VALUES(Products[Dept]),"TblGSM",[MbrMix10_GSM],"TblSREV",[MbrMix03_SREV])
			Var Result = SUMX(tbl,[TblGSM])
			RETURN
			Result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixProduct
		lineageTag: f98a79fb-2d89-4226-bddb-635f26a32af4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MbrMixTotal06_VAT =
			VAR comp_metric = [slctd_Variable]
			RETURN
			    IF ( comp_metric = "VAT", DIVIDE ( ([MbrMix01_FPPSales]+[MbrMix02_RPSales]), [MbrMix03_SREV] ) - 1 , [MbrComp06_VAT])
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Calculations\MbrMixTotal
		lineageTag: a6a704ff-944d-41e1-b676-1c503aa8a2af

	measure MbrMixTotal07_POS =
			VAR comp_metric = [slctd_Variable]
			VAR Result =
			    SWITCH (
			        comp_metric,
			        "Vol", Divide(-[MbrComp12_POS],[MbrComp02_SRIVFPP]),
			        "FP&P Mix", Divide(-[MbrComp12_POS],[MbrComp02_SRIVFPP]),
			        "BIM", Divide(-[MbrComp12_POS],[MbrComp02_SRIVFPP]),
			        Divide([MbrMix04_POS],[MbrMix01_FPPSales])
			    )
			RETURN
			    Result * [MbrMixTotal02_SRIVFPP]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixTotal
		lineageTag: 91ab587a-1472-454f-a43b-82fa4989a9ca

	measure MbrMixTotal09_SaleMD =
			VAR comp_metric = [slctd_Variable]
			VAR md_pct =
			    SWITCH (
			        comp_metric,
			        "Vol", Divide(-[MbrComp09_SaleMD],([MbrComp03_SRIVRP]-[MbrComp09_SaleMD])),
			        "FP&P Mix", Divide(-[MbrComp09_SaleMD],([MbrComp03_SRIVRP]-[MbrComp09_SaleMD])),
			        "BIM", Divide(-[MbrComp09_SaleMD],([MbrComp03_SRIVRP]-[MbrComp09_SaleMD])),
			        "POS", Divide(-[MbrComp09_SaleMD],([MbrComp03_SRIVRP]-[MbrComp09_SaleMD])),
			        Divide([MbrMix05_Realised],[MbrMix02_RPSales]+[MbrMix05_Realised])
			    )
			RETURN
			    DIVIDE ( [MbrMixTotal03_SRIVRP], ( 1 - md_pct ) ) - [MbrMixTotal03_SRIVRP]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixTotal
		lineageTag: f63fb9a5-0bc6-4986-862b-e1adab50faf4

	measure MbrMixTotal10_SaleMDExVAT =
			VAR comp_metric = [slctd_Variable]
			VAR vat_rate =
			    SWITCH (
			        comp_metric,
			        "VAT", Divide([MbrMix05_Realised],[MbrMix06_RealisedExVAT]),
			        Divide([MbrComp09_SaleMD],[MbrComp10_SaleMDExVAT])
			    )
			VAR ex_vat =
			    DIVIDE ( [MbrMixTotal09_SaleMD], ( vat_rate ) )
			RETURN
			    ex_vat
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixTotal
		lineageTag: 64758373-6ecc-46a9-875e-c858b9f04721

		annotation PBI_FormatHint = {"isCustom":true}

	measure MbrMixTotal12_TotalMD = [MbrMixTotal07_POS]+[MbrMixTotal09_SaleMD]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixTotal
		lineageTag: 757c439f-db6f-493a-8a21-2c8db099692d

	measure MbrMixTotal15_GrossSRIV = [MbrMixTotal01_SRIVMainchain]+[MbrMixTotal12_TotalMD]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixTotal
		lineageTag: 8cd06edd-6a14-461c-a153-a8d87c0ce2b7

	measure MbrMixTotal16_GrossSREV =
			VAR comp_metric = [slctd_Variable]
			VAR result =
			    SWITCH (
			        comp_metric,
			        "Vol", [MbrMixTotal01_SRIVMainchain] * DIVIDE ( [MbrComp14_GrossSREV],[MbrComp01_SRIVMainchain] ),
			        "FP&P Mix", Divide([MbrMixTotal15_GrossSRIV], Divide([MbrComp13_GrossSRIV],[MbrComp14_GrossSREV])),
			        "BIM", Divide([MbrMixTotal15_GrossSRIV], Divide([MbrComp13_GrossSRIV],[MbrComp14_GrossSREV])),
			        "POS", Divide([MbrMixTotal15_GrossSRIV], Divide([MbrComp13_GrossSRIV],[MbrComp14_GrossSREV])),
			        "DoC", Divide([MbrMixTotal15_GrossSRIV], Divide([MbrComp13_GrossSRIV],[MbrComp14_GrossSREV])),
			        "VAT", Divide([MbrMixTotal15_GrossSRIV], Divide([MbrMix07_GSRIV],[MbrMix08_GSREV]))
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixTotal
		lineageTag: e622f57c-4b22-4c45-8637-c1f6bfcab6d2

	measure MbrMixTotal18_COGS =
			VAR comp_metric = [slctd_Variable]
			VAR result =
			    SWITCH (
			        comp_metric,
			        "Vol", Divide(-[MbrComp17_COGS],[MbrComp05_SREVMainchain]) * [MbrMixTotal05_SREVMainchain],
			        "FP&P Mix", Divide(-[MbrComp17_COGS],[MbrComp14_GrossSREV]) * [MbrMixTotal16_GrossSREV],
			        [MbrMixTotal16_GrossSREV] * Divide([MbrMix09_COGS],[MbrMix08_GSREV])
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixTotal
		lineageTag: 68af3782-05e6-4413-86b9-ac338191c236

	measure MbrMixTotal19_GSM = [MbrMixTotal05_SREVMainchain]-[MbrMixTotal18_COGS]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixTotal
		lineageTag: 27b52852-5d09-48fc-97ce-261254a5bd37

	measure MbrMixTotal20_GSMPct = Divide([MbrMixTotal19_GSM],[MbrMixTotal05_SREVMainchain])
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Calculations\MbrMixTotal
		lineageTag: 5bc810f2-a746-46c6-9f76-f835570e063a

	measure MbrMixTotal01_SRIVMainchain = [MbrMix01_FPPSales]+[MbrMix02_RPSales]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixTotal
		lineageTag: ce3cb1d6-4134-485e-bb3f-4d97d3d2391d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MbrMixTotal02_SRIVFPP =
			VAR comp_metric = [slctd_Variable]
			VAR result_for_vol =
			    DIVIDE ( [MbrComp02_SRIVFPP], [MbrComp01_SRIVMainchain] ) * [MbrMixTotal01_SRIVMainchain]
			RETURN
			SWITCH(SELECTEDVALUE(SalesType[SalesType]),"Reduced",0,
			    IF (
			        comp_metric = "Vol",
			        result_for_vol,
			        [MbrMix01_FPPSales]
			    ))
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixTotal
		lineageTag: 32897092-0ec3-41db-8c9e-4250460e45b6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MbrMixTotal03_SRIVRP = [MbrMixTotal01_SRIVMainchain] - [MbrMixTotal02_SRIVFPP]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixTotal
		lineageTag: a678f74b-2b70-45ad-b8f7-2b808fe4d023

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MbrMixTotal04_SRIV = [MbrMixTotal01_SRIVMainchain]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixTotal
		lineageTag: eb9c93f2-72d3-4ca1-8ed3-b5a0b003ae03

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MbrMixTotal05_SREVMainchain =
			VAR comp_metric = [slctd_Variable]
			VAR result =
			    SWITCH (
			        comp_metric,
			        "VAT", Divide([MbrMixTotal04_SRIV],divide([MbrMix01_FPPSales]+[MbrMix02_RPSales],[MbrMix03_SREV])),
			        Divide([MbrMixTotal04_SRIV],divide([MbrComp04_SRIV],[MbrComp05_SREVMainchain]))
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Margin\Bridge\Calculations\MbrMixTotal
		lineageTag: 308e2dbb-ec6f-4b1e-9e3e-83824311da10

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MbrMix00_SRIV =
			
			//Var tbl = ADDCOLUMNS(VALUES(Products[Dept]),"ActTot",[Mbr01_SRIVMainchain])
			//Var CompMix = DIVIDE([MbrComp04_SRIV],CALCULATE([MbrComp04_SRIV],ALL(Products)))
			//Var ActTot = CALCULATE([Mbr01_SRIVMainchain],ALL(Products))
			Var tbl = ADDCOLUMNS(   VALUES(Products[Dept]),
			                        "ActLYMix",
			                        DIVIDE(
			                            [MbrComp04_SRIV],                               //CompSRIVbyDept
			                            CALCULATE([MbrComp04_SRIV],ALL(Products))) *    //CompTotal
			                            CALCULATE([Mbr01_SRIVMainchain],ALL(Products))) //ActTotal
			Var Result = SUMX(tbl,[ActLYMix])
			RETURN
			Result
		displayFolder: Margin\Bridge\Calculations\MbrMixProduct
		lineageTag: cf2f5c07-d929-4fae-ba47-1f84ce3b80a0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MbrVis07_MixWalk% = ```
			
			VAR SelectedComp = [slctd_MarginBridgeComparator]
			VAR Selectedcompresult =
			    SWITCH (
			        SelectedComp,
			        "ACT", CALCULATE([GSM % SREV], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "LW", CALCULATE([GSM % SREV LW], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "QRF", CALCULATE([GSM % SREV QRF], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "FC", CALCULATE([GSM % SREV FC], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "BUD", CALCULATE([GSM % SREV BUD], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets"),
			        "LY", CALCULATE([GSM % SREV LY], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets")
			    )
			VAR RealComp =
			    SWITCH (
			        SelectedComp,
			        "ACT", [GSM % SREV],
			        "LW", [GSM % SREV LW],
			        "QRF", [GSM % SREV QRF],
			        "FC", [GSM % SREV FC], 
			        "BUD", [GSM % SREV BUD], 
			        "LY", [GSM % SREV LY]
			    )
			VAR Comp = Selectedcompresult
			VAR Vol = CALCULATE([MbrMixTotal20_GSMPct], All(MarginBridgeVariable), MarginBridgeVariable[Variable] = "Vol")
			Var FPP = CALCULATE([MbrMixTotal20_GSMPct], All(MarginBridgeVariable), MarginBridgeVariable[Variable] = "FP&P Mix")
			Var BIM = CALCULATE([MbrMixTotal20_GSMPct], All(MarginBridgeVariable), MarginBridgeVariable[Variable] = "BIM")
			Var POS = CALCULATE([MbrMixTotal20_GSMPct], All(MarginBridgeVariable), MarginBridgeVariable[Variable] = "POS")
			Var DOC = CALCULATE([MbrMixTotal20_GSMPct], All(MarginBridgeVariable), MarginBridgeVariable[Variable] = "DOC")
			Var VAT = CALCULATE([MbrMixTotal20_GSMPct], All(MarginBridgeVariable), MarginBridgeVariable[Variable] = "VAT")
			Var Act = CALCULATE([GSM % SREV], OutletsControl[Ex Outlets/Outlets] = "M&S Ex Outlets")
			Var VolVar = 0
			Var FPPVar = FPP - Vol
			Var BIMVar = BIM - FPP
			Var POSVar = POS - BIM
			Var DOCVar = DOC - POS
			Var VatVar = VAT - DOC
			Var OtherVar = Act - VatVar - DOCVar - POSVar - BIMVar - FPPVar - VolVar - Comp
			Var RealAct = [GSM % SREV]
			RETURN
			SWITCH(
			    SELECTEDVALUE(MarginBridgeWalk[Step])
			    ,"Comp", RealComp
			    ,"Vol", VolVar
			    ,"FP&P Mix", FPPVar
			    ,"BIM", BIMVar
			    ,"POS", POSVar
			    ,"DOC", DOCVar
			    ,"VAT", VatVar
			    ,"Other", OtherVar
			    ,"Outlets",[MbrVis02_OutletGSMVar]
			    ,"Actual", RealAct
			    )
			```
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Margin\Bridge\Presentation
		lineageTag: 10904528-3435-4cc2-b234-c74c18ba6bfe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure AOV =
			VAR num = [sum_net_revenue_factAOV]
			VAR denom = [sum_orders_factAOV]
			VAR result =
			    DIVIDE ( num, denom )
			RETURN
			    IF ( OR ( num = BLANK (), denom = BLANK () ), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\AOV\Actual
		lineageTag: 822584e1-3b1a-484f-9743-8407ca437dd7

	measure 'AOV LW' =
			CALCULATE (
			    [AOV],
			    USERELATIONSHIP ( factAOV[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\AOV\LW
		lineageTag: b0a5bc60-8d8c-494f-b55d-63573f4dcb36

	measure 'AOV vs LW' =
			VAR act = [ABV]
			VAR comp = [ABV LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\AOV\LW
		lineageTag: bc02853e-0dae-4f83-a61e-77507bc29555

	measure 'AOV vs LW %' =
			VAR act = [AOV]
			VAR comp = [AOV LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\AOV\LW
		lineageTag: b8d369f8-b5a7-418b-9e2e-70b5dfcd7534

	measure 'Unadj Traffic' =
			
			CALCULATE(SUM(factAdobe[visitsUnadjusted]),factAdobe[visitType] = 2)
			//[sum_visitsL2_factAdobe]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Traffic\Actual
		lineageTag: f1d659b0-98fd-4f71-9479-9c281abc432c

	measure 'Traffic LW' =
			
			CALCULATE(SUM(factAdobe[visitsL2]), factAdobe[visitType] = 1, USERELATIONSHIP(factAdobe[fiscalWeek],'Calendar'[fiscalWeekLastWeek]))
			
			/*VAR unadj = CALCULATE (
			        [Unadj Traffic],
			        USERELATIONSHIP ( factAdobe[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			    )
			VAR adj =
			    CALCULATE (
			        [Unadj Traffic],
			        USERELATIONSHIP ( factAdobe[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			    ) * [TY Actuals Uplift]
			RETURN
			    IF (
			        VALUE ( LEFT ( SELECTEDVALUE ( 'Calendar'[fiscalWeekLastWeek] ), 4 ) ) = 3000,
			        adj,
			        unadj
			    )*/
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Traffic\LW
		lineageTag: 1c66f516-be28-4d8b-822b-d359c30c2605

	measure 'Traffic vs LW' =
			VAR act = [Unadj Traffic]
			VAR comp = [Traffic LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Traffic\LW
		lineageTag: f8c53da5-eb81-4503-9775-74ea47222062

	measure 'Traffic vs LW %' =
			VAR act = [Unadj Traffic]
			VAR comp = [Traffic LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\Traffic\LW
		lineageTag: 9d0e49bd-8a29-4aa6-a8d5-74a851e32bdc

	measure SwitchOnlineMetric =
			VAR channel =
			    SELECTEDVALUE ( ChannelControl[Channel] )
			VAR metric = [slctd_OnlineMetric]
			VAR result =
			    SWITCH (
			        metric,
			        "Traffic", [Visits],
			        "Conv", [Conversion %],
			        "Orders", [sum_orders_factAOV],
			        "AOV", [AOV]
			    )
			RETURN
			    SWITCH (
			        channel,
			        "Online", result,
			        BLANK ()
			)
		formatString: #,##0.0;(#,##0.0)
		displayFolder: SwitchOnlineMetric\Actual
		lineageTag: f2aaf890-c0b4-4ed8-9777-e78ace912906

	measure 'SwitchOnlineMetric LW' =
			VAR channel =
			    SELECTEDVALUE ( ChannelControl[Channel] )
			VAR metric = [slctd_OnlineMetric]
			VAR result =
			    SWITCH (
			        metric,
			        "Traffic", [Visits LW],
			        "Conv", [Conversion % LW],
			        "Orders", [factAOV Orders LW],
			        "AOV", [AOV LW]
			    )
			RETURN
			    SWITCH (
			        channel,
			        "Online", result,
			        BLANK ()
			)
		formatString: #,##0.0;(#,##0.0)
		displayFolder: SwitchOnlineMetric\LW
		lineageTag: 63da9736-29e9-448d-9080-632e98065cc9

	measure 'SwitchOnlineMetric vs LW' =
			VAR act = [SwitchOnlineMetric]
			VAR comp = [SwitchOnlineMetric LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: SwitchOnlineMetric\LW
		lineageTag: ef4d39f5-f1e9-4529-9f6b-b93deda8c598

	measure 'SwitchOnlineMetric vs LW %' =
			VAR act = [SwitchOnlineMetric]
			VAR comp = [SwitchOnlineMetric LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0%;(#,##0)%
		displayFolder: SwitchOnlineMetric\LW
		lineageTag: 717bcf34-2515-4877-9d43-b4d94405ec4c

	measure 'SwitchOnlineMetric vs LW Hybrid' =
			VAR metric = [slctd_OnlineMetric]
			VAR result =
			    SWITCH (
			        metric,
			         "Traffic", [Visits vs LW %],
			        "Conv", [Conversion % vs LW],
			        "Orders", [Transactions vs LW %],
			        "AOV", [AOV vs LW %]
			    )
			RETURN
			    result
		formatString: #,##0%;(#,##0)%
		displayFolder: SwitchOnlineMetric\LW
		lineageTag: cd37b4dd-7009-4485-b297-a9a57d4745f3

	measure tiExFurnitureHeadlines = [tiWeekNo] & " | " & [tiProductExFurniture] & " | " & [tiChannel] & " | " & [tiSalesType] & " | " & [tiSalesRecogType]
		lineageTag: 093dd4ba-8bab-443c-bad2-905d8d43df53

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure tiProductExFurniture =
			VAR _ProductDisplay =
			    SWITCH (
			        TRUE (),
			        OR ( ISFILTERED ( Products[Dept] ), ISFILTERED ( Products[Dept Code] ) ), SELECTEDVALUE ( Products[Dept], "Multiple Depts" ),
			        OR ( ISFILTERED ( Products[BU] ), ISFILTERED ( Products[BU Code] ) ), SELECTEDVALUE ( Products[BU], "Multiple BUs" ),
			        "All FH&B"
			    )
			RETURN
			    IF ( ISBLANK ( _ProductDisplay ), "All FH&B", _ProductDisplay ) & " Ex. Furniture"
		lineageTag: dfe242b8-5947-4950-8dd4-1f2467aac1b2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Traffic LY' =
			
			CALCULATE(SUM(factAdobe[visitsL2]), factAdobe[visitType] = 1, USERELATIONSHIP(factAdobe[fiscalWeek],'Calendar'[fiscalWeekLastYear]))
			
			/*CALCULATE (
			    [Unadj Traffic],
			    USERELATIONSHIP ( factAdobe[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)*/
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Traffic\LY
		lineageTag: 87294e99-378d-4112-ab4d-adf43af4dbbc

	measure 'Traffic LY-1' =
			
			CALCULATE(SUM(factAdobe[visitsL2]), factAdobe[visitType] = 1, USERELATIONSHIP(factAdobe[fiscalWeek],'Calendar'[fiscalWeekLastToLastyear]))
			
			/*CALCULATE (
			    [Unadj Traffic],
			    USERELATIONSHIP ( factAdobe[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)*/
		description: Two years ago equivalent of Traffic LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Traffic\LY-1
		lineageTag: 736edca3-d86d-4ec9-a054-f1582088bddc

	measure 'Traffic vs LY' =
			VAR act = [Traffic]
			VAR comp = [Traffic LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Traffic\LY
		lineageTag: 7d0aa6bb-9441-46a7-a62d-7bd94c5dd8a6

	measure 'Traffic vs LY-1' =
			VAR act = [Traffic]
			VAR comp = [Traffic LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of Traffic vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Traffic\LY-1
		lineageTag: 2dc81447-b213-4399-836f-fb38a6f5926b

	measure 'Traffic vs LY %' =
			VAR act = [Traffic]
			VAR comp = [Traffic LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\Traffic\LY
		lineageTag: b46114de-1b9d-4cc5-9672-babd9ea797fa

	measure 'TY Actuals Uplift' = IF ( SELECTEDVALUE ( 'Calendar'[fiscalYear] ) = 2025, 1.22, 1 )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Traffic\LY
		lineageTag: 702ee372-ddd3-47d7-a725-4915f6b5144b

	measure 'factAdobe Orders' =
			VAR TY_AOV_orders = [factAOV Orders]
			VAR LY_AOV_orders = [factAOV Orders LY]
			VAR true_yoy_pct =
			    DIVIDE ( TY_AOV_orders - LY_AOV_orders, LY_AOV_orders )
			VAR LY_Adobe_orders = [factAdobe Orders LY]
			VAR adj_TY_Adobe_orders = LY_Adobe_orders * ( 1 + true_yoy_pct )
			RETURN
			    IF (
			        SELECTEDVALUE ( 'Calendar'[fiscalYear] ) = 3000,
			        adj_TY_Adobe_orders,
			        [Unadj factAdobe Orders]
			    )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Online Orders\Actual
		lineageTag: b002e18a-c05b-43c0-97dd-5ec7596b898e

	measure 'SwitchOnlineMetric vs LY Hybrid' =
			VAR metric = [slctd_OnlineMetric]
			VAR result =
			    SWITCH (
			        metric,
			        "Traffic", [Visits vs LY %],
			        "Conv", [Conversion % vs LY],
			        "Orders", [factAOV Orders vs LY %],
			        "AOV", [AOV vs LY %]
			    )
			RETURN
			    result
		formatString: #,##0%;(#,##0)%
		displayFolder: SwitchOnlineMetric\LY
		lineageTag: 768e57ca-bb85-44d1-b3a7-8795539962d4

	measure 'AOV LY' =
			CALCULATE (
			    [AOV],
			    USERELATIONSHIP ( factAOV[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\AOV\LY
		lineageTag: 1429667c-9cca-41e6-b5ef-88add5d7bfa7

	measure 'AOV LY-1' =
			CALCULATE (
			    [AOV],
			    USERELATIONSHIP ( factAOV[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		description: Two years ago equivalent of AOV LY.
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\AOV\LY-1
		lineageTag: c00db6d2-7442-493f-a1ac-461a33df6b47

	measure 'AOV vs LY' =
			VAR act = [ABV]
			VAR comp = [ABV LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\AOV\LY
		lineageTag: a958867d-65fe-4162-b024-d95d482543f6

	measure 'AOV vs LY-1' =
			VAR act = [ABV]
			VAR comp = [ABV LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of AOV vs LY.
		formatString: #,##0.0;(#,##0.0)
		displayFolder: Transactions\AOV\LY-1
		lineageTag: 879b77e0-358d-4504-98aa-2bdb43249b21

	measure 'AOV vs LY %' =
			VAR act = [AOV]
			VAR comp = [AOV LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\AOV\LY
		lineageTag: abee0d4f-8680-457b-b2d7-5a285d8a4649

	measure Traffic =
			
			CALCULATE(SUM(factAdobe[visitsL2]), factAdobe[visitType] = 1)
			/*IF (
			    SELECTEDVALUE ( 'Calendar'[fiscalYear] ) = 3000,
			    [Unadj Traffic] * [TY Actuals Uplift],
			    [Unadj Traffic]
			)*/
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Traffic\Actual
		lineageTag: c741451c-be1c-4bbb-9eb8-5d996d2344b4

	measure WeekTest = VALUE(LEFT(SELECTEDVALUE('Calendar'[fiscalWeekLastWeek]),4)) = 2025
		formatString: #,##0;(#,##0)
		displayFolder: Transactions\Traffic\Actual
		lineageTag: 508a74cf-1a01-42f8-b9b1-9ef419b370c2

	/// This measure is the sum of column 'factTransactions'[trans]
	measure 'Store Transactions' =
			CALCULATE (
			    SUM ( 'factTransactions'[trans] ),
			    factTransactions[channel] = "01"
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Transactions\Actual
		lineageTag: 66cceb96-8b96-465a-a867-acd459e02c13

	measure 'factAOV Orders LW' =
			CALCULATE (
			        [sum_orders_factAOV],
			        USERELATIONSHIP ( factAOV[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			    )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\factAOV Orders\LW
		lineageTag: 8497b0ba-623d-47c2-8a60-cbe87db1d71b

	measure 'factAOV Orders vs LW' =
			VAR act = [factAOV Orders]
			VAR comp = [factAOV Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\factAOV Orders\LW
		lineageTag: f3d9e5ec-f819-4932-a499-f2b58ceaa511

	measure 'factAOV Orders vs LW %' =
			VAR act = [factAOV Orders]
			VAR comp = [factAOV Orders LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\factAOV Orders\LW
		lineageTag: 4a31820c-fe50-4b4c-8845-b552a7dc0cf0

	measure 'factAOV Orders LY' =
			CALCULATE (
			        [sum_orders_factAOV],
			        USERELATIONSHIP ( factAOV[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			    )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\factAOV Orders\LY
		lineageTag: 1af16cc2-e370-40df-b673-3a7f41a132b9

	measure 'factAOV Orders LY-1' =
			CALCULATE (
			        [sum_orders_factAOV],
			        USERELATIONSHIP ( factAOV[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			    )
		description: Two years ago equivalent of factAOV Orders LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\factAOV Orders\LY-1
		lineageTag: 2de177cb-ec52-444d-9451-0b2760c085c2

	measure 'factAOV Orders vs LY' =
			VAR act = [factAOV Orders]
			VAR comp = [factAOV Orders LY]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\factAOV Orders\LY
		lineageTag: 403d89ba-d0d9-45dd-8059-ef6b2c5e5c98

	measure 'factAOV Orders vs LY-1' =
			VAR act = [factAOV Orders]
			VAR comp = [factAOV Orders LY-1]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		description: Two years ago equivalent of factAOV Orders vs LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\factAOV Orders\LY-1
		lineageTag: 3c57fd2c-8980-4353-bf14-f6ba63f3f795

	measure 'factAOV Orders vs LY %' =
			VAR act = [factAOV Orders]
			VAR comp = [factAOV Orders LY]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\factAOV Orders\LY
		lineageTag: 2c1459f5-62c1-4384-9469-8e612b8606ea

	measure 'factAdobe Orders LY' =
			CALCULATE (
			        [Unadj factAdobe Orders],
			        USERELATIONSHIP ( factAdobe[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			    )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Online Orders\LY
		lineageTag: d032613c-a17f-42ca-8c15-a4ec579be9d1

	measure 'factAdobe Orders LY-1' =
			CALCULATE (
			        [Unadj factAdobe Orders],
			        USERELATIONSHIP ( factAdobe[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			    )
		description: Two years ago equivalent of factAdobe Orders LY.
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Online Orders\LY-1
		lineageTag: ef4e7698-a7b2-4b26-a26d-5d34f0df1334

	measure 'Unadj factAdobe Orders' = [sum_ordersL2_factAdobe]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Online Orders\Actual
		lineageTag: 7a640f48-b82a-463f-a405-ab40fb06ef5e

	measure 'factAOV Orders' = [sum_orders_factAOV]
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\factAOV Orders\Actual
		lineageTag: a1ec3f82-e720-4850-a8e5-f9a03852b08d

	measure 'factAdobe Orders LW' =
			VAR this_week_idx =
			    CALCULATE (
			        MAX ( RefCalendar[Index] ),
			        RefCalendar[fiscalWeek] = SELECTEDVALUE ( 'Calendar'[fiscalWeek] )
			    )
			VAR last_fiscal_week =
			    CALCULATE (
			        MAX ( RefCalendar[fiscalWeek] ),
			        RefCalendar[Index] = ( this_week_idx - 1 )
			    )
			VAR LW_AOV_orders =
			    CALCULATE (
			        [factAOV Orders],
			        ALL ( 'Calendar' ),
			        ALL ( 'Time Period' ),
			        'Calendar'[fiscalWeek] = last_fiscal_week
			    )
			VAR LW_LY_AOV_orders =
			    CALCULATE (
			        [factAOV Orders LY],
			        ALL ( 'Calendar' ),
			        ALL ( 'Time Period' ),
			        'Calendar'[fiscalWeek] = last_fiscal_week
			    )
			VAR true_yoy_pct =
			    DIVIDE ( LW_AOV_orders - LW_LY_AOV_orders, LW_LY_AOV_orders )
			VAR LY_Adobe_orders =
			    CALCULATE (
			        [factAdobe Orders LY],
			        ALL ( 'Calendar' ),
			        ALL ( 'Time Period' ),
			        'Calendar'[fiscalWeek] = last_fiscal_week
			    )
			VAR adj_TY_Adobe_orders = LY_Adobe_orders * ( 1 + true_yoy_pct )
			RETURN
			    IF (
			        VALUE ( LEFT ( SELECTEDVALUE ( 'Calendar'[fiscalWeekLastWeek] ), 4 ) ) = 3000,
			        adj_TY_Adobe_orders,
			        CALCULATE (
			            [Unadj factAdobe Orders],
			            USERELATIONSHIP ( factAdobe[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			        )
			    )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Online Orders\LW
		lineageTag: 08e757f5-e580-4769-91f2-5207d6b27bca

	measure 'factAdobe Orders vs LW' =
			VAR act = [factAdobe Orders]
			VAR comp = [factAdobe Orders LW]
			VAR result = act - comp
			RETURN
			    IF ( comp = BLANK (), BLANK (), result )
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Transactions\Online Orders\LW
		lineageTag: f350dd95-73c0-4b1c-8382-7a21a3278ade

	measure 'factAdobe Orders vs LW %' =
			VAR act = [factAdobe Orders]
			VAR comp = [factAdobe Orders LW]
			VAR result =
			    DIVIDE ( act - comp, comp )
			RETURN
			    IF ( OR ( act = BLANK (), comp = BLANK () ), BLANK (), result )
		formatString: #,##0.0%;(#,##0.0)%
		displayFolder: Transactions\Online Orders\LW
		lineageTag: c833d6d0-90ce-4fae-a516-90a18b978f4e

	measure 'SRIV Fwd View for LW' =
			VAR projection_scenario = [slctd_Projection Scenario]
			VAR latest_actuals = [LatestSalesFiscalWeek]
			VAR salesTable =
			    ADDCOLUMNS (
			        VALUES ( 'Calendar'[fiscalWeek] ),
			        "Hybrid",
			            IF (
			                [fiscalWeek]-1 <= latest_actuals,
			                [SRIV],
			                SWITCH (
			                    projection_scenario,
			                    "BUD", [SRIV Channel BUD],
			                    "FC", [SRIV Channel FC],
			                    "QRF", [SRIV Channel QRF],
			                    "LE", [SRIV Channel LE],
			                    [SRIV Channel BUD]
			                )
			            )
			    )
			RETURN
			    SUMX ( salesTable, [Hybrid] )
		lineageTag: d4c546aa-9529-4398-98a9-fa25dc1ccf76

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Warning = ```
			
			VAR MinWeek = MIN('Calendar'[Week])
			VAR MaxWeek = MAX('Calendar'[Week])
			VAR IsInLimitedPeriod =
			    MinWeek <= 18 && MaxWeek >= 4
			RETURN
			    IF(
			        IsInLimitedPeriod,
			        "Missing Data Warning: 
			        Please note, for fiscal weeks between 202604 and 202618, only Sales Inc VAT, Sales Exc VAT, GSM, and Volume data are available, and it has limited granularity.",
			        ""
			    )
			```
		lineageTag: 0b3f56d7-93ff-4905-a7a1-7850dccb3219

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TT Warning' =
			
			VAR MinWeek = MIN('Calendar'[Week])
			VAR td = SELECTEDVALUE('Time Period'[Time Period])
			VAR MaxWeek = MAX('Calendar'[Week])
			VAR IsInLimitedPeriod =
			    MinWeek <= 19 && MaxWeek >= 4
			RETURN
			    IF(
			        td <> "This Week" && IsInLimitedPeriod,
			        "",
			        ""
			    )
		lineageTag: 5b726f44-8f52-41bd-8c4a-196594d5815d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'OT Warning' = ```
			
			VAR MinWeek = MIN('Calendar'[Week])
			VAR MaxWeek = MAX('Calendar'[Week])
			VAR IsInLimitedPeriod =
			MaxWeek >= 4
			RETURN
			    IF(
			        IsInLimitedPeriod,
			        "Missing Data Warning: 
			        Please note, Online transaction data is unavailable and not udpated following the incident.",
			        ""
			    )
			```
		lineageTag: 5171a303-6e4c-462f-a2d7-de9417b07597

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '1Front Cover' = "FH&B Weekly Trading Dashboard - "&[tiWeekNo]
		displayFolder: Dynamic Labels
		lineageTag: 7d73e5eb-919e-4671-afdd-2ef7302d8015

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'POS new SRIV Orders' = [GSRIV Orders] - [SRIV Orders]
		displayFolder: Sales\Orders\SRIV\Actual
		lineageTag: b340d540-2399-4129-9500-e0a3b34d65e3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'old_Promo Markdown % Orders' =
			VAR metric = - [Promo Markdown Orders]
			VAR sales =
			    - [Promo Markdown Orders]
			        + CALCULATE ( [SRIV Orders], SalesType[SalesType] = "FP&P" )
			VAR result =
			    DIVIDE ( metric, sales )
			RETURN
			    IF ( OR ( metric = BLANK (), sales = BLANK () ), BLANK (), result )
		displayFolder: Margin\Orders\Promo Markdown\Actual
		lineageTag: 51244d73-3fea-4776-b48e-67d03a0feb71

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Measure 3' = SUM(factSalesOrders[gsrev])
		lineageTag: a5445747-11d1-43a5-bf15-fd71545ae3b5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Orders Returns' = CALCULATE(SUM(factSalesOrders[sriv]),factSalesOrders[return_flag] = "R")
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\Actual
		lineageTag: c2259169-3d8d-45ca-9751-e79e66b93012

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Dispatch Returns' =
			VAR sale_type = [slctd_SalesType]
			VAR total_returns = [FP Returns] + [RP Returns]
			VAR result =
			    SWITCH (
			        sale_type,
			        "Total", total_returns,
			        "FP&P", [FP Returns],
			        "Reduced", [RP Returns],
			        total_returns
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		displayFolder: Sales\Returns\Actual
		lineageTag: 8e45e566-7444-442c-aa79-9a739a4d918d

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Orders Returns LW' =
			CALCULATE (
			    [Orders Returns],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		displayFolder: Sales\Returns\FP Returns\LW
		lineageTag: 18f18349-6f3c-44ac-b5d3-63c906ec0b7d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dispatch Returns LW' =
			
			VAR sale_type = [slctd_SalesType]
			VAR total_returns = [FP Returns LW] + [RP Returns LW]
			VAR result =
			    SWITCH (
			        sale_type,
			        "Total", total_returns,
			        "FP&P", [FP Returns LW],
			        "Reduced", [RP Returns LW],
			        total_returns
			    )
			RETURN
			    result
		displayFolder: Sales\Returns\FP Returns\LW
		lineageTag: 5663f0f2-a1c4-46e4-a9f2-734a876ab6e7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Returns LW TEST' =
			VAR recog_type = [slctd_SalesRecognitionType]
			VAR result =
			    SWITCH (
			        recog_type,
			        "Order", [Orders Returns LW],
			        "Dispatch", [Dispatch Returns LW],
			        [Orders Returns LW]
			    )
			RETURN
			    result
		displayFolder: Sales\Returns\Actual
		lineageTag: 4f9cab15-09fd-49eb-9e3e-bf470ea2e5d4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dispatch Returns LY' =
			
			VAR sale_type = [slctd_SalesType]
			VAR total_returns = [FP Returns LY] + [RP Returns LY]
			VAR result =
			    SWITCH (
			        sale_type,
			        "Total", total_returns,
			        "FP&P", [FP Returns LY],
			        "Reduced", [RP Returns LY],
			        total_returns
			    )
			RETURN
			    result
		displayFolder: Sales\Returns\FP Returns\LY
		lineageTag: b49ecb39-aba9-4e50-9632-c14c7460eb97

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dispatch Returns LY-1' =
			
			VAR sale_type = [slctd_SalesType]
			VAR total_returns = [FP Returns LY-1] + [RP Returns LY-1]
			VAR result =
			    SWITCH (
			        sale_type,
			        "Total", total_returns,
			        "FP&P", [FP Returns LY-1],
			        "Reduced", [RP Returns LY-1],
			        total_returns
			    )
			RETURN
			    result
		displayFolder: Sales\Returns\FP Returns\LY-1
		lineageTag: 7c116574-1c65-4994-b346-91d234e9a442

		description: Two years ago equivalent of Dispatch Returns LY.
		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Orders Returns LY' =
			CALCULATE (
			    [Orders Returns],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastYear] ))
		displayFolder: Sales\Returns\FP Returns\LY
		lineageTag: dfa08676-68ad-498f-ac5a-cfba23115742

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Orders Returns LY-1' =
			CALCULATE (
			    [Orders Returns],
			    USERELATIONSHIP ( factSalesOrders[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] ))
		displayFolder: Sales\Returns\FP Returns\LY-1
		lineageTag: 400b998e-f4a9-478b-b454-e87418fb1f21

		description: Two years ago equivalent of Orders Returns LY.
		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column1
		dataType: string
		isHidden
		displayFolder: Commentary
		lineageTag: a5801bac-47c9-425d-af45-6ca0c11dc6e7
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 1_Measures-b5c8d884-97c1-43ed-9b22-061c4a5308e2 = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

