table factSRIVOrdersChannelForecast
	lineageTag: c73f5606-178b-4c20-80db-ca7479ad29f9

	/// This measure is the sum of column 'factSRIVOrdersChannelForecast'[sriv]
	measure sum_sriv_factSRIVOrdersChannelForecast = SUM ( 'factSRIVOrdersChannelForecast'[sriv] )
		formatString: #,##0;(#,##0)
		lineageTag: f2083dcc-7d26-45fd-8d58-c83698575c13

	column product
		dataType: string
		lineageTag: 813a680d-aa09-4d91-a4ba-c535b2409508
		summarizeBy: none
		sourceColumn: product

		annotation SummarizationSetBy = Automatic

	column fp_rp_ind
		dataType: string
		lineageTag: 5e1dfebd-ba46-48c2-baf0-15c44d37d1e8
		summarizeBy: none
		sourceColumn: fp_rp_ind

		annotation SummarizationSetBy = Automatic

	column sriv
		dataType: double
		isHidden
		lineageTag: 061e6e7f-dd91-4f83-808f-5dc5bf6f8765
		summarizeBy: sum
		sourceColumn: sriv

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column plan
		dataType: string
		lineageTag: 70ed6ade-08e1-4543-a04e-9a8c1d97bd0c
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 3f75b432-a730-4017-8991-7e0cbcfdcc37
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column siteID
		dataType: int64
		formatString: 0
		lineageTag: 42d5df7c-5445-49f9-86e8-106a71df6f94
		summarizeBy: none
		sourceColumn: siteID

		annotation SummarizationSetBy = Automatic

	column fiscalWeek
		dataType: int64
		formatString: 0
		lineageTag: 2a558278-f8b7-434f-bcfb-c6389c036048
		summarizeBy: none
		sourceColumn: fiscalWeek

		annotation SummarizationSetBy = Automatic

	partition factSRIVOrdersChannelForecast-25e143ec-cf2c-40c6-bbd0-a86c59b2d33b = m
		mode: import
		queryGroup: 'Orders fact tables'
		source =
				let
				    Source = PowerBI.Dataflows([]),
				    #"1e21bb0e-7319-4d52-a1b9-84f8819e9fa0" = Source{[workspaceId="1e21bb0e-7319-4d52-a1b9-84f8819e9fa0"]}[Data],
				    #"1fbe7454-060f-456f-a5ec-cb42cf8cf0af" = #"1e21bb0e-7319-4d52-a1b9-84f8819e9fa0"{[dataflowId="1fbe7454-060f-456f-a5ec-cb42cf8cf0af"]}[Data],
				    #"MP Plans Channel" = #"1fbe7454-060f-456f-a5ec-cb42cf8cf0af"{[entity="MP Plans Channel"]}[Data]
				in
				    #"MP Plans Channel"

	annotation PBI_ResultType = Table

