table factOnlineCustomerMetrics
	lineageTag: 93733fa1-5328-434d-8e73-d6b4607a2134

	/// This measure is the sum of column 'factOnlineCustomerMetrics'[Visits]
	measure sum_online_visits = SUM ( 'factOnlineCustomerMetrics'[Visits] )
		formatString: #,##0;(#,##0)
		lineageTag: 132dee00-773f-4058-b540-c0eb5963c971

	/// This measure is the sum of column 'factOnlineCustomerMetrics'[Orders]
	measure sum_online_orders = SUM ( 'factOnlineCustomerMetrics'[Orders] )
		formatString: #,##0;(#,##0)
		lineageTag: 1c49477d-ad2b-4704-a3a1-dd370b0cec5d

	column Area
		dataType: string
		lineageTag: 6629d396-f6ef-4190-92d3-96761dfed01c
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column fiscalWeek
		dataType: int64
		formatString: 0
		lineageTag: b949cc50-6551-4589-a610-b7d275d5c422
		summarizeBy: none
		sourceColumn: fiscalWeek

		annotation SummarizationSetBy = Automatic

	column Visits
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 197a1512-ba7a-4b9b-b257-adca37c23b02
		summarizeBy: sum
		sourceColumn: Visits

		annotation SummarizationSetBy = Automatic

	column Orders
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4ff706c6-0f26-45cc-b3fc-55692483ee1e
		summarizeBy: sum
		sourceColumn: Orders

		annotation SummarizationSetBy = Automatic

	partition factOnlineCustomerMetrics-c9824d11-ba71-424d-97b9-a3b60a53b4c3 = m
		mode: import
		queryGroup: 'Other fact tables'
		source =
				let
				    Source = PowerBI.Dataflows(null),
				    #"1e21bb0e-7319-4d52-a1b9-84f8819e9fa0" = Source{[workspaceId="1e21bb0e-7319-4d52-a1b9-84f8819e9fa0"]}[Data],
				    #"46faf90b-c9ef-4882-93b9-9bdbbc03b562" = #"1e21bb0e-7319-4d52-a1b9-84f8819e9fa0"{[dataflowId="46faf90b-c9ef-4882-93b9-9bdbbc03b562"]}[Data],
				    factOnlineCustomerMetrics1 = #"46faf90b-c9ef-4882-93b9-9bdbbc03b562"{[entity="factOnlineCustomerMetrics"]}[Data]
				in
				    factOnlineCustomerMetrics1

	annotation PBI_ResultType = Table

