table factTransactions
	lineageTag: 3953b28f-ffec-4947-93c5-94bd722ceff7

	/// This measure is the sum of column 'factTransactions'[salesg]
	measure 'Sale Trans Value' = SUM ( 'factTransactions'[salesg] )
		formatString: #,##0,,.0;(#,##0,,.0)
		lineageTag: 13569060-6117-476f-974b-fbfe1de85597

	/// This measure is the sum of column 'factTransactions'[salesg]
	measure 'Sale Trans Value LY' =
			CALCULATE (
			    [Sale Trans Value],
			    USERELATIONSHIP ( factTransactions[fiscalWeek], 'Calendar'[fiscalWeekLastYear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		lineageTag: 19cbc7dd-18e1-4721-8794-b48b1183afef

	/// Two years ago equivalent of Sale Trans Value LY.
	measure 'Sale Trans Value LY-1' =
			CALCULATE (
			    [Sale Trans Value],
			    USERELATIONSHIP ( factTransactions[fiscalWeek], 'Calendar'[fiscalWeekLastToLastyear] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		lineageTag: 0330f413-b5b2-4e7a-afc0-c89b5809351c

	/// This measure is the sum of column 'factTransactions'[salesg]
	measure 'Sale Trans Value LW' =
			CALCULATE (
			    [Sale Trans Value],
			    USERELATIONSHIP ( factTransactions[fiscalWeek], 'Calendar'[fiscalWeekLastWeek] )
			)
		formatString: #,##0,,.0;(#,##0,,.0)
		lineageTag: 86417ba5-a095-49f7-883a-cd139c4102d9

	column fiscalWeek
		dataType: int64
		formatString: 0
		lineageTag: a42e9760-7877-4b41-9e14-227cda096f24
		summarizeBy: none
		sourceColumn: fiscalWeek

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 284247dc-734c-4562-b65a-7f6f3281eca6
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column trans
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 125760dd-0ea9-4cd5-b94c-fa917b9e837c
		summarizeBy: sum
		sourceColumn: trans

		annotation SummarizationSetBy = Automatic

	column num_items
		dataType: int64
		formatString: 0
		lineageTag: 90989e1a-2f46-4d55-8576-f54bf9156619
		summarizeBy: sum
		sourceColumn: num_items

		annotation SummarizationSetBy = Automatic

	column salesg
		dataType: double
		isHidden
		lineageTag: d98bca65-ec4e-4cf0-bff3-b8dc54fd3657
		summarizeBy: sum
		sourceColumn: salesg

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition factTransactions-189524db-bc07-4b83-8641-c9ab9fec12ec = m
		mode: import
		queryGroup: 'Other fact tables'
		source =
				let
				    Source = PowerBI.Dataflows(null),
				    #"1e21bb0e-7319-4d52-a1b9-84f8819e9fa0" = Source{[workspaceId="1e21bb0e-7319-4d52-a1b9-84f8819e9fa0"]}[Data],
				    #"6aaee58a-737b-477f-9e0b-6b4a95309533" = #"1e21bb0e-7319-4d52-a1b9-84f8819e9fa0"{[dataflowId="6aaee58a-737b-477f-9e0b-6b4a95309533"]}[Data],
				    Transactions = #"6aaee58a-737b-477f-9e0b-6b4a95309533"{[entity="Transactions"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(Transactions,{{"items", "num_items"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

