table factStock
	lineageTag: 338bf576-880d-4183-858f-da5eaa4517ba

	/// This measure is the sum of column 'factStock'[val]
	measure sum_fact_stock =
			VAR max_selected_we_date =
			    MAX ( 'Time Period'[Date] )
			VAR max_selected_fiscal_week =
			    CALCULATE (
			        MAX ( RefCalendar[fiscalWeek] ),
			        RefCalendar[fiscalWeekEndingDate] = max_selected_we_date
			    )
			VAR result =
			    CALCULATE (
			        SUM ( 'factStock'[val] ),
			        'Calendar'[fiscalWeek] = max_selected_fiscal_week
			    )
			RETURN
			    result
		formatString: #,##0,,.0;(#,##0,,.0)
		lineageTag: 70911f5c-4443-4df9-bd9e-2abd46ff804b

	measure stock_fwd_cover_base = ```
			VAR currentWeek = [LatestSalesOrdersFiscalWeek]
			VAR currentStock =
			    CALCULATE ( [sum_fact_stock], 'Calendar'[fiscalWeek] = currentWeek ) // Create a table with rows starting at next week and going into the future
			// (as long as the MP plan extends for)
			VAR stockFutureWeeks =
			    ADDCOLUMNS (
			        FILTER (
			            ALL ( 'Calendar'[fiscalWeek] ),
			            'Calendar'[fiscalWeek] > currentWeek
			                && 'Calendar'[fiscalWeek] <= MAX ( factForecast[fiscalWeek] )
			        ),
			        "cumulativeStock",
			            // Store the week of the current row as a variable
			            VAR tableWeek =
			                CALCULATE ( SELECTEDVALUE ( 'Calendar'[fiscalWeek] ) ) // Calculate cumulative sales up to the current row week
			            VAR cumulativeSales =
			                CALCULATE (
			                    [sum_TotSlsV] - [sum_TotPoSV] - [sum_TotStDV],
			                    'Calendar'[fiscalWeek] <= tableWeek
			                        && 'Calendar'[fiscalWeek] > currentWeek
			                ) // Subtract cumulative sales from stock position now
			            // (At some future week cumulative sales will exceed stock and the result
			            // will begin to be negative from then onwards)
			            VAR stockPosition = currentStock - cumulativeSales
			            RETURN
			                stockPosition,
			        "cumulativeSales",
			            VAR tableWeek =
			                CALCULATE ( SELECTEDVALUE ( 'Calendar'[fiscalWeek] ) )
			            VAR cumulativeSales =
			                CALCULATE (
			                    [sum_TotSlsV] - [sum_TotPoSV] - [sum_TotStDV],
			                    'Calendar'[fiscalWeek] <= tableWeek
			                        && 'Calendar'[fiscalWeek] > currentWeek
			                )
			            RETURN
			                cumulativeSales,
			        // Calculate sales (non-cumulative for the row week)
			        "salesAmt",
			            [sum_TotSlsV] - [sum_TotPoSV] - [sum_TotStDV]
			    )
			VAR posRows =
			    FILTER ( stockFutureWeeks, [cumulativeStock] > 0 )
			VAR negRows =
			    FILTER ( stockFutureWeeks, [cumulativeStock] < 0 ) // Filter table to only negative rows (after stock runs out)
			VAR fullWeeksStock =
			    COUNTROWS ( posRows ) // Count rows to get total number of WHOLE weeks of future sales the current stock can cover
			VAR lastFullWeek =
			    TOPN ( 1, SUMMARIZE ( posRows, [cumulativeStock] ), [cumulativeStock], ASC ) // Store the smallest value of cumulative stock (which will be the week just before stock runs out) 
			// Two step process to get sales value for the week just after stock runs out 
			VAR firstNegWeek =
			    TOPN ( 1, SUMMARIZE ( negRows, [fiscalWeek], [salesAmt] ), [fiscalWeek], ASC ) // Need to order by calendar date so first get the value of the calendar date for the row
			VAR firstNegWeekSales =
			    TOPN ( 1, SUMMARIZE ( firstNegWeek, [salesAmt] ), [salesAmt], ASC ) // Return the actual sales value of the week
			// Number of weeks of stock cover is a partial week consisting of number of WHOLE weeks + fraction of the next week of sales the remaining stock can cover
			VAR result = fullWeeksStock + DIVIDE ( lastFullWeek, firstNegWeekSales )
			RETURN
			    IF ( currentStock > 0, result, BLANK() )
			```
		formatString: #,##0.0;(#,##0.0)
		lineageTag: 03c8cf4e-a6fb-4259-871a-b3c1f0f78472

	measure stock_fwd_cover_base2 = ```
			VAR currentWeek = [LatestSalesOrdersFiscalWeek]
			VAR currentStock =
			    CALCULATE ( [sum_fact_stock], 'Calendar'[fiscalWeek] = currentWeek ) // Create a table with rows starting at next week and going into the future
			// (as long as the MP plan extends for)
			VAR stockFutureWeeks =
			    ADDCOLUMNS (
			        FILTER (
			            ALL ( 'Calendar'[fiscalWeek] ),
			            'Calendar'[fiscalWeek] > currentWeek
			                && 'Calendar'[fiscalWeek] <= MAX ( factForecast[fiscalWeek] )
			        ),
			        "cumulativeStock",
			            // Store the week of the current row as a variable
			            VAR tableWeek =
			                CALCULATE ( SELECTEDVALUE ( 'Calendar'[fiscalWeek] ) ) // Calculate cumulative sales up to the current row week
			            VAR cumulativeSales =
			                CALCULATE (
			                    [sum_TotSlsV] - [sum_TotPoSV] - [sum_TotStDV],
			                    'Calendar'[fiscalWeek] <= tableWeek
			                        && 'Calendar'[fiscalWeek] > currentWeek
			                ) // Subtract cumulative sales from stock position now
			            // (At some future week cumulative sales will exceed stock and the result
			            // will begin to be negative from then onwards)
			            VAR stockPosition = currentStock - cumulativeSales
			            RETURN
			                stockPosition,
			        "cumulativeSales",
			            VAR tableWeek =
			                CALCULATE ( SELECTEDVALUE ( 'Calendar'[fiscalWeek] ) )
			            VAR cumulativeSales =
			                CALCULATE (
			                    [sum_TotSlsV] - [sum_TotPoSV] - [sum_TotStDV],
			                    'Calendar'[fiscalWeek] <= tableWeek
			                        && 'Calendar'[fiscalWeek] > currentWeek
			                )
			            RETURN
			                cumulativeSales,
			        // Calculate sales (non-cumulative for the row week)
			        "salesAmt",
			            [sum_TotSlsV] - [sum_TotPoSV] - [sum_TotStDV]
			    )
			VAR posRows = 
			    FILTER ( stockFutureWeeks, [cumulativeStock] > 0 )
			VAR negRows =
			    FILTER ( stockFutureWeeks, [cumulativeStock] < 0 ) // Filter table to only negative rows (after stock runs out)
			VAR fullWeeksStock =
			    COUNTROWS ( posRows ) // Count rows to get total number of WHOLE weeks of future sales the current stock can cover
			VAR lastFullWeek =
			    TOPN ( 1, SUMMARIZE ( posRows, [cumulativeStock] ), [cumulativeStock], ASC ) // Store the smallest value of cumulative stock (which will be the week just before stock runs out) 
			// Two step process to get sales value for the week just after stock runs out 
			VAR firstNegWeek =
			    TOPN ( 1, SUMMARIZE ( negRows, [fiscalWeek], [salesAmt] ), [fiscalWeek], ASC ) // Need to order by calendar date so first get the value of the calendar date for the row
			VAR firstNegWeekSales =
			    TOPN ( 1, SUMMARIZE ( firstNegWeek, [salesAmt] ), [salesAmt], ASC ) // Return the actual sales value of the week
			// Number of weeks of stock cover is a partial week consisting of number of WHOLE weeks + fraction of the next week of sales the remaining stock can cover
			VAR result = fullWeeksStock + DIVIDE ( lastFullWeek, firstNegWeekSales )
			RETURN
			    //IF ( currentStock > 0, result, BLANK() )
			    firstNegWeekSales
			```
		lineageTag: d5429b67-5498-40a9-bbc9-49c494b43e05

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fiscalWeek
		dataType: int64
		formatString: 0
		lineageTag: e3683211-fcd4-4413-ba8a-529973cf433e
		summarizeBy: none
		sourceColumn: fiscalWeek

		annotation SummarizationSetBy = Automatic

	column fp_rp_ind
		dataType: string
		lineageTag: 9609c3e9-b052-4d55-badd-e8ad37bcf3da
		summarizeBy: none
		sourceColumn: fp_rp_ind

		annotation SummarizationSetBy = Automatic

	column comp_code
		dataType: string
		lineageTag: 3cd4c8eb-953a-4afc-88d0-2cc06f76594e
		summarizeBy: none
		sourceColumn: comp_code

		annotation SummarizationSetBy = Automatic

	column siteID
		dataType: int64
		formatString: 0
		lineageTag: 59840c54-3868-4488-b3d0-fded829a2b7d
		summarizeBy: none
		sourceColumn: siteID

		annotation SummarizationSetBy = Automatic

	column dept
		dataType: string
		lineageTag: 3bcc61ad-c1d0-4f88-a4bb-a8c4ca2214ea
		summarizeBy: none
		sourceColumn: dept

		annotation SummarizationSetBy = Automatic

	column qty
		dataType: double
		lineageTag: 9d49d7d9-d5f5-4dde-939f-36a15f4c1ad8
		summarizeBy: sum
		sourceColumn: qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column val
		dataType: double
		lineageTag: 986c87f1-6021-402d-8ade-be47840c98a7
		summarizeBy: sum
		sourceColumn: val

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column channel
		dataType: string
		lineageTag: fd96fd55-30d1-4096-a44b-dd3c60495e71
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	partition factStock-08af6c80-c846-47e1-a976-1288dd4fa90e = m
		mode: import
		queryGroup: 'Orders fact tables'
		source =
				let
				    Source = PowerBI.Dataflows(null),
				    #"1e21bb0e-7319-4d52-a1b9-84f8819e9fa0" = Source{[workspaceId="1e21bb0e-7319-4d52-a1b9-84f8819e9fa0"]}[Data],
				    #"07ab2b44-6de1-4f23-ab09-b16ff74c7437" = #"1e21bb0e-7319-4d52-a1b9-84f8819e9fa0"{[dataflowId="07ab2b44-6de1-4f23-ab09-b16ff74c7437"]}[Data],
				    fact_orders_fhbwk = #"07ab2b44-6de1-4f23-ab09-b16ff74c7437"{[entity="fact_stock_fhbwk"]}[Data]
				in
				    fact_orders_fhbwk

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

