table IntakeMeasureSelection
	lineageTag: 9f58b06a-873e-4c5b-97be-0075a3319bcd

	measure Intake_ACT =
			
			SWITCH(
			    SELECTEDVALUE(IntakeMeasureSelection[IntakeMeasureSelection])
			    ,"FP&P Sales",[Rolling_FPPSRIV]
			    ,"FP&P Intake",[Rolling_FPPIntakeValue]
			    ,"FP&P Intake Vol",[Rolling_FPPIntakeVolume]
			    ,blank())
		formatString: #,##0,,.0;(#,##0,,.0)
		lineageTag: 3a3897d4-e978-41ae-b94f-bfbbd651fca7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Intake_Var =
			
			SWITCH(
			    SELECTEDVALUE(IntakeMeasureSelection[IntakeMeasureSelection])
			    ,"FP&P Sales",[Rolling_FPPSRIVvsComp]
			    ,"FP&P Intake",[Rolling_FPPIntakeValuevsComp]
			    ,"FP&P Intake Vol",[Rolling_FPPIntakeVolumevsComp]
			    ,Blank())
		formatString: #,##0,,.0;(#,##0,,.0)
		lineageTag: 83836e77-5943-4ef1-a784-7fa4b6570633

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Intake_Var %' =
			
			Var Intake = SWITCH(
			    SELECTEDVALUE(IntakeMeasureSelection[IntakeMeasureSelection])
			    ,"FP&P Sales",[Rolling_FPPSRIVvsComp%]
			    ,"FP&P Intake",[Rolling_FPPIntakeValuevsComp%]
			    ,"FP&P Intake Vol",[Rolling_FPPIntakeVolumevsComp%]
			    ,blank())
			    Return if(Intake = -1, blank(), Intake)
		formatString: #,##0.0%;(#,##0.0)%
		lineageTag: 12809d35-29c7-48fd-bb95-558c092f0e04

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IntakeMeasureSelection
		dataType: string
		lineageTag: b9155d6a-2789-49f9-86a2-fe7df699d5d6
		summarizeBy: none
		sourceColumn: IntakeMeasureSelection
		sortByColumn: Index

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 001f0fb1-ef03-436a-8938-4e2d1b51f643
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition IntakeMeasureSelection = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WcguIKTUwMDILUAhOzEktVorVQRbzzCtJzE7FKqgQlp+jFBsLAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [IntakeMeasureSelection = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"IntakeMeasureSelection", type text}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type", "Index", 1, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_ResultType = Table

