table MarginBridgeComparator
	lineageTag: a51a182b-c11a-4858-8e05-331f928d4452

	/// This measure is the SELECTEDVALUE of column 'MarginBridgeComparator'[Comparator]
	measure slctd_MarginBridgeComparator = SELECTEDVALUE ( 'MarginBridgeComparator'[Comparator] )
		lineageTag: 5a390e57-c9bd-427c-a5ec-2a68acf98d33

	column Comparator
		lineageTag: bad6c59c-49c7-43f9-a8a9-994a6a3bb2ce
		summarizeBy: none
		isNameInferred
		sourceColumn: ComparatorMaster[Comparator]
		sortByColumn: ComparatorOrder

		annotation SummarizationSetBy = Automatic

	column ComparatorOrder
		formatString: 0
		lineageTag: 24652005-21fc-4773-a979-d2170f0036f2
		summarizeBy: sum
		isNameInferred
		sourceColumn: ComparatorMaster[ComparatorOrder]

		annotation SummarizationSetBy = Automatic

	partition MarginBridgeComparator-6ce6c62e-21d3-47bd-8f7a-1b192c86532f = calculated
		mode: import
		source = CALCULATETABLE(SUMMARIZECOLUMNS(ComparatorMaster[Comparator],ComparatorMaster[ComparatorOrder]),ComparatorMaster[Comparator]<>BLANK())

	annotation PBI_Id = f7af03fa4f524b198dfcef1365a7a334

