table MetricMasterPnL
	lineageTag: 8d2eb979-23d5-463b-b51b-2d3acebac625

	/// This measure is the SELECTEDVALUE of column 'MetricMasterPnL'[Metric]
	measure slctd_MetricMasterPnL = SELECTEDVALUE ( 'MetricMasterPnL'[Metric] )
		lineageTag: 91744357-0435-4478-b76d-9be2e14e038b

	column Metric
		dataType: string
		lineageTag: 7691b38b-d743-464c-9a2e-e05ace729a5b
		summarizeBy: none
		sourceColumn: Metric
		sortByColumn: MetricOrder

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column MetricOrder
		dataType: int64
		formatString: 0
		lineageTag: b2a44990-763e-4b54-89dd-624333f61e4e
		summarizeBy: sum
		sourceColumn: MetricOrder

		annotation SummarizationSetBy = Automatic

	column ValFormatString
		dataType: string
		lineageTag: 9cf317f2-e473-4879-a646-aeec9085ecf8
		summarizeBy: none
		sourceColumn: ValFormatString

		annotation SummarizationSetBy = Automatic

	column VarFormatString
		dataType: string
		lineageTag: 1667002f-6a34-496f-977a-dce319bf5e73
		summarizeBy: none
		sourceColumn: VarFormatString

		annotation SummarizationSetBy = Automatic

	column PctVarFormatString
		dataType: string
		lineageTag: a65321be-1f2f-4fb5-a78e-978f46f3af6c
		summarizeBy: none
		sourceColumn: PctVarFormatString

		annotation SummarizationSetBy = Automatic

	column ActOrdersChannelAvailable
		dataType: int64
		formatString: 0
		lineageTag: 52b00ec5-834f-4d57-a28e-bcbb8a467380
		summarizeBy: sum
		sourceColumn: ActOrdersChannelAvailable

		annotation SummarizationSetBy = Automatic

	column PlanOrdersChannelAvailable
		dataType: int64
		formatString: 0
		lineageTag: 3ef213ad-e06f-4a30-933e-4dd24a893795
		summarizeBy: sum
		sourceColumn: PlanOrdersChannelAvailable

		annotation SummarizationSetBy = Automatic

	partition MetricMasterPnL-33d47956-2ef8-4dd9-bff3-893b9db149c2 = m
		mode: import
		queryGroup: 'Dimension tables'
		source =
				let
				    Source = PowerBI.Dataflows(null),
				    #"1e21bb0e-7319-4d52-a1b9-84f8819e9fa0" = Source{[workspaceId="1e21bb0e-7319-4d52-a1b9-84f8819e9fa0"]}[Data],
				    #"96438038-62f5-4fb3-bf97-feade6da8d6f" = #"1e21bb0e-7319-4d52-a1b9-84f8819e9fa0"{[dataflowId="96438038-62f5-4fb3-bf97-feade6da8d6f"]}[Data],
				    MetricMasterPnL1 = #"96438038-62f5-4fb3-bf97-feade6da8d6f"{[entity="MetricMasterPnL"]}[Data]
				in
				    MetricMasterPnL1

	annotation PBI_ResultType = Table

