table RefCalendar
	lineageTag: 018f63c4-5faf-487f-9c50-411442b7bbd0

	column fiscalWeek
		dataType: int64
		formatString: 0
		lineageTag: 048bb549-8580-459d-8b48-4c40755c6364
		summarizeBy: sum
		sourceColumn: fiscalWeek

		annotation SummarizationSetBy = Automatic

	column fiscalWeekNumber
		dataType: int64
		formatString: 0
		lineageTag: 0c1b6d7b-9f83-4fec-a504-66030b2e4f24
		summarizeBy: sum
		sourceColumn: fiscalWeekNumber

		annotation SummarizationSetBy = Automatic

	column fiscalWeekEndingDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: b3481681-023d-4381-97ca-898d67b2fb68
		summarizeBy: none
		sourceColumn: fiscalWeekEndingDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column fiscalWeekLastWeek
		dataType: int64
		formatString: 0
		lineageTag: f65ee7b9-e3fa-4389-b149-2ebb16a3bbd5
		summarizeBy: sum
		sourceColumn: fiscalWeekLastWeek

		annotation SummarizationSetBy = Automatic

	column fiscalWeekLastYear
		dataType: int64
		formatString: 0
		lineageTag: be72e711-296f-4850-8bee-fc9423378d28
		summarizeBy: sum
		sourceColumn: fiscalWeekLastYear

		annotation SummarizationSetBy = Automatic

	column fiscalWeekLastToLastyear
		dataType: int64
		formatString: 0
		lineageTag: fea6cbd7-ee33-4211-bf55-4cb87a461277
		summarizeBy: sum
		sourceColumn: fiscalWeekLastToLastyear

		annotation SummarizationSetBy = Automatic

	column fiscalMonth
		dataType: int64
		formatString: 0
		lineageTag: ada8c251-6551-45aa-99fe-bcb32170193d
		summarizeBy: sum
		sourceColumn: fiscalMonth

		annotation SummarizationSetBy = Automatic

	column fiscalMonthName
		dataType: string
		lineageTag: c9f6214e-5352-4fff-9c93-42d0cd53b0a7
		summarizeBy: none
		sourceColumn: fiscalMonthName

		annotation SummarizationSetBy = Automatic

	column fiscalMonthNumber
		dataType: int64
		formatString: 0
		lineageTag: 8468b9da-6744-43f9-9d5e-ccdcd23a1817
		summarizeBy: sum
		sourceColumn: fiscalMonthNumber

		annotation SummarizationSetBy = Automatic

	column fiscalQuarter
		dataType: int64
		formatString: 0
		lineageTag: dbf1eca7-e8ea-4502-8417-f72c9fc298b7
		summarizeBy: sum
		sourceColumn: fiscalQuarter

		annotation SummarizationSetBy = Automatic

	column fiscalQuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: 7273c9e7-3e0a-4f70-b220-d9d8fe649738
		summarizeBy: sum
		sourceColumn: fiscalQuarterNumber

		annotation SummarizationSetBy = Automatic

	column fiscalHalfYear
		dataType: int64
		formatString: 0
		lineageTag: 5f8cea69-22eb-46f6-b381-7245f62d96d5
		summarizeBy: sum
		sourceColumn: fiscalHalfYear

		annotation SummarizationSetBy = Automatic

	column fiscalYear
		dataType: int64
		formatString: 0
		lineageTag: da75db2b-52e0-43fd-8762-c801f7c0f1ee
		summarizeBy: sum
		sourceColumn: fiscalYear

		annotation SummarizationSetBy = Automatic

	column season
		dataType: string
		lineageTag: 1c369a25-4515-4e2b-a9e3-9270e310171c
		summarizeBy: none
		sourceColumn: season

		annotation SummarizationSetBy = Automatic

	column calendarID
		dataType: int64
		formatString: 0
		lineageTag: 23a2af79-911e-4f88-ad17-d8ded396ef2c
		summarizeBy: count
		sourceColumn: calendarID

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: bc838a5c-fabc-4264-b0dd-86eb64422187
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition RefCalendar-fd19a110-3181-4d9d-875e-4ce13517b0bf = m
		mode: import
		source =
				let
				    Source = PowerBI.Dataflows(null),
				    #"1e21bb0e-7319-4d52-a1b9-84f8819e9fa0" = Source{[workspaceId="1e21bb0e-7319-4d52-a1b9-84f8819e9fa0"]}[Data],
				    #"132e6a64-03a6-44df-9ddf-05f716b36d98" = #"1e21bb0e-7319-4d52-a1b9-84f8819e9fa0"{[dataflowId="132e6a64-03a6-44df-9ddf-05f716b36d98"]}[Data],
				    #"Weekly Calendar" = #"132e6a64-03a6-44df-9ddf-05f716b36d98"{[entity="Weekly Calendar"]}[Data],
				    #"Sorted Rows" = Table.Sort(#"Weekly Calendar",{{"fiscalWeekEndingDate", Order.Ascending}}),
				    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "Index", 0, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

