table ReturnsBridgeWalk
	lineageTag: 5269b823-4464-4eeb-befe-6946be056f19

	column Walk
		dataType: string
		lineageTag: b29d2233-efb9-414d-8a73-2a9ee8664ab5
		summarizeBy: none
		sourceColumn: Walk
		sortByColumn: WalkSort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column WalkSort
		dataType: int64
		formatString: 0
		lineageTag: 045bfbca-be6a-4091-a390-a5e5083588d0
		summarizeBy: sum
		sourceColumn: WalkSort

		annotation SummarizationSetBy = Automatic

	partition ReturnsBridgeWalk-fad9aca4-3b6b-4b7d-9b00-ec4f0d287796 = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8olUitWJVgoBUrEA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Walk = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Walk", type text}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "WalkSort"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

