table 'Total Furniture'
	lineageTag: 2c0038ed-1b3c-4804-8daa-1944159584e9

	column 'Total Furniture'
		dataType: string
		lineageTag: c9fd016c-670f-403b-98d6-2013ed7075ca
		summarizeBy: none
		sourceColumn: Total Furniture

		annotation SummarizationSetBy = Automatic

	column 'In/Ex Furniture'
		dataType: string
		lineageTag: fe6b530c-b512-487d-987f-5aced3ce2e2f
		summarizeBy: none
		sourceColumn: In/Ex Furniture

		annotation SummarizationSetBy = Automatic

	partition 'Total Furniture' = m
		mode: import
		queryGroup: 'Dimension tables'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCskvUfDMS1ZwKy3KU1DSUQLRmSWlRalKsTqYsq4VyTl6CphqXCtwK4kFAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Total Furniture" = _t, #"In/Ex Furniture" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Total Furniture", type text}, {"In/Ex Furniture", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

