table TransMetrics
	lineageTag: ab95e713-aa3a-427b-a86a-e7e64f972691

	/// This measure is the SELECTEDVALUE of column 'TransMetrics'[Metric]
	measure slctd_TransMetric = SELECTEDVALUE ( 'TransMetrics'[Metric] )
		lineageTag: bb7b3087-3b96-44e2-859f-4a88dc7e9ff8

	column Metric
		dataType: string
		lineageTag: 416c7c0b-567c-4bdb-9a29-8dc60cb28689
		summarizeBy: none
		sourceColumn: Metric
		sortByColumn: MetricOrder

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column MetricOrder
		dataType: int64
		formatString: 0
		lineageTag: c86f21d8-72a1-4e06-8287-29621c7ce950
		summarizeBy: sum
		sourceColumn: MetricOrder

		annotation SummarizationSetBy = Automatic

	column NumFormatString
		dataType: string
		lineageTag: 68164e4b-ccf9-48df-9e62-99d4e38e2be4
		summarizeBy: none
		sourceColumn: NumFormatString

		annotation SummarizationSetBy = Automatic

	column 'Metric (unit)'
		dataType: string
		lineageTag: 800a1221-35e6-4b2c-a650-3bc976f309b5
		summarizeBy: none
		sourceColumn: Metric (unit)
		sortByColumn: MetricOrder

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition TransMetrics-4900aa81-e59c-4cf3-a656-46a6e6dc773d = m
		mode: import
		queryGroup: 'Dimension tables'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCsssziwpVtKBMhQ0cjWBHAMgVtZRVjbQ0dEzsNaAMzWVYnWilZzz88pSi4oz8/OAyhAcBQ1VkF5DkH49A1VrDSCpqQrW4VmSmguyBExD7TDCa0dIUWJecWJyCdBckEZkLlS/MV79jk5h+o7+YUA1UJaCxqHFIG0mMG1wTXAtwQEg5cEBMKWmOJU6JRZnp5YoBGdWpQLVhOaBQq4gtUgByZlAcTPs+mMB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Metric = _t, #"Metric (unit)" = _t, MetricOrder = _t, NumFormatString = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Metric", type text}, {"MetricOrder", Int64.Type}, {"NumFormatString", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

