table factAOV
	lineageTag: 7c2144c8-7ea2-4fae-86bb-c1413cb0fa62

	/// This measure is the sum of column 'factAOV'[orders]
	measure sum_orders_factAOV = SUM('factAOV'[orders])
		formatString: #,##0;(#,##0)
		lineageTag: 1f1d12c5-f9cb-475e-9ac7-df9ef6f7f3b3

	/// This measure is the sum of column 'factAOV'[net_revenue]
	measure sum_net_revenue_factAOV = SUM('factAOV'[net_revenue])
		formatString: #,##0;(#,##0)
		lineageTag: eed5cde6-d6da-40ec-86bc-025736773b37

	column week_ending
		dataType: dateTime
		formatString: Long Date
		lineageTag: add0ec4a-226b-40b9-9bad-777f735cb8c8
		summarizeBy: none
		sourceColumn: week_ending

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column dayID
		dataType: dateTime
		formatString: Long Date
		lineageTag: c8d5c881-7658-483f-9cd4-a2c3a0b129d5
		summarizeBy: none
		sourceColumn: dayID

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column orders
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 315ac9c4-74be-4839-972f-7a75b984347f
		summarizeBy: sum
		sourceColumn: orders

		annotation SummarizationSetBy = Automatic

	column net_revenue
		dataType: double
		isHidden
		lineageTag: 44e5a42b-7e3d-4e36-bc5c-c11a377dc3b5
		summarizeBy: sum
		sourceColumn: net_revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fiscalWeek
		dataType: int64
		formatString: 0
		lineageTag: 85fa8b81-b725-4c10-ac7a-c90de1ef2052
		summarizeBy: none
		sourceColumn: fiscalWeek

		annotation SummarizationSetBy = Automatic

	partition factAOV = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"dbdde023-0de1-4da5-bc99-1bda1526f5b1" = Workspaces{[workspaceId="dbdde023-0de1-4da5-bc99-1bda1526f5b1"]}[Data],
				    #"1b8c55a9-c0d5-4918-bed1-c0cbf0a378c9" = #"dbdde023-0de1-4da5-bc99-1bda1526f5b1"{[dataflowId="1b8c55a9-c0d5-4918-bed1-c0cbf0a378c9"]}[Data],
				    Query_ = #"1b8c55a9-c0d5-4918-bed1-c0cbf0a378c9"{[entity="Query",version=""]}[Data],
				    #"Filtered Rows" = Table.SelectRows(Query_, each ([category] = "Clothing & Home") and ([CountryL2ID] = 1000)),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"dayID", "week_ending", "orders", "net_revenue"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Other Columns", {"dayID"}, DailyCalendar, {"naturalDate"}, "DailyCalendar", JoinKind.LeftOuter),
				    #"Expanded DailyCalendar" = Table.ExpandTableColumn(#"Merged Queries", "DailyCalendar", {"fiscalWeek"}, {"fiscalWeek"})
				in
				    #"Expanded DailyCalendar"

	annotation PBI_ResultType = Table

