table factForecast
	lineageTag: 4de6e86d-3f7c-4eb0-94c6-766846c82af4

	measure Sum_OrdersPlan_TotSlsxVTest = CALCULATE(Sum(factForecast[TotSlsxV]),factForecast[Dispatch or Orders] = "Orders")
		lineageTag: df795010-1692-4c28-8744-842ed0e634bf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This measure is the sum of column 'factForecast'[DiscMDV]
	measure sum_DiscMDV = SUM('factForecast'[DiscMDV])
		formatString: #,##0;(#,##0)
		lineageTag: d81ab43e-1a8b-4f37-99d7-4ba372f287b2

	/// This measure is the sum of column 'factForecast'[FPGSlsxV]
	measure sum_FPGSlsxV = SUM('factForecast'[FPGSlsxV])
		formatString: #,##0;(#,##0)
		lineageTag: 6734ff04-7b31-43d0-b41d-6dfd72d254dc

	/// This measure is the sum of column 'factForecast'[FPPSlsV]
	measure sum_FPPSlsV = SUM('factForecast'[FPPSlsV])
		formatString: #,##0;(#,##0)
		lineageTag: 5ad5eb9a-be57-4de9-b563-8c5a68e823be

	/// This measure is the sum of column 'factForecast'[FPPGSlsxV]
	measure sum_FPPGSlsxV = SUM('factForecast'[FPPGSlsxV])
		formatString: #,##0;(#,##0)
		lineageTag: 54ace9cf-ffdc-4775-a2cc-18b1c3bfee5c

	/// This measure is the sum of column 'factForecast'[TotSlsV]
	measure sum_TotSlsV = SUM('factForecast'[TotSlsV])
		formatString: #,##0;(#,##0)
		lineageTag: aff9d3b6-f3bd-4ce6-b411-7271d9e3027e

	/// This measure is the sum of column 'factForecast'[FPPSlsxV]
	measure sum_FPPSlsxV = SUM('factForecast'[FPPSlsxV])
		formatString: #,##0;(#,##0)
		lineageTag: 6e0e1d3f-ca61-4800-aae8-dfec2e0b4101

	/// This measure is the sum of column 'factForecast'[TotBIMAV]
	measure sum_TotBIMAV = SUM('factForecast'[TotBIMAV])
		formatString: #,##0;(#,##0)
		lineageTag: 4f8c9331-03eb-4b79-a54e-55ac351fa237

	/// This measure is the sum of column 'factForecast'[FPSlsV]
	measure sum_FPSlsV = SUM('factForecast'[FPSlsV])
		formatString: #,##0;(#,##0)
		lineageTag: 3e5599be-f304-477c-ae21-8f31fc3d098e

	/// This measure is the sum of column 'factForecast'[PrRedSlsV]
	measure sum_PrRedSlsV = SUM('factForecast'[PrRedSlsV])
		formatString: #,##0;(#,##0)
		lineageTag: 4fb40090-c076-43ac-aafc-e7113f86528a

	/// This measure is the sum of column 'factForecast'[TotBIMBV]
	measure sum_TotBIMBV = SUM('factForecast'[TotBIMBV])
		formatString: #,##0;(#,##0)
		lineageTag: 5daaa76f-51c6-407d-9c0f-c16b3651aaad

	/// This measure is the sum of column 'factForecast'[RealMDV]
	measure sum_RealMDV = SUM('factForecast'[RealMDV])
		formatString: #,##0;(#,##0)
		lineageTag: 2738627a-95b3-4120-97bd-304d39e91c87

	/// This measure is the sum of column 'factForecast'[TotBIMP]
	measure sum_TotBIMP = SUM('factForecast'[TotBIMP])
		formatString: #,##0;(#,##0)
		lineageTag: b9d558a9-c294-4f0a-9ac9-5b8c3e5fbbac

	/// This measure is the sum of column 'factForecast'[PrGSlsxV]
	measure sum_PrGSlsxV = SUM('factForecast'[PrGSlsxV])
		formatString: #,##0;(#,##0)
		lineageTag: 4919086c-e84c-4cdb-8b4d-d802830af483

	/// This measure is the sum of column 'factForecast'[RealMDxV]
	measure sum_RealMDxV = SUM('factForecast'[RealMDxV])
		formatString: #,##0;(#,##0)
		lineageTag: b37d3383-1514-4d94-a59e-b1fdced8d498

	/// This measure is the sum of column 'factForecast'[TotGSMV]
	measure sum_TotGSMV = SUM('factForecast'[TotGSMV])
		formatString: #,##0;(#,##0)
		lineageTag: 26d4a6ad-2f8b-412d-9bae-22fce01f650c

	/// This measure is the sum of column 'factForecast'[RedGSlsxV]
	measure sum_RedGSlsxV = SUM('factForecast'[RedGSlsxV])
		formatString: #,##0;(#,##0)
		lineageTag: 5f462827-5688-40d7-b35c-f645c299c7d2

	/// This measure is the sum of column 'factForecast'[TotPoSV]
	measure sum_TotPoSV = SUM('factForecast'[TotPoSV])
		formatString: #,##0;(#,##0)
		lineageTag: 2952216c-6b56-4290-a0b3-41a482904db5

	/// This measure is the sum of column 'factForecast'[PrSlsV]
	measure sum_PrSlsV = SUM('factForecast'[PrSlsV])
		formatString: #,##0;(#,##0)
		lineageTag: 77de1dc1-9d0a-4740-aebf-40745eb64172

	/// This measure is the sum of column 'factForecast'[TotSlsC]
	measure sum_TotSlsC = SUM('factForecast'[TotSlsC])
		formatString: #,##0;(#,##0)
		lineageTag: 23af76e5-d97b-454c-a147-fc491a492c6e

	/// This measure is the sum of column 'factForecast'[TotSlsxV]
	measure sum_TotSlsxV = SUM('factForecast'[TotSlsxV])
		formatString: #,##0;(#,##0)
		lineageTag: d796e4f1-b2c0-43b8-997b-5a897b16a0e4

	/// This measure is the sum of column 'factForecast'[FPPGSMV]
	measure sum_FPPGSMV = SUM('factForecast'[FPPGSMV])
		formatString: #,##0;(#,##0)
		lineageTag: b975f666-447f-4b83-923f-62817be041c3

	/// This measure is the sum of column 'factForecast'[TotStDV]
	measure sum_TotStDV = SUM('factForecast'[TotStDV])
		formatString: #,##0;(#,##0)
		lineageTag: a9658d06-599b-4b49-8561-457d105f54f4

	/// This measure is the sum of column 'factForecast'[FPPBIMAV]
	measure sum_FPPBIMAV = SUM('factForecast'[FPPBIMAV])
		formatString: #,##0;(#,##0)
		lineageTag: 871ae7c8-6d5c-4524-8dd8-50c73fa163ab

	/// This measure is the sum of column 'factForecast'[fpp_rev_intake_units]
	measure sum_fpp_rev_intake_units = SUM('factForecast'[fpp_rev_intake_units])
		formatString: #,##0;(#,##0)
		lineageTag: 0ee236e7-5dc8-4acb-9581-8ae29b17ef91

	/// This measure is the sum of column 'factForecast'[FPPBIMBV]
	measure sum_FPPBIMBV = SUM('factForecast'[FPPBIMBV])
		formatString: #,##0;(#,##0)
		lineageTag: 37d179ed-3695-4c97-bc5e-774283d1ccf2

	/// This measure is the sum of column 'factForecast'[TotPromoActV]
	measure sum_TotPromoActV = SUM ( factForecast[TotPoSV] ) + SUM ( factForecast[TotStDV] )
		formatString: #,##0;(#,##0)
		lineageTag: de908247-7d25-4319-84ba-f9cb3eb5db44

	/// This measure is the sum of column 'factForecast'[fpp_rev_intake_val]
	measure sum_fpp_rev_intake_val = SUM('factForecast'[fpp_rev_intake_val])
		formatString: #,##0;(#,##0)
		lineageTag: 7cea8dbb-d8b9-4ec1-8206-81e139e50667

	/// This measure is the sum of column 'factForecast'[FPPBIMP]
	measure sum_FPPBIMP = SUM('factForecast'[FPPBIMP])
		formatString: #,##0;(#,##0)
		lineageTag: 78e9006e-3f0a-4cbc-b383-af804425c7c3

	/// This measure is the sum of column 'factForecast'[FPPSlsC]
	measure sum_FPPSlsC = SUM('factForecast'[FPPSlsC])
		formatString: #,##0;(#,##0)
		lineageTag: 6c1492ad-ef57-4079-b3be-150cca336df1

	/// This measure is the sum of column 'factForecast'[SST]
	measure sum_SST = SUM('factForecast'[SST])
		formatString: #,##0;(#,##0)
		lineageTag: 1c2ef338-7d8b-4932-bb99-001c61b8f7f2

	/// This measure is the sum of column 'factForecast'[DoC]
	measure sum_DoC = SUM('factForecast'[DoC])
		formatString: #,##0;(#,##0)
		lineageTag: d4297eb0-25d6-40fe-9514-526e4bd64e52

	/// This measure is the sum of column 'factForecast'[FPPPoSV]
	measure sum_FPPPoSV = SUM('factForecast'[FPPPoSV])
		formatString: #,##0;(#,##0)
		lineageTag: 53304438-ee37-4176-85dc-6cc1da8ae8ff

	/// This measure is the sum of column 'factForecast'[FPPPromoActV]
	measure sum_FPPPromoActV = SUM('factForecast'[FPPPromoActV])
		formatString: #,##0;(#,##0)
		lineageTag: 3be525de-8dd4-4129-b75d-2fb776f31849

	/// This measure is the sum of column 'factForecast'[RedGSMV]
	measure sum_RedGSMV = SUM('factForecast'[RedGSMV])
		formatString: #,##0;(#,##0)
		lineageTag: da307e75-8ae2-4350-bd9b-3a74a8a05180

	/// This measure is the sum of column 'factForecast'[RedBIMAV]
	measure sum_RedBIMAV = SUM('factForecast'[RedBIMAV])
		formatString: #,##0;(#,##0)
		lineageTag: d1e65f02-d5ed-4510-913d-b64b93b52d52

	/// This measure is the sum of column 'factForecast'[RedBIMBV]
	measure sum_RedBIMBV = SUM('factForecast'[RedBIMBV])
		formatString: #,##0;(#,##0)
		lineageTag: 3801c538-485a-46f9-8fe0-a934debfecaa

	/// This measure is the sum of column 'factForecast'[RedBIMP]
	measure sum_RedBIMP = SUM('factForecast'[RedBIMP])
		formatString: #,##0;(#,##0)
		lineageTag: fefc72ca-4e3f-4cea-bd88-9dd3011b252c

	/// This measure is the sum of column 'factForecast'[RedSlsV]
	measure sum_RedSlsV = SUM('factForecast'[RedSlsV])
		formatString: #,##0;(#,##0)
		lineageTag: 1352982c-8642-41c4-bf52-52e2bb40d507

	/// This measure is the sum of column 'factForecast'[RedSlsC]
	measure sum_RedSlsC = SUM('factForecast'[RedSlsC])
		formatString: #,##0;(#,##0)
		lineageTag: 0d081e89-ec91-4ab3-9661-cb17889aa51e

	/// This measure is the sum of column 'factForecast'[RedSlsxV]
	measure sum_RedSlsxV = SUM('factForecast'[RedSlsxV])
		formatString: #,##0;(#,##0)
		lineageTag: 244f9c0c-24cb-4d1f-b30c-8ff76df8fa3b

	/// This measure is the sum of column 'factForecast'[RedPoSV]
	measure sum_RedPoSV = SUM('factForecast'[RedPoSV])
		formatString: #,##0;(#,##0)
		lineageTag: 47344dfb-d2ea-41ba-99f9-9e4cb2aa4088

	/// This measure is the sum of column 'factForecast'[RedPromoActV]
	measure sum_RedPromoActV = SUM('factForecast'[RedPromoActV])
		formatString: #,##0;(#,##0)
		lineageTag: 3fc061ff-b379-41ec-a023-2b5b707261b3

	measure sriv_orders_mp_rf = CALCULATE ( [sum_TotSlsV], factForecast[plan] = "RF" )
		formatString: #,##0,,.0;(#,##0,,.0)
		lineageTag: f8210197-f79c-485b-94cb-0fbdc3d349e2

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'SRIV GMOR vs MP Actuals' = [SRIV Orders] - [sriv_orders_mp_rf]
		formatString: #,##0.0;(#,##0.0)
		lineageTag: 8151d7bf-5daf-45b3-a83b-315912854e28

	measure 'SRIV GMOR vs MP Actuals %' = DIVIDE ( [SRIV Orders], [sriv_orders_mp_rf] ) - 1
		formatString: #,##0.0%;(#,##0.0)%
		lineageTag: dd2dc040-ff9a-4c15-93ee-dd898cf90a72

	/// This measure is the sum of column 'factForecast'[RedSlsV]
	measure calc_RealMDxV = [sum_RealMDxV] + ( [sum_RedGSlsxV] - [sum_RedSlsxV] )
		formatString: #,##0;(#,##0)
		lineageTag: 6034e82d-df84-4d02-ae50-5bce6d52f21e

	/// This measure is the sum of column 'factForecast'[RedSlsV]
	measure calc_TotGSlsxV = [sum_FPPGSlsxV] + [sum_RedGSlsxV] - [MbrComp10_SaleMDExVAT]
		formatString: #,##0;(#,##0)
		lineageTag: fc0e1231-d33a-456f-9d54-232b136a7e1e

	column fiscalWeek
		dataType: int64
		formatString: 0
		lineageTag: 41cad225-eb59-426b-b380-8069ab8cab15
		summarizeBy: none
		sourceColumn: fiscalWeek

		annotation SummarizationSetBy = Automatic

	column plan
		dataType: string
		lineageTag: 26a2ff91-617a-46c9-8722-905fcc68ce35
		summarizeBy: none
		sourceColumn: plan

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 7ce2b2e6-334c-4d66-aab5-ec70baffa6e8
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column product
		dataType: string
		lineageTag: 1be431f6-f5bb-4aa0-9b43-d07466b25044
		summarizeBy: none
		sourceColumn: product

		annotation SummarizationSetBy = Automatic

	column 'Dispatch or Orders'
		dataType: string
		lineageTag: 893ff7af-4dc2-430c-9f24-45b8344fdc51
		summarizeBy: none
		sourceColumn: Dispatch or Orders

		annotation SummarizationSetBy = Automatic

	column DiscMDV
		dataType: double
		isHidden
		lineageTag: 09c11489-f785-4e0d-8bda-a0bfb894ea7f
		summarizeBy: sum
		sourceColumn: DiscMDV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FPGSlsxV
		dataType: double
		isHidden
		lineageTag: c18eee40-5d8e-46e8-922c-2b22422f8634
		summarizeBy: sum
		sourceColumn: FPGSlsxV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FPPSlsV
		dataType: double
		isHidden
		lineageTag: 69f74aa8-45c7-4a17-9f1d-acbf06db05ae
		summarizeBy: sum
		sourceColumn: FPPSlsV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FPPGSlsxV
		dataType: double
		isHidden
		lineageTag: 82885612-2dce-4b42-afea-cfe5470a3a36
		summarizeBy: sum
		sourceColumn: FPPGSlsxV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotSlsV
		dataType: double
		isHidden
		lineageTag: a8f1cbdd-d959-4561-8fb4-598b1b0b52da
		summarizeBy: sum
		sourceColumn: TotSlsV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FPPSlsxV
		dataType: double
		isHidden
		lineageTag: 07ab1c9c-79b8-4fe3-88a6-c701d62bf32c
		summarizeBy: sum
		sourceColumn: FPPSlsxV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotBIMAV
		dataType: double
		isHidden
		lineageTag: ee38a0e8-2de5-4e79-bb66-a9764edce375
		summarizeBy: sum
		sourceColumn: TotBIMAV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FPSlsV
		dataType: double
		isHidden
		lineageTag: 18b5cee5-3110-4ca1-b974-306d369c0dfd
		summarizeBy: sum
		sourceColumn: FPSlsV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PrRedSlsV
		dataType: double
		isHidden
		lineageTag: b978f48a-7fb7-43c9-8c56-afe420410d95
		summarizeBy: sum
		sourceColumn: PrRedSlsV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotBIMBV
		dataType: double
		isHidden
		lineageTag: 48647324-02eb-43b0-b0c6-8186373cabe0
		summarizeBy: sum
		sourceColumn: TotBIMBV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RealMDV
		dataType: double
		isHidden
		lineageTag: 973bb4ca-bf24-4907-81bb-183bdaf02339
		summarizeBy: sum
		sourceColumn: RealMDV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotBIMP
		dataType: double
		isHidden
		lineageTag: 126abf3b-7e5b-49d3-b561-527dc237f781
		summarizeBy: sum
		sourceColumn: TotBIMP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PrGSlsxV
		dataType: double
		isHidden
		lineageTag: 3382dcca-d765-414a-9523-e9d04e27a1c4
		summarizeBy: sum
		sourceColumn: PrGSlsxV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RealMDxV
		dataType: double
		isHidden
		lineageTag: 2424b1d5-5a9e-417f-aa5b-6340cbf7ba11
		summarizeBy: sum
		sourceColumn: RealMDxV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotGSMV
		dataType: double
		isHidden
		lineageTag: 596158ed-4592-4b8f-bf1a-78b915bdf983
		summarizeBy: sum
		sourceColumn: TotGSMV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RedGSlsxV
		dataType: double
		isHidden
		lineageTag: 3e326b9e-4bb5-44e3-8862-bba8ce2aacc5
		summarizeBy: sum
		sourceColumn: RedGSlsxV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotPoSV
		dataType: double
		isHidden
		lineageTag: 087c740b-fe43-4be6-b734-a71942e70ef0
		summarizeBy: sum
		sourceColumn: TotPoSV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PrSlsV
		dataType: double
		isHidden
		lineageTag: 773b2211-e734-4fff-8d2a-8177f982bd6f
		summarizeBy: sum
		sourceColumn: PrSlsV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotSlsC
		dataType: double
		isHidden
		lineageTag: dc951936-cdd4-41cf-a894-0b5a0d4d2e43
		summarizeBy: sum
		sourceColumn: TotSlsC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotSlsxV
		dataType: double
		isHidden
		lineageTag: 1e59ef91-65bc-4f58-9e60-ecd3f9fe492a
		summarizeBy: sum
		sourceColumn: TotSlsxV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FPPGSMV
		dataType: double
		isHidden
		lineageTag: 84837535-01eb-45f1-a37a-7bb67e4e4566
		summarizeBy: sum
		sourceColumn: FPPGSMV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotStDV
		dataType: double
		isHidden
		lineageTag: 467deccf-f0e4-4c68-8fc4-73a11509cea2
		summarizeBy: sum
		sourceColumn: TotStDV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FPPBIMAV
		dataType: double
		isHidden
		lineageTag: af92c50e-d41c-4056-897c-475fdff4e3c8
		summarizeBy: sum
		sourceColumn: FPPBIMAV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fpp_rev_intake_units
		dataType: double
		isHidden
		lineageTag: 2bd68ba2-c38d-46d8-9660-5788cfc7ab42
		summarizeBy: sum
		sourceColumn: fpp_rev_intake_units

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FPPBIMBV
		dataType: double
		isHidden
		lineageTag: 81c1af51-88f1-4f45-9036-8045be8670c1
		summarizeBy: sum
		sourceColumn: FPPBIMBV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotPromoActV
		dataType: double
		isHidden
		lineageTag: efe182cb-3578-4e3e-9784-1715555c5ca9
		summarizeBy: sum
		sourceColumn: TotPromoActV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fpp_rev_intake_val
		dataType: double
		isHidden
		lineageTag: 83f4503a-ab57-45b4-b259-5689b1140e8f
		summarizeBy: sum
		sourceColumn: fpp_rev_intake_val

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FPPBIMP
		dataType: double
		isHidden
		lineageTag: 60d86f6f-fdcb-4e2d-ada0-1c0e1f4120ef
		summarizeBy: sum
		sourceColumn: FPPBIMP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FPPSlsC
		dataType: double
		isHidden
		lineageTag: b0896f0b-2cce-4845-bd22-7f4145aa4b26
		summarizeBy: sum
		sourceColumn: FPPSlsC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SST
		dataType: double
		isHidden
		lineageTag: c76b4885-70ef-42a2-9c7a-ec29d91c1871
		summarizeBy: sum
		sourceColumn: SST

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DoC
		dataType: double
		isHidden
		lineageTag: 9d28b57e-b9ea-48fb-9244-7bd32364125f
		summarizeBy: sum
		sourceColumn: DoC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FPPPoSV
		dataType: double
		isHidden
		lineageTag: bcad395a-e781-49ae-8dc2-bcebdae7477b
		summarizeBy: sum
		sourceColumn: FPPPoSV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FPPPromoActV
		dataType: double
		isHidden
		lineageTag: 622066ac-f8f8-4315-8300-70691a1c3dab
		summarizeBy: sum
		sourceColumn: FPPPromoActV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RedGSMV
		dataType: double
		isHidden
		lineageTag: 0c01ada5-9b3f-4ab1-a973-b8e9cb8b27c6
		summarizeBy: sum
		sourceColumn: RedGSMV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RedBIMAV
		dataType: double
		isHidden
		lineageTag: 0b77efce-4886-47fa-8cba-28f1cfa87aa7
		summarizeBy: sum
		sourceColumn: RedBIMAV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RedBIMBV
		dataType: double
		isHidden
		lineageTag: fc43dded-3b9c-4c29-9749-4fc2976da36c
		summarizeBy: sum
		sourceColumn: RedBIMBV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RedBIMP
		dataType: double
		isHidden
		lineageTag: d8776df0-ce64-436e-b711-06c9ee4d240d
		summarizeBy: sum
		sourceColumn: RedBIMP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RedSlsV
		dataType: double
		isHidden
		lineageTag: 011bc41a-a9a7-4c87-b679-7193f9b07761
		summarizeBy: sum
		sourceColumn: RedSlsV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RedSlsC
		dataType: double
		isHidden
		lineageTag: 7da31a5c-aa9d-4420-9da8-3674e300e2a7
		summarizeBy: sum
		sourceColumn: RedSlsC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RedSlsxV
		dataType: double
		isHidden
		lineageTag: f18ceef9-8b77-49f4-8d5f-8f4ffddbd820
		summarizeBy: sum
		sourceColumn: RedSlsxV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RedPoSV
		dataType: double
		isHidden
		lineageTag: 53465570-6507-4140-acde-3e2be50b2768
		summarizeBy: sum
		sourceColumn: RedPoSV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RedPromoActV
		dataType: double
		isHidden
		lineageTag: 28c6c0fc-27b1-4d87-b7ec-8e3cede9026d
		summarizeBy: sum
		sourceColumn: RedPromoActV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column siteID
		dataType: int64
		formatString: 0
		lineageTag: 74f05753-2904-42cc-8d15-23408046e250
		summarizeBy: none
		sourceColumn: siteID

		annotation SummarizationSetBy = Automatic

	column Test = RELATED(ForecastScenarios[Forecast Scenario])
		lineageTag: 3fbe0826-3423-46ff-8631-2afe0964e871
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition factForecast = m
		mode: import
		queryGroup: 'Other fact tables'
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    Workspace = Workspaces{[workspaceId="1e21bb0e-7319-4d52-a1b9-84f8819e9fa0"]}[Data],
				
				// factForecast
				    factForecast = Workspace{[dataflowId="f0b60027-5a54-485c-8c6a-fd302daec7bb"]}[Data],
				    factForecastTbl = factForecast{[entity="C&H Plan",version=""]}[Data],
				    RenameColNames = Table.RenameColumns(factForecastTbl,{{"Week No", "fiscalWeek"}, {"Plan Type", "plan"}, {"Distribution Channel Code", "channel"}, {"Department / Category Code", "product"}}),
				    RemoveRF = Table.SelectRows(RenameColNames, each ([plan] <> "RF" and [plan] <> "MRF")),
				
				// MP Orders
				    //MPOrders = Workspace{[dataflowId="e6346887-90f6-49c0-b628-7e8e6cb1d341"]}[Data],
				    MPOrders = Workspace{[dataflowId="befd4cdc-e23e-4f5e-97e9-b9c56cc99655"]}[Data],
				    MPOrdersTbl = MPOrders{[entity="MP Plans Margin",version=""]}[Data],
				    Adddispordcolumn = Table.AddColumn(MPOrdersTbl, "Dispatch or Orders", each "Orders"),
				    #"Changed Type" = Table.TransformColumnTypes(Adddispordcolumn,{{"Dispatch or Orders", type text}}),
				    KeepRF = Table.SelectRows(#"Changed Type", each ([plan] = "RF" or [plan] = "MRF")),
				
				// Append Tables together
				    #"Appended Query" = Table.Combine({RemoveRF, KeepRF})
				in
				    #"Appended Query"

	annotation PBI_ResultType = Table

