table firstWeekCurrentQuarter
	lineageTag: 6867afa1-4cdf-4026-97de-c82036a8872d

	measure SlctdFirstWeekQtr = SELECTEDVALUE(firstWeekCurrentQuarter[fiscalWeek]) - 13
		lineageTag: 2d791c71-5657-4f56-ac89-c414af90b832

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure slctdFirstWeekYr = FORMAT(left(FORMAT([SlctdFirstWeekQtr],"000000"),4),0)*100+1
		lineageTag: 29de5c85-9e5a-4e4f-821c-4e0847bacec1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SlctdFirstWeekQtrBackup = Max(ActualisationWeek[ActualisationWeek])
		lineageTag: 0899b1bb-cc15-4dd4-924e-031100e5a518

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fiscalWeek
		dataType: int64
		formatString: 0
		lineageTag: 9eb9d2bc-66cb-4083-8e79-fe91d5f600ef
		summarizeBy: sum
		sourceColumn: fiscalWeek

		annotation SummarizationSetBy = Automatic

	partition firstWeekCurrentQuarter = m
		mode: import
		source =
				let
				    Source = PowerBI.Dataflows(null),
				    #"1e21bb0e-7319-4d52-a1b9-84f8819e9fa0" = Source{[workspaceId="1e21bb0e-7319-4d52-a1b9-84f8819e9fa0"]}[Data],
				    #"9d00c5c6-989f-4813-bae4-dc9f6262029c" = #"1e21bb0e-7319-4d52-a1b9-84f8819e9fa0"{[dataflowId="9d00c5c6-989f-4813-bae4-dc9f6262029c"]}[Data],
				    firstWeekCurrentQuarter1 = #"9d00c5c6-989f-4813-bae4-dc9f6262029c"{[entity="firstWeekCurrentQuarter"]}[Data]
				in
				    firstWeekCurrentQuarter1

	annotation PBI_ResultType = Table

