table ForecastVersion
	lineageTag: 563a45bb-fe3a-4ae0-910b-0958e239f614

	measure SlctdForecastVersion = SELECTEDVALUE(ForecastVersion[ForecastVersion],"FC")
		lineageTag: 40157a37-bb98-45a2-9b80-b6b46762a221

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure SlctdFirstWeekQtrFC = SELECTEDVALUE(ForecastVersion[ForecastActualisation],[SlctdFirstWeekQtrBackup])+1
		lineageTag: c371620f-7345-4dfb-8cb8-ff9f20527407

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ForecastVersion
		dataType: string
		lineageTag: 930c5d64-76c6-4a4a-91a1-60d0b0012891
		summarizeBy: none
		sourceColumn: ForecastVersion

		annotation SummarizationSetBy = Automatic

	column ForecastActualisation
		dataType: double
		lineageTag: 2ec79b77-932f-4f66-b9e2-f2a991a65739
		summarizeBy: sum
		sourceColumn: ForecastActualisation

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition ForecastVersion = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"1e21bb0e-7319-4d52-a1b9-84f8819e9fa0" = Workspaces{[workspaceId="1e21bb0e-7319-4d52-a1b9-84f8819e9fa0"]}[Data],
				    #"f0b60027-5a54-485c-8c6a-fd302daec7bb" = #"1e21bb0e-7319-4d52-a1b9-84f8819e9fa0"{[dataflowId="f0b60027-5a54-485c-8c6a-fd302daec7bb"]}[Data],
				    FCVersionNames_ = #"f0b60027-5a54-485c-8c6a-fd302daec7bb"{[entity="FCVersionNames",version=""]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(FCVersionNames_,{{"Plan Type", "ForecastVersion"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each not Text.Contains([ForecastVersion], "QRF")),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each ([ForecastVersion] <> "BUDGET" and [ForecastVersion] <> "Original Budget")),
				    #"Added Custom" = Table.AddColumn(#"Filtered Rows1", "ForecastActualisation", each try Number.FromText(Text.Middle([ForecastVersion],1,1)) * 13 otherwise 39),
				    #"Added to Column" = Table.TransformColumns(#"Added Custom", {{"ForecastActualisation", each _ + (FiscalYear * 100), type number}})
				in
				    #"Added to Column"

	annotation PBI_ResultType = Table

